
let flowers = [
    'minecraft:dandelion', 
    'minecraft:poppy', 
    'minecraft:blue_orchid', 
    'minecraft:allium', 
    'minecraft:azure_bluet', 
    'minecraft:red_tulip', 
    'minecraft:orange_tulip', 
    'minecraft:white_tulip', 
    'minecraft:pink_tulip', 
    'minecraft:oxeye_daisy', 
    'minecraft:cornflower', 
    'minecraft:lily_of_the_valley', 
    'minecraft:wither_rose', 
    'minecraft:sunflower', 
    'minecraft:lilac', 
    'minecraft:rose_bush', 
    'minecraft:peony', 
    'minecraft:sweet_berries', 
    'botania:white_mystical_flower', 
    'botania:orange_mystical_flower', 
    'botania:magenta_mystical_flower', 
    'botania:light_blue_mystical_flower', 
    'botania:yellow_mystical_flower', 
    'botania:lime_mystical_flower', 
    'botania:pink_mystical_flower', 
    'botania:gray_mystical_flower', 
    'botania:light_gray_mystical_flower', 
    'botania:cyan_mystical_flower', 
    'botania:purple_mystical_flower', 
    'botania:blue_mystical_flower', 
    'botania:brown_mystical_flower', 
    'botania:green_mystical_flower', 
    'botania:red_mystical_flower', 
    'botania:black_mystical_flower', 
    'botania:white_double_flower', 
    'botania:orange_double_flower', 
    'botania:magenta_double_flower', 
    'botania:light_blue_double_flower', 
    'botania:yellow_double_flower', 
    'botania:lime_double_flower', 
    'botania:pink_double_flower', 
    'botania:gray_double_flower', 
    'botania:light_gray_double_flower', 
    'botania:cyan_double_flower', 
    'botania:purple_double_flower', 
    'botania:blue_double_flower', 
    'botania:brown_double_flower', 
    'botania:green_double_flower', 
    'botania:red_double_flower', 
    'botania:black_double_flower', 
    'tropicraft:anemone', 
    'tropicraft:bromeliad', 
    'tropicraft:canna', 
    'tropicraft:commelina_diffusa', 
    'tropicraft:crocosmia', 
    'tropicraft:croton', 
    'tropicraft:dracaena', 
    'tropicraft:orange_anthurium', 
    'tropicraft:orchid', 
    'minestuck:glowflower', 
    'ecologics:azalea_flower'
]

onEvent('item.tooltip', tooltip => {
    flowers.forEach(id => {
      tooltip.addAdvanced(`${id}`, (item, advanced, text) => {
          text.add(1, Text.yellow('Factory Catagory : Flowers'))
    })
  })
})