
let fruit = [
    'minecraft:apple', 
    'the_vault:hearty_apple', 
    'tropicraft:pineapple', 
    'minecraft:sweet_berries', 
    'minecraft:glow_berries', 
    'ecologics:prickly_pear', 
    'tropicraft:lemon', 
    'tropicraft:lime', 
    'tropicraft:grapefruit', 
    'tropicraft:orange', 
    'delightful:salmonberries', 
    'ars_nouveau:source_berry', 
    'minecraft:chorus_fruit', 
    'minecraft:pumpkin', 
    'minecraft:carved_pumpkin', 
    'chipped:carved_pumpkin_1', 
    'chipped:carved_pumpkin_2', 
    'chipped:carved_pumpkin_3', 
    'chipped:carved_pumpkin_4', 
    'chipped:carved_pumpkin_5', 
    'chipped:carved_pumpkin_6', 
    'chipped:carved_pumpkin_7', 
    'chipped:carved_pumpkin_8', 
    'chipped:carved_pumpkin_9', 
    'chipped:carved_pumpkin_10', 
    'chipped:carved_pumpkin_11', 
    'chipped:carved_pumpkin_12', 
    'chipped:carved_pumpkin_13', 
    'chipped:carved_pumpkin_13', 
    'chipped:carved_pumpkin_14', 
    'chipped:carved_pumpkin_15', 
    'chipped:carved_pumpkin_16', 
    'chipped:carved_pumpkin_17', 
    'chipped:carved_pumpkin_18', 
    'chipped:carved_pumpkin_19', 
    'chipped:carved_pumpkin_20', 
    'chipped:carved_pumpkin_21', 
    'chipped:carved_pumpkin_22', 
    'chipped:pumpkin_1', 
    'chipped:pumpkin_2', 
    'chipped:pumpkin_3', 
    'chipped:pumpkin_4', 
    'chipped:pumpkin_5', 
    'chipped:pumpkin_6', 
    'chipped:pumpkin_7', 
    'chipped:pumpkin_8', 
    'chipped:pumpkin_9', 
    'chipped:pumpkin_10', 
    'chipped:pumpkin_11', 
    'chipped:pumpkin_12', 
    'chipped:pumpkin_13', 
    'chipped:pumpkin_14', 
    'chipped:pumpkin_15', 
    'chipped:pumpkin_16', 
    'magic_vibe_decorations:yellowpumpkin', 
    'magic_vibe_decorations:bluepumpkin', 
    'magic_vibe_decorations:redpumpkin', 
    'magic_vibe_decorations:greenpumpkin', 
    'magic_vibe_decorations:pinkpumpkin',
    'minecraft:melon',
    'farmersdelight:tomato'
]

onEvent('item.tooltip', tooltip => {
    fruit.forEach(id => {
      tooltip.addAdvanced(`${id}`, (item, advanced, text) => {
          text.add(1, Text.yellow('Factory Catagory : Fruit'))
    })
  })
})