// CHEAP
const GOOD_NAMES = [
  "Sole Carver",
  "Just a Gnome",
  "Simply Goblin",
  "Tiger Striped Yinglet",
  "Green Dragon",
  "Green Pony",
  "Slicer Von Dicer",
  "Magical Brat",
  "Flaming Fancy",
  "Fancy Feast",
  "Easy Squeezy"
];

const GOOD_ADDRESS = [
  "Kanto Server",
  "Johto Server",
  "Hoenn Server",
  "Sinnoh Server",
  "Unova Server",
  "Kalos Server",
  "Alola Server",
  "Galar Server",
  "Paldea Server",
  "Sevii Island Server",
  "Isle of Armor Server",
  "Crown Tundra Server",
  "Kitakami Server",
  "Orre Server",
  "Fiore Server",
  "Almia Server",
  "Oblivia Server",
  "Companion Park Server",
  "Mintale Server",
  "Ransei Server",
  "Ryme Server",
  "Tumblecube Server",
  "Ferrum Server",
  "Pasio Server",
  "Aeos Server",
  "Apple Server",
  "Orange Server",
  "Mango Server",
  "Strawberry Server",
  "Grape Server",
  "Lemon Server",
  "Lime Server",
  "Neo Turkey Server",
  "Neo Japan Server",
  "Guyana Server",
  "Neo Hong Kong Server",
  "Neo England Server",
  "Neo Egypt Server",
  "Neo Mexico Server",
  "Neo America Server",
  "Neo France Server"
];

const GOOD_MESSAGES = [
  "Look, don`t ask why I need this, I just do!",
  "I think my Vault Altar is broken, why is it asking for these? A little help?",
  "I`m in a bit of trouble, I need these to fill my own Work Order and I`m out of all the items!",
  "I`m just missing these from my collection.",
  "Hi! I heard about this service and I wanted to give it a little test!",
  "Does this system even work? Hello?",
  "Third time`s a charm trying to get this item.",
  "My Vault Companion started eating my supplies. Is it glitched? Whatever, I need to replace them before my party gets angry."
];

const GOOD_REQUESTABLE_ITEMS = {
  "botania:terrasteel_ingot":6,
  "botania:gaia_ingot":1,
  "botanicalextramachinery:malachite_ingot":2,
  "thermal_extra:dragonsteel_ingot":11,
  "avaritia:crystal_matrix_ingot":2,
  "minecraft:lodestone":17,
  "minecraft:beacon":7,
  "minecraft:nether_star":7,
  "minecraft:totem_of_undying":3,
  "ae2:cell_component_16k":2,
  "ae2:singularity":5,
  "ae2:crafting_terminal":2,
  "botania:gaia_spreader":5,
  "botania:mana_fluxfield":2,
  "botania:gaia_spirit":5,
  "botania:floating_orechid":1,
  "compressium:obsidian_3":6,
  "compressium:silver_scrap_block_2":6,
  "compressium:quartz_2":3,
  "compressium:diamond_1":1,
  "compressium:carbon_block_2":4,
  "compressium:magic_silk_block_2":1,
  "compressium:soulsand_3":6,
  "compressium:coal_3":6,
  "compressium:lapis_3":1,
  "compressium:ancient_copper_block_3":6,
  "compressium:living_rock_block_cobble_4":2,
  "compressium:gilded_block_4":2,
  "compressium:rotten_meat_block_4":2,
  "compressium:sandy_block_4":2,
  "compressium:velvet_block_4":2,
  "compressium:chromatic_iron_block_2":4,
  "compressium:chromatic_steel_block_1":5,
  "compressium:ornate_block_4":2,
  "compressium:redstone_3":2,
  "compressium:copper_2":2,
  "compressium:iron_2":2,
  "compressium:clay_3":5,
  "compressium:gold_1":2,
  "cookingforblockheads:sink":6,
  "create:water_wheel":5,
  "create:large_water_wheel":2,
  "create:crushing_wheel":5,
  "create:mechanical_roller":5,
  "easy_villagers:iron_farm":5,
  "mekanism:qio_drive_hyper_dense":1,
  "mekanism:atomic_disassembler":1,
  "mekanism:elite_tier_installer":5,
  "mekanism:ultimate_tier_installer":3,
  "mekanism:ultimate_smelting_factory":2,
  "mekanism:ultimate_enriching_factory":2,
  "mekanism:ultimate_crushing_factory":2,
  "mekanism:ultimate_compressing_factory":2,
  "mekanism:ultimate_combining_factory":2,
  "mekanism:ultimate_purifying_factory":2,
  "mekanism:ultimate_injecting_factory":2,
  "mekanism:ultimate_infusing_factory":2,
  "mekanism:ultimate_sawing_factory":2,
  "mekanism:basic_induction_cell":2,
  "mekanismgenerators:gas_burning_generator":2,
  "mekanismgenerators:wind_generator":5,
  "pipez:ultimate_upgrade":2,
  "powah:capacitor_nitro":2,
  "powah:solar_panel_spirited":2,
  "powah:energy_hopper_spirited":2,
  "snad:snad":4,
  "snad:red_snad":4,
  "snad:suol_snad":4,
  "sophisticatedbackpacks:identification_upgrade_advanced":6,
  "sophisticatedbackpacks:recycler_upgrade":1,
  "sophisticatedbackpacks:advanced_pickup_upgrade":6,
  "sophisticatedbackpacks:restock_upgrade":5,
  "sophisticatedbackpacks:deposit_upgrade":5,
  "sophisticatedbackpacks:stack_upgrade_tier_3":4,
  "sophisticatedbackpacks:stack_upgrade_tier_4":1,
  "sophisticatedbackpacks:tool_swapper_upgrade":2,
  "thermal:machine_insolator":1,
  "thermal:device_rock_gen":5,
  "thermal:upgrade_augment_3":5,
  "cagerium:cage":3,
  "cagerium:ominous_skull":6,
  "cagerium:binding_gemstone":1,
  "the_vault:vault_palladium":2,
  "the_vault:echo_pog":1,
  "the_vault:key_iskallium":2,
  "the_vault:key_gorginite":2,
  "the_vault:key_sparkletine":2,
  "the_vault:key_ashium":2,
  "the_vault:key_bomignite":2,
  "the_vault:key_tubium":2,
  "the_vault:key_upaline":2,
  "the_vault:key_petzanite":2,
  "the_vault:key_xenium":2,
  "the_vault:bitter_lemon":2,
  "the_vault:sour_orange":2,
  "the_vault:mystic_pear":1,
  "the_vault:mango":2,
  "the_vault:key_mould":3,
  "the_vault:blank_key":3,
  "the_vault:cluster_netherite":5,
  "the_vault:chunk_iskallium":2,
  "the_vault:chunk_gorginite":2,
  "the_vault:chunk_sparkletine":2,
  "the_vault:chunk_ashium":2,
  "the_vault:chunk_bomignite":2,
  "the_vault:chunk_tubium":2,
  "the_vault:chunk_upaline":2,
  "the_vault:chunk_petzanite":2,
  "the_vault:chunk_xenium":2,
  "the_vault:omega_pog":2,
  "the_vault:knowledge_star":2,
  "the_vault:infused_eternal_soul":1,
  "the_vault:perfect_echo_gem":4,
  "the_vault:repair_core":5,
  "the_vault:vault_catalyst_chaos":5,
  "the_vault:capstone_blacksmith":1,
  "the_vault:crystal_seal_cake":5,
  "the_vault:unidentified_treasure_key":2,
  "the_vault:hardened_wutodic_mass":2,
  "the_vault:sublime_vault_elixir":3,
  "the_vault:sublime_vault_substance":2,
  "the_vault:extraordinary_echo_gem":1,
  "the_vault:memory_shard":2,
  "the_vault:sublime_vault_vision":2,
  "the_vault:deck_station":4,
  "the_vault:vault_harvester":1,
  "the_vault:unboxing_station":4,
  "the_vault:card_binder":3,
  "the_vault:companion_incubator":1,
  "the_vault:vault_anvil":4,
  "the_vault:angel_block":1,
  "the_vault:ascension_forge":2,
  "the_vault:vault_sealer":1,
  "ironfurnaces:diamond_furnace":4,
  "ironfurnaces:emerald_furnace":3,
  "ironfurnaces:netherite_furnace":2,
  "ironfurnaces:augment_generator":1,
  "ironfurnaces:rainbow_plating":4,
  "botanypots:terracotta_botany_pot":6,
  "botanypots:terracotta_hopper_botany_pot":3,
  "botanypots:purple_concrete_botany_pot":6,
  "botanypots:purple_concrete_hopper_botany_pot":3,
  "botanypots:purple_glazed_terracotta_botany_pot":6,
  "botanypots:purple_glazed_terracotta_hopper_botany_pot":3,
  "irongenerators:gold_generator":4,
  "irongenerators:diamond_generator":2,
  "fluxnetworks:flux_plug":6,
  "fluxnetworks:flux_point":6,
  "fluxnetworks:flux_controller":1,
  "fluxnetworks:herculean_flux_storage":3,
  "bonsaitrees3:bonsaipot":6,
  "pneumaticcraft:drone":2,
  "pneumaticcraft:assembly_platform":5,
  "pneumaticcraft:assembly_io_unit_import":5,
  "pneumaticcraft:assembly_io_unit_export":5,
  "pneumaticcraft:assembly_drill":5,
  "pneumaticcraft:assembly_laser":5,
  "pneumaticcraft:assembly_controller":2,
  "pneumaticcraft:programmer":6,
  "pneumaticcraft:solar_compressor":3,
  "pneumaticcraft:flux_compressor":3,
  "scannable:blank_module":3,
  "scannable:entity_module":3,
  "scannable:hostile_entity_module":3,
  "scannable:common_ores_module":3,
  "scannable:rare_ores_module":3,
  "scannable:vault_ores_module":1,
  "scannable:vault_chests_module_living":1,
  "scannable:vault_chests_module_ornate":1,
  "scannable:vault_chests_module_gilded":1,
  "scannable:vault_chests_module_wooden":2,
  "scannable:vault_chests_module_raw":1,
  "scannable:vault_chests_module_treasure":1,
  "scannable:vault_spirit_module":1,
  "sophisticatedstorage:diffuser_upgrade":1,
  "sophisticatedstorage:recycler_upgrade":1,
  "sophisticatedstorage:ornate_chest":6,
  "sophisticatedstorage:gilded_chest":6,
  "sophisticatedstorage:living_chest":6,
  "sophisticatedstorage:altar_chest":5,
  "sophisticatedstorage:enigma_chest":5,
  "sophisticatedstorage:ornate_strongbox":5,
  "sophisticatedstorage:gilded_strongbox":5,
  "sophisticatedstorage:living_strongbox":5,
  "sophisticatedstorage:unique_crate":4,
  "sophisticatedstorage:ornate_barrel":3,
  "sophisticatedstorage:gilded_barrel":3,
  "sophisticatedstorage:living_barrel":3,
  "sophisticatedstorage:wooden_barrel":3,
  "sophisticatedstorage:netherite_barrel":5,
  "sophisticatedstorage:limited_netherite_barrel_1":5,
  "sophisticatedstorage:limited_netherite_barrel_2":5,
  "sophisticatedstorage:limited_netherite_barrel_3":5,
  "sophisticatedstorage:limited_netherite_barrel_4":5,
  "sophisticatedstorage:netherite_chest":5,
  "sophisticatedstorage:controller":3,
  "sophisticatedstorage:basic_to_netherite_tier_upgrade":5,
  "sfm:manager":1,
  "weather_control:rm_sensor":3,
  "weather_control:rm_core":1,
  "weather_control:dw_core":1,
  "woldsvaults:crystal_seal_unhinged":3,
  "woldsvaults:crystal_seal_spirits":3,
  "woldsvaults:crystal_seal_enchanter":2,
  "woldsvaults:crystal_seal_titan":2,
  "woldsvaults:crystal_seal_doomsayer":2,
  "woldsvaults:crystal_seal_corrupt":1,
  "woldsvaults:crystal_seal_alchemy":2,
  "woldsvaults:omega_box":3,
  "woldsvaults:repair_augmenter":2,
  "woldsvaults:hasty_pomegranate":4,
  "woldsvaults:mercy_orb":3,
  "woldsvaults:wold_star_chunk":4,
  "woldsvaults:pog_prism":4,
  "woldsvaults:arcane_essence":4,
  "woldsvaults:poltergeist_plum":4,
  "woldsvaults:pogominium_ingot":1,
  "woldsvaults:chunk_of_power":2,
  "woldsvaults:ruined_essence":1,
  "woldsvaults:nullite_fragment":1,
  "woldsvaults:prismatic_fiber":2,
  "woldsvaults:chroma_core":2,
  "woldsvaults:pogging_seed_base":1,
  "woldsvaults:vault_salvager":1,
  "woldsvaults:mod_box_workstation":1,
  "woldsvaults:chromatic_steel_vault_infuser":4,
  "botanicalmachinery:mechanical_daisy":5,
  "integrateddynamics:part_connector_omni_directional":6,
  "integratedterminals:part_terminal_storage":2,
  "integratedterminals:part_terminal_crafting_job":3,
  "integratedtunnels:part_player_simulator":2,
  "toms_storage:ts.crafting_terminal":3,
  "psi:programmer":3,
  "computercraft:turtle_normal":2,
  "advancedperipherals:block_reader":4,
  "appbot:mana_cell_housing":2,
  "appliedcooking:kitchen_station":2,
  "ars_nouveau:glyph_split":2,
  "ars_nouveau:enchanting_apparatus":3,
  "ars_nouveau:relay":2,
  "ars_nouveau:relay_splitter":2,
  "ars_nouveau:arcane_core":5,
  "ars_nouveau:ritual_brazier":1,
  "ars_nouveau:basic_spell_turret":3,
  "botanicalextramachinery:malachite_dragonstone":2,
  "ccvault:vault_reader":3,
  "experienceobelisk:astute_assembly":4,
  "experienceobelisk:experience_obelisk":2,
  "experienceobelisk:experience_fountain":2,
  "createaddition:electric_motor":6,
  "createdieselgenerators:huge_diesel_engine":2,
  "create_mechanical_extruder:mechanical_extruder":4,
  "createoreexcavation:drilling_machine":1,
  "industrialforegoing:plant_gatherer":2,
  "industrialforegoing:hydroponic_bed":2,
  "industrialforegoing:marine_fisher":2,
  "industrialforegoing:laser_drill":2,
  "industrialforegoing:infinity_charger":2,
  "industrialforegoing:machine_frame_simple":3,
  "industrialforegoing:machine_frame_advanced":2,
  "industrialforegoing:machine_frame_supreme":2,
  "industrialforegoing:speed_addon_1":2,
  "industrialforegoing:efficiency_addon_1":2,
  "industrialforegoing:simple_black_hole_unit":2,
  "integratedcrafting:part_interface_crafting":2,
  "littlelogistics:rapid_hopper":6,
  "megacells:mega_energy_cell":1,
  "megacells:mega_crafting_accelerator":4,
  "megacells:mega_crafting_monitor":5,
  "peripherals:trading_interface":2,
  "peripherals:anvil_interface":3,
  "occultism:wormhole_frame":3,
  "occultism:storage_remote_inert":4,
  "occultism:magic_lamp_empty":6,
  "occultism:stable_wormhole":3,
  "occultism:storage_controller_base":1,
  "quarryplus:workbench":5,
  "quarryplus:mining_well":1,
  "quarryplus:exp_pump":5,
  "quarryplus:marker":2,
  "quarryplus:flex_marker":2,
  "quarryplus:marker16":2,
  "rftoolspower:blazing_generator":3,
  "rftoolspower:dimensionalcell":3,
  "rftoolspower:dimensionalcelladvanced":1,
  "rftoolspower:endergenic":3,
  "rftoolspower:cell1":3,
  "rftoolsstorage:storage_module3":2,
  "rftoolsstorage:storage_scanner":5,
  "rftoolsutility:matter_booster":1,
  "rftoolsutility:haste_module":4,
  "rftoolsutility:glowing_module":4,
  "rftoolsutility:nightvision_module":4,
  "thermal_extra:av_item_filter_augment":3,
  "thermal_extra:area_radius_augment_3":1,
  "thermal_extra:rf_coil_storage_augment_2":1,
  "thermal_extra:fluid_tank_augment_1":2,
  "thermal_extra:machine_efficiency_augment_2":2,
  "thermal_extra:machine_output_augment_3":1,
  "thermal_extra:dynamo_fuel_augment_3":2,
  "tiab:time_in_a_bottle":1,
  "immersiveengineering:tesla_coil":1,
  "immersiveengineering:coil_mv":2,
  "immersiveengineering:generator":2,
  "immersiveengineering:transformer":2,
  "immersivepetroleum:gas_generator":2,
  "grapplemod:block_grapple_modifier":4,
  "adfinders:metal_finder":1,
  "adfinders:mineral_finder":1,
  "summoningrituals:altar":5,
  "summoningrituals:indestructible_altar":3,
  "silence_s_defense_tower:brand_new":5,
  "silence_s_defense_tower:overclock":2,
  "silence_s_defense_tower:pactof_blood":2,
  "silence_s_defense_tower:arrogance":2,
  "silence_s_defense_tower:large_fireworks_2":4,
  "silence_s_defense_tower:battery_1":1,
  "silence_s_defense_tower:arcane_missiles_1":4,
  "silence_s_defense_tower:flesh_armor_1":5,
  "silence_s_defense_tower:heavy_armor":2,
  "silence_s_defense_tower:slime_armor_1":2,
  "silence_s_defense_tower:tesla_electric_tower":2,
  "silence_s_defense_tower:firework_launcher_p":1,
  "silence_s_defense_tower:hell_core_3":2,
  "silence_s_defense_tower:reinforcement_materials_2":5,
  "vaultbeacon:vault_beacon":3,
  "vaultbeacon:black_haste_catalyst":3,
  "vaultbeacon:black_jump_catalyst":3,
  "vaultbeacon:black_speed_catalyst":3,
  "vaultbeacon:black_range_catalyst":3,
  "cardsnboards:coin_chip_5_0_0":4,
  "car:generator":5,
  "car:engine_6_cylinder":6,
  "car:red_tank_container":3,
  "car:medium_tank":4,
  "vending_companions:companion_vending_machine":1
};

const GOOD_REWARD_ITEMS = {
  "botania:terrasteel_ingot":9,
  "botania:gaia_ingot":2,
  "botanicalextramachinery:malachite_ingot":3,
  "thermal_extra:dragonsteel_ingot":16,
  "avaritia:crystal_matrix_ingot":3,
  "minecraft:lodestone":25,
  "minecraft:beacon":10,
  "minecraft:nether_star":10,
  "minecraft:totem_of_undying":5,
  "ae2:cell_component_16k":3,
  "ae2:singularity":8,
  "ae2:crafting_terminal":3,
  "botania:gaia_spreader":8,
  "botania:mana_fluxfield":3,
  "botania:gaia_spirit":8,
  "botania:floating_orechid":2,
  "compressium:obsidian_3":9,
  "compressium:silver_scrap_block_2":9,
  "compressium:quartz_2":4,
  "compressium:diamond_1":2,
  "compressium:carbon_block_2":5,
  "compressium:magic_silk_block_2":2,
  "compressium:soulsand_3":9,
  "compressium:coal_3":9,
  "compressium:lapis_3":1,
  "compressium:ancient_copper_block_3":9,
  "compressium:living_rock_block_cobble_4":3,
  "compressium:gilded_block_4":4,
  "compressium:rotten_meat_block_4":4,
  "compressium:sandy_block_4":4,
  "compressium:velvet_block_4":4,
  "compressium:chromatic_iron_block_2":5,
  "compressium:chromatic_steel_block_1":7,
  "compressium:ornate_block_4":2,
  "compressium:redstone_3":3,
  "compressium:copper_2":3,
  "compressium:iron_2":2,
  "compressium:clay_3":7,
  "compressium:gold_1":3,
  "cookingforblockheads:sink":9,
  "create:water_wheel":7,
  "create:large_water_wheel":3,
  "create:crushing_wheel":7,
  "create:mechanical_roller":7,
  "easy_villagers:iron_farm":7,
  "mekanism:qio_drive_hyper_dense":1,
  "mekanism:atomic_disassembler":1,
  "mekanism:elite_tier_installer":7,
  "mekanism:ultimate_tier_installer":5,
  "mekanism:ultimate_smelting_factory":3,
  "mekanism:ultimate_enriching_factory":3,
  "mekanism:ultimate_crushing_factory":3,
  "mekanism:ultimate_compressing_factory":3,
  "mekanism:ultimate_combining_factory":3,
  "mekanism:ultimate_purifying_factory":3,
  "mekanism:ultimate_injecting_factory":2,
  "mekanism:ultimate_infusing_factory":3,
  "mekanism:ultimate_sawing_factory":3,
  "mekanism:basic_induction_cell":3,
  "mekanismgenerators:gas_burning_generator":3,
  "mekanismgenerators:wind_generator":7,
  "pipez:ultimate_upgrade":3,
  "powah:capacitor_nitro":3,
  "powah:solar_panel_spirited":3,
  "powah:energy_hopper_spirited":3,
  "snad:snad":5,
  "snad:red_snad":5,
  "snad:suol_snad":5,
  "sophisticatedbackpacks:identification_upgrade_advanced":9,
  "sophisticatedbackpacks:recycler_upgrade":1,
  "sophisticatedbackpacks:advanced_pickup_upgrade":9,
  "sophisticatedbackpacks:restock_upgrade":7,
  "sophisticatedbackpacks:deposit_upgrade":7,
  "sophisticatedbackpacks:stack_upgrade_tier_3":5,
  "sophisticatedbackpacks:stack_upgrade_tier_4":1,
  "sophisticatedbackpacks:tool_swapper_upgrade":2,
  "thermal:machine_insolator":2,
  "thermal:device_rock_gen":7,
  "thermal:upgrade_augment_3":7,
  "cagerium:cage":5,
  "cagerium:ominous_skull":9,
  "cagerium:binding_gemstone":1,
  "the_vault:vault_palladium":3,
  "the_vault:echo_pog":2,
  "the_vault:key_iskallium":3,
  "the_vault:key_gorginite":3,
  "the_vault:key_sparkletine":3,
  "the_vault:key_ashium":3,
  "the_vault:key_bomignite":3,
  "the_vault:key_tubium":3,
  "the_vault:key_upaline":3,
  "the_vault:key_petzanite":3,
  "the_vault:key_xenium":3,
  "the_vault:bitter_lemon":3,
  "the_vault:sour_orange":3,
  "the_vault:mystic_pear":2,
  "the_vault:mango":2,
  "the_vault:key_mould":5,
  "the_vault:blank_key":4,
  "the_vault:cluster_netherite":7,
  "the_vault:chunk_iskallium":2,
  "the_vault:chunk_gorginite":2,
  "the_vault:chunk_sparkletine":2,
  "the_vault:chunk_ashium":2,
  "the_vault:chunk_bomignite":2,
  "the_vault:chunk_tubium":2,
  "the_vault:chunk_upaline":2,
  "the_vault:chunk_petzanite":2,
  "the_vault:chunk_xenium":2,
  "the_vault:omega_pog":2,
  "the_vault:knowledge_star":3,
  "the_vault:infused_eternal_soul":1,
  "the_vault:perfect_echo_gem":6,
  "the_vault:repair_core":7,
  "the_vault:vault_catalyst_chaos":8,
  "the_vault:capstone_blacksmith":2,
  "the_vault:crystal_seal_cake":8,
  "the_vault:unidentified_treasure_key":3,
  "the_vault:hardened_wutodic_mass":2,
  "the_vault:sublime_vault_elixir":5,
  "the_vault:sublime_vault_substance":3,
  "the_vault:extraordinary_echo_gem":2,
  "the_vault:memory_shard":3,
  "the_vault:sublime_vault_vision":3,
  "the_vault:deck_station":6,
  "the_vault:vault_harvester":2,
  "the_vault:unboxing_station":6,
  "the_vault:card_binder":4,
  "the_vault:companion_incubator":2,
  "the_vault:vault_anvil":6,
  "the_vault:angel_block":1,
  "the_vault:ascension_forge":3,
  "the_vault:vault_sealer":2,
  "ironfurnaces:diamond_furnace":7,
  "ironfurnaces:emerald_furnace":5,
  "ironfurnaces:netherite_furnace":2,
  "ironfurnaces:augment_generator":2,
  "ironfurnaces:rainbow_plating":7,
  "botanypots:terracotta_botany_pot":8,
  "botanypots:terracotta_hopper_botany_pot":5,
  "botanypots:purple_concrete_botany_pot":8,
  "botanypots:purple_concrete_hopper_botany_pot":5,
  "botanypots:purple_glazed_terracotta_botany_pot":8,
  "botanypots:purple_glazed_terracotta_hopper_botany_pot":5,
  "irongenerators:gold_generator":7,
  "irongenerators:diamond_generator":3,
  "fluxnetworks:flux_plug":8,
  "fluxnetworks:flux_point":8,
  "fluxnetworks:flux_controller":1,
  "fluxnetworks:herculean_flux_storage":4,
  "bonsaitrees3:bonsaipot":8,
  "pneumaticcraft:drone":3,
  "pneumaticcraft:assembly_platform":8,
  "pneumaticcraft:assembly_io_unit_import":8,
  "pneumaticcraft:assembly_io_unit_export":8,
  "pneumaticcraft:assembly_drill":7,
  "pneumaticcraft:assembly_laser":8,
  "pneumaticcraft:assembly_controller":3,
  "pneumaticcraft:programmer":8,
  "pneumaticcraft:solar_compressor":5,
  "pneumaticcraft:flux_compressor":4,
  "scannable:blank_module":5,
  "scannable:entity_module":5,
  "scannable:hostile_entity_module":5,
  "scannable:common_ores_module":5,
  "scannable:rare_ores_module":4,
  "scannable:vault_ores_module":1,
  "scannable:vault_chests_module_living":2,
  "scannable:vault_chests_module_ornate":2,
  "scannable:vault_chests_module_gilded":2,
  "scannable:vault_chests_module_wooden":2,
  "scannable:vault_chests_module_raw":2,
  "scannable:vault_chests_module_treasure":2,
  "scannable:vault_spirit_module":2,
  "sophisticatedstorage:diffuser_upgrade":2,
  "sophisticatedstorage:recycler_upgrade":1,
  "sophisticatedstorage:ornate_chest":8,
  "sophisticatedstorage:gilded_chest":8,
  "sophisticatedstorage:living_chest":8,
  "sophisticatedstorage:altar_chest":7,
  "sophisticatedstorage:enigma_chest":7,
  "sophisticatedstorage:ornate_strongbox":7,
  "sophisticatedstorage:gilded_strongbox":7,
  "sophisticatedstorage:living_strongbox":7,
  "sophisticatedstorage:unique_crate":5,
  "sophisticatedstorage:ornate_barrel":4,
  "sophisticatedstorage:gilded_barrel":4,
  "sophisticatedstorage:living_barrel":4,
  "sophisticatedstorage:wooden_barrel":4,
  "sophisticatedstorage:netherite_barrel":8,
  "sophisticatedstorage:limited_netherite_barrel_1":8,
  "sophisticatedstorage:limited_netherite_barrel_2":8,
  "sophisticatedstorage:limited_netherite_barrel_3":8,
  "sophisticatedstorage:limited_netherite_barrel_4":8,
  "sophisticatedstorage:netherite_chest":8,
  "sophisticatedstorage:controller":4,
  "sophisticatedstorage:basic_to_netherite_tier_upgrade":8,
  "sfm:manager":2,
  "weather_control:rm_sensor":4,
  "weather_control:rm_core":2,
  "weather_control:dw_core":2,
  "woldsvaults:crystal_seal_unhinged":4,
  "woldsvaults:crystal_seal_spirits":5,
  "woldsvaults:crystal_seal_enchanter":3,
  "woldsvaults:crystal_seal_titan":3,
  "woldsvaults:crystal_seal_doomsayer":3,
  "woldsvaults:crystal_seal_corrupt":1,
  "woldsvaults:crystal_seal_alchemy":3,
  "woldsvaults:omega_box":5,
  "woldsvaults:repair_augmenter":2,
  "woldsvaults:hasty_pomegranate":6,
  "woldsvaults:mercy_orb":4,
  "woldsvaults:wold_star_chunk":6,
  "woldsvaults:pog_prism":5,
  "woldsvaults:arcane_essence":6,
  "woldsvaults:poltergeist_plum":6,
  "woldsvaults:pogominium_ingot":2,
  "woldsvaults:chunk_of_power":3,
  "woldsvaults:ruined_essence":2,
  "woldsvaults:nullite_fragment":2,
  "woldsvaults:prismatic_fiber":2,
  "woldsvaults:chroma_core":2,
  "woldsvaults:pogging_seed_base":2,
  "woldsvaults:vault_salvager":2,
  "woldsvaults:mod_box_workstation":2,
  "woldsvaults:chromatic_steel_vault_infuser":6,
  "botanicalmachinery:mechanical_daisy":8,
  "integrateddynamics:part_connector_omni_directional":9,
  "integratedterminals:part_terminal_storage":3,
  "integratedterminals:part_terminal_crafting_job":4,
  "integratedtunnels:part_player_simulator":2,
  "toms_storage:ts.crafting_terminal":5,
  "psi:programmer":5,
  "computercraft:turtle_normal":3,
  "advancedperipherals:block_reader":6,
  "appbot:mana_cell_housing":3,
  "appliedcooking:kitchen_station":3,
  "ars_nouveau:glyph_split":3,
  "ars_nouveau:enchanting_apparatus":4,
  "ars_nouveau:relay":3,
  "ars_nouveau:relay_splitter":3,
  "ars_nouveau:arcane_core":8,
  "ars_nouveau:ritual_brazier":2,
  "ars_nouveau:basic_spell_turret":4,
  "botanicalextramachinery:malachite_dragonstone":3,
  "ccvault:vault_reader":4,
  "experienceobelisk:astute_assembly":5,
  "experienceobelisk:experience_obelisk":3,
  "experienceobelisk:experience_fountain":2,
  "createaddition:electric_motor":9,
  "createdieselgenerators:huge_diesel_engine":3,
  "create_mechanical_extruder:mechanical_extruder":5,
  "createoreexcavation:drilling_machine":2,
  "industrialforegoing:plant_gatherer":3,
  "industrialforegoing:hydroponic_bed":3,
  "industrialforegoing:marine_fisher":3,
  "industrialforegoing:laser_drill":3,
  "industrialforegoing:infinity_charger":3,
  "industrialforegoing:machine_frame_simple":4,
  "industrialforegoing:machine_frame_advanced":3,
  "industrialforegoing:machine_frame_supreme":2,
  "industrialforegoing:speed_addon_1":2,
  "industrialforegoing:efficiency_addon_1":2,
  "industrialforegoing:simple_black_hole_unit":3,
  "integratedcrafting:part_interface_crafting":3,
  "littlelogistics:rapid_hopper":8,
  "megacells:mega_energy_cell":1,
  "megacells:mega_crafting_accelerator":6,
  "megacells:mega_crafting_monitor":7,
  "peripherals:trading_interface":3,
  "peripherals:anvil_interface":5,
  "occultism:wormhole_frame":5,
  "occultism:storage_remote_inert":6,
  "occultism:magic_lamp_empty":8,
  "occultism:stable_wormhole":5,
  "occultism:storage_controller_base":2,
  "quarryplus:workbench":8,
  "quarryplus:mining_well":2,
  "quarryplus:exp_pump":7,
  "quarryplus:marker":3,
  "quarryplus:flex_marker":3,
  "quarryplus:marker16":3,
  "rftoolspower:blazing_generator":5,
  "rftoolspower:dimensionalcell":5,
  "rftoolspower:dimensionalcelladvanced":2,
  "rftoolspower:endergenic":5,
  "rftoolspower:cell1":5,
  "rftoolsstorage:storage_module3":3,
  "rftoolsstorage:storage_scanner":8,
  "rftoolsutility:matter_booster":2,
  "rftoolsutility:haste_module":5,
  "rftoolsutility:glowing_module":5,
  "rftoolsutility:nightvision_module":5,
  "thermal_extra:av_item_filter_augment":5,
  "thermal_extra:area_radius_augment_3":2,
  "thermal_extra:rf_coil_storage_augment_2":2,
  "thermal_extra:fluid_tank_augment_1":3,
  "thermal_extra:machine_efficiency_augment_2":3,
  "thermal_extra:machine_output_augment_3":2,
  "thermal_extra:dynamo_fuel_augment_3":3,
  "tiab:time_in_a_bottle":1,
  "immersiveengineering:tesla_coil":2,
  "immersiveengineering:coil_mv":2,
  "immersiveengineering:generator":2,
  "immersiveengineering:transformer":2,
  "immersivepetroleum:gas_generator":2,
  "grapplemod:block_grapple_modifier":5,
  "adfinders:metal_finder":2,
  "adfinders:mineral_finder":2,
  "summoningrituals:altar":8,
  "summoningrituals:indestructible_altar":5,
  "silence_s_defense_tower:brand_new":8,
  "silence_s_defense_tower:overclock":3,
  "silence_s_defense_tower:pactof_blood":3,
  "silence_s_defense_tower:arrogance":2,
  "silence_s_defense_tower:large_fireworks_2":6,
  "silence_s_defense_tower:battery_1":2,
  "silence_s_defense_tower:arcane_missiles_1":5,
  "silence_s_defense_tower:flesh_armor_1":8,
  "silence_s_defense_tower:heavy_armor":2,
  "silence_s_defense_tower:slime_armor_1":3,
  "silence_s_defense_tower:tesla_electric_tower":3,
  "silence_s_defense_tower:firework_launcher_p":2,
  "silence_s_defense_tower:hell_core_3":2,
  "silence_s_defense_tower:reinforcement_materials_2":8,
  "vaultbeacon:vault_beacon":5,
  "vaultbeacon:black_haste_catalyst":4,
  "vaultbeacon:black_jump_catalyst":4,
  "vaultbeacon:black_speed_catalyst":4,
  "vaultbeacon:black_range_catalyst":4,
  "cardsnboards:coin_chip_5_0_0":6,
  "car:generator":8,
  "car:engine_6_cylinder":8,
  "car:red_tank_container":4,
  "car:medium_tank":6,
  "vending_companions:companion_vending_machine":2
};

onEvent('item.right_click', event => {
  if (event.item.id == 'tfb2:trade_order_good') {
    let randomName = GOOD_NAMES[Math.floor(Math.random() * GOOD_NAMES.length)];
    let randomAddress = GOOD_ADDRESS[Math.floor(Math.random() * GOOD_ADDRESS.length)];
    let randomMessage = GOOD_MESSAGES[Math.floor(Math.random() * GOOD_MESSAGES.length)];
    let randomRequestItem = Object.keys(GOOD_REQUESTABLE_ITEMS)[ Math.floor(Math.random() * Object.keys(GOOD_REQUESTABLE_ITEMS).length) ]
    let randomRewardItem = Object.keys(GOOD_REWARD_ITEMS)[ Math.floor(Math.random() * Object.keys(GOOD_REWARD_ITEMS).length) ]

    console.log('give ' + event.getEntity() + ' wares:sealed_delivery_agreement{message:{"text":"' + randomMessage + '"},buyerAddress:{"text":"' + randomAddress + '"},buyerName:{"text":"' + randomName + '"}, requested:[{id:"' + randomRequestItem + '",Count:' + GOOD_REQUESTABLE_ITEMS[randomRequestItem] +'}],payment:[{id:"' + randomRewardItem + '",Count:' + GOOD_REWARD_ITEMS[randomRewardItem] + '}],ordered:' + (1 + Math.floor(Math.random() * 10)) + '}')
    
    event.server.runCommandSilent('give ' + event.getEntity() + ' wares:delivery_agreement{title:\'{"text":"[Good Trade Order]"}\',message:\'{"text":"' + randomMessage + '"}\',buyerAddress:\'{"text":"' + randomAddress + '"}\',buyerName:\'{"text":"' + randomName + '"}\', requestedItems:[{id:"' + randomRequestItem + '",Count:' + GOOD_REQUESTABLE_ITEMS[randomRequestItem] +'}],paymentItems:[{id:"' + randomRewardItem + '",Count:' + GOOD_REWARD_ITEMS[randomRewardItem] + '}],ordered:' + (1 + Math.floor(Math.random() * 10)) + '}');
	  
	if (!event.player.isCreativeMode()) { //if creative mode dont consume; not necessary
	  event.item.setCount(event.item.getCount() - 1)
	}
  }
});