// CHEAP
const AMAZING_NAMES = [
  "Sole Carver",
  "Just a Gnome",
  "Simply Goblin",
  "Tiger Striped Yinglet",
  "Green Dragon",
  "Green Pony",
  "Slicer Von Dicer",
  "Magical Brat",
  "Flaming Fancy",
  "Fancy Feast",
  "Easy Squeezy"
];

const AMAZING_ADDRESS = [
  "Kanto Server",
  "Johto Server",
  "Hoenn Server",
  "Sinnoh Server",
  "Unova Server",
  "Kalos Server",
  "Alola Server",
  "Galar Server",
  "Paldea Server",
  "Sevii Island Server",
  "Isle of Armor Server",
  "Crown Tundra Server",
  "Kitakami Server",
  "Orre Server",
  "Fiore Server",
  "Almia Server",
  "Oblivia Server",
  "Companion Park Server",
  "Mintale Server",
  "Ransei Server",
  "Ryme Server",
  "Tumblecube Server",
  "Ferrum Server",
  "Pasio Server",
  "Aeos Server",
  "Apple Server",
  "Orange Server",
  "Mango Server",
  "Strawberry Server",
  "Grape Server",
  "Lemon Server",
  "Lime Server",
  "Neo Turkey Server",
  "Neo Japan Server",
  "Guyana Server",
  "Neo Hong Kong Server",
  "Neo England Server",
  "Neo Egypt Server",
  "Neo Mexico Server",
  "Neo America Server",
  "Neo France Server"
];

const AMAZING_MESSAGES = [
  "Look, don`t ask why I need this, I just do!",
  "I think my Vault Altar is broken, why is it asking for these? A little help?",
  "I`m in a bit of trouble, I need these to fill my own Work Order and I`m out of all the items!",
  "I`m just missing these from my collection.",
  "Hi! I heard about this service and I wanted to give it a little test!",
  "Does this system even work? Hello?",
  "Third time`s a charm trying to get this item.",
  "My Vault Companion started eating my supplies. Is it glitched? Whatever, I need to replace them before my party gets angry."
];

const AMAZING_REQUESTABLE_ITEMS = {
  "ae2:256k_crafting_storage":3,
  "ae2:cell_component_256k":3,
  "botania:creative_pool":1,
  "compressium:obsidian_5":2,
  "compressium:silver_scrap_block_4":2,
  "compressium:quartz_3":5,
  "compressium:diamond_2":2,
  "compressium:vault_diamond_block_3":2,
  "compressium:carbon_block_3":6,
  "compressium:netherite_1":4,
  "compressium:magic_silk_block_3":2,
  "compressium:soulsand_4":10,
  "compressium:coal_4":10,
  "compressium:lapis_4":2,
  "compressium:emerald_2":3,
  "compressium:ancient_copper_block_5":2,
  "compressium:chromatic_gold_block_1":2,
  "compressium:gilded_block_5":3,
  "compressium:rotten_meat_block_5":3,
  "compressium:sandy_block_5":3,
  "compressium:velvet_block_5":3,
  "compressium:chromatic_iron_block_3":6,
  "compressium:chromatic_steel_block_3":1,
  "compressium:ornate_block_5":3,
  "compressium:redstone_4":3,
  "compressium:copper_3":3,
  "compressium:iron_3":2,
  "compressium:clay_5":1,
  "compressium:gold_2":4,
  "compressium:vault_plating_block_3":5,
  "create:creative_motor":1,
  "create:creative_fluid_tank":1,
  "mekanismgenerators:fusion_reactor_controller":4,
  "powah:magmator_nitro":7,
  "sophisticatedbackpacks:diffuser_upgrade":3,
  "sophisticatedbackpacks:diffuser_upgrade_advanced":2,
  "sophisticatedbackpacks:recycler_upgrade_advanced":6,
  "sophisticatedbackpacks:diamond_backpack":5,
  "sophisticatedbackpacks:netherite_backpack":3,
  "sophisticatedbackpacks:battery_upgrade":5,
  "thermal:rf_coil_creative_augment":2,
  "thermal:fluid_tank_creative_augment":2,
  "thermal:machine_efficiency_creative_augment":2,
  "thermal:machine_catalyst_creative_augment":2,
  "ironfurnaces;rainbow_core":6,
  "ironfurnaces:million_furnace":3,
  "fluxnetworks:gargantuan_flux_storage":7,
  "ae2things:disk_drive_256k":3,
  "botanypotstiers:ultra_purple_concrete_botany_pot":3,
  "botanypotstiers:creative_magenta_glazed_terracotta_botany_pot":2,
  "scannable:range_module":4,
  "scannable:vault_chests_module":2,
  "scannable:vault_objectives_module":4,
  "scannable:vault_dungeon_doors_module":5,
  "scannable:vault_treasure_doors_module":5,
  "scannable:vault_vendoors_module":5,
  "scannable:vault_pylon_module":5,
  "scannable:vault_coins_module":5,
  "sophisticatedstorage:diffuser_upgrade_advanced":5,
  "weather_control:rm_offline":6,
  "weather_control:dw_offline":3,
  "woldsvaults:chromatic_iron_angel_ring":3,
  "woldsvaults:chromatic_gold_angel_ring":1,
  "woldsvaults:expertise_orb":1,
  "woldsvaults:resonating_reinforcement":7,
  "woldsvaults:zephyr_charm":1,
  "woldsvaults:uber_chaos_catalyst":2,
  "woldsvaults:wold_star":2,
  "woldsvaults:extraordinary_pog_prism":4,
  "woldsvaults:heart_of_chaos":2,
  "woldsvaults:idona_dagger":7,
  "woldsvaults:wendarr_gem":7,
  "woldsvaults:velara_apple":7,
  "woldsvaults:tome_of_tenos":7,
  "woldsvaults:xl_backpack":1,
  "woldsvaults:nullite_crystal":3,
  "woldsvaults:echoing_seed_base":3,
  "botanicalmachinery:mana_battery_creative":1,
  "integrateddynamics:energy_battery_creative":2,
  "incorporeal:quintuple_compressed_tiny_potato":2,
  "appbot:mana_storage_cell_64k":7,
  "appmek:chemical_storage_cell_256k":3,
  "botanicalextramachinery:base_mana_pool":1,
  "botanicalextramachinery:base_runic_altar":1,
  "botanicalextramachinery:base_daisy":1,
  "botanicalextramachinery:base_apothecary":1,
  "botanicalextramachinery:base_industrial_agglomeration_factory":1,
  "botanicalextramachinery:base_alfheim_market":1,
  "botanicalextramachinery:base_orechid":1,
  "botanicalextramachinery:saffron_dragonstone":5,
  "botanicalextramachinery:shadow_dragonstone":2,
  "botanicalextramachinery:shadow_ingot":2,
  "botanicalextramachinery:malachite_spark":2,
  "industrialforegoing:supreme_black_hole_unit":2,
  "industrialforegoing:supreme_black_hole_tank":2,
  "occultism:storage_stabilizer_tier4":6,
  "quarryplus:quarry":3,
  "quarryplus:solid_fuel_quarry":5,
  "quarryplus:pump_plus":7,
  "quarryplus:adv_pump":2,
  "quarryplus:adv_quarry":1,
  "quarryplus:pump_module":6,
  "rftoolspower:cell3":7,
  "rftoolsutility:environmental_controller":5,
  "thermal_extra:rf_coil_augment_5":4,
  "thermal_extra:rf_coil_storage_augment_5":4,
  "thermal_extra:rf_coil_xfer_augment_5":4,
  "thermal_extra:fluid_tank_augment_5":4,
  "thermal_extra:machine_speed_augment_3":5,
  "thermal_extra:machine_speed_augment_4":3,
  "adfinders:gem_finder":3,
  "pocketstorage:psu_3":2,
  "silence_s_defense_tower:hellraiser_level_4_p":5,
  "silence_s_defense_tower:tyrant_cannon_level2_p":5
};

const AMAZING_REWARD_ITEMS = {
  "ae2:256k_crafting_storage":4,
  "ae2:cell_component_256k":4,
  "botania:creative_pool":1,
  "compressium:obsidian_5":2,
  "compressium:silver_scrap_block_4":2,
  "compressium:quartz_3":7,
  "compressium:diamond_2":2,
  "compressium:vault_diamond_block_3":3,
  "compressium:carbon_block_3":8,
  "compressium:netherite_1":6,
  "compressium:magic_silk_block_3":2,
  "compressium:soulsand_4":13,
  "compressium:coal_4":13,
  "compressium:lapis_4":2,
  "compressium:emerald_2":4,
  "compressium:ancient_copper_block_5":2,
  "compressium:chromatic_gold_block_1":3,
  "compressium:gilded_block_5":4,
  "compressium:rotten_meat_block_5":4,
  "compressium:sandy_block_5":4,
  "compressium:velvet_block_5":4,
  "compressium:chromatic_iron_block_3":7,
  "compressium:chromatic_steel_block_3":2,
  "compressium:ornate_block_5":4,
  "compressium:redstone_4":4,
  "compressium:copper_3":4,
  "compressium:iron_3":3,
  "compressium:clay_5":2,
  "compressium:gold_2":6,
  "compressium:vault_plating_block_3":7,
  "create:creative_motor":1,
  "create:creative_fluid_tank":1,
  "mekanismgenerators:fusion_reactor_controller":5,
  "powah:magmator_nitro":9,
  "sophisticatedbackpacks:diffuser_upgrade":4,
  "sophisticatedbackpacks:diffuser_upgrade_advanced":2,
  "sophisticatedbackpacks:recycler_upgrade_advanced":7,
  "sophisticatedbackpacks:diamond_backpack":7,
  "sophisticatedbackpacks:netherite_backpack":4,
  "sophisticatedbackpacks:battery_upgrade":6,
  "thermal:rf_coil_creative_augment":2,
  "thermal:fluid_tank_creative_augment":2,
  "thermal:machine_efficiency_creative_augment":2,
  "thermal:machine_catalyst_creative_augment":2,
  "ironfurnaces;rainbow_core":7,
  "ironfurnaces:million_furnace":4,
  "fluxnetworks:gargantuan_flux_storage":9,
  "ae2things:disk_drive_256k":4,
  "botanypotstiers:ultra_purple_concrete_botany_pot":4,
  "botanypotstiers:creative_magenta_glazed_terracotta_botany_pot":3,
  "scannable:range_module":5,
  "scannable:vault_chests_module":3,
  "scannable:vault_objectives_module":5,
  "scannable:vault_dungeon_doors_module":7,
  "scannable:vault_treasure_doors_module":7,
  "scannable:vault_vendoors_module":7,
  "scannable:vault_pylon_module":7,
  "scannable:vault_coins_module":7,
  "sophisticatedstorage:diffuser_upgrade_advanced":7,
  "weather_control:rm_offline":8,
  "weather_control:dw_offline":4,
  "woldsvaults:chromatic_iron_angel_ring":4,
  "woldsvaults:chromatic_gold_angel_ring":1,
  "woldsvaults:expertise_orb":1,
  "woldsvaults:resonating_reinforcement":9,
  "woldsvaults:zephyr_charm":1,
  "woldsvaults:uber_chaos_catalyst":2,
  "woldsvaults:wold_star":2,
  "woldsvaults:extraordinary_pog_prism":5,
  "woldsvaults:heart_of_chaos":2,
  "woldsvaults:idona_dagger":9,
  "woldsvaults:wendarr_gem":9,
  "woldsvaults:velara_apple":9,
  "woldsvaults:tome_of_tenos":9,
  "woldsvaults:xl_backpack":1,
  "woldsvaults:nullite_crystal":4,
  "woldsvaults:echoing_seed_base":4,
  "botanicalmachinery:mana_battery_creative":1,
  "integrateddynamics:energy_battery_creative":2,
  "incorporeal:quintuple_compressed_tiny_potato":2,
  "appbot:mana_storage_cell_64k":9,
  "appmek:chemical_storage_cell_256k":4,
  "botanicalextramachinery:base_mana_pool":1,
  "botanicalextramachinery:base_runic_altar":1,
  "botanicalextramachinery:base_daisy":1,
  "botanicalextramachinery:base_apothecary":1,
  "botanicalextramachinery:base_industrial_agglomeration_factory":1,
  "botanicalextramachinery:base_alfheim_market":1,
  "botanicalextramachinery:base_orechid":1,
  "botanicalextramachinery:saffron_dragonstone":7,
  "botanicalextramachinery:shadow_dragonstone":2,
  "botanicalextramachinery:shadow_ingot":3,
  "botanicalextramachinery:malachite_spark":2,
  "industrialforegoing:supreme_black_hole_unit":3,
  "industrialforegoing:supreme_black_hole_tank":3,
  "occultism:storage_stabilizer_tier4":8,
  "quarryplus:quarry":4,
  "quarryplus:solid_fuel_quarry":7,
  "quarryplus:pump_plus":9,
  "quarryplus:adv_pump":3,
  "quarryplus:adv_quarry":1,
  "quarryplus:pump_module":8,
  "rftoolspower:cell3":9,
  "rftoolsutility:environmental_controller":7,
  "thermal_extra:rf_coil_augment_5":5,
  "thermal_extra:rf_coil_storage_augment_5":5,
  "thermal_extra:rf_coil_xfer_augment_5":5,
  "thermal_extra:fluid_tank_augment_5":5,
  "thermal_extra:machine_speed_augment_3":7,
  "thermal_extra:machine_speed_augment_4":4,
  "adfinders:gem_finder":4,
  "pocketstorage:psu_3":3,
  "silence_s_defense_tower:hellraiser_level_4_p":7,
  "silence_s_defense_tower:tyrant_cannon_level2_p":7
};

onEvent('item.right_click', event => {
  if (event.item.id == 'tfb2:trade_order_amazing') {
    let randomName = AMAZING_NAMES[Math.floor(Math.random() * AMAZING_NAMES.length)];
    let randomAddress = AMAZING_ADDRESS[Math.floor(Math.random() * AMAZING_ADDRESS.length)];
    let randomMessage = AMAZING_MESSAGES[Math.floor(Math.random() * AMAZING_MESSAGES.length)];
    let randomRequestItem = Object.keys(AMAZING_REQUESTABLE_ITEMS)[ Math.floor(Math.random() * Object.keys(AMAZING_REQUESTABLE_ITEMS).length) ]
    let randomRewardItem = Object.keys(AMAZING_REWARD_ITEMS)[ Math.floor(Math.random() * Object.keys(AMAZING_REWARD_ITEMS).length) ]

    console.log('give ' + event.getEntity() + ' wares:sealed_delivery_agreement{message:{"text":"' + randomMessage + '"},buyerAddress:{"text":"' + randomAddress + '"},buyerName:{"text":"' + randomName + '"}, requested:[{id:"' + randomRequestItem + '",Count:' + AMAZING_REQUESTABLE_ITEMS[randomRequestItem] +'}],payment:[{id:"' + randomRewardItem + '",Count:' + AMAZING_REWARD_ITEMS[randomRewardItem] + '}],ordered:' + (1 + Math.floor(Math.random() * 10)) + '}')
    
    event.server.runCommandSilent('give ' + event.getEntity() + ' wares:delivery_agreement{title:\'{"text":"[Amazing Trade Order]"}\',message:\'{"text":"' + randomMessage + '"}\',buyerAddress:\'{"text":"' + randomAddress + '"}\',buyerName:\'{"text":"' + randomName + '"}\', requestedItems:[{id:"' + randomRequestItem + '",Count:' + AMAZING_REQUESTABLE_ITEMS[randomRequestItem] +'}],paymentItems:[{id:"' + randomRewardItem + '",Count:' + AMAZING_REWARD_ITEMS[randomRewardItem] + '}],ordered:' + (1 + Math.floor(Math.random() * 10)) + '}');
	  
	if (!event.player.isCreativeMode()) { //if creative mode dont consume; not necessary
	  event.item.setCount(event.item.getCount() - 1)
	}
  }
});