const ALLOWED_DIMENSIONS = [
    'minecraft:overworld',
    'minecraft:the_nether',
    'minecraft:the_end',
    'bonsaitrees3:growtown',
    'tropicraft:tropics',
    'minestuck:skaia',
    'javd:void',
    'lostcities:lostcity',
    'mahoutsukai:reality_marble',
    'ae2:spatial_storage'
];

const MAHOU_ITEMS = [
    'mahoutsukai:dagger',
    'mahoutsukai:weapon_projectile_bow',
    'mahoutsukai:caliburn',
    'mahoutsukai:clarent',
    'mahoutsukai:morgan',
    'mahoutsukai:hammer',
    'mahoutsukai:mystic_code',
    'mahoutsukai:attuner',
    'mahoutsukai:attuned_diamond',
    'mahoutsukai:attuned_emerald',
    'mahoutsukai:pestle',
    'mahoutsukai:theripper',
    'mahoutsukai:staff_emrys',
    'mahoutsukai:replica',
    'mahoutsukai:mystic_code_first_sorcery',
    'mahoutsukai:mortar',
    'mahoutsukai:kodoku',
    'mahoutsukai:faecake',
    'mahoutsukai:mortar_and_pestle',
    'mahoutsukai:proximity_projection_keys',
    'mahoutsukai:murky_bucket',
    'mahoutsukai:treasury_projection_gauntlet',
    'mahoutsukai:powdered_diamond',
    'mahoutsukai:powdered_emerald',
    'mahoutsukai:powdered_ender',
    'mahoutsukai:powdered_eye',
    'mahoutsukai:powdered_gold',
    'mahoutsukai:powdered_iron',
    'mahoutsukai:powdered_quartz',
    'mahoutsukai:fae_essence',
    'mahoutsukai:mystic_staff',
    'mahoutsukai:spatial_disorientation_staff',
    'mahoutsukai:rule_breaker',
    'mahoutsukai:scroll_boundary_displacement',
    'mahoutsukai:scroll_boundary_alarm',
    'mahoutsukai:scroll_boundary_raise_enclosure',
    'mahoutsukai:scroll_boundary_tangible',
    'mahoutsukai:scroll_boundary_gravity',
    'mahoutsukai:scroll_boundary_drain_life',
    'mahoutsukai:scroll_weapon_shooter',
    'mahoutsukai:scroll_projection',
    'mahoutsukai:scroll_projection',
    'mahoutsukai:scroll_reality_marble',
    'mahoutsukai:scroll_strengthening',
    'mahoutsukai:scroll_treasury_projection',
    'mahoutsukai:scroll_proximity_projection',
    'mahoutsukai:scroll_damage_exchange',
    'mahoutsukai:scroll_immunity_exchange',
    'mahoutsukai:scroll_projectile_displacement',
    'mahoutsukai:scroll_protective_displacement',
    'mahoutsukai:scroll_death_collection',
    'mahoutsukai:scroll_black_flame',
    'mahoutsukai:scroll_mental_displacement',
    'mahoutsukai:scroll_ascension',
    'mahoutsukai:scroll_prediction',
    'mahoutsukai:scroll_mystic_eyes',
    'mahoutsukai:scroll_fay_sight',
    'mahoutsukai:scroll_insight',
    'mahoutsukai:scroll_familiars_garden',
    'mahoutsukai:scroll_possess_entity',
    'mahoutsukai:scroll_reversion_eyes',
    'mahoutsukai:scroll_recall_familiar',
    'mahoutsukai:scroll_damage_replication',
    'mahoutsukai:scroll_spatial_disorientation',
    'mahoutsukai:scroll_rho_aias',
    'mahoutsukai:scroll_butterfly_effect',
    'mahoutsukai:scroll_borrowed_authority',
    'mahoutsukai:scroll_summon_familiar',
    'mahoutsukai:scroll_mystic_staff',
    'mahoutsukai:scroll_swap_familiar',
    'mahoutsukai:scroll_cup_of_heaven',
    'mahoutsukai:scroll_presence_concealment',
    'mahoutsukai:scroll_geas',
    'mahoutsukai:scroll_retribution',
    'mahoutsukai:scroll_gandr',
    'mahoutsukai:scroll_probability_alter',
    'mahoutsukai:scroll_fallen_down',
    'mahoutsukai:scroll_selective_displacement',
    'mahoutsukai:mahoujin',
    'mahoutsukai:mahoujin_projector',
    'mahoutsukai:fog_projector',
    'mahoutsukai:spell_cloth',
    'mahoutsukai:mana_circuit',
    'mahoutsukai:mana_circuit_magitech',
    'mahoutsukai:murky_bucket'
];

onEvent('item.right_click', event => {
  if(!ALLOWED_DIMENSIONS.includes(String(event.level.dimension)) && MAHOU_ITEMS.includes(String(event.item.id))) { 
    //event.player.tell(Text.red("UNAUTHORIZED ACCESS. CONTACT ADMINISTRATOR."))
    event.cancel()
  }
});

onEvent('block.right_click', event => {
  if(!ALLOWED_DIMENSIONS.includes(String(event.level.dimension)) && MAHOU_ITEMS.includes(String(event.item.id))) { 
    //event.player.tell(Text.red("UNAUTHORIZED ACCESS. CONTACT ADMINISTRATOR."))
    event.cancel()
  }
});