// priority: 0

console.info('Hello, World! (You will only see this line once in console, during startup)')

onEvent('item.registry', event => {
	event.create('tfb2:grist_build').group('tfb2').displayName('Grist - Build')
	event.create('tfb2:grist_amber').group('tfb2').displayName('Grist - Amber')
	event.create('tfb2:grist_amethyst').group('tfb2').displayName('Grist - Amethyst')
	event.create('tfb2:grist_artifact').group('tfb2').displayName('Grist - Artifact')
	event.create('tfb2:grist_caulk').group('tfb2').displayName('Grist - Caulk')
	event.create('tfb2:grist_chalk').group('tfb2').displayName('Grist - Chalk')
	event.create('tfb2:grist_cobalt').group('tfb2').displayName('Grist - Cobalt')
	event.create('tfb2:grist_diamond').group('tfb2').displayName('Grist - Diamond')
	event.create('tfb2:grist_garnet').group('tfb2').displayName('Grist - Garnet')
	event.create('tfb2:grist_gold').group('tfb2').displayName('Grist - Gold')
	event.create('tfb2:grist_iodine').group('tfb2').displayName('Grist - Iodine')
	event.create('tfb2:grist_marble').group('tfb2').displayName('Grist - Marble')
	event.create('tfb2:grist_mercury').group('tfb2').displayName('Grist - Mercury')
	event.create('tfb2:grist_quartz').group('tfb2').displayName('Grist - Quartz')
	event.create('tfb2:grist_ruby').group('tfb2').displayName('Grist - Ruby')
	event.create('tfb2:grist_rust').group('tfb2').displayName('Grist - Rust')
	event.create('tfb2:grist_shale').group('tfb2').displayName('Grist - Shale')
	event.create('tfb2:grist_sulfur').group('tfb2').displayName('Grist - Sulfur')
	event.create('tfb2:grist_tar').group('tfb2').displayName('Grist - Tar')
	event.create('tfb2:grist_uranium').group('tfb2').displayName('Grist - Uranium')
	event.create('tfb2:grist_zillium').group('tfb2').displayName('Grist - Zillium')
	event.create('tfb2:grist_rainbownium').group('tfb2').displayName('Grist - Rainbownium')
	event.create('tfb2:grist_vitaminv').group('tfb2').displayName('Grist - Vitamin V')
	event.create('tfb2:grist_ego').group('tfb2').displayName('Grist - Ego')
	event.create('tfb2:grist_chroma').group('tfb2').displayName('Grist - Chroma')
	event.create('tfb2:grist_morkite').group('tfb2').displayName('Grist - Morkite')
    event.create('tfb2:ferret_dollar').group('tfb2').displayName('Ferret Dollar')
    })


onEvent('block.registry', event => {
	// Register new blocks here
	// event.create('example_block').material('wood').hardness(1.0).displayName('Example Block')
})

// WOLDS CUSTOM ITEMS AND BLOCKS

onEvent('item.registry', event => {
	event.create('the_vault:vault_palladium').group('the_vault')
	event.create('the_vault:vault_iridium').group('the_vault')
	event.create('the_vault:chromatic_gold_ingot').group('the_vault')
	event.create('the_vault:chromatic_gold_nugget').group('the_vault')
	event.create('the_vault:prismatic_leather').group('the_vault')
	event.create('the_vault:smashed_vault_gem').group('the_vault')
	event.create('the_vault:smashed_vault_gem_cluster').group('the_vault').displayName('Smashed Gem Cluster')
	event.create('the_vault:wold_star').group('the_vault')
	event.create('the_vault:wold_star_chunk').group('the_vault')
	event.create('mysticalagriculture:pogging_seed_base').group('the_vault')
	event.create('mysticalagriculture:echoing_seed_base').group('the_vault')
	event.create('botania:uninfused_terrasteel_ingot').group('the_vault')
	event.create('the_vault:pog_prism').group('the_vault')
	event.create('woldsvaults:general_decor_scroll').group('the_vault').displayName('Vault Deco Scroll')
	event.create('woldsvaults:arcane_essence').group('the_vault').displayName('Arcane Essence')
	event.create('woldsvaults:arcane_shard').group('the_vault').displayName('Arcane Shard')
	event.create('woldsvaults:extraordinary_pog_prism').group('the_vault').displayName('Extraordinary Pog Prism')
	event.create('woldsvaults:heart_of_chaos').group('the_vault').displayName('Heart of Chaos')
})

onEvent('block.registry', event => {
	event.create('the_vault:silver_scrap_1').displayName('1x Compressed Silver Scrap').tagBlock('minecraft:mineable/pickaxe')
	event.create('the_vault:silver_scrap_2').displayName('2x Compressed Silver Scrap').tagBlock('minecraft:mineable/pickaxe')
	event.create('the_vault:chromatic_gold_block').displayName('Block of Chromatic Gold').tagBlock('minecraft:mineable/pickaxe').tag('forge:storage_blocks/chromatic_gold')
	//Gem Blocks
	event.create('the_vault:block_gem_larimar').displayName('Block of Larimar Gem').tagBlock('forge:storage_blocks/larimar').tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:beacon_base_blocks')
	event.create('the_vault:block_gem_benitoite').displayName('Block of Benitoite Gem').tagBlock('forge:storage_blocks/benitoite').tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:beacon_base_blocks')
	event.create('the_vault:block_gem_wutodie').displayName('Block of Wutodie Gem').tagBlock('forge:storage_blocks/wutodie').tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:beacon_base_blocks')
	event.create('the_vault:block_gem_painite').displayName('Block of Painite Gem').tagBlock('forge:storage_blocks/painite').tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:beacon_base_blocks')
	event.create('the_vault:block_gem_alexandrite').displayName('Block of Alexandrite Gem').tagBlock('forge:storage_blocks/alexandrite').tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:beacon_base_blocks')
	event.create('the_vault:block_gem_black_opal').displayName('Block of Black Opal Gem').tagBlock('forge:storage_blocks/black_opal').tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:beacon_base_blocks')
	event.create('the_vault:block_gem_echo').displayName('Block of Echo Gem').tagBlock('forge:storage_blocks/echo').tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:beacon_base_blocks')
	event.create('the_vault:block_gem_sparkletine').displayName('Block of Sparkletine Gem').tagBlock('forge:storage_blocks/sparkletine').tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:beacon_base_blocks')
	event.create('the_vault:block_gem_iskallium').displayName('Block of Iskallium Gem').tagBlock('forge:storage_blocks/iskallium').tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:beacon_base_blocks')
	event.create('the_vault:block_gem_upaline').displayName('Block of Upaline Gem').tagBlock('forge:storage_blocks/upaline').tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:beacon_base_blocks')
	event.create('the_vault:block_gem_xenium').displayName('Block of Xeenium Gem').tagBlock('forge:storage_blocks/xenium').tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:beacon_base_blocks')
	event.create('the_vault:block_gem_petzanite').displayName('Block of Petezanite Gem').tagBlock('forge:storage_blocks/petzanite').tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:beacon_base_blocks')
	event.create('the_vault:block_gem_gorginite').displayName('Block of Gorginite Gem').tagBlock('forge:storage_blocks/gorginite').tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:beacon_base_blocks')
	event.create('the_vault:block_gem_bomignite').displayName('Block of Bomignite Gem').tagBlock('forge:storage_blocks/bomignite').tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:beacon_base_blocks')
	event.create('the_vault:block_gem_tubium').displayName('Block of Tubium Gem').tagBlock('forge:storage_blocks/tubium').tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:beacon_base_blocks')
	event.create('the_vault:block_gem_ashium').displayName('Block of Ashium Gem').tagBlock('forge:storage_blocks/ashium').tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:beacon_base_blocks')
})