
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 1547964
	#The name of the modpack
	modpackName = "The Ferret Business 2 - Vaults of Fortune"
	#The version of the modpack
	modpackVersion = "0.3.0"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

