
[logbegone]
	phrases = ["Disconnecting VANILLA connection attempt", "Channels ", "Received unknown attacker"]
	regex = ["Disconnecting VANILLA connection attempt", "Channels ", "Received unknown attacker"]

