#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Nov 21 10:03:16 CST 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=Complementary_meets_VH.zip
