#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Feb 10 21:33:10 CST 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=Complementary_meets_VH.zip
