
["JEI Settings"]
	#Whether to show JEI that is useful for debugging when modding Vault Hunters, this option only controls some added JEI pages, this will hide ones I deem not very useful to the general public. (default: true)
	enableDebugJEI = true

