#Whether to show the built-in Vault Map in the HUD
showVanillaVaultMap = false
#Whether to hide Xaero's Minimap while in Vaults.
hideXaerosMinimapInVaults = false
#Whether to play special tracks while inside the Vault
playVaultMusic = false
#Whether to enable Better Combat or not (default: false)
weaponsShouldntBeBetter = false

["Mining Speedometer"]
	#The Output Format for the speedometer jade tooltip
	#Allowed Values: TOTAL_MINING_SPEED_WITHBASE, TOTAL_MINING_SPEED_WITHOUTBASE, ADDITIONAL_MINING_SPEED, NEXT_MINING_SPEED_BREAKPOINT
	"Jade Output Format" = "NEXT_MINING_SPEED_BREAKPOINT"
	#Hide vault loot info tooltip
	hideVaultLootInfoTooltip = true

