#Whether to show the built-in Vault Inventory HUD
showVanillaVaultHud = false
#Whether to show the built-in Vault Map in the HUD
showVanillaVaultMap = false
#Whether to play special tracks while inside the Vault
playVaultMusic = false

