import crafttweaker.api.tag.MCTag;
import crafttweaker.api.item.IItemStack;
import crafttweaker.api.ingredient.IIngredient;
import crafttweaker.api.item.tooltip.ITooltipFunction;
import stdlib.List;
import mods.projecte.CustomEMC;
import mods.projecte.NSSResolver;

// Item  to EMC/FMC value map.
val priceTable as int[IItemStack] = {
    <item:ae2:vibration_chamber> : 2425,
    <item:ae2:void_card> : 13175,
    <item:ae2:portable_fluid_cell_64k> : 197950,
    <item:ae2:portable_item_cell_64k> : 1196075,
    <item:ae2:portable_fluid_cell_256k> : 606000,
    <item:ae2:portable_item_cell_1k> : 20375,
    <item:ae2:portable_fluid_cell_1k> : 22250,
    <item:ae2:portable_item_cell_256k> : 604125,
    <item:ae2:portable_fluid_cell_4k> : 29675,
    <item:ae2:portable_item_cell_4k> : 27800,
    <item:ae2:dark_monitor> : 200,
    <item:ae2:semi_dark_monitor> : 200,
    <item:ae2:portable_fluid_cell_16k> : 69500,
    <item:ae2:portable_item_cell_16k> : 67625,
    <item:ae2:creative_energy_cell> : 2630575,
    <item:ae2:256k_crafting_storage> : 589250,
    <item:ae2:cell_component_256k> : 586925,
    <item:ae2:fluid_storage_cell_256k> : 587500,
    <item:ae2:item_storage_cell_256k> : 587000,
    <item:ae2:pattern_encoding_terminal> : 161925,
    <item:ae2:quantum_ring> : 40775,
    <item:ae2:16k_crafting_storage> : 52750,
    <item:ae2:64k_crafting_storage> : 181200,
    <item:ae2:cable_pattern_provider> : 43000,
    <item:ae2:cell_component_64k> : 178875,
    <item:ae2:crafting_terminal> : 58250,
    <item:ae2:dense_energy_cell> : 19450,
    <item:ae2:fluid_storage_cell_64k> : 179450,
    <item:ae2:item_storage_cell_64k> : 179835,
    <item:ae2:molecular_assembler> : 43900,
    <item:ae2:pattern_access_terminal> : 45450,
    <item:ae2:pattern_provider> : 43000,
    <item:ae2:spatial_anchor> : 79800,
    <item:ae2:spatial_cell_component_128> : 74775,
    <item:ae2:spatial_storage_cell_128> : 75725,
    <item:ae2:1k_crafting_storage> : 5500,
    <item:ae2:4k_crafting_storage> : 12925,
    <item:ae2:advanced_card> : 12975,
    <item:ae2:basic_card> : 12750,
    <item:ae2:biometric_card> : 4050,
    <item:ae2:black_covered_dense_cable> : 200,
    <item:ae2:black_smart_cable> : 75,
    <item:ae2:black_smart_dense_cable> : 250,
    <item:ae2:blank_pattern> : 7850,
    <item:ae2:blue_covered_dense_cable> : 200,
    <item:ae2:blue_smart_cable> : 75,
    <item:ae2:blue_smart_dense_cable> : 250,
    <item:ae2:brown_covered_dense_cable> : 200,
    <item:ae2:brown_smart_cable> : 75,
    <item:ae2:brown_smart_dense_cable> : 250,
    <item:ae2:cable_interface> : 4300,
    <item:ae2:calculation_processor> : 425,
    <item:ae2:capacity_card> : 12850,
    <item:ae2:cell_component_16k> : 50425,
    <item:ae2:cell_component_4k> : 10600,
    <item:ae2:chest> : 13875,
    <item:ae2:color_applicator> : 13125,
    <item:ae2:controller> : 3600,
    <item:ae2:conversion_monitor> : 3400,
    <item:ae2:crafting_accelerator> : 4550,
    <item:ae2:crafting_card> : 21750,
    <item:ae2:crafting_monitor> : 3000,
    <item:ae2:crafting_unit> : 2325,
    <item:ae2:cyan_smart_cable> : 75,
    <item:ae2:cyan_smart_dense_cable> : 250,
    <item:ae2:drive> : 14675,
    <item:ae2:ender_dust> : 25,
    <item:ae2:energy_card> : 19200,
    <item:ae2:energy_cell> : 2375,
    <item:ae2:engineering_processor> : 2225,
    <item:ae2:entropy_manipulator> : 3450,
    <item:ae2:equal_distribution_card> : 13400,
    <item:ae2:export_bus> : 2025,
    <item:ae2:fe_p2p_tunnel> : 3050,
    <item:ae2:fluid_cell_housing> : 2825,
    <item:ae2:fluid_p2p_tunnel> : 3050,
    <item:ae2:fluid_storage_cell_16k> : 51000,
    <item:ae2:fluid_storage_cell_4k> : 11175,
    <item:ae2:fluix_covered_dense_cable> : 200,
    <item:ae2:fluix_pearl> : 425,
    <item:ae2:fluix_smart_cable> : 75,
    <item:ae2:fluix_smart_dense_cable> : 250,
    <item:ae2:formation_core> : 1350,
    <item:ae2:formation_plane> : 1950,
    <item:ae2:fuzzy_card> : 12975,
    <item:ae2:gray_covered_dense_cable> : 200,
    <item:ae2:gray_smart_cable> : 75,
    <item:ae2:gray_smart_dense_cable> : 250,
    <item:ae2:green_covered_dense_cable> : 200,
    <item:ae2:green_smart_cable> : 75,
    <item:ae2:green_smart_dense_cable> : 250,
    <item:ae2:import_bus> : 2100,
    <item:ae2:interface> : 4300,
    <item:ae2:inverter_card> : 12975,
    <item:ae2:io_port> : 2300,
    <item:ae2:item_p2p_tunnel> : 3050,
    <item:ae2:item_storage_cell_16k> : 51375,
    <item:ae2:item_storage_cell_4k> : 11550,
    <item:ae2:light_blue_covered_dense_cable> : 200,
    <item:ae2:light_blue_smart_cable> : 75,
    <item:ae2:light_blue_smart_dense_cable> : 250,
    <item:ae2:light_gray_covered_dense_cable> : 200,
    <item:ae2:light_gray_smart_cable> : 75,
    <item:ae2:light_gray_smart_dense_cable> : 250,
    <item:ae2:light_p2p_tunnel> : 3050,
    <item:ae2:lime_covered_dense_cable> : 200,
    <item:ae2:lime_smart_cable> : 75,
    <item:ae2:lime_smart_dense_cable> : 250,
    <item:ae2:logic_processor> : 1100,
    <item:ae2:magenta_covered_dense_cable> : 200,
    <item:ae2:magenta_smart_cable> : 75,
    <item:ae2:magenta_smart_dense_cable> : 250,
    <item:ae2:matter_cannon> : 13350,
    <item:ae2:me_p2p_tunnel> : 3050,
    <item:ae2:memory_card> : 2250,
    <item:ae2:memory_card_black> : 2250,
    <item:ae2:memory_card_blue> : 2250,
    <item:ae2:memory_card_brown> : 2250,
    <item:ae2:memory_card_cyan> : 2250,
    <item:ae2:memory_card_gray> : 2250,
    <item:ae2:memory_card_green> : 2250,
    <item:ae2:memory_card_light_blue> : 2250,
    <item:ae2:memory_card_light_gray> : 2250,
    <item:ae2:memory_card_lime> : 2250,
    <item:ae2:memory_card_magenta> : 2250,
    <item:ae2:memory_card_orange> : 2250,
    <item:ae2:memory_card_pink> : 2250,
    <item:ae2:memory_card_purple> : 2250,
    <item:ae2:memory_card_red> : 2250,
    <item:ae2:memory_card_white> : 2250,
    <item:ae2:memory_card_yellow> : 2250,
    <item:ae2:monitor> : 200,
    <item:ae2:network_tool> : 1150,
    <item:ae2:orange_covered_dense_cable> : 200,
    <item:ae2:orange_smart_cable> : 75,
    <item:ae2:orange_smart_dense_cable> : 250,
    <item:ae2:pink_covered_dense_cable> : 200,
    <item:ae2:pink_smart_cable> : 75,
    <item:ae2:pink_smart_dense_cable> : 250,
    <item:ae2:purple_covered_dense_cable> : 200,
    <item:ae2:purple_smart_cable> : 75,
    <item:ae2:purple_smart_dense_cable> : 250,
    <item:ae2:quantum_entangled_singularity> : 20650,
    <item:ae2:quantum_link> : 2200,
    <item:ae2:red_covered_dense_cable> : 200,
    <item:ae2:red_smart_cable> : 75,
    <item:ae2:red_smart_dense_cable> : 250,
    <item:ae2:redstone_card> : 12750,
    <item:ae2:redstone_p2p_tunnel> : 3050,
    <item:ae2:security_station> : 4825,
    <item:ae2:singularity> : 20625,
    <item:ae2:sky_stone_tank> : 125,
    <item:ae2:spatial_cell_component_16> : 18125,
    <item:ae2:spatial_cell_component_2> : 3975,
    <item:ae2:spatial_io_port> : 5100,
    <item:ae2:spatial_storage_cell_16> : 19075,
    <item:ae2:spatial_storage_cell_2> : 4925,
    <item:ae2:speed_card> : 14975,
    <item:ae2:storage_bus> : 4400,
    <item:ae2:terminal> : 13050,
    <item:ae2:tiny_tnt> : 250,
    <item:ae2:white_covered_dense_cable> : 200,
    <item:ae2:white_smart_cable> : 75,
    <item:ae2:white_smart_dense_cable> : 250,
    <item:ae2:wireless_access_point> : 3050,
    <item:ae2:wireless_booster> : 1375,
    <item:ae2:wireless_crafting_terminal> : 21025,
    <item:ae2:wireless_receiver> : 1300,
    <item:ae2:wireless_terminal> : 20600,
    <item:ae2:yellow_covered_dense_cable> : 200,
    <item:ae2:yellow_smart_cable> : 75,
    <item:ae2:yellow_smart_dense_cable> : 250,
    <item:ae2:annihilation_core> : 1400,
    <item:ae2:annihilation_plane> : 2000,
    <item:ae2:black_covered_cable> : 50,
    <item:ae2:black_glass_cable> : 50,
    <item:ae2:black_lumen_paint_ball> : 1,
    <item:ae2:black_paint_ball> : 0,
    <item:ae2:blue_covered_cable> : 50,
    <item:ae2:blue_glass_cable> : 50,
    <item:ae2:blue_lumen_paint_ball> : 1,
    <item:ae2:blue_paint_ball> : 0,
    <item:ae2:brown_covered_cable> : 50,
    <item:ae2:brown_glass_cable> : 50,
    <item:ae2:brown_lumen_paint_ball> : 1,
    <item:ae2:brown_paint_ball> : 0,
    <item:ae2:cable_anchor> : 10,
    <item:ae2:cable_energy_acceptor> : 850,
    <item:ae2:cell_component_1k> : 3175,
    <item:ae2:cell_workbench> : 1575,
    <item:ae2:certus_crystal_seed> : 100,
    <item:ae2:certus_quartz_axe> : 300,
    <item:ae2:certus_quartz_crystal> : 100,
    <item:ae2:certus_quartz_cutting_knife> : 425,
    <item:ae2:certus_quartz_dust> : 100,
    <item:ae2:certus_quartz_hoe> : 200,
    <item:ae2:certus_quartz_pickaxe> : 300,
    <item:ae2:certus_quartz_shovel> : 100,
    <item:ae2:certus_quartz_sword> : 200,
    <item:ae2:certus_quartz_wrench> : 500,
    <item:ae2:charged_certus_quartz_crystal> : 100,
    <item:ae2:charged_staff> : 550,
    <item:ae2:charger> : 1125,
    <item:ae2:chiseled_quartz_block> : 400,
    <item:ae2:chiseled_quartz_slab> : 200,
    <item:ae2:chiseled_quartz_stairs> : 400,
    <item:ae2:chiseled_quartz_wall> : 400,
    <item:ae2:condenser> : 950,
    <item:ae2:cyan_covered_cable> : 50,
    <item:ae2:cyan_covered_dense_cable> : 50,
    <item:ae2:cyan_glass_cable> : 50,
    <item:ae2:cyan_lumen_paint_ball> : 1,
    <item:ae2:cyan_paint_ball> : 0,
    <item:ae2:deepslate_quartz_ore> : 200,
    <item:ae2:energy_acceptor> : 850,
    <item:ae2:energy_level_emitter> : 550,
    <item:ae2:fluid_storage_cell_1k> : 3750,
    <item:ae2:fluix_axe> : 500,
    <item:ae2:fluix_block> : 200,
    <item:ae2:fluix_covered_cable> : 50,
    <item:ae2:fluix_crystal> : 50,
    <item:ae2:fluix_crystal_seed> : 50,
    <item:ae2:fluix_dust> : 50,
    <item:ae2:fluix_glass_cable> : 50,
    <item:ae2:fluix_hoe> : 400,
    <item:ae2:fluix_pickaxe> : 500,
    <item:ae2:fluix_shovel> : 300,
    <item:ae2:fluix_slab> : 100,
    <item:ae2:fluix_stairs> : 200,
    <item:ae2:fluix_sword> : 400,
    <item:ae2:fluix_wall> : 200,
    <item:ae2:gray_covered_cable> : 50,
    <item:ae2:gray_glass_cable> : 50,
    <item:ae2:gray_lumen_paint_ball> : 1,
    <item:ae2:gray_paint_ball> : 0,
    <item:ae2:green_covered_cable> : 50,
    <item:ae2:green_glass_cable> : 50,
    <item:ae2:green_lumen_paint_ball> : 1,
    <item:ae2:green_paint_ball> : 0,
    <item:ae2:inscriber> : 2425,
    <item:ae2:inverted_toggle_bus> : 125,
    <item:ae2:item_cell_housing> : 950,
    <item:ae2:item_storage_cell_1k> : 4125,
    <item:ae2:level_emitter> : 450,
    <item:ae2:light_blue_covered_cable> : 50,
    <item:ae2:light_blue_glass_cable> : 50,
    <item:ae2:light_blue_lumen_paint_ball> : 1,
    <item:ae2:light_blue_paint_ball> : 0,
    <item:ae2:light_detector> : 350,
    <item:ae2:light_gray_covered_cable> : 50,
    <item:ae2:light_gray_glass_cable> : 50,
    <item:ae2:light_gray_lumen_paint_ball> : 1,
    <item:ae2:light_gray_paint_ball> : 0,
    <item:ae2:lime_covered_cable> : 50,
    <item:ae2:lime_glass_cable> : 50,
    <item:ae2:lime_lumen_paint_ball> : 1,
    <item:ae2:lime_paint_ball> : 0,
    <item:ae2:magenta_covered_cable> : 50,
    <item:ae2:magenta_glass_cable> : 50,
    <item:ae2:magenta_lumen_paint_ball> : 1,
    <item:ae2:magenta_paint_ball> : 0,
    <item:ae2:matter_ball> : 0,
    <item:ae2:nether_quartz_axe> : 375,
    <item:ae2:nether_quartz_cutting_knife> : 475,
    <item:ae2:nether_quartz_hoe> : 250,
    <item:ae2:nether_quartz_pickaxe> : 375,
    <item:ae2:nether_quartz_shovel> : 125,
    <item:ae2:nether_quartz_sword> : 250,
    <item:ae2:nether_quartz_wrench> : 625,
    <item:ae2:orange_covered_cable> : 50,
    <item:ae2:orange_glass_cable> : 50,
    <item:ae2:orange_lumen_paint_ball> : 1,
    <item:ae2:orange_paint_ball> : 0,
    <item:ae2:pink_covered_cable> : 50,
    <item:ae2:pink_glass_cable> : 50,
    <item:ae2:pink_lumen_paint_ball> : 1,
    <item:ae2:pink_paint_ball> : 0,
    <item:ae2:purple_covered_cable> : 50,
    <item:ae2:purple_glass_cable> : 50,
    <item:ae2:purple_lumen_paint_ball> : 1,
    <item:ae2:purple_paint_ball> : 0,
    <item:ae2:quartz_block> : 400,
    <item:ae2:quartz_fiber> : 100,
    <item:ae2:quartz_fixture> : 150,
    <item:ae2:quartz_glass> : 125,
    <item:ae2:quartz_growth_accelerator> : 1275,
    <item:ae2:quartz_ore> : 200,
    <item:ae2:quartz_pillar> : 400,
    <item:ae2:quartz_pillar_slab> : 200,
    <item:ae2:quartz_pillar_stairs> : 400,
    <item:ae2:quartz_pillar_wall> : 400,
    <item:ae2:quartz_slab> : 200,
    <item:ae2:quartz_stairs> : 400,
    <item:ae2:quartz_vibrant_glass> : 150,
    <item:ae2:quartz_wall> : 400,
    <item:ae2:red_covered_cable> : 50,
    <item:ae2:red_glass_cable> : 50,
    <item:ae2:red_lumen_paint_ball> : 1,
    <item:ae2:red_paint_ball> : 0,
    <item:ae2:silicon> : 100,
    <item:ae2:sky_compass> : 1000,
    <item:ae2:sky_dust> : 1,
    <item:ae2:sky_stone_block> : 1,
    <item:ae2:sky_stone_brick> : 1,
    <item:ae2:sky_stone_brick_slab> : 1,
    <item:ae2:sky_stone_brick_stairs> : 1,
    <item:ae2:sky_stone_brick_wall> : 1,
    <item:ae2:sky_stone_chest> : 10,
    <item:ae2:sky_stone_slab> : 1,
    <item:ae2:sky_stone_small_brick> : 1,
    <item:ae2:sky_stone_small_brick_slab> : 1,
    <item:ae2:sky_stone_small_brick_stairs> : 1,
    <item:ae2:sky_stone_small_brick_wall> : 1,
    <item:ae2:sky_stone_stairs> : 1,
    <item:ae2:sky_stone_wall> : 1,
    <item:ae2:smooth_sky_stone_block> : 1,
    <item:ae2:smooth_sky_stone_chest> : 10,
    <item:ae2:smooth_sky_stone_slab> : 1,
    <item:ae2:smooth_sky_stone_stairs> : 1,
    <item:ae2:smooth_sky_stone_wall> : 1,
    <item:ae2:spatial_pylon> : 750,
    <item:ae2:storage_monitor> : 650,
    <item:ae2:toggle_bus> : 125,
    <item:ae2:view_cell> : 1050,
    <item:ae2:white_covered_cable> : 50,
    <item:ae2:white_glass_cable> : 50,
    <item:ae2:white_lumen_paint_ball> : 1,
    <item:ae2:white_paint_ball> : 0,
    <item:ae2:yellow_covered_cable> : 50,
    <item:ae2:yellow_glass_cable> : 50,
    <item:ae2:yellow_lumen_paint_ball> : 1,
    <item:ae2:yellow_paint_ball> : 0
};

// For each item in the map, check if we're in release mode. If we are, anything below 26 EMC/FMC becomes unburnable for EMC
for item, value in priceTable {
    if (ReleaseMode.releaseMode == true){
        if (value < 26 ) {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), 0);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        } else {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        }
        if (value > 999 && value < 10001) {
            <tag:items:tfb2:fop_miniscule>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Miniscule");
            });
        }
        if (value > 10000 && value < 25001) {
            <tag:items:tfb2:fop_small>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Small");
            });
        }
        if (value > 25000 && value < 75001) {
            <tag:items:tfb2:fop_medium>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Medium");
            });
        }
        if (value > 75000) {
            <tag:items:tfb2:fop_large>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Large");
            });
        }
    } else {
        CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
        <tag:items:projectextended:blacklist_condenser>.add(item);
        <tag:items:projectextended:blacklist_learning>.add(item);
    }
        if (value > 10000 && value < 25001) {
            <tag:items:tfb2:fop_small>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Small");
            });
        }
        if (value > 25000 && value < 75001) {
            <tag:items:tfb2:fop_medium>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Medium");
            });
        }
        if (value > 75000) {
            <tag:items:tfb2:fop_large>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Large");
            });
        }
}