import crafttweaker.api.text.TextComponent;
import crafttweaker.api.tag.MCTag;
import crafttweaker.api.item.IItemStack;
import crafttweaker.api.ingredient.IIngredient;
import crafttweaker.api.item.tooltip.ITooltipFunction;
import stdlib.List;
import mods.projecte.CustomEMC;
import mods.projecte.NSSResolver;

// Item  to EMC/FMC value map.
val priceTable as int[IItemStack] = {
    <item:architects_palette:ancient_plating> : 10,
    <item:architects_palette:ancient_plating_fence> : 10,
    <item:architects_palette:ancient_plating_slab> : 5,
    <item:architects_palette:ancient_plating_stairs> : 10,
    <item:architects_palette:ancient_plating_vertical_slab> : 5,
    <item:architects_palette:ancient_plating_wall> : 10,
    <item:architects_palette:molten_nether_bricks> : 75,
    <item:architects_palette:wither_lamp> : 175,
    <item:architects_palette:withered_bone> : 25,
    <item:architects_palette:abyssaline> : 10,
    <item:architects_palette:abyssaline_brick_slab> : 5,
    <item:architects_palette:abyssaline_brick_vertical_slab> : 5,
    <item:architects_palette:abyssaline_bricks> : 10,
    <item:architects_palette:abyssaline_lamp> : 10,
    <item:architects_palette:abyssaline_pillar> : 10,
    <item:architects_palette:abyssaline_plating> : 10,
    <item:architects_palette:abyssaline_tile_slab> : 5,
    <item:architects_palette:abyssaline_tile_vertical_slab> : 5,
    <item:architects_palette:abyssaline_tiles> : 10,
    <item:architects_palette:acacia_board_slab> : 1,
    <item:architects_palette:acacia_board_stairs> : 1,
    <item:architects_palette:acacia_board_vertical_slab> : 1,
    <item:architects_palette:acacia_board_wall> : 1,
    <item:architects_palette:acacia_boards> : 1,
    <item:architects_palette:acacia_railing> : 1,
    <item:architects_palette:acacia_totem_wing> : 1,
    <item:architects_palette:algal_blend> : 5,
    <item:architects_palette:algal_brick> : 5,
    <item:architects_palette:algal_brick_slab> : 10,
    <item:architects_palette:algal_brick_stairs> : 25,
    <item:architects_palette:algal_brick_vertical_slab> : 10,
    <item:architects_palette:algal_brick_wall> : 25,
    <item:architects_palette:algal_bricks> : 25,
    <item:architects_palette:algal_cage_lantern> : 25,
    <item:architects_palette:algal_lamp> : 75,
    <item:architects_palette:andesite_nub> : 1,
    <item:architects_palette:basalt_tile_slab> : 1,
    <item:architects_palette:basalt_tile_stairs> : 1,
    <item:architects_palette:basalt_tile_vertical_slab> : 1,
    <item:architects_palette:basalt_tile_wall> : 1,
    <item:architects_palette:basalt_tiles> : 1,
    <item:architects_palette:birch_board_slab> : 1,
    <item:architects_palette:birch_board_stairs> : 1,
    <item:architects_palette:birch_board_vertical_slab> : 1,
    <item:architects_palette:birch_board_wall> : 1,
    <item:architects_palette:birch_boards> : 1,
    <item:architects_palette:birch_railing> : 1,
    <item:architects_palette:blackstone_nub> : 1,
    <item:architects_palette:blank_acacia_totem> : 1,
    <item:architects_palette:bone_nub> : 100,
    <item:architects_palette:bread_block> : 10,
    <item:architects_palette:bread_slab> : 5,
    <item:architects_palette:calcite_brick_slab> : 1,
    <item:architects_palette:calcite_brick_stairs> : 1,
    <item:architects_palette:calcite_brick_vertical_slab> : 1,
    <item:architects_palette:calcite_brick_wall> : 1,
    <item:architects_palette:calcite_bricks> : 1,
    <item:architects_palette:calcite_lamp> : 10,
    <item:architects_palette:calcite_pillar> : 1,
    <item:architects_palette:cerebral_block> : 10,
    <item:architects_palette:cerebral_pillar> : 10,
    <item:architects_palette:cerebral_plate> : 10,
    <item:architects_palette:cerebral_slab> : 10,
    <item:architects_palette:cerebral_stairs> : 10,
    <item:architects_palette:cerebral_tile_slab> : 10,
    <item:architects_palette:cerebral_tile_stairs> : 10,
    <item:architects_palette:cerebral_tile_vertical_slab> : 10,
    <item:architects_palette:cerebral_tile_wall> : 10,
    <item:architects_palette:cerebral_tiles> : 10,
    <item:architects_palette:cerebral_vertical_slab> : 10,
    <item:architects_palette:cerebral_wall> : 10,
    <item:architects_palette:chiseled_abyssaline_bricks> : 10,
    <item:architects_palette:chiseled_algal_bricks> : 25,
    <item:architects_palette:chiseled_basalt_tiles> : 1,
    <item:architects_palette:chiseled_calcite> : 1,
    <item:architects_palette:chiseled_coal_ore_bricks> : 1,
    <item:architects_palette:chiseled_diamond_ore_bricks> : 225,
    <item:architects_palette:chiseled_dripstone> : 10,
    <item:architects_palette:chiseled_emerald_ore_bricks> : 125,
    <item:architects_palette:chiseled_end_stone_bricks> : 1,
    <item:architects_palette:chiseled_entwine> : 25,
    <item:architects_palette:chiseled_gilded_sandstone> : 75,
    <item:architects_palette:chiseled_gold_ore_bricks> : 75,
    <item:architects_palette:chiseled_hadaline_bricks> : 10,
    <item:architects_palette:chiseled_iron_ore_bricks> : 25,
    <item:architects_palette:chiseled_lapis_ore_bricks> : 5,
    <item:architects_palette:chiseled_olivestone> : 1,
    <item:architects_palette:chiseled_packed_ice> : 1,
    <item:architects_palette:chiseled_redstone_ore_bricks> : 2,
    <item:architects_palette:chiseled_sunmetal_block> : 50,
    <item:architects_palette:chiseled_tuff> : 1,
    <item:architects_palette:chiseled_wardstone> : 10,
    <item:architects_palette:choral_end_stone_bricks> : 5,
    <item:architects_palette:coal_ore_brick_slab> : 1,
    <item:architects_palette:coal_ore_brick_stairs> : 1,
    <item:architects_palette:coal_ore_brick_vertical_slab> : 1,
    <item:architects_palette:coal_ore_brick_wall> : 1,
    <item:architects_palette:coal_ore_bricks> : 1,
    <item:architects_palette:coarse_snow> : 1,
    <item:architects_palette:cod_log> : 10,
    <item:architects_palette:cod_scales> : 25,
    <item:architects_palette:copper_nub> : 50,
    <item:architects_palette:cracked_algal_bricks> : 25,
    <item:architects_palette:cracked_basalt_tiles> : 1,
    <item:architects_palette:cracked_coal_ore_bricks> : 1,
    <item:architects_palette:cracked_diamond_ore_bricks> : 225,
    <item:architects_palette:cracked_emerald_ore_bricks> : 125,
    <item:architects_palette:cracked_end_stone_bricks> : 1,
    <item:architects_palette:cracked_gold_ore_bricks> : 75,
    <item:architects_palette:cracked_iron_ore_bricks> : 25,
    <item:architects_palette:cracked_lapis_ore_bricks> : 5,
    <item:architects_palette:cracked_olivestone_bricks> : 1,
    <item:architects_palette:cracked_olivestone_tiles> : 1,
    <item:architects_palette:cracked_redstone_ore_bricks> : 2,
    <item:architects_palette:crimson_board_slab> : 1,
    <item:architects_palette:crimson_board_stairs> : 1,
    <item:architects_palette:crimson_board_vertical_slab> : 1,
    <item:architects_palette:crimson_board_wall> : 1,
    <item:architects_palette:crimson_boards> : 1,
    <item:architects_palette:crimson_railing> : 1,
    <item:architects_palette:cut_nether_brass> : 25,
    <item:architects_palette:cut_nether_brass_slab> : 25,
    <item:architects_palette:cut_nether_brass_stairs> : 25,
    <item:architects_palette:cut_nether_brass_vertical_slab> : 25,
    <item:architects_palette:cut_nether_brass_wall> : 25,
    <item:architects_palette:dark_oak_board_slab> : 1,
    <item:architects_palette:dark_oak_board_stairs> : 1,
    <item:architects_palette:dark_oak_board_vertical_slab> : 1,
    <item:architects_palette:dark_oak_board_wall> : 1,
    <item:architects_palette:dark_oak_boards> : 1,
    <item:architects_palette:dark_oak_railing> : 1,
    <item:architects_palette:dark_oracle_brick_slab> : 2,
    <item:architects_palette:dark_oracle_brick_stairs> : 5,
    <item:architects_palette:dark_oracle_brick_vertical_slab> : 2,
    <item:architects_palette:dark_oracle_brick_wall> : 5,
    <item:architects_palette:dark_oracle_bricks> : 5,
    <item:architects_palette:deepslate_nub> : 1,
    <item:architects_palette:diamond_nub> : 900,
    <item:architects_palette:diamond_ore_brick_slab> : 125,
    <item:architects_palette:diamond_ore_brick_stairs> : 225,
    <item:architects_palette:diamond_ore_brick_vertical_slab> : 125,
    <item:architects_palette:diamond_ore_brick_wall> : 225,
    <item:architects_palette:diamond_ore_bricks> : 225,
    <item:architects_palette:diorite_nub> : 1,
    <item:architects_palette:dripstone_brick_slab> : 5,
    <item:architects_palette:dripstone_brick_stairs> : 10,
    <item:architects_palette:dripstone_brick_vertical_slab> : 5,
    <item:architects_palette:dripstone_brick_wall> : 10,
    <item:architects_palette:dripstone_bricks> : 10,
    <item:architects_palette:dripstone_lamp> : 25,
    <item:architects_palette:dripstone_pillar> : 10,
    <item:architects_palette:ekanite_rod> : 1,
    <item:architects_palette:emerald_nub> : 475,
    <item:architects_palette:emerald_ore_brick_slab> : 50,
    <item:architects_palette:emerald_ore_brick_stairs> : 125,
    <item:architects_palette:emerald_ore_brick_vertical_slab> : 50,
    <item:architects_palette:emerald_ore_brick_wall> : 125,
    <item:architects_palette:emerald_ore_bricks> : 125,
    <item:architects_palette:ender_pearl_block> : 100,
    <item:architects_palette:entrails> : 225,
    <item:architects_palette:entrails_slab> : 100,
    <item:architects_palette:entrails_stairs> : 225,
    <item:architects_palette:entrails_vertical_slab> : 100,
    <item:architects_palette:entwine_bars> : 5,
    <item:architects_palette:entwine_block> : 25,
    <item:architects_palette:entwine_pillar> : 25,
    <item:architects_palette:entwine_rod> : 25,
    <item:architects_palette:entwine_slab> : 10,
    <item:architects_palette:entwine_stairs> : 25,
    <item:architects_palette:entwine_vertical_slab> : 10,
    <item:architects_palette:esoterrack> : 1,
    <item:architects_palette:esoterrack_brick_slab> : 1,
    <item:architects_palette:esoterrack_brick_stairs> : 1,
    <item:architects_palette:esoterrack_brick_vertical_slab> : 1,
    <item:architects_palette:esoterrack_brick_wall> : 1,
    <item:architects_palette:esoterrack_bricks> : 1,
    <item:architects_palette:esoterrack_pillar> : 1,
    <item:architects_palette:esoterrack_slab> : 1,
    <item:architects_palette:esoterrack_stairs> : 1,
    <item:architects_palette:esoterrack_vertical_slab> : 1,
    <item:architects_palette:esoterrack_wall> : 1,
    <item:architects_palette:exposed_copper_nub> : 75,
    <item:architects_palette:flint_block> : 5,
    <item:architects_palette:flint_pillar> : 5,
    <item:architects_palette:flint_tile_slab> : 2,
    <item:architects_palette:flint_tile_stairs> : 5,
    <item:architects_palette:flint_tile_vertical_slab> : 2,
    <item:architects_palette:flint_tile_wall> : 5,
    <item:architects_palette:flint_tiles> : 5,
    <item:architects_palette:framed_oracle_block> : 25,
    <item:architects_palette:gilded_sandstone> : 75,
    <item:architects_palette:gilded_sandstone_pillar> : 75,
    <item:architects_palette:gilded_sandstone_slab> : 50,
    <item:architects_palette:gilded_sandstone_stairs> : 75,
    <item:architects_palette:gilded_sandstone_vertical_slab> : 50,
    <item:architects_palette:glowstone_cage_lantern> : 50,
    <item:architects_palette:gold_nub> : 350,
    <item:architects_palette:gold_ore_brick_slab> : 50,
    <item:architects_palette:gold_ore_brick_stairs> : 75,
    <item:architects_palette:gold_ore_brick_vertical_slab> : 50,
    <item:architects_palette:gold_ore_brick_wall> : 75,
    <item:architects_palette:gold_ore_bricks> : 75,
    <item:architects_palette:granite_nub> : 1,
    <item:architects_palette:grinning_acacia_totem> : 2,
    <item:architects_palette:hadaline> : 10,
    <item:architects_palette:hadaline_brick_slab> : 5,
    <item:architects_palette:hadaline_brick_vertical_slab> : 5,
    <item:architects_palette:hadaline_bricks> : 10,
    <item:architects_palette:hadaline_lamp> : 10,
    <item:architects_palette:hadaline_pillar> : 10,
    <item:architects_palette:hadaline_plating> : 10,
    <item:architects_palette:hadaline_tile_slab> : 5,
    <item:architects_palette:hadaline_tile_vertical_slab> : 5,
    <item:architects_palette:hadaline_tiles> : 10,
    <item:architects_palette:hazard_block> : 2,
    <item:architects_palette:hazard_sign> : 125,
    <item:architects_palette:hazard_slab> : 1,
    <item:architects_palette:hazard_vertical_slab> : 1,
    <item:architects_palette:hazard_wall> : 2,
    <item:architects_palette:heavy_calcite_bricks> : 1,
    <item:architects_palette:heavy_cracked_end_stone_bricks> : 1,
    <item:architects_palette:heavy_cracked_stone_bricks> : 1,
    <item:architects_palette:heavy_dripstone_bricks> : 1,
    <item:architects_palette:heavy_end_stone_bricks> : 1,
    <item:architects_palette:heavy_mossy_stone_bricks> : 1,
    <item:architects_palette:heavy_stone_bricks> : 1,
    <item:architects_palette:heavy_tuff_bricks> : 1,
    <item:architects_palette:heliodor_rod> : 1,
    <item:architects_palette:illuminated_olivestone> : 10,
    <item:architects_palette:iron_nub> : 100,
    <item:architects_palette:iron_ore_brick_slab> : 10,
    <item:architects_palette:iron_ore_brick_stairs> : 25,
    <item:architects_palette:iron_ore_brick_vertical_slab> : 10,
    <item:architects_palette:iron_ore_brick_wall> : 25,
    <item:architects_palette:iron_ore_bricks> : 25,
    <item:architects_palette:jungle_board_slab> : 1,
    <item:architects_palette:jungle_board_stairs> : 1,
    <item:architects_palette:jungle_board_vertical_slab> : 1,
    <item:architects_palette:jungle_board_wall> : 1,
    <item:architects_palette:jungle_boards> : 1,
    <item:architects_palette:jungle_railing> : 1,
    <item:architects_palette:lapis_ore_brick_slab> : 2,
    <item:architects_palette:lapis_ore_brick_stairs> : 5,
    <item:architects_palette:lapis_ore_brick_vertical_slab> : 2,
    <item:architects_palette:lapis_ore_brick_wall> : 5,
    <item:architects_palette:lapis_ore_bricks> : 5,
    <item:architects_palette:lit_osseous_skull> : 225,
    <item:architects_palette:lit_withered_osseous_skull> : 225,
    <item:architects_palette:monazite_rod> : 1,
    <item:architects_palette:moonstone> : 25,
    <item:architects_palette:mushy_myonite_brick_slab> : 2,
    <item:architects_palette:mushy_myonite_brick_stairs> : 5,
    <item:architects_palette:mushy_myonite_brick_vertical_slab> : 2,
    <item:architects_palette:mushy_myonite_brick_wall> : 5,
    <item:architects_palette:mushy_myonite_bricks> : 5,
    <item:architects_palette:myonite> : 1,
    <item:architects_palette:myonite_brick_slab> : 1,
    <item:architects_palette:myonite_brick_stairs> : 1,
    <item:architects_palette:myonite_brick_vertical_slab> : 1,
    <item:architects_palette:myonite_brick_wall> : 1,
    <item:architects_palette:myonite_bricks> : 1,
    <item:architects_palette:myonite_slab> : 1,
    <item:architects_palette:myonite_stairs> : 1,
    <item:architects_palette:myonite_vertical_slab> : 1,
    <item:architects_palette:myonite_wall> : 1,
    <item:architects_palette:nether_brass_blend> : 50,
    <item:architects_palette:nether_brass_block> : 50,
    <item:architects_palette:nether_brass_chain> : 25,
    <item:architects_palette:nether_brass_ingot> : 50,
    <item:architects_palette:nether_brass_lantern> : 50,
    <item:architects_palette:nether_brass_nub> : 25,
    <item:architects_palette:nether_brass_nugget> : 5,
    <item:architects_palette:nether_brass_pillar> : 50,
    <item:architects_palette:nether_brass_slab> : 25,
    <item:architects_palette:nether_brass_stairs> : 50,
    <item:architects_palette:nether_brass_torch> : 5,
    <item:architects_palette:nether_brass_vertical_slab> : 25,
    <item:architects_palette:nether_brass_wall> : 50,
    <item:architects_palette:netherite_nub> : 1,
    <item:architects_palette:nub_of_ender> : 400,
    <item:architects_palette:oak_board_slab> : 1,
    <item:architects_palette:oak_board_stairs> : 1,
    <item:architects_palette:oak_board_vertical_slab> : 1,
    <item:architects_palette:oak_board_wall> : 1,
    <item:architects_palette:oak_boards> : 1,
    <item:architects_palette:oak_railing> : 1,
    <item:architects_palette:olivestone_brick_slab> : 1,
    <item:architects_palette:olivestone_brick_stairs> : 1,
    <item:architects_palette:olivestone_brick_vertical_slab> : 1,
    <item:architects_palette:olivestone_brick_wall> : 1,
    <item:architects_palette:olivestone_bricks> : 1,
    <item:architects_palette:olivestone_pillar> : 1,
    <item:architects_palette:olivestone_tile_slab> : 1,
    <item:architects_palette:olivestone_tile_stairs> : 1,
    <item:architects_palette:olivestone_tile_vertical_slab> : 1,
    <item:architects_palette:olivestone_tile_wall> : 1,
    <item:architects_palette:olivestone_tiles> : 1,
    <item:architects_palette:onyx> : 1,
    <item:architects_palette:onyx_brick_slab> : 1,
    <item:architects_palette:onyx_brick_stairs> : 1,
    <item:architects_palette:onyx_brick_vertical_slab> : 1,
    <item:architects_palette:onyx_brick_wall> : 1,
    <item:architects_palette:onyx_bricks> : 1,
    <item:architects_palette:onyx_pillar> : 1,
    <item:architects_palette:onyx_slab> : 1,
    <item:architects_palette:onyx_stairs> : 1,
    <item:architects_palette:onyx_vertical_slab> : 1,
    <item:architects_palette:onyx_wall> : 1,
    <item:architects_palette:oracle_block> : 5,
    <item:architects_palette:oracle_brick_slab> : 2,
    <item:architects_palette:oracle_brick_stairs> : 5,
    <item:architects_palette:oracle_brick_vertical_slab> : 2,
    <item:architects_palette:oracle_brick_wall> : 5,
    <item:architects_palette:oracle_bricks> : 5,
    <item:architects_palette:oracle_jelly> : 10,
    <item:architects_palette:oracle_lamp> : 50,
    <item:architects_palette:oracle_pillar> : 5,
    <item:architects_palette:oracle_slab> : 2,
    <item:architects_palette:oracle_stairs> : 5,
    <item:architects_palette:oracle_tile_slab> : 2,
    <item:architects_palette:oracle_tile_stairs> : 5,
    <item:architects_palette:oracle_tile_vertical_slab> : 2,
    <item:architects_palette:oracle_tile_wall> : 5,
    <item:architects_palette:oracle_tiles> : 2,
    <item:architects_palette:oracle_vertical_slab> : 2,
    <item:architects_palette:osseous_brick_slab> : 100,
    <item:architects_palette:osseous_brick_stairs> : 225,
    <item:architects_palette:osseous_brick_vertical_slab> : 100,
    <item:architects_palette:osseous_brick_wall> : 225,
    <item:architects_palette:osseous_bricks> : 225,
    <item:architects_palette:osseous_pillar> : 225,
    <item:architects_palette:osseous_skull> : 225,
    <item:architects_palette:overgrown_algal_brick_slab> : 10,
    <item:architects_palette:overgrown_algal_brick_stairs> : 25,
    <item:architects_palette:overgrown_algal_brick_vertical_slab> : 10,
    <item:architects_palette:overgrown_algal_brick_wall> : 25,
    <item:architects_palette:overgrown_algal_bricks> : 25,
    <item:architects_palette:oxidized_copper_nub> : 450,
    <item:architects_palette:packed_ice_pillar> : 10,
    <item:architects_palette:pipe> : 50,
    <item:architects_palette:placid_acacia_totem> : 1,
    <item:architects_palette:plating_block> : 50,
    <item:architects_palette:plating_nub> : 25,
    <item:architects_palette:plating_slab> : 25,
    <item:architects_palette:plating_stairs> : 50,
    <item:architects_palette:plating_vertical_slab> : 25,
    <item:architects_palette:plating_wall> : 50,
    <item:architects_palette:polished_glowstone> : 75,
    <item:architects_palette:polished_glowstone_nub> : 25,
    <item:architects_palette:polished_glowstone_slab> : 25,
    <item:architects_palette:polished_glowstone_vertical_slab> : 25,
    <item:architects_palette:polished_glowstone_wall> : 75,
    <item:architects_palette:polished_packed_ice> : 10,
    <item:architects_palette:polished_packed_ice_slab> : 5,
    <item:architects_palette:polished_packed_ice_stairs> : 10,
    <item:architects_palette:polished_packed_ice_vertical_slab> : 5,
    <item:architects_palette:polished_packed_ice_wall> : 10,
    <item:architects_palette:redstone_cage_lantern> : 50,
    <item:architects_palette:redstone_ore_brick_slab> : 1,
    <item:architects_palette:redstone_ore_brick_stairs> : 2,
    <item:architects_palette:redstone_ore_brick_vertical_slab> : 1,
    <item:architects_palette:redstone_ore_brick_wall> : 2,
    <item:architects_palette:redstone_ore_bricks> : 2,
    <item:architects_palette:rotten_flesh_block> : 225,
    <item:architects_palette:runic_glowstone> : 75,
    <item:architects_palette:salmon_log> : 10,
    <item:architects_palette:salmon_scales> : 25,
    <item:architects_palette:sandstone_nub> : 1,
    <item:architects_palette:scute_block> : 10,
    <item:architects_palette:sheet_metal_block> : 25,
    <item:architects_palette:sheet_metal_wall> : 25,
    <item:architects_palette:shocked_acacia_totem> : 1,
    <item:architects_palette:smooth_nether_brass> : 25,
    <item:architects_palette:smooth_nether_brass_slab> : 10,
    <item:architects_palette:smooth_nether_brass_stairs> : 25,
    <item:architects_palette:smooth_nether_brass_vertical_slab> : 10,
    <item:architects_palette:smooth_stone_nub> : 10,
    <item:architects_palette:spool> : 10,
    <item:architects_palette:spruce_board_slab> : 1,
    <item:architects_palette:spruce_board_stairs> : 1,
    <item:architects_palette:spruce_board_vertical_slab> : 1,
    <item:architects_palette:spruce_board_wall> : 1,
    <item:architects_palette:spruce_boards> : 1,
    <item:architects_palette:spruce_railing> : 1,
    <item:architects_palette:stone_nub> : 1,
    <item:architects_palette:stripped_twisted_log> : 1,
    <item:architects_palette:stripped_twisted_wood> : 1,
    <item:architects_palette:sunmetal_bars> : 25,
    <item:architects_palette:sunmetal_blend> : 50,
    <item:architects_palette:sunmetal_block> : 50,
    <item:architects_palette:sunmetal_brick> : 50,
    <item:architects_palette:sunmetal_nub> : 25,
    <item:architects_palette:sunmetal_pillar> : 50,
    <item:architects_palette:sunmetal_slab> : 25,
    <item:architects_palette:sunmetal_stairs> : 50,
    <item:architects_palette:sunmetal_vertical_slab> : 25,
    <item:architects_palette:sunstone> : 25,
    <item:architects_palette:tread_plate> : 25,
    <item:architects_palette:tread_plate_slab> : 10,
    <item:architects_palette:tread_plate_stairs> : 25,
    <item:architects_palette:tread_plate_vertical_slab> : 10,
    <item:architects_palette:tread_plate_wall> : 25,
    <item:architects_palette:tuff_brick_slab> : 1,
    <item:architects_palette:tuff_brick_stairs> : 1,
    <item:architects_palette:tuff_brick_vertical_slab> : 1,
    <item:architects_palette:tuff_brick_wall> : 1,
    <item:architects_palette:tuff_bricks> : 1,
    <item:architects_palette:tuff_lamp> : 5,
    <item:architects_palette:tuff_pillar> : 1,
    <item:architects_palette:twisted_board_slab> : 1,
    <item:architects_palette:twisted_board_stairs> : 1,
    <item:architects_palette:twisted_board_vertical_slab> : 1,
    <item:architects_palette:twisted_board_wall> : 1,
    <item:architects_palette:twisted_boards> : 1,
    <item:architects_palette:twisted_button> : 1,
    <item:architects_palette:twisted_door> : 1,
    <item:architects_palette:twisted_fence> : 1,
    <item:architects_palette:twisted_fence_gate> : 1,
    <item:architects_palette:twisted_leaves> : 1,
    <item:architects_palette:twisted_log> : 1,
    <item:architects_palette:twisted_planks> : 1,
    <item:architects_palette:twisted_pressure_plate> : 1,
    <item:architects_palette:twisted_railing> : 1,
    <item:architects_palette:twisted_sapling> : 1,
    <item:architects_palette:twisted_slab> : 1,
    <item:architects_palette:twisted_stairs> : 1,
    <item:architects_palette:twisted_trapdoor> : 1,
    <item:architects_palette:twisted_vertical_slab> : 1,
    <item:architects_palette:twisted_wood> : 1,
    <item:architects_palette:twisting_blackstone> : 5,
    <item:architects_palette:twisting_blackstone_bricks> : 5,
    <item:architects_palette:unobtanium> : 0,
    <item:architects_palette:unobtanium_block> : 0,
    <item:architects_palette:wardstone> : 10,
    <item:architects_palette:wardstone_blend> : 10,
    <item:architects_palette:wardstone_brick> : 10,
    <item:architects_palette:wardstone_brick_slab> : 5,
    <item:architects_palette:wardstone_brick_stairs> : 10,
    <item:architects_palette:wardstone_brick_vertical_slab> : 5,
    <item:architects_palette:wardstone_brick_wall> : 10,
    <item:architects_palette:wardstone_bricks> : 10,
    <item:architects_palette:wardstone_lamp> : 75,
    <item:architects_palette:wardstone_pillar> : 10,
    <item:architects_palette:wardstone_slab> : 5,
    <item:architects_palette:wardstone_stairs> : 10,
    <item:architects_palette:wardstone_vertical_slab> : 5,
    <item:architects_palette:wardstone_wall> : 10,
    <item:architects_palette:warped_board_slab> : 1,
    <item:architects_palette:warped_board_stairs> : 1,
    <item:architects_palette:warped_board_vertical_slab> : 1,
    <item:architects_palette:warped_board_wall> : 1,
    <item:architects_palette:warped_boards> : 1,
    <item:architects_palette:warped_railing> : 1,
    <item:architects_palette:warpstone> : 25,
    <item:architects_palette:warpstone_slab> : 10,
    <item:architects_palette:warpstone_stairs> : 25,
    <item:architects_palette:warpstone_vertical_slab> : 10,
    <item:architects_palette:warpstone_wall> : 25,
    <item:architects_palette:waxed_copper_nub> : 450,
    <item:architects_palette:waxed_exposed_copper_nub> : 450,
    <item:architects_palette:waxed_oxidized_copper_nub> : 450,
    <item:architects_palette:waxed_weathered_copper_nub> : 450,
    <item:architects_palette:weathered_copper_nub> : 450,
    <item:architects_palette:weeping_blackstone> : 5,
    <item:architects_palette:weeping_blackstone_bricks> : 5,
    <item:architects_palette:withered_bone_block> : 75,
    <item:architects_palette:withered_osseous_brick_slab> : 25,
    <item:architects_palette:withered_osseous_brick_stairs> : 75,
    <item:architects_palette:withered_osseous_brick_vertical_slab> : 25,
    <item:architects_palette:withered_osseous_brick_wall> : 75,
    <item:architects_palette:withered_osseous_bricks> : 75,
    <item:architects_palette:withered_osseous_pillar> : 75,
    <item:architects_palette:withered_osseous_skull> : 75
};

// For each item in the map, check if we're in release mode. If we are, anything below 26 EMC/FMC becomes unburnable for EMC
for item, value in priceTable {
    if (ReleaseMode.releaseMode == true){
        if (value < 26 ) {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), 0);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        } else {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        }
        if (value > 999 && value < 10001) {
            <tag:items:tfb2:fop_miniscule>.add(item);
            item.addTooltip(new TextComponent("FOP Digitization Value: Miniscule").withStyle(style => style.withColor(<constant:minecraft:formatting:white>)));
        }
        if (value > 10000 && value < 25001) {
            <tag:items:tfb2:fop_small>.add(item);
            item.addTooltip(new TextComponent("FOP Digitization Value: Small").withStyle(style => style.withColor(<constant:minecraft:formatting:white>)));
        }
        if (value > 25000 && value < 75001) {
            <tag:items:tfb2:fop_medium>.add(item);
            item.addTooltip(new TextComponent("FOP Digitization Value: Medium").withStyle(style => style.withColor(<constant:minecraft:formatting:white>)));
        }
        if (value > 75000) {
            <tag:items:tfb2:fop_large>.add(item);
            item.addTooltip(new TextComponent("FOP Digitization Value: Large").withStyle(style => style.withColor(<constant:minecraft:formatting:white>)));
        }
    } else {
        CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
        <tag:items:projectextended:blacklist_condenser>.add(item);
        <tag:items:projectextended:blacklist_learning>.add(item);
        
        if (value > 10000 && value < 25001) {
            <tag:items:tfb2:fop_small>.add(item);
            item.addTooltip(new TextComponent("FOP Digitization Value: Small").withStyle(style => style.withColor(<constant:minecraft:formatting:white>)));
        }
        if (value > 25000 && value < 75001) {
            <tag:items:tfb2:fop_medium>.add(item);
            item.addTooltip(new TextComponent("FOP Digitization Value: Medium").withStyle(style => style.withColor(<constant:minecraft:formatting:white>)));
        }
        if (value > 75000) {
            <tag:items:tfb2:fop_large>.add(item);
            item.addTooltip(new TextComponent("FOP Digitization Value: Large").withStyle(style => style.withColor(<constant:minecraft:formatting:white>)));
        }
    }
}