import crafttweaker.api.text.TextComponent;
import crafttweaker.api.tag.MCTag;
import crafttweaker.api.item.IItemStack;
import crafttweaker.api.ingredient.IIngredient;
import crafttweaker.api.item.tooltip.ITooltipFunction;
import stdlib.List;
import mods.projecte.CustomEMC;
import mods.projecte.NSSResolver;

// Item  to EMC/FMC value map.
val priceTable as int[IItemStack] = {
    <item:chipped:acacia_door_1> : 1,
    <item:chipped:acacia_door_10> : 1,
    <item:chipped:acacia_door_11> : 1,
    <item:chipped:acacia_door_12> : 1,
    <item:chipped:acacia_door_13> : 1,
    <item:chipped:acacia_door_14> : 1,
    <item:chipped:acacia_door_15> : 1,
    <item:chipped:acacia_door_16> : 1,
    <item:chipped:acacia_door_17> : 1,
    <item:chipped:acacia_door_18> : 1,
    <item:chipped:acacia_door_19> : 1,
    <item:chipped:acacia_door_2> : 1,
    <item:chipped:acacia_door_20> : 1,
    <item:chipped:acacia_door_3> : 1,
    <item:chipped:acacia_door_4> : 1,
    <item:chipped:acacia_door_5> : 1,
    <item:chipped:acacia_door_6> : 1,
    <item:chipped:acacia_door_7> : 1,
    <item:chipped:acacia_door_8> : 1,
    <item:chipped:acacia_door_9> : 1,
    <item:chipped:acacia_leaves_1> : 1,
    <item:chipped:acacia_leaves_10> : 1,
    <item:chipped:acacia_leaves_11> : 1,
    <item:chipped:acacia_leaves_12> : 1,
    <item:chipped:acacia_leaves_2> : 1,
    <item:chipped:acacia_leaves_3> : 1,
    <item:chipped:acacia_leaves_4> : 1,
    <item:chipped:acacia_leaves_5> : 1,
    <item:chipped:acacia_leaves_6> : 1,
    <item:chipped:acacia_leaves_7> : 1,
    <item:chipped:acacia_leaves_8> : 1,
    <item:chipped:acacia_leaves_9> : 1,
    <item:chipped:acacia_log_1> : 2,
    <item:chipped:acacia_log_10> : 2,
    <item:chipped:acacia_log_11> : 2,
    <item:chipped:acacia_log_2> : 2,
    <item:chipped:acacia_log_3> : 2,
    <item:chipped:acacia_log_4> : 2,
    <item:chipped:acacia_log_5> : 2,
    <item:chipped:acacia_log_6> : 2,
    <item:chipped:acacia_log_7> : 2,
    <item:chipped:acacia_log_8> : 2,
    <item:chipped:acacia_log_9> : 2,
    <item:chipped:acacia_planks_1> : 1,
    <item:chipped:acacia_planks_10> : 1,
    <item:chipped:acacia_planks_11> : 1,
    <item:chipped:acacia_planks_12> : 1,
    <item:chipped:acacia_planks_13> : 1,
    <item:chipped:acacia_planks_14> : 1,
    <item:chipped:acacia_planks_15> : 1,
    <item:chipped:acacia_planks_16> : 1,
    <item:chipped:acacia_planks_17> : 1,
    <item:chipped:acacia_planks_18> : 1,
    <item:chipped:acacia_planks_19> : 1,
    <item:chipped:acacia_planks_2> : 1,
    <item:chipped:acacia_planks_20> : 1,
    <item:chipped:acacia_planks_21> : 1,
    <item:chipped:acacia_planks_22> : 1,
    <item:chipped:acacia_planks_23> : 1,
    <item:chipped:acacia_planks_24> : 1,
    <item:chipped:acacia_planks_25> : 1,
    <item:chipped:acacia_planks_26> : 1,
    <item:chipped:acacia_planks_27> : 1,
    <item:chipped:acacia_planks_28> : 1,
    <item:chipped:acacia_planks_29> : 1,
    <item:chipped:acacia_planks_3> : 1,
    <item:chipped:acacia_planks_30> : 1,
    <item:chipped:acacia_planks_31> : 1,
    <item:chipped:acacia_planks_32> : 1,
    <item:chipped:acacia_planks_33> : 1,
    <item:chipped:acacia_planks_34> : 1,
    <item:chipped:acacia_planks_35> : 1,
    <item:chipped:acacia_planks_36> : 1,
    <item:chipped:acacia_planks_37> : 1,
    <item:chipped:acacia_planks_38> : 1,
    <item:chipped:acacia_planks_39> : 1,
    <item:chipped:acacia_planks_4> : 1,
    <item:chipped:acacia_planks_40> : 1,
    <item:chipped:acacia_planks_41> : 1,
    <item:chipped:acacia_planks_5> : 1,
    <item:chipped:acacia_planks_6> : 1,
    <item:chipped:acacia_planks_7> : 1,
    <item:chipped:acacia_planks_8> : 1,
    <item:chipped:acacia_planks_9> : 1,
    <item:chipped:acacia_trapdoor_1> : 1,
    <item:chipped:acacia_trapdoor_10> : 1,
    <item:chipped:acacia_trapdoor_11> : 1,
    <item:chipped:acacia_trapdoor_2> : 1,
    <item:chipped:acacia_trapdoor_3> : 1,
    <item:chipped:acacia_trapdoor_4> : 1,
    <item:chipped:acacia_trapdoor_5> : 1,
    <item:chipped:acacia_trapdoor_6> : 1,
    <item:chipped:acacia_trapdoor_7> : 1,
    <item:chipped:acacia_trapdoor_8> : 1,
    <item:chipped:acacia_trapdoor_9> : 1,
    <item:chipped:alchemy_bench> : 3775,
    <item:chipped:amethyst_block_1> : 100,
    <item:chipped:amethyst_block_10> : 100,
    <item:chipped:amethyst_block_11> : 100,
    <item:chipped:amethyst_block_12> : 100,
    <item:chipped:amethyst_block_13> : 100,
    <item:chipped:amethyst_block_14> : 100,
    <item:chipped:amethyst_block_15> : 100,
    <item:chipped:amethyst_block_16> : 100,
    <item:chipped:amethyst_block_17> : 100,
    <item:chipped:amethyst_block_18> : 100,
    <item:chipped:amethyst_block_19> : 100,
    <item:chipped:amethyst_block_2> : 100,
    <item:chipped:amethyst_block_20> : 100,
    <item:chipped:amethyst_block_21> : 100,
    <item:chipped:amethyst_block_22> : 100,
    <item:chipped:amethyst_block_23> : 100,
    <item:chipped:amethyst_block_24> : 100,
    <item:chipped:amethyst_block_25> : 100,
    <item:chipped:amethyst_block_26> : 100,
    <item:chipped:amethyst_block_27> : 100,
    <item:chipped:amethyst_block_28> : 100,
    <item:chipped:amethyst_block_29> : 100,
    <item:chipped:amethyst_block_3> : 100,
    <item:chipped:amethyst_block_30> : 100,
    <item:chipped:amethyst_block_31> : 100,
    <item:chipped:amethyst_block_32> : 100,
    <item:chipped:amethyst_block_33> : 100,
    <item:chipped:amethyst_block_34> : 100,
    <item:chipped:amethyst_block_35> : 100,
    <item:chipped:amethyst_block_36> : 100,
    <item:chipped:amethyst_block_37> : 100,
    <item:chipped:amethyst_block_38> : 100,
    <item:chipped:amethyst_block_39> : 100,
    <item:chipped:amethyst_block_4> : 100,
    <item:chipped:amethyst_block_40> : 100,
    <item:chipped:amethyst_block_41> : 100,
    <item:chipped:amethyst_block_42> : 100,
    <item:chipped:amethyst_block_43> : 100,
    <item:chipped:amethyst_block_44> : 100,
    <item:chipped:amethyst_block_45> : 100,
    <item:chipped:amethyst_block_46> : 100,
    <item:chipped:amethyst_block_47> : 100,
    <item:chipped:amethyst_block_48> : 100,
    <item:chipped:amethyst_block_49> : 100,
    <item:chipped:amethyst_block_5> : 100,
    <item:chipped:amethyst_block_50> : 100,
    <item:chipped:amethyst_block_51> : 100,
    <item:chipped:amethyst_block_52> : 100,
    <item:chipped:amethyst_block_53> : 100,
    <item:chipped:amethyst_block_54> : 100,
    <item:chipped:amethyst_block_55> : 100,
    <item:chipped:amethyst_block_56> : 100,
    <item:chipped:amethyst_block_57> : 100,
    <item:chipped:amethyst_block_58> : 100,
    <item:chipped:amethyst_block_59> : 100,
    <item:chipped:amethyst_block_6> : 100,
    <item:chipped:amethyst_block_60> : 100,
    <item:chipped:amethyst_block_61> : 100,
    <item:chipped:amethyst_block_62> : 100,
    <item:chipped:amethyst_block_63> : 100,
    <item:chipped:amethyst_block_64> : 100,
    <item:chipped:amethyst_block_65> : 100,
    <item:chipped:amethyst_block_66> : 100,
    <item:chipped:amethyst_block_67> : 100,
    <item:chipped:amethyst_block_68> : 100,
    <item:chipped:amethyst_block_69> : 100,
    <item:chipped:amethyst_block_7> : 100,
    <item:chipped:amethyst_block_8> : 100,
    <item:chipped:amethyst_block_9> : 100,
    <item:chipped:ancient_debris_1> : 825,
    <item:chipped:ancient_debris_10> : 825,
    <item:chipped:ancient_debris_11> : 825,
    <item:chipped:ancient_debris_12> : 825,
    <item:chipped:ancient_debris_13> : 825,
    <item:chipped:ancient_debris_14> : 825,
    <item:chipped:ancient_debris_15> : 825,
    <item:chipped:ancient_debris_16> : 825,
    <item:chipped:ancient_debris_17> : 825,
    <item:chipped:ancient_debris_18> : 825,
    <item:chipped:ancient_debris_19> : 825,
    <item:chipped:ancient_debris_2> : 825,
    <item:chipped:ancient_debris_20> : 825,
    <item:chipped:ancient_debris_21> : 825,
    <item:chipped:ancient_debris_22> : 825,
    <item:chipped:ancient_debris_23> : 825,
    <item:chipped:ancient_debris_24> : 825,
    <item:chipped:ancient_debris_25> : 825,
    <item:chipped:ancient_debris_26> : 825,
    <item:chipped:ancient_debris_27> : 825,
    <item:chipped:ancient_debris_28> : 825,
    <item:chipped:ancient_debris_29> : 825,
    <item:chipped:ancient_debris_3> : 825,
    <item:chipped:ancient_debris_30> : 825,
    <item:chipped:ancient_debris_31> : 825,
    <item:chipped:ancient_debris_32> : 825,
    <item:chipped:ancient_debris_33> : 825,
    <item:chipped:ancient_debris_34> : 825,
    <item:chipped:ancient_debris_35> : 825,
    <item:chipped:ancient_debris_36> : 825,
    <item:chipped:ancient_debris_37> : 825,
    <item:chipped:ancient_debris_38> : 825,
    <item:chipped:ancient_debris_39> : 825,
    <item:chipped:ancient_debris_4> : 825,
    <item:chipped:ancient_debris_40> : 825,
    <item:chipped:ancient_debris_41> : 825,
    <item:chipped:ancient_debris_42> : 825,
    <item:chipped:ancient_debris_43> : 825,
    <item:chipped:ancient_debris_44> : 825,
    <item:chipped:ancient_debris_45> : 825,
    <item:chipped:ancient_debris_46> : 825,
    <item:chipped:ancient_debris_47> : 825,
    <item:chipped:ancient_debris_48> : 825,
    <item:chipped:ancient_debris_49> : 825,
    <item:chipped:ancient_debris_5> : 825,
    <item:chipped:ancient_debris_50> : 825,
    <item:chipped:ancient_debris_51> : 825,
    <item:chipped:ancient_debris_52> : 825,
    <item:chipped:ancient_debris_53> : 825,
    <item:chipped:ancient_debris_54> : 825,
    <item:chipped:ancient_debris_55> : 825,
    <item:chipped:ancient_debris_56> : 825,
    <item:chipped:ancient_debris_57> : 825,
    <item:chipped:ancient_debris_58> : 825,
    <item:chipped:ancient_debris_59> : 825,
    <item:chipped:ancient_debris_6> : 825,
    <item:chipped:ancient_debris_60> : 825,
    <item:chipped:ancient_debris_61> : 825,
    <item:chipped:ancient_debris_62> : 825,
    <item:chipped:ancient_debris_63> : 825,
    <item:chipped:ancient_debris_64> : 825,
    <item:chipped:ancient_debris_65> : 825,
    <item:chipped:ancient_debris_66> : 825,
    <item:chipped:ancient_debris_67> : 825,
    <item:chipped:ancient_debris_68> : 825,
    <item:chipped:ancient_debris_69> : 825,
    <item:chipped:ancient_debris_7> : 825,
    <item:chipped:ancient_debris_8> : 825,
    <item:chipped:ancient_debris_9> : 825,
    <item:chipped:andesite_1> : 1,
    <item:chipped:andesite_10> : 1,
    <item:chipped:andesite_11> : 1,
    <item:chipped:andesite_12> : 1,
    <item:chipped:andesite_13> : 1,
    <item:chipped:andesite_14> : 1,
    <item:chipped:andesite_15> : 1,
    <item:chipped:andesite_16> : 1,
    <item:chipped:andesite_17> : 1,
    <item:chipped:andesite_18> : 1,
    <item:chipped:andesite_19> : 1,
    <item:chipped:andesite_2> : 1,
    <item:chipped:andesite_20> : 1,
    <item:chipped:andesite_21> : 1,
    <item:chipped:andesite_22> : 1,
    <item:chipped:andesite_23> : 1,
    <item:chipped:andesite_24> : 1,
    <item:chipped:andesite_25> : 1,
    <item:chipped:andesite_26> : 1,
    <item:chipped:andesite_27> : 1,
    <item:chipped:andesite_28> : 1,
    <item:chipped:andesite_29> : 1,
    <item:chipped:andesite_3> : 1,
    <item:chipped:andesite_30> : 1,
    <item:chipped:andesite_31> : 1,
    <item:chipped:andesite_32> : 1,
    <item:chipped:andesite_33> : 1,
    <item:chipped:andesite_34> : 1,
    <item:chipped:andesite_35> : 1,
    <item:chipped:andesite_36> : 1,
    <item:chipped:andesite_37> : 1,
    <item:chipped:andesite_38> : 1,
    <item:chipped:andesite_39> : 1,
    <item:chipped:andesite_4> : 1,
    <item:chipped:andesite_40> : 1,
    <item:chipped:andesite_41> : 1,
    <item:chipped:andesite_42> : 1,
    <item:chipped:andesite_43> : 1,
    <item:chipped:andesite_44> : 1,
    <item:chipped:andesite_45> : 1,
    <item:chipped:andesite_46> : 1,
    <item:chipped:andesite_47> : 1,
    <item:chipped:andesite_48> : 1,
    <item:chipped:andesite_49> : 1,
    <item:chipped:andesite_5> : 1,
    <item:chipped:andesite_50> : 1,
    <item:chipped:andesite_51> : 1,
    <item:chipped:andesite_52> : 1,
    <item:chipped:andesite_53> : 1,
    <item:chipped:andesite_54> : 1,
    <item:chipped:andesite_55> : 1,
    <item:chipped:andesite_56> : 1,
    <item:chipped:andesite_57> : 1,
    <item:chipped:andesite_58> : 1,
    <item:chipped:andesite_59> : 1,
    <item:chipped:andesite_6> : 1,
    <item:chipped:andesite_60> : 1,
    <item:chipped:andesite_61> : 1,
    <item:chipped:andesite_62> : 1,
    <item:chipped:andesite_63> : 1,
    <item:chipped:andesite_64> : 1,
    <item:chipped:andesite_65> : 1,
    <item:chipped:andesite_66> : 1,
    <item:chipped:andesite_67> : 1,
    <item:chipped:andesite_68> : 1,
    <item:chipped:andesite_69> : 1,
    <item:chipped:andesite_7> : 1,
    <item:chipped:andesite_8> : 1,
    <item:chipped:andesite_9> : 1,
    <item:chipped:barrel_1> : 2,
    <item:chipped:barrel_10> : 2,
    <item:chipped:barrel_11> : 2,
    <item:chipped:barrel_12> : 2,
    <item:chipped:barrel_13> : 2,
    <item:chipped:barrel_14> : 2,
    <item:chipped:barrel_15> : 2,
    <item:chipped:barrel_16> : 2,
    <item:chipped:barrel_17> : 2,
    <item:chipped:barrel_18> : 2,
    <item:chipped:barrel_19> : 2,
    <item:chipped:barrel_2> : 2,
    <item:chipped:barrel_20> : 2,
    <item:chipped:barrel_21> : 2,
    <item:chipped:barrel_22> : 2,
    <item:chipped:barrel_23> : 2,
    <item:chipped:barrel_24> : 2,
    <item:chipped:barrel_25> : 2,
    <item:chipped:barrel_26> : 2,
    <item:chipped:barrel_27> : 2,
    <item:chipped:barrel_28> : 2,
    <item:chipped:barrel_29> : 2,
    <item:chipped:barrel_3> : 2,
    <item:chipped:barrel_30> : 2,
    <item:chipped:barrel_31> : 2,
    <item:chipped:barrel_32> : 2,
    <item:chipped:barrel_33> : 2,
    <item:chipped:barrel_4> : 2,
    <item:chipped:barrel_5> : 2,
    <item:chipped:barrel_6> : 2,
    <item:chipped:barrel_7> : 2,
    <item:chipped:barrel_8> : 2,
    <item:chipped:barrel_9> : 2,
    <item:chipped:basalt_1> : 1,
    <item:chipped:basalt_10> : 1,
    <item:chipped:basalt_11> : 1,
    <item:chipped:basalt_12> : 1,
    <item:chipped:basalt_13> : 1,
    <item:chipped:basalt_14> : 1,
    <item:chipped:basalt_15> : 1,
    <item:chipped:basalt_16> : 1,
    <item:chipped:basalt_17> : 1,
    <item:chipped:basalt_18> : 1,
    <item:chipped:basalt_19> : 1,
    <item:chipped:basalt_2> : 1,
    <item:chipped:basalt_20> : 1,
    <item:chipped:basalt_21> : 1,
    <item:chipped:basalt_22> : 1,
    <item:chipped:basalt_23> : 1,
    <item:chipped:basalt_24> : 1,
    <item:chipped:basalt_25> : 1,
    <item:chipped:basalt_26> : 1,
    <item:chipped:basalt_27> : 1,
    <item:chipped:basalt_28> : 1,
    <item:chipped:basalt_29> : 1,
    <item:chipped:basalt_3> : 1,
    <item:chipped:basalt_30> : 1,
    <item:chipped:basalt_31> : 1,
    <item:chipped:basalt_32> : 1,
    <item:chipped:basalt_33> : 1,
    <item:chipped:basalt_34> : 1,
    <item:chipped:basalt_35> : 1,
    <item:chipped:basalt_36> : 1,
    <item:chipped:basalt_37> : 1,
    <item:chipped:basalt_38> : 1,
    <item:chipped:basalt_39> : 1,
    <item:chipped:basalt_4> : 1,
    <item:chipped:basalt_40> : 1,
    <item:chipped:basalt_41> : 1,
    <item:chipped:basalt_42> : 1,
    <item:chipped:basalt_43> : 1,
    <item:chipped:basalt_44> : 1,
    <item:chipped:basalt_45> : 1,
    <item:chipped:basalt_46> : 1,
    <item:chipped:basalt_47> : 1,
    <item:chipped:basalt_48> : 1,
    <item:chipped:basalt_49> : 1,
    <item:chipped:basalt_5> : 1,
    <item:chipped:basalt_50> : 1,
    <item:chipped:basalt_51> : 1,
    <item:chipped:basalt_52> : 1,
    <item:chipped:basalt_53> : 1,
    <item:chipped:basalt_54> : 1,
    <item:chipped:basalt_55> : 1,
    <item:chipped:basalt_56> : 1,
    <item:chipped:basalt_57> : 1,
    <item:chipped:basalt_58> : 1,
    <item:chipped:basalt_59> : 1,
    <item:chipped:basalt_6> : 1,
    <item:chipped:basalt_60> : 1,
    <item:chipped:basalt_61> : 1,
    <item:chipped:basalt_62> : 1,
    <item:chipped:basalt_63> : 1,
    <item:chipped:basalt_64> : 1,
    <item:chipped:basalt_65> : 1,
    <item:chipped:basalt_66> : 1
};

// For each item in the map, check if we're in release mode. If we are, anything below 26 EMC/FMC becomes unburnable for EMC
for item, value in priceTable {
    if (ReleaseMode.releaseMode == true){
        if (value < 26 ) {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), 0);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        } else {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        }
        if (value > 999 && value < 10001) {
            <tag:items:tfb2:fop_miniscule>.add(item);
            item.addTooltip(new TextComponent("FOP Digitization Value: Miniscule").withStyle(style => style.withColor(<constant:minecraft:formatting:white>)));
        }
        if (value > 10000 && value < 25001) {
            <tag:items:tfb2:fop_small>.add(item);
            item.addTooltip(new TextComponent("FOP Digitization Value: Small").withStyle(style => style.withColor(<constant:minecraft:formatting:white>)));
        }
        if (value > 25000 && value < 75001) {
            <tag:items:tfb2:fop_medium>.add(item);
            item.addTooltip(new TextComponent("FOP Digitization Value: Medium").withStyle(style => style.withColor(<constant:minecraft:formatting:white>)));
        }
        if (value > 75000) {
            <tag:items:tfb2:fop_large>.add(item);
            item.addTooltip(new TextComponent("FOP Digitization Value: Large").withStyle(style => style.withColor(<constant:minecraft:formatting:white>)));
        }
    } else {
        CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
        <tag:items:projectextended:blacklist_condenser>.add(item);
        <tag:items:projectextended:blacklist_learning>.add(item);
        
        if (value > 10000 && value < 25001) {
            <tag:items:tfb2:fop_small>.add(item);
            item.addTooltip(new TextComponent("FOP Digitization Value: Small").withStyle(style => style.withColor(<constant:minecraft:formatting:white>)));
        }
        if (value > 25000 && value < 75001) {
            <tag:items:tfb2:fop_medium>.add(item);
            item.addTooltip(new TextComponent("FOP Digitization Value: Medium").withStyle(style => style.withColor(<constant:minecraft:formatting:white>)));
        }
        if (value > 75000) {
            <tag:items:tfb2:fop_large>.add(item);
            item.addTooltip(new TextComponent("FOP Digitization Value: Large").withStyle(style => style.withColor(<constant:minecraft:formatting:white>)));
        }
    }
}