import crafttweaker.api.tag.MCTag;
import crafttweaker.api.item.IItemStack;
import crafttweaker.api.ingredient.IIngredient;
import crafttweaker.api.item.tooltip.ITooltipFunction;
import stdlib.List;
import mods.projecte.CustomEMC;
import mods.projecte.NSSResolver;

// Item  to EMC/FMC value map.
val priceTable as int[IItemStack] = {
    <item:create:cart_assembler> : 252125,
    <item:create:creative_blaze_cake> : 1500650,
    <item:create:creative_motor> : 1581825,
    <item:create:extendo_grip> : 382875,
    <item:create:controls> : 2925,
    <item:create:large_water_wheel> : 73250,
    <item:create:mechanical_roller> : 23375,
    <item:create:netherite_backtank> : 7325,
    <item:create:netherite_diving_boots> : 6525,
    <item:create:netherite_diving_helmet> : 6575,
    <item:create:steam_engine> : 54075,
    <item:create:wand_of_symmetry> : 8000,
    <item:create:windmill_bearing> : 18375,
    <item:create:adjustable_chain_gearshift> : 650,
    <item:create:analog_lever> : 425,
    <item:create:andesite_alloy> : 25,
    <item:create:andesite_alloy_block> : 250,
    <item:create:andesite_door> : 425,
    <item:create:andesite_funnel> : 10,
    <item:create:andesite_tunnel> : 25,
    <item:create:attribute_filter> : 150,
    <item:create:bar_of_chocolate> : 10,
    <item:create:black_toolbox> : 5750,
    <item:create:blaze_burner> : 5400,
    <item:create:blaze_cake> : 25,
    <item:create:blaze_cake_base> : 25,
    <item:create:blue_toolbox> : 5750,
    <item:create:brass_block> : 100,
    <item:create:brass_casing> : 1300,
    <item:create:brass_door> : 1300,
    <item:create:brass_funnel> : 25,
    <item:create:brass_hand> : 425,
    <item:create:brass_ingot> : 100,
    <item:create:brass_ladder> : 50,
    <item:create:brass_nugget> : 10,
    <item:create:brass_scaffolding> : 50,
    <item:create:brass_sheet> : 100,
    <item:create:brass_tunnel> : 175,
    <item:create:brown_toolbox> : 5750,
    <item:create:builders_tea> : 2,
    <item:create:cinder_flour> : 1,
    <item:create:clockwork_bearing> : 1450,
    <item:create:clutch> : 450,
    <item:create:content_observer> : 1600,
    <item:create:contraption_controls> : 575,
    <item:create:controller_rail> : 700,
    <item:create:copper_backtank> : 1275,
    <item:create:copper_casing> : 1300,
    <item:create:crafter_slot_cover> : 25,
    <item:create:crafting_blueprint> : 10,
    <item:create:crushed_raw_gold> : 675,
    <item:create:crushed_raw_lead> : 300,
    <item:create:crushed_raw_nickel> : 350,
    <item:create:crushed_raw_osmium> : 225,
    <item:create:crushed_raw_silver> : 350,
    <item:create:crushed_raw_uranium> : 300,
    <item:create:crushing_wheel> : 22800,
    <item:create:cuckoo_clock> : 3125,
    <item:create:cyan_toolbox> : 5750,
    <item:create:deployer> : 1000,
    <item:create:display_board> : 100,
    <item:create:display_link> : 1400,
    <item:create:electron_tube> : 150,
    <item:create:elevator_pulley> : 1575,
    <item:create:empty_blaze_burner> : 2000,
    <item:create:encased_chain_drive> : 500,
    <item:create:encased_fan> : 1375,
    <item:create:fluid_pipe> : 75,
    <item:create:fluid_tank> : 200,
    <item:create:fluid_valve> : 300,
    <item:create:flywheel> : 825,
    <item:create:gantry_carriage> : 550,
    <item:create:gantry_shaft> : 950,
    <item:create:gearbox> : 625,
    <item:create:gearshift> : 485,
    <item:create:goggles> : 675,
    <item:create:golden_sheet> : 675,
    <item:create:granite_pillar> : 1,
    <item:create:gray_toolbox> : 5750,
    <item:create:green_toolbox> : 5750,
    <item:create:hand_crank> : 450,
    <item:create:haunted_bell> : 200,
    <item:create:hose_pulley> : 1450,
    <item:create:iron_sheet> : 225,
    <item:create:item_drain> : 1375,
    <item:create:item_vault> : 1375,
    <item:create:light_blue_toolbox> : 5750,
    <item:create:light_gray_toolbox> : 5750,
    <item:create:lime_toolbox> : 5750,
    <item:create:linked_controller> : 650,
    <item:create:magenta_toolbox> : 5750,
    <item:create:mechanical_arm> : 3250,
    <item:create:mechanical_bearing> : 525,
    <item:create:mechanical_crafter> : 475,
    <item:create:mechanical_drill> : 725,
    <item:create:mechanical_harvester> : 975,
    <item:create:mechanical_mixer> : 1650,
    <item:create:mechanical_piston> : 675,
    <item:create:mechanical_plough> : 1175,
    <item:create:mechanical_press> : 2470,
    <item:create:mechanical_pump> : 125,
    <item:create:mechanical_saw> : 1325,
    <item:create:millstone> : 475,
    <item:create:minecart_coupling> : 275,
    <item:create:nixie_tube> : 75,
    <item:create:orange_toolbox> : 5750,
    <item:create:peculiar_bell> : 200,
    <item:create:pink_toolbox> : 5750,
    <item:create:placard> : 100,
    <item:create:polished_rose_quartz> : 125,
    <item:create:portable_fluid_interface> : 1550,
    <item:create:portable_storage_interface> : 675,
    <item:create:potato_cannon> : 2075,
    <item:create:powered_latch> : 25,
    <item:create:powered_toggle_latch> : 10,
    <item:create:precision_mechanism> : 1625,
    <item:create:propeller> : 925,
    <item:create:pulse_extender> : 125,
    <item:create:pulse_repeater> : 125,
    <item:create:purple_toolbox> : 5750,
    <item:create:railway_casing> : 1300,
    <item:create:raw_zinc> : 125,
    <item:create:red_toolbox> : 5750,
    <item:create:redstone_contact> : 125,
    <item:create:redstone_link> : 650,
    <item:create:rope_pulley> : 650,
    <item:create:rose_quartz> : 125,
    <item:create:rose_quartz_block> : 75,
    <item:create:rose_quartz_lamp> : 225,
    <item:create:rose_quartz_tiles> : 125,
    <item:create:rotation_speed_controller> : 13675,
    <item:create:schedule> : 2,
    <item:create:schematic_and_quill> : 175,
    <item:create:schematicannon> : 9075,
    <item:create:secondary_linear_chassis> : 150,
    <item:create:sequenced_gearshift> : 1500,
    <item:create:smart_chute> : 1225,
    <item:create:smart_fluid_pipe> : 325,
    <item:create:speedometer> : 925,
    <item:create:spout> : 1300,
    <item:create:steam_whistle> : 775,
    <item:create:sticker> : 75,
    <item:create:sticky_mechanical_piston> : 825,
    <item:create:stockpile_switch> : 1600,
    <item:create:stressometer> : 925,
    <item:create:track> : 2,
    <item:create:track_observer> : 1300,
    <item:create:track_signal> : 1450,
    <item:create:track_station> : 1800,
    <item:create:train_door> : 1300,
    <item:create:train_trapdoor> : 1300,
    <item:create:vertical_gearbox> : 625,
    <item:create:water_wheel> : 21700,
    <item:create:weighted_ejector> : 1175,
    <item:create:whisk> : 1175,
    <item:create:white_toolbox> : 5750,
    <item:create:wrench> : 2225,
    <item:create:yellow_toolbox> : 5750,
    <item:create:zinc_ingot> : 125,
    <item:create:acacia_window> : 2,
    <item:create:acacia_window_pane> : 1,
    <item:create:andesite_bars> : 5,
    <item:create:andesite_casing> : 425,
    <item:create:andesite_ladder> : 10,
    <item:create:andesite_pillar> : 1,
    <item:create:andesite_scaffolding> : 10,
    <item:create:asurine> : 5,
    <item:create:asurine_pillar> : 5,
    <item:create:basin> : 450,
    <item:create:belt_connector> : 75,
    <item:create:birch_window> : 2,
    <item:create:birch_window_pane> : 1,
    <item:create:black_seat> : 10,
    <item:create:black_valve_handle> : 325,
    <item:create:blue_seat> : 10,
    <item:create:blue_valve_handle> : 325,
    <item:create:brass_bars> : 25,
    <item:create:brown_seat> : 10,
    <item:create:brown_valve_handle> : 325,
    <item:create:calcite_pillar> : 1,
    <item:create:chocolate_bucket> : 725,
    <item:create:chocolate_glazed_berries> : 10,
    <item:create:chute> : 250,
    <item:create:clipboard> : 25,
    <item:create:cogwheel> : 50,
    <item:create:copper_bars> : 25,
    <item:create:copper_diving_boots> : 450,
    <item:create:copper_diving_helmet> : 500,
    <item:create:copper_door> : 1300,
    <item:create:copper_ladder> : 50,
    <item:create:copper_nugget> : 10,
    <item:create:copper_scaffolding> : 50,
    <item:create:copper_sheet> : 100,
    <item:create:copper_shingle_slab> : 25,
    <item:create:copper_shingle_stairs> : 50,
    <item:create:copper_shingles> : 50,
    <item:create:copper_tile_slab> : 25,
    <item:create:copper_tile_stairs> : 50,
    <item:create:copper_tiles> : 50,
    <item:create:copper_valve_handle> : 325,
    <item:create:copycat_panel> : 25,
    <item:create:copycat_step> : 25,
    <item:create:crimsite> : 10,
    <item:create:crimsite_pillar> : 10,
    <item:create:crimson_window> : 2,
    <item:create:crimson_window_pane> : 1,
    <item:create:crushed_raw_copper> : 100,
    <item:create:crushed_raw_iron> : 225,
    <item:create:crushed_raw_tin> : 100,
    <item:create:crushed_raw_zinc> : 125,
    <item:create:cut_andesite> : 1,
    <item:create:cut_andesite_brick_slab> : 1,
    <item:create:cut_andesite_brick_stairs> : 1,
    <item:create:cut_andesite_brick_wall> : 1,
    <item:create:cut_andesite_bricks> : 1,
    <item:create:cut_andesite_slab> : 1,
    <item:create:cut_andesite_stairs> : 1,
    <item:create:cut_andesite_wall> : 1,
    <item:create:cut_asurine> : 5,
    <item:create:cut_asurine_brick_slab> : 2,
    <item:create:cut_asurine_brick_stairs> : 5,
    <item:create:cut_asurine_brick_wall> : 5,
    <item:create:cut_asurine_bricks> : 5,
    <item:create:cut_asurine_slab> : 2,
    <item:create:cut_asurine_stairs> : 5,
    <item:create:cut_asurine_wall> : 5,
    <item:create:cut_calcite> : 1,
    <item:create:cut_calcite_brick_slab> : 1,
    <item:create:cut_calcite_brick_stairs> : 1,
    <item:create:cut_calcite_brick_wall> : 1,
    <item:create:cut_calcite_bricks> : 1,
    <item:create:cut_calcite_slab> : 1,
    <item:create:cut_calcite_stairs> : 1,
    <item:create:cut_calcite_wall> : 1,
    <item:create:cut_crimsite> : 10,
    <item:create:cut_crimsite_brick_slab> : 5,
    <item:create:cut_crimsite_brick_stairs> : 10,
    <item:create:cut_crimsite_brick_wall> : 10,
    <item:create:cut_crimsite_bricks> : 10,
    <item:create:cut_crimsite_slab> : 5,
    <item:create:cut_crimsite_stairs> : 10,
    <item:create:cut_crimsite_wall> : 10,
    <item:create:cut_deepslate> : 1,
    <item:create:cut_deepslate_brick_slab> : 1,
    <item:create:cut_deepslate_brick_stairs> : 1,
    <item:create:cut_deepslate_brick_wall> : 1,
    <item:create:cut_deepslate_bricks> : 1,
    <item:create:cut_deepslate_slab> : 1,
    <item:create:cut_deepslate_stairs> : 1,
    <item:create:cut_deepslate_wall> : 1,
    <item:create:cut_diorite> : 1,
    <item:create:cut_diorite_brick_slab> : 1,
    <item:create:cut_diorite_brick_stairs> : 1,
    <item:create:cut_diorite_brick_wall> : 1,
    <item:create:cut_diorite_bricks> : 1,
    <item:create:cut_diorite_slab> : 1,
    <item:create:cut_diorite_stairs> : 1,
    <item:create:cut_diorite_wall> : 1,
    <item:create:cut_dripstone> : 10,
    <item:create:cut_dripstone_brick_slab> : 5,
    <item:create:cut_dripstone_brick_stairs> : 10,
    <item:create:cut_dripstone_brick_wall> : 10,
    <item:create:cut_dripstone_bricks> : 10,
    <item:create:cut_dripstone_slab> : 5,
    <item:create:cut_dripstone_stairs> : 10,
    <item:create:cut_dripstone_wall> : 10,
    <item:create:cut_granite> : 1,
    <item:create:cut_granite_brick_slab> : 1,
    <item:create:cut_granite_brick_stairs> : 1,
    <item:create:cut_granite_brick_wall> : 1,
    <item:create:cut_granite_bricks> : 1,
    <item:create:cut_granite_slab> : 1,
    <item:create:cut_granite_stairs> : 1,
    <item:create:cut_granite_wall> : 1,
    <item:create:cut_limestone> : 1,
    <item:create:cut_limestone_brick_slab> : 1,
    <item:create:cut_limestone_brick_stairs> : 1,
    <item:create:cut_limestone_brick_wall> : 1,
    <item:create:cut_limestone_bricks> : 1,
    <item:create:cut_limestone_slab> : 1,
    <item:create:cut_limestone_stairs> : 1,
    <item:create:cut_limestone_wall> : 1,
    <item:create:cut_ochrum> : 50,
    <item:create:cut_ochrum_brick_slab> : 25,
    <item:create:cut_ochrum_brick_stairs> : 50,
    <item:create:cut_ochrum_brick_wall> : 50,
    <item:create:cut_ochrum_bricks> : 50,
    <item:create:cut_ochrum_slab> : 25,
    <item:create:cut_ochrum_stairs> : 50,
    <item:create:cut_ochrum_wall> : 50,
    <item:create:cut_scorchia> : 25,
    <item:create:cut_scorchia_brick_slab> : 10,
    <item:create:cut_scorchia_brick_stairs> : 25,
    <item:create:cut_scorchia_brick_wall> : 25,
    <item:create:cut_scorchia_bricks> : 25,
    <item:create:cut_scorchia_slab> : 10,
    <item:create:cut_scorchia_stairs> : 25,
    <item:create:cut_scorchia_wall> : 25,
    <item:create:cut_scoria> : 25,
    <item:create:cut_scoria_brick_slab> : 10,
    <item:create:cut_scoria_brick_stairs> : 25,
    <item:create:cut_scoria_brick_wall> : 25,
    <item:create:cut_scoria_bricks> : 25,
    <item:create:cut_scoria_slab> : 10,
    <item:create:cut_scoria_stairs> : 25,
    <item:create:cut_scoria_wall> : 25,
    <item:create:cut_tuff> : 1,
    <item:create:cut_tuff_brick_slab> : 1,
    <item:create:cut_tuff_brick_stairs> : 1,
    <item:create:cut_tuff_brick_wall> : 1,
    <item:create:cut_tuff_bricks> : 1,
    <item:create:cut_tuff_slab> : 1,
    <item:create:cut_tuff_stairs> : 1,
    <item:create:cut_tuff_wall> : 1,
    <item:create:cut_veridium> : 5,
    <item:create:cut_veridium_brick_slab> : 2,
    <item:create:cut_veridium_brick_stairs> : 5,
    <item:create:cut_veridium_brick_wall> : 5,
    <item:create:cut_veridium_bricks> : 5,
    <item:create:cut_veridium_slab> : 2,
    <item:create:cut_veridium_stairs> : 5,
    <item:create:cut_veridium_wall> : 5,
    <item:create:cyan_seat> : 10,
    <item:create:cyan_valve_handle> : 325,
    <item:create:dark_oak_window> : 2,
    <item:create:dark_oak_window_pane> : 1,
    <item:create:deepslate_pillar> : 1,
    <item:create:deepslate_zinc_ore> : 250,
    <item:create:depot> : 450,
    <item:create:diorite_pillar> : 1,
    <item:create:dough> : 5,
    <item:create:dripstone_pillar> : 1,
    <item:create:empty_schematic> : 150,
    <item:create:experience_block> : 900,
    <item:create:experience_nugget> : 100,
    <item:create:exposed_copper_shingle_slab> : 25,
    <item:create:exposed_copper_shingle_stairs> : 50,
    <item:create:exposed_copper_shingles> : 50,
    <item:create:exposed_copper_tile_slab> : 25,
    <item:create:exposed_copper_tile_stairs> : 50,
    <item:create:exposed_copper_tiles> : 50,
    <item:create:filter> : 50,
    <item:create:framed_glass> : 1,
    <item:create:framed_glass_door> : 2,
    <item:create:framed_glass_pane> : 1,
    <item:create:framed_glass_trapdoor> : 2,
    <item:create:gray_seat> : 10,
    <item:create:gray_valve_handle> : 325,
    <item:create:green_seat> : 10,
    <item:create:green_valve_handle> : 325,
    <item:create:honey_bucket> : 200,
    <item:create:honeyed_apple> : 50,
    <item:create:horizontal_framed_glass> : 1,
    <item:create:horizontal_framed_glass_pane> : 1,
    <item:create:industrial_iron_block> : 100,
    <item:create:jungle_window> : 2,
    <item:create:jungle_window_pane> : 1,
    <item:create:large_cogwheel> : 125,
    <item:create:layered_andesite> : 1,
    <item:create:layered_asurine> : 5,
    <item:create:layered_calcite> : 1,
    <item:create:layered_crimsite> : 5,
    <item:create:layered_deepslate> : 1,
    <item:create:layered_diorite> : 1,
    <item:create:layered_dripstone> : 1,
    <item:create:layered_granite> : 1,
    <item:create:layered_limestone> : 1,
    <item:create:layered_ochrum> : 50,
    <item:create:layered_scorchia> : 25,
    <item:create:layered_scoria> : 25,
    <item:create:layered_tuff> : 1,
    <item:create:layered_veridium> : 5,
    <item:create:light_blue_seat> : 10,
    <item:create:light_blue_valve_handle> : 325,
    <item:create:light_gray_seat> : 10,
    <item:create:light_gray_valve_handle> : 325,
    <item:create:lime_seat> : 10,
    <item:create:lime_valve_handle> : 325,
    <item:create:limestone> : 1,
    <item:create:limestone_pillar> : 1,
    <item:create:linear_chassis> : 150,
    <item:create:magenta_seat> : 10,
    <item:create:magenta_valve_handle> : 325,
    <item:create:metal_bracket> : 125,
    <item:create:metal_girder> : 100,
    <item:create:nozzle> : 100,
    <item:create:oak_window> : 2,
    <item:create:oak_window_pane> : 1,
    <item:create:ochrum> : 50,
    <item:create:ochrum_pillar> : 50,
    <item:create:orange_seat> : 10,
    <item:create:orange_valve_handle> : 325,
    <item:create:ornate_iron_window> : 50,
    <item:create:ornate_iron_window_pane> : 10,
    <item:create:oxidized_copper_shingle_slab> : 25,
    <item:create:oxidized_copper_shingle_stairs> : 50,
    <item:create:oxidized_copper_shingles> : 50,
    <item:create:oxidized_copper_tile_slab> : 25,
    <item:create:oxidized_copper_tile_stairs> : 50,
    <item:create:oxidized_copper_tiles> : 50,
    <item:create:pink_seat> : 10,
    <item:create:pink_valve_handle> : 325,
    <item:create:piston_extension_pole> : 175,
    <item:create:polished_cut_andesite> : 1,
    <item:create:polished_cut_andesite_slab> : 1,
    <item:create:polished_cut_andesite_stairs> : 1,
    <item:create:polished_cut_andesite_wall> : 1,
    <item:create:polished_cut_asurine> : 5,
    <item:create:polished_cut_asurine_slab> : 2,
    <item:create:polished_cut_asurine_stairs> : 5,
    <item:create:polished_cut_asurine_wall> : 5,
    <item:create:polished_cut_calcite> : 1,
    <item:create:polished_cut_calcite_slab> : 1,
    <item:create:polished_cut_calcite_stairs> : 1,
    <item:create:polished_cut_calcite_wall> : 1,
    <item:create:polished_cut_crimsite> : 10,
    <item:create:polished_cut_crimsite_slab> : 5,
    <item:create:polished_cut_crimsite_stairs> : 10,
    <item:create:polished_cut_crimsite_wall> : 10,
    <item:create:polished_cut_deepslate> : 1,
    <item:create:polished_cut_deepslate_slab> : 1,
    <item:create:polished_cut_deepslate_stairs> : 1,
    <item:create:polished_cut_deepslate_wall> : 1,
    <item:create:polished_cut_diorite> : 1,
    <item:create:polished_cut_diorite_slab> : 1,
    <item:create:polished_cut_diorite_stairs> : 1,
    <item:create:polished_cut_diorite_wall> : 1,
    <item:create:polished_cut_dripstone> : 1,
    <item:create:polished_cut_dripstone_slab> : 1,
    <item:create:polished_cut_dripstone_stairs> : 1,
    <item:create:polished_cut_dripstone_wall> : 1,
    <item:create:polished_cut_granite> : 1,
    <item:create:polished_cut_granite_slab> : 1,
    <item:create:polished_cut_granite_stairs> : 1,
    <item:create:polished_cut_granite_wall> : 1,
    <item:create:polished_cut_limestone> : 1,
    <item:create:polished_cut_limestone_slab> : 1,
    <item:create:polished_cut_limestone_stairs> : 1,
    <item:create:polished_cut_limestone_wall> : 1,
    <item:create:polished_cut_ochrum> : 50,
    <item:create:polished_cut_ochrum_slab> : 25,
    <item:create:polished_cut_ochrum_stairs> : 50,
    <item:create:polished_cut_ochrum_wall> : 50,
    <item:create:polished_cut_scorchia> : 25,
    <item:create:polished_cut_scorchia_slab> : 10,
    <item:create:polished_cut_scorchia_stairs> : 25,
    <item:create:polished_cut_scorchia_wall> : 25,
    <item:create:polished_cut_scoria> : 25,
    <item:create:polished_cut_scoria_slab> : 10,
    <item:create:polished_cut_scoria_stairs> : 25,
    <item:create:polished_cut_scoria_wall> : 25,
    <item:create:polished_cut_tuff> : 1,
    <item:create:polished_cut_tuff_slab> : 1,
    <item:create:polished_cut_tuff_stairs> : 1,
    <item:create:polished_cut_tuff_wall> : 1,
    <item:create:polished_cut_veridium> : 5,
    <item:create:polished_cut_veridium_slab> : 2,
    <item:create:polished_cut_veridium_stairs> : 5,
    <item:create:polished_cut_veridium_wall> : 5,
    <item:create:powdered_obsidian> : 10,
    <item:create:purple_seat> : 10,
    <item:create:purple_valve_handle> : 325,
    <item:create:radial_chassis> : 150,
    <item:create:raw_zinc_block> : 1125,
    <item:create:red_sand_paper> : 2,
    <item:create:red_seat> : 10,
    <item:create:red_valve_handle> : 325,
    <item:create:sail_frame> : 10,
    <item:create:sand_paper> : 2,
    <item:create:schematic_table> : 225,
    <item:create:scorchia> : 25,
    <item:create:scorchia_pillar> : 25,
    <item:create:scoria> : 25,
    <item:create:scoria_pillar> : 25,
    <item:create:shaft> : 25,
    <item:create:small_andesite_brick_slab> : 1,
    <item:create:small_andesite_brick_stairs> : 1,
    <item:create:small_andesite_brick_wall> : 1,
    <item:create:small_andesite_bricks> : 1,
    <item:create:small_asurine_brick_slab> : 2,
    <item:create:small_asurine_brick_stairs> : 5,
    <item:create:small_asurine_brick_wall> : 5,
    <item:create:small_asurine_bricks> : 5,
    <item:create:small_calcite_brick_slab> : 1,
    <item:create:small_calcite_brick_stairs> : 1,
    <item:create:small_calcite_brick_wall> : 1,
    <item:create:small_calcite_bricks> : 1,
    <item:create:small_crimsite_brick_slab> : 2,
    <item:create:small_crimsite_brick_stairs> : 5,
    <item:create:small_crimsite_brick_wall> : 5,
    <item:create:small_crimsite_bricks> : 5,
    <item:create:small_deepslate_brick_slab> : 1,
    <item:create:small_deepslate_brick_stairs> : 1,
    <item:create:small_deepslate_brick_wall> : 1,
    <item:create:small_deepslate_bricks> : 1,
    <item:create:small_diorite_brick_slab> : 1,
    <item:create:small_diorite_brick_stairs> : 1,
    <item:create:small_diorite_brick_wall> : 1,
    <item:create:small_diorite_bricks> : 1,
    <item:create:small_dripstone_brick_slab> : 1,
    <item:create:small_dripstone_brick_stairs> : 1,
    <item:create:small_dripstone_brick_wall> : 1,
    <item:create:small_dripstone_bricks> : 1,
    <item:create:small_granite_brick_slab> : 1,
    <item:create:small_granite_brick_stairs> : 1,
    <item:create:small_granite_brick_wall> : 1,
    <item:create:small_granite_bricks> : 1,
    <item:create:small_limestone_brick_slab> : 1,
    <item:create:small_limestone_brick_stairs> : 1,
    <item:create:small_limestone_brick_wall> : 1,
    <item:create:small_limestone_bricks> : 1,
    <item:create:small_ochrum_brick_slab> : 25,
    <item:create:small_ochrum_brick_stairs> : 50,
    <item:create:small_ochrum_brick_wall> : 50,
    <item:create:small_ochrum_bricks> : 50,
    <item:create:small_rose_quartz_tiles> : 75,
    <item:create:small_scorchia_brick_slab> : 10,
    <item:create:small_scorchia_brick_stairs> : 25,
    <item:create:small_scorchia_brick_wall> : 25,
    <item:create:small_scorchia_bricks> : 25,
    <item:create:small_scoria_brick_slab> : 10,
    <item:create:small_scoria_brick_stairs> : 25,
    <item:create:small_scoria_brick_wall> : 25,
    <item:create:small_scoria_bricks> : 25,
    <item:create:small_tuff_brick_slab> : 1,
    <item:create:small_tuff_brick_stairs> : 1,
    <item:create:small_tuff_brick_wall> : 1,
    <item:create:small_tuff_bricks> : 1,
    <item:create:small_veridium_brick_slab> : 2,
    <item:create:small_veridium_brick_stairs> : 5,
    <item:create:small_veridium_brick_wall> : 5,
    <item:create:small_veridium_bricks> : 5,
    <item:create:spruce_window> : 2,
    <item:create:spruce_window_pane> : 1,
    <item:create:sturdy_sheet> : 10,
    <item:create:super_glue> : 300,
    <item:create:sweet_roll> : 5,
    <item:create:tiled_glass> : 1,
    <item:create:tiled_glass_pane> : 1,
    <item:create:tree_fertilizer> : 10,
    <item:create:tuff_pillar> : 1,
    <item:create:turntable> : 25,
    <item:create:veridium> : 5,
    <item:create:veridium_pillar> : 5,
    <item:create:vertical_framed_glass> : 1,
    <item:create:vertical_framed_glass_pane> : 1,
    <item:create:warped_window> : 2,
    <item:create:warped_window_pane> : 1,
    <item:create:waxed_copper_shingle_slab> : 25,
    <item:create:waxed_copper_shingle_stairs> : 50,
    <item:create:waxed_copper_shingles> : 50,
    <item:create:waxed_copper_tile_slab> : 25,
    <item:create:waxed_copper_tile_stairs> : 50,
    <item:create:waxed_copper_tiles> : 50,
    <item:create:waxed_exposed_copper_shingle_slab> : 25,
    <item:create:waxed_exposed_copper_shingle_stairs> : 50,
    <item:create:waxed_exposed_copper_shingles> : 50,
    <item:create:waxed_exposed_copper_tile_slab> : 25,
    <item:create:waxed_exposed_copper_tile_stairs> : 50,
    <item:create:waxed_exposed_copper_tiles> : 50,
    <item:create:waxed_oxidized_copper_shingle_slab> : 25,
    <item:create:waxed_oxidized_copper_shingle_stairs> : 50,
    <item:create:waxed_oxidized_copper_shingles> : 50,
    <item:create:waxed_oxidized_copper_tile_slab> : 25,
    <item:create:waxed_oxidized_copper_tile_stairs> : 50,
    <item:create:waxed_oxidized_copper_tiles> : 50,
    <item:create:waxed_weathered_copper_shingle_slab> : 25,
    <item:create:waxed_weathered_copper_shingle_stairs> : 50,
    <item:create:waxed_weathered_copper_shingles> : 50,
    <item:create:waxed_weathered_copper_tile_slab> : 25,
    <item:create:waxed_weathered_copper_tile_stairs> : 50,
    <item:create:waxed_weathered_copper_tiles> : 50,
    <item:create:weathered_copper_shingle_slab> : 25,
    <item:create:weathered_copper_shingle_stairs> : 50,
    <item:create:weathered_copper_shingles> : 50,
    <item:create:weathered_copper_tile_slab> : 25,
    <item:create:weathered_copper_tile_stairs> : 50,
    <item:create:weathered_copper_tiles> : 50,
    <item:create:wheat_flour> : 5,
    <item:create:white_sail> : 25,
    <item:create:white_seat> : 10,
    <item:create:white_valve_handle> : 325,
    <item:create:wooden_bracket> : 5,
    <item:create:yellow_seat> : 10,
    <item:create:yellow_valve_handle> : 325,
    <item:create:zinc_block> : 1125,
    <item:create:zinc_nugget> : 10,
    <item:create:zinc_ore> : 250
};

// For each item in the map, check if we're in release mode. If we are, anything below 26 EMC/FMC becomes unburnable for EMC
for item, value in priceTable {
    if (ReleaseMode.releaseMode == true){
        if (value < 26 ) {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), 0);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        } else {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        }
        if (value > 999 && value < 10001) {
            <tag:items:tfb2:fop_miniscule>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Miniscule");
            });
        }
        if (value > 10000 && value < 25001) {
            <tag:items:tfb2:fop_small>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Small");
            });
        }
        if (value > 25000 && value < 75001) {
            <tag:items:tfb2:fop_medium>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Medium");
            });
        }
        if (value > 75000) {
            <tag:items:tfb2:fop_large>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Large");
            });
        }
    } else {
        CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
        <tag:items:projectextended:blacklist_condenser>.add(item);
        <tag:items:projectextended:blacklist_learning>.add(item);
    }
        if (value > 10000 && value < 25001) {
            <tag:items:tfb2:fop_small>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Small");
            });
        }
        if (value > 25000 && value < 75001) {
            <tag:items:tfb2:fop_medium>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Medium");
            });
        }
        if (value > 75000) {
            <tag:items:tfb2:fop_large>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Large");
            });
        }
}