import crafttweaker.api.text.TextComponent;
import crafttweaker.api.tag.MCTag;
import crafttweaker.api.item.IItemStack;
import crafttweaker.api.ingredient.IIngredient;
import crafttweaker.api.item.tooltip.ITooltipFunction;
import stdlib.List;
import mods.projecte.CustomEMC;
import mods.projecte.NSSResolver;

// Item  to EMC/FMC value map.
val priceTable as int[IItemStack] = {
    <item:decorativeentities:alex> : 250,
    <item:decorativeentities:allay> : 250,
    <item:decorativeentities:ari> : 250,
    <item:decorativeentities:armadillo> : 250,
    <item:decorativeentities:ashen_wolf> : 250,
    <item:decorativeentities:bat> : 250,
    <item:decorativeentities:bee> : 250,
    <item:decorativeentities:black_cat> : 250,
    <item:decorativeentities:black_horse> : 250,
    <item:decorativeentities:black_rabbit> : 250,
    <item:decorativeentities:black_sheep> : 250,
    <item:decorativeentities:black_shulker> : 250,
    <item:decorativeentities:black_wolf> : 250,
    <item:decorativeentities:black_y_white_rabbit> : 250,
    <item:decorativeentities:blaze> : 250,
    <item:decorativeentities:blue_axolotl> : 250,
    <item:decorativeentities:blue_parrot> : 250,
    <item:decorativeentities:blue_sheep> : 250,
    <item:decorativeentities:blue_shulker> : 250,
    <item:decorativeentities:bogged> : 250,
    <item:decorativeentities:breeze> : 250,
    <item:decorativeentities:british_shorthair_cat> : 250,
    <item:decorativeentities:brown_horse> : 250,
    <item:decorativeentities:brown_llama> : 250,
    <item:decorativeentities:brown_llama_trader> : 250,
    <item:decorativeentities:brown_llama_with_chest> : 250,
    <item:decorativeentities:brown_llama_with_magenta_carpet> : 250,
    <item:decorativeentities:brown_llama_with_pink_carpet> : 250,
    <item:decorativeentities:brown_llama_with_purple_carpet> : 250,
    <item:decorativeentities:brown_llama_with_red_carpet> : 250,
    <item:decorativeentities:brown_mooshroom> : 250,
    <item:decorativeentities:brown_panda> : 250,
    <item:decorativeentities:brown_rabbit> : 250,
    <item:decorativeentities:brown_sheep> : 250,
    <item:decorativeentities:brown_shulker> : 250,
    <item:decorativeentities:calico_cat> : 250,
    <item:decorativeentities:camel> : 250,
    <item:decorativeentities:cave_spider> : 250,
    <item:decorativeentities:chestnut_horse> : 250,
    <item:decorativeentities:chestnut_wolf> : 250,
    <item:decorativeentities:chicken> : 250,
    <item:decorativeentities:cod> : 250,
    <item:decorativeentities:cold_frog> : 250,
    <item:decorativeentities:cold_strider> : 250,
    <item:decorativeentities:cow> : 250,
    <item:decorativeentities:creaking> : 250,
    <item:decorativeentities:creamy_horse> : 250,
    <item:decorativeentities:creamy_llama> : 250,
    <item:decorativeentities:creamy_llama_trader> : 250,
    <item:decorativeentities:creamy_llama_with_brown_carpet> : 250,
    <item:decorativeentities:creamy_llama_with_chest> : 250,
    <item:decorativeentities:creamy_llama_with_light_gray_carpet> : 250,
    <item:decorativeentities:creamy_llama_with_white_carpet> : 250,
    <item:decorativeentities:creamy_llama_with_yellow_carpet> : 250,
    <item:decorativeentities:creeper> : 250,
    <item:decorativeentities:cyan_axolotl> : 250,
    <item:decorativeentities:cyan_sheep> : 250,
    <item:decorativeentities:cyan_shulker> : 250,
    <item:decorativeentities:dark_brown_horse> : 250,
    <item:decorativeentities:dolphin> : 250,
    <item:decorativeentities:donkey> : 250,
    <item:decorativeentities:donkey_with_chest> : 250,
    <item:decorativeentities:drowned> : 250,
    <item:decorativeentities:efe> : 250,
    <item:decorativeentities:ender_dragon> : 250,
    <item:decorativeentities:enderman> : 250,
    <item:decorativeentities:endermite> : 250,
    <item:decorativeentities:evoker> : 250,
    <item:decorativeentities:fox> : 250,
    <item:decorativeentities:frame> : 250,
    <item:decorativeentities:ghast> : 250,
    <item:decorativeentities:ghast_shooting> : 250,
    <item:decorativeentities:glow_squid> : 250,
    <item:decorativeentities:goat> : 250,
    <item:decorativeentities:gold_axolotl> : 250,
    <item:decorativeentities:gold_rabbit> : 250,
    <item:decorativeentities:gray_horse> : 250,
    <item:decorativeentities:gray_llama> : 250,
    <item:decorativeentities:gray_llama_trader> : 250,
    <item:decorativeentities:gray_llama_with_black_carpet> : 250,
    <item:decorativeentities:gray_llama_with_blue_carpet> : 250,
    <item:decorativeentities:gray_llama_with_chest> : 250,
    <item:decorativeentities:gray_llama_with_gray_carpet> : 250,
    <item:decorativeentities:gray_llama_with_light_blue_carpet> : 250,
    <item:decorativeentities:gray_sheep> : 250,
    <item:decorativeentities:gray_shulker> : 250,
    <item:decorativeentities:green_parrot> : 250,
    <item:decorativeentities:green_sheep> : 250,
    <item:decorativeentities:green_shulker> : 250,
    <item:decorativeentities:grey_parrot> : 250,
    <item:decorativeentities:guardian> : 250,
    <item:decorativeentities:guardian_elder> : 250,
    <item:decorativeentities:hoglin> : 250,
    <item:decorativeentities:husk> : 250,
    <item:decorativeentities:illusioner> : 250,
    <item:decorativeentities:iron_golem> : 250,
    <item:decorativeentities:jellie_cat> : 250,
    <item:decorativeentities:kai> : 250,
    <item:decorativeentities:killer_bunny_rabbit> : 250,
    <item:decorativeentities:light_blue_sheep> : 250,
    <item:decorativeentities:light_blue_shulker> : 250,
    <item:decorativeentities:light_gray_sheep> : 250,
    <item:decorativeentities:light_gray_shulker> : 250,
    <item:decorativeentities:lime_sheep> : 250,
    <item:decorativeentities:lime_shulker> : 250,
    <item:decorativeentities:lucy_axolotl> : 250,
    <item:decorativeentities:magenta_sheep> : 250,
    <item:decorativeentities:magenta_shulker> : 250,
    <item:decorativeentities:magmacube> : 250,
    <item:decorativeentities:makena> : 250,
    <item:decorativeentities:mini_zombie> : 250,
    <item:decorativeentities:mule> : 250,
    <item:decorativeentities:mule_with_chest> : 250,
    <item:decorativeentities:noor> : 250,
    <item:decorativeentities:ocelot> : 250,
    <item:decorativeentities:orange_sheep> : 250,
    <item:decorativeentities:orange_shulker> : 250,
    <item:decorativeentities:pale_wolf> : 250,
    <item:decorativeentities:panda> : 250,
    <item:decorativeentities:persian_cat> : 250,
    <item:decorativeentities:phantom> : 250,
    <item:decorativeentities:pig> : 250,
    <item:decorativeentities:piglin> : 250,
    <item:decorativeentities:piglin_brute> : 250,
    <item:decorativeentities:pillager> : 250,
    <item:decorativeentities:pink_sheep> : 250,
    <item:decorativeentities:pink_shulker> : 250,
    <item:decorativeentities:polar_bear> : 250,
    <item:decorativeentities:pufferfish_big> : 250,
    <item:decorativeentities:pufferfish_small> : 250,
    <item:decorativeentities:purple_sheep> : 250,
    <item:decorativeentities:purple_shulker> : 250,
    <item:decorativeentities:ragdoll_cat> : 250,
    <item:decorativeentities:ravager> : 250,
    <item:decorativeentities:red_blue_parrot> : 250,
    <item:decorativeentities:red_cat> : 250,
    <item:decorativeentities:red_mooshroom> : 250,
    <item:decorativeentities:red_sheep> : 250,
    <item:decorativeentities:red_shulker> : 250,
    <item:decorativeentities:rusty_wolf> : 250,
    <item:decorativeentities:salmon> : 250,
    <item:decorativeentities:salt_y_pepper_rabbit> : 250,
    <item:decorativeentities:sheep> : 250,
    <item:decorativeentities:shulker> : 250,
    <item:decorativeentities:siamese_cat> : 250,
    <item:decorativeentities:silverfish> : 250,
    <item:decorativeentities:skeleton> : 250,
    <item:decorativeentities:skeleton_horse> : 250,
    <item:decorativeentities:slime> : 250,
    <item:decorativeentities:sniffer> : 250,
    <item:decorativeentities:snow_fox> : 250,
    <item:decorativeentities:snow_golem> : 250,
    <item:decorativeentities:snowy_wolf> : 250,
    <item:decorativeentities:spider> : 250,
    <item:decorativeentities:spotted_wolf> : 250,
    <item:decorativeentities:squid> : 250,
    <item:decorativeentities:steven> : 250,
    <item:decorativeentities:stray> : 250,
    <item:decorativeentities:stray_overlay> : 250,
    <item:decorativeentities:strider> : 250,
    <item:decorativeentities:striped_wolf> : 250,
    <item:decorativeentities:sunny> : 250,
    <item:decorativeentities:tabby_cat> : 250,
    <item:decorativeentities:temperate_frog> : 250,
    <item:decorativeentities:toast_rabbit> : 250,
    <item:decorativeentities:tropical_fish_1> : 250,
    <item:decorativeentities:tropical_fish_2> : 250,
    <item:decorativeentities:turtle> : 250,
    <item:decorativeentities:tuxedo_cat> : 250,
    <item:decorativeentities:vex> : 250,
    <item:decorativeentities:vex_charging> : 250,
    <item:decorativeentities:villager> : 250,
    <item:decorativeentities:villager_armorer> : 250,
    <item:decorativeentities:villager_butcher> : 250,
    <item:decorativeentities:villager_cartographer> : 250,
    <item:decorativeentities:villager_cleric> : 250,
    <item:decorativeentities:villager_desert> : 250,
    <item:decorativeentities:villager_farmer> : 250,
    <item:decorativeentities:villager_fisherman> : 250,
    <item:decorativeentities:villager_fletcher> : 250,
    <item:decorativeentities:villager_jungle> : 250,
    <item:decorativeentities:villager_leatherworker> : 250,
    <item:decorativeentities:villager_librarian> : 250,
    <item:decorativeentities:villager_mason> : 250,
    <item:decorativeentities:villager_nitwit> : 250,
    <item:decorativeentities:villager_plains> : 250,
    <item:decorativeentities:villager_savanna> : 250,
    <item:decorativeentities:villager_shepherd> : 250,
    <item:decorativeentities:villager_snow> : 250,
    <item:decorativeentities:villager_swamp> : 250,
    <item:decorativeentities:villager_taiga> : 250,
    <item:decorativeentities:villager_toolsmith> : 250,
    <item:decorativeentities:villager_weaponsmith> : 250,
    <item:decorativeentities:vindicator> : 250,
    <item:decorativeentities:wandering_trader> : 250,
    <item:decorativeentities:warden> : 250,
    <item:decorativeentities:warm_frog> : 250,
    <item:decorativeentities:white_cat> : 250,
    <item:decorativeentities:white_horse> : 250,
    <item:decorativeentities:white_llama> : 250,
    <item:decorativeentities:white_llama_trader> : 250,
    <item:decorativeentities:white_llama_with_chest> : 250,
    <item:decorativeentities:white_llama_with_cyan_carpet> : 250,
    <item:decorativeentities:white_llama_with_green_carpet> : 250,
    <item:decorativeentities:white_llama_with_lime_carpet> : 250,
    <item:decorativeentities:white_llama_with_orange_carpet> : 250,
    <item:decorativeentities:white_rabbit> : 250,
    <item:decorativeentities:white_shulker> : 250,
    <item:decorativeentities:wild_axolotl> : 250,
    <item:decorativeentities:witch> : 250,
    <item:decorativeentities:wither> : 250,
    <item:decorativeentities:wither_invulnerable> : 250,
    <item:decorativeentities:wither_skeleton> : 250,
    <item:decorativeentities:woods_wolf> : 250,
    <item:decorativeentities:yellow_blue_parrot> : 250,
    <item:decorativeentities:yellow_sheep> : 250,
    <item:decorativeentities:yellow_shulker> : 250,
    <item:decorativeentities:zoglin> : 250,
    <item:decorativeentities:zombie> : 250,
    <item:decorativeentities:zombie_horse> : 250,
    <item:decorativeentities:zombie_villager> : 250,
    <item:decorativeentities:zombified_piglin> : 250,
    <item:decorativeentities:zuri> : 250
};

// For each item in the map, check if we're in release mode. If we are, anything below 26 EMC/FMC becomes unburnable for EMC
for item, value in priceTable {
    if (ReleaseMode.releaseMode == true){
        if (value < 26 ) {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), 0);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        } else {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
            item.addTooltip(new TextComponent("Lost Deco").withStyle(style => style.withColor(<constant:minecraft:formatting:gold>)));
            item.addTooltip(new TextComponent("Only Found in the Liminal Mall").withStyle(style => style.withColor(<constant:minecraft:formatting:gold>)));
        }
    } else {
        CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
        <tag:items:projectextended:blacklist_condenser>.add(item);
        <tag:items:projectextended:blacklist_learning>.add(item);
            item.addTooltip(new TextComponent("Lost Deco").withStyle(style => style.withColor(<constant:minecraft:formatting:gold>)));
            item.addTooltip(new TextComponent("Only Found in the Liminal Mall").withStyle(style => style.withColor(<constant:minecraft:formatting:gold>)));
    }
}