import crafttweaker.api.tag.MCTag;
import crafttweaker.api.item.IItemStack;
import crafttweaker.api.ingredient.IIngredient;
import crafttweaker.api.item.tooltip.ITooltipFunction;
import stdlib.List;
import mods.projecte.CustomEMC;
import mods.projecte.NSSResolver;

// Item  to EMC/FMC value map.
val priceTable as int[IItemStack] = {
    <item:everycomp:mcw/minestuck/time_aspect_plank_parapet> : 1,
    <item:everycomp:mcw/minestuck/time_aspect_plank_window> : 2,
    <item:everycomp:mcw/minestuck/time_aspect_plank_window2> : 2,
    <item:everycomp:mcw/minestuck/time_aspect_shutter> : 1,
    <item:everycomp:mcw/minestuck/time_aspect_window> : 2,
    <item:everycomp:mcw/minestuck/time_aspect_window2> : 2,
    <item:everycomp:mcw/minestuck/void_aspect_blinds> : 2,
    <item:everycomp:mcw/minestuck/void_aspect_four_window> : 2,
    <item:everycomp:mcw/minestuck/void_aspect_log_parapet> : 1,
    <item:everycomp:mcw/minestuck/void_aspect_louvered_shutter> : 1,
    <item:everycomp:mcw/minestuck/void_aspect_pane_window> : 2,
    <item:everycomp:mcw/minestuck/void_aspect_plank_four_window> : 2,
    <item:everycomp:mcw/minestuck/void_aspect_plank_pane_window> : 2,
    <item:everycomp:mcw/minestuck/void_aspect_plank_parapet> : 1,
    <item:everycomp:mcw/minestuck/void_aspect_plank_window> : 2,
    <item:everycomp:mcw/minestuck/void_aspect_plank_window2> : 2,
    <item:everycomp:mcw/minestuck/void_aspect_shutter> : 1,
    <item:everycomp:mcw/minestuck/void_aspect_window> : 2,
    <item:everycomp:mcw/minestuck/void_aspect_window2> : 2,
    <item:everycomp:mcw/quark/azalea_blinds> : 2,
    <item:everycomp:mcw/quark/azalea_four_window> : 2,
    <item:everycomp:mcw/quark/azalea_log_parapet> : 1,
    <item:everycomp:mcw/quark/azalea_louvered_shutter> : 1,
    <item:everycomp:mcw/quark/azalea_pane_window> : 2,
    <item:everycomp:mcw/quark/azalea_plank_four_window> : 2,
    <item:everycomp:mcw/quark/azalea_plank_pane_window> : 2,
    <item:everycomp:mcw/quark/azalea_plank_parapet> : 1,
    <item:everycomp:mcw/quark/azalea_plank_window> : 2,
    <item:everycomp:mcw/quark/azalea_plank_window2> : 2,
    <item:everycomp:mcw/quark/azalea_shutter> : 1,
    <item:everycomp:mcw/quark/azalea_window> : 2,
    <item:everycomp:mcw/quark/azalea_window2> : 2,
    <item:everycomp:mcw/quark/blossom_blinds> : 2,
    <item:everycomp:mcw/quark/blossom_four_window> : 2,
    <item:everycomp:mcw/quark/blossom_log_parapet> : 1,
    <item:everycomp:mcw/quark/blossom_louvered_shutter> : 1,
    <item:everycomp:mcw/quark/blossom_pane_window> : 2,
    <item:everycomp:mcw/quark/blossom_plank_four_window> : 2,
    <item:everycomp:mcw/quark/blossom_plank_pane_window> : 2,
    <item:everycomp:mcw/quark/blossom_plank_parapet> : 1,
    <item:everycomp:mcw/quark/blossom_plank_window> : 2,
    <item:everycomp:mcw/quark/blossom_plank_window2> : 2,
    <item:everycomp:mcw/quark/blossom_shutter> : 1,
    <item:everycomp:mcw/quark/blossom_window> : 2,
    <item:everycomp:mcw/quark/blossom_window2> : 2,
    <item:everycomp:mcw/quark/stripped_azalea_log_four_window> : 2,
    <item:everycomp:mcw/quark/stripped_azalea_log_window> : 2,
    <item:everycomp:mcw/quark/stripped_azalea_log_window2> : 2,
    <item:everycomp:mcw/quark/stripped_azalea_pane_window> : 2,
    <item:everycomp:mcw/quark/stripped_blossom_log_four_window> : 2,
    <item:everycomp:mcw/quark/stripped_blossom_log_window> : 2,
    <item:everycomp:mcw/quark/stripped_blossom_log_window2> : 2,
    <item:everycomp:mcw/quark/stripped_blossom_pane_window> : 2,
    <item:everycomp:mcw/the_vault/chromatic_blinds> : 2,
    <item:everycomp:mcw/the_vault/chromatic_four_window> : 2,
    <item:everycomp:mcw/the_vault/chromatic_log_parapet> : 1,
    <item:everycomp:mcw/the_vault/chromatic_louvered_shutter> : 1,
    <item:everycomp:mcw/the_vault/chromatic_pane_window> : 2,
    <item:everycomp:mcw/the_vault/chromatic_plank_four_window> : 2,
    <item:everycomp:mcw/the_vault/chromatic_plank_pane_window> : 2,
    <item:everycomp:mcw/the_vault/chromatic_plank_parapet> : 1,
    <item:everycomp:mcw/the_vault/chromatic_plank_window> : 2,
    <item:everycomp:mcw/the_vault/chromatic_plank_window2> : 2,
    <item:everycomp:mcw/the_vault/chromatic_shutter> : 1,
    <item:everycomp:mcw/the_vault/chromatic_window> : 2,
    <item:everycomp:mcw/the_vault/chromatic_window2> : 2,
    <item:everycomp:mcw/the_vault/stripped_chromatic_log_four_window> : 2,
    <item:everycomp:mcw/the_vault/stripped_chromatic_log_window> : 2,
    <item:everycomp:mcw/the_vault/stripped_chromatic_log_window2> : 2,
    <item:everycomp:mcw/the_vault/stripped_chromatic_pane_window> : 2,
    <item:everycomp:mcw/the_vault/stripped_tenos_log_four_window> : 2,
    <item:everycomp:mcw/the_vault/stripped_tenos_log_window> : 2,
    <item:everycomp:mcw/the_vault/stripped_tenos_log_window2> : 2,
    <item:everycomp:mcw/the_vault/stripped_tenos_pane_window> : 2,
    <item:everycomp:mcw/the_vault/stripped_velara_log_four_window> : 2,
    <item:everycomp:mcw/the_vault/stripped_velara_log_window> : 2,
    <item:everycomp:mcw/the_vault/stripped_velara_log_window2> : 2,
    <item:everycomp:mcw/the_vault/stripped_velara_pane_window> : 2,
    <item:everycomp:mcw/the_vault/tenos_blinds> : 2,
    <item:everycomp:mcw/the_vault/tenos_four_window> : 2,
    <item:everycomp:mcw/the_vault/tenos_log_parapet> : 1,
    <item:everycomp:mcw/the_vault/tenos_louvered_shutter> : 1,
    <item:everycomp:mcw/the_vault/tenos_pane_window> : 2,
    <item:everycomp:mcw/the_vault/tenos_plank_four_window> : 2,
    <item:everycomp:mcw/the_vault/tenos_plank_pane_window> : 2,
    <item:everycomp:mcw/the_vault/tenos_plank_parapet> : 1,
    <item:everycomp:mcw/the_vault/tenos_plank_window> : 2,
    <item:everycomp:mcw/the_vault/tenos_plank_window2> : 2,
    <item:everycomp:mcw/the_vault/tenos_shutter> : 1,
    <item:everycomp:mcw/the_vault/tenos_window> : 2,
    <item:everycomp:mcw/the_vault/tenos_window2> : 2,
    <item:everycomp:mcw/the_vault/velara_blinds> : 2,
    <item:everycomp:mcw/the_vault/velara_four_window> : 2,
    <item:everycomp:mcw/the_vault/velara_log_parapet> : 1,
    <item:everycomp:mcw/the_vault/velara_louvered_shutter> : 1,
    <item:everycomp:mcw/the_vault/velara_pane_window> : 2,
    <item:everycomp:mcw/the_vault/velara_plank_four_window> : 2,
    <item:everycomp:mcw/the_vault/velara_plank_pane_window> : 2,
    <item:everycomp:mcw/the_vault/velara_plank_parapet> : 1,
    <item:everycomp:mcw/the_vault/velara_plank_window> : 2,
    <item:everycomp:mcw/the_vault/velara_plank_window2> : 2,
    <item:everycomp:mcw/the_vault/velara_shutter> : 1,
    <item:everycomp:mcw/the_vault/velara_window> : 2,
    <item:everycomp:mcw/the_vault/velara_window2> : 2,
    <item:everycomp:mcw/tropicraft/mahogany_blinds> : 2,
    <item:everycomp:mcw/tropicraft/mahogany_four_window> : 2,
    <item:everycomp:mcw/tropicraft/mahogany_log_parapet> : 1,
    <item:everycomp:mcw/tropicraft/mahogany_louvered_shutter> : 1,
    <item:everycomp:mcw/tropicraft/mahogany_pane_window> : 2,
    <item:everycomp:mcw/tropicraft/mahogany_plank_four_window> : 2,
    <item:everycomp:mcw/tropicraft/mahogany_plank_pane_window> : 2,
    <item:everycomp:mcw/tropicraft/mahogany_plank_parapet> : 1,
    <item:everycomp:mcw/tropicraft/mahogany_plank_window> : 2,
    <item:everycomp:mcw/tropicraft/mahogany_plank_window2> : 2,
    <item:everycomp:mcw/tropicraft/mahogany_shutter> : 1,
    <item:everycomp:mcw/tropicraft/mahogany_window> : 2,
    <item:everycomp:mcw/tropicraft/mahogany_window2> : 2,
    <item:everycomp:mcw/tropicraft/palm_blinds> : 2,
    <item:everycomp:mcw/tropicraft/palm_four_window> : 2,
    <item:everycomp:mcw/tropicraft/palm_log_parapet> : 1,
    <item:everycomp:mcw/tropicraft/palm_louvered_shutter> : 1,
    <item:everycomp:mcw/tropicraft/palm_pane_window> : 2,
    <item:everycomp:mcw/tropicraft/palm_plank_four_window> : 2,
    <item:everycomp:mcw/tropicraft/palm_plank_pane_window> : 2,
    <item:everycomp:mcw/tropicraft/palm_plank_parapet> : 1,
    <item:everycomp:mcw/tropicraft/palm_plank_window> : 2,
    <item:everycomp:mcw/tropicraft/palm_plank_window2> : 2,
    <item:everycomp:mcw/tropicraft/palm_shutter> : 1,
    <item:everycomp:mcw/tropicraft/palm_window> : 2,
    <item:everycomp:mcw/tropicraft/palm_window2> : 2,
    <item:everycomp:mcw/tropicraft/stripped_mahogany_log_four_window> : 2,
    <item:everycomp:mcw/tropicraft/stripped_mahogany_log_window> : 2,
    <item:everycomp:mcw/tropicraft/stripped_mahogany_log_window2> : 2,
    <item:everycomp:mcw/tropicraft/stripped_mahogany_pane_window> : 2,
    <item:everycomp:mcw/tropicraft/stripped_palm_log_four_window> : 2,
    <item:everycomp:mcw/tropicraft/stripped_palm_log_window> : 2,
    <item:everycomp:mcw/tropicraft/stripped_palm_log_window2> : 2,
    <item:everycomp:mcw/tropicraft/stripped_palm_pane_window> : 2,
    <item:everycomp:mcw/twigs/bamboo_blinds> : 2,
    <item:everycomp:mcw/twigs/bamboo_four_window> : 2,
    <item:everycomp:mcw/twigs/bamboo_log_parapet> : 1,
    <item:everycomp:mcw/twigs/bamboo_louvered_shutter> : 1,
    <item:everycomp:mcw/twigs/bamboo_pane_window> : 2,
    <item:everycomp:mcw/twigs/bamboo_plank_four_window> : 2,
    <item:everycomp:mcw/twigs/bamboo_plank_pane_window> : 2,
    <item:everycomp:mcw/twigs/bamboo_plank_parapet> : 1,
    <item:everycomp:mcw/twigs/bamboo_plank_window> : 2,
    <item:everycomp:mcw/twigs/bamboo_plank_window2> : 1,
    <item:everycomp:mcw/twigs/bamboo_window> : 2,
    <item:everycomp:mcw/twigs/bamboo_window2> : 2,
    <item:everycomp:mcw/twigs/stripped_bamboo_log_four_window> : 2,
    <item:everycomp:mcw/twigs/stripped_bamboo_log_window> : 2,
    <item:everycomp:mcw/twigs/stripped_bamboo_log_window2> : 2,
    <item:everycomp:mcw/twigs/stripped_bamboo_pane_window> : 2,
    <item:everycomp:q/architects_palette/stripped_twisted_post> : 1,
    <item:everycomp:q/architects_palette/twisted_bookshelf> : 25,
    <item:everycomp:q/architects_palette/twisted_chest> : 10,
    <item:everycomp:q/architects_palette/twisted_hedge> : 1,
    <item:everycomp:q/architects_palette/twisted_ladder> : 1,
    <item:everycomp:q/architects_palette/twisted_post> : 1,
    <item:everycomp:q/architects_palette/twisted_trapped_chest> : 125,
    <item:everycomp:q/architects_palette/vertical_twisted_planks> : 1,
    <item:everycomp:q/botania/livingwood_bookshelf> : 25,
    <item:everycomp:q/botania/livingwood_chest> : 10,
    <item:everycomp:q/botania/livingwood_ladder> : 1,
    <item:everycomp:q/botania/livingwood_post> : 1,
    <item:everycomp:q/botania/livingwood_trapped_chest> : 125,
    <item:everycomp:q/botania/stripped_dreamwood_post> : 1,
    <item:everycomp:q/botania/stripped_livingwood_post> : 1,
    <item:everycomp:q/botania/vertical_dreamwood_planks> : 1,
    <item:everycomp:q/botania/vertical_livingwood_planks> : 1,
    <item:everycomp:q/createdieselgenerators/chip_wood_bookshelf> : 25,
    <item:everycomp:q/createdieselgenerators/chip_wood_chest> : 10,
    <item:everycomp:q/createdieselgenerators/chip_wood_ladder> : 1,
    <item:everycomp:q/createdieselgenerators/chip_wood_trapped_chest> : 125,
    <item:everycomp:q/createdieselgenerators/vertical_chip_wood_planks> : 1,
    <item:everycomp:q/ecologics/coconut_bookshelf> : 25,
    <item:everycomp:q/ecologics/coconut_chest> : 10,
    <item:everycomp:q/ecologics/coconut_hedge> : 1,
    <item:everycomp:q/ecologics/coconut_ladder> : 1,
    <item:everycomp:q/ecologics/coconut_post> : 1,
    <item:everycomp:q/ecologics/coconut_trapped_chest> : 125,
    <item:everycomp:q/ecologics/flowering_azalea_bookshelf> : 25,
    <item:everycomp:q/ecologics/flowering_azalea_chest> : 10,
    <item:everycomp:q/ecologics/flowering_azalea_ladder> : 1,
    <item:everycomp:q/ecologics/flowering_azalea_post> : 1,
    <item:everycomp:q/ecologics/flowering_azalea_trapped_chest> : 125,
    <item:everycomp:q/ecologics/stripped_coconut_post> : 1,
    <item:everycomp:q/ecologics/stripped_flowering_azalea_post> : 1,
    <item:everycomp:q/ecologics/stripped_walnut_post> : 1,
    <item:everycomp:q/ecologics/vertical_coconut_planks> : 1,
    <item:everycomp:q/ecologics/vertical_flowering_azalea_planks> : 1,
    <item:everycomp:q/ecologics/vertical_walnut_planks> : 1,
    <item:everycomp:q/ecologics/walnut_bookshelf> : 25,
    <item:everycomp:q/ecologics/walnut_chest> : 10,
    <item:everycomp:q/ecologics/walnut_hedge> : 1,
    <item:everycomp:q/ecologics/walnut_ladder> : 1,
    <item:everycomp:q/ecologics/walnut_post> : 1,
    <item:everycomp:q/ecologics/walnut_trapped_chest> : 125,
    <item:everycomp:q/hexcasting/akashic_chest> : 10,
    <item:everycomp:q/hexcasting/akashic_ladder> : 1,
    <item:everycomp:q/hexcasting/akashic_trapped_chest> : 125,
    <item:everycomp:q/hexcasting/vertical_akashic_planks> : 1,
    <item:everycomp:q/integrateddynamics/menril_bookshelf> : 25,
    <item:everycomp:q/integrateddynamics/menril_chest> : 10,
    <item:everycomp:q/integrateddynamics/menril_hedge> : 1,
    <item:everycomp:q/integrateddynamics/menril_ladder> : 1,
    <item:everycomp:q/integrateddynamics/menril_post> : 1,
    <item:everycomp:q/integrateddynamics/menril_trapped_chest> : 125,
    <item:everycomp:q/integrateddynamics/vertical_menril_planks> : 1,
    <item:everycomp:q/luphieclutteredmod/luphie_flowering_pink_chest> : 10,
    <item:everycomp:q/luphieclutteredmod/luphie_flowering_pink_ladder> : 1,
    <item:everycomp:q/luphieclutteredmod/luphie_flowering_pink_post> : 1,
    <item:everycomp:q/luphieclutteredmod/luphie_flowering_pink_trapped_chest> : 125,
    <item:everycomp:q/luphieclutteredmod/luphie_flowering_purple_bookshelf> : 25,
    <item:everycomp:q/luphieclutteredmod/luphie_flowering_purple_chest> : 10,
    <item:everycomp:q/luphieclutteredmod/luphie_flowering_purple_ladder> : 1,
    <item:everycomp:q/luphieclutteredmod/luphie_flowering_purple_post> : 1,
    <item:everycomp:q/luphieclutteredmod/luphie_flowering_purple_trapped_chest> : 125,
    <item:everycomp:q/luphieclutteredmod/luphie_flowering_yellow_chest> : 10,
    <item:everycomp:q/luphieclutteredmod/luphie_flowering_yellow_ladder> : 1,
    <item:everycomp:q/luphieclutteredmod/luphie_flowering_yellow_post> : 1,
    <item:everycomp:q/luphieclutteredmod/luphie_flowering_yellow_trapped_chest> : 125,
    <item:everycomp:q/luphieclutteredmod/luphie_glow_chest> : 10,
    <item:everycomp:q/luphieclutteredmod/luphie_glow_ladder> : 1,
    <item:everycomp:q/luphieclutteredmod/luphie_glow_trapped_chest> : 125,
    <item:everycomp:q/luphieclutteredmod/luphie_green_chest> : 10,
    <item:everycomp:q/luphieclutteredmod/luphie_green_ladder> : 1,
    <item:everycomp:q/luphieclutteredmod/luphie_green_post> : 1,
    <item:everycomp:q/luphieclutteredmod/luphie_green_trapped_chest> : 125,
    <item:everycomp:q/luphieclutteredmod/luphie_pink_chest> : 10,
    <item:everycomp:q/luphieclutteredmod/luphie_pink_ladder> : 1,
    <item:everycomp:q/luphieclutteredmod/luphie_pink_post> : 1,
    <item:everycomp:q/luphieclutteredmod/luphie_pink_trapped_chest> : 125,
    <item:everycomp:q/luphieclutteredmod/luphie_purple_bookshelf> : 25,
    <item:everycomp:q/luphieclutteredmod/luphie_purple_chest> : 10,
    <item:everycomp:q/luphieclutteredmod/luphie_purple_ladder> : 1,
    <item:everycomp:q/luphieclutteredmod/luphie_purple_trapped_chest> : 125,
    <item:everycomp:q/luphieclutteredmod/luphie_yellow_chest> : 10,
    <item:everycomp:q/luphieclutteredmod/luphie_yellow_ladder> : 1,
    <item:everycomp:q/luphieclutteredmod/luphie_yellow_post> : 1,
    <item:everycomp:q/luphieclutteredmod/luphie_yellow_trapped_chest> : 125,
    <item:everycomp:q/luphieclutteredmod/stripped_luphie_flowering_purple_post> : 1,
    <item:everycomp:q/luphieclutteredmod/stripped_luphie_green_post> : 1,
    <item:everycomp:q/luphieclutteredmod/stripped_luphie_pink_post> : 1,
    <item:everycomp:q/luphieclutteredmod/stripped_luphie_yellow_post> : 1,
    <item:everycomp:q/luphieclutteredmod/vertical_luphie_flowering_pink_planks> : 1,
    <item:everycomp:q/luphieclutteredmod/vertical_luphie_flowering_purple_planks> : 1,
    <item:everycomp:q/luphieclutteredmod/vertical_luphie_flowering_yellow_planks> : 1,
    <item:everycomp:q/luphieclutteredmod/vertical_luphie_glow_planks> : 1,
    <item:everycomp:q/luphieclutteredmod/vertical_luphie_green_planks> : 1,
    <item:everycomp:q/luphieclutteredmod/vertical_luphie_pink_planks> : 1,
    <item:everycomp:q/luphieclutteredmod/vertical_luphie_purple_planks> : 1,
    <item:everycomp:q/luphieclutteredmod/vertical_luphie_yellow_planks> : 1,
    <item:everycomp:q/minestuck/blood_aspect_bookshelf> : 25,
    <item:everycomp:q/minestuck/blood_aspect_chest> : 10,
    <item:everycomp:q/minestuck/blood_aspect_hedge> : 1,
    <item:everycomp:q/minestuck/blood_aspect_ladder> : 1,
    <item:everycomp:q/minestuck/blood_aspect_trapped_chest> : 125,
    <item:everycomp:q/minestuck/breath_aspect_bookshelf> : 25,
    <item:everycomp:q/minestuck/breath_aspect_chest> : 10,
    <item:everycomp:q/minestuck/breath_aspect_hedge> : 1,
    <item:everycomp:q/minestuck/breath_aspect_ladder> : 1,
    <item:everycomp:q/minestuck/breath_aspect_trapped_chest> : 125,
    <item:everycomp:q/minestuck/dead_bookshelf> : 25,
    <item:everycomp:q/minestuck/dead_chest> : 10,
    <item:everycomp:q/minestuck/dead_ladder> : 1,
    <item:everycomp:q/minestuck/dead_trapped_chest> : 125,
    <item:everycomp:q/minestuck/doom_aspect_bookshelf> : 25,
    <item:everycomp:q/minestuck/doom_aspect_chest> : 10,
    <item:everycomp:q/minestuck/doom_aspect_hedge> : 1,
    <item:everycomp:q/minestuck/doom_aspect_ladder> : 1,
    <item:everycomp:q/minestuck/doom_aspect_trapped_chest> : 125,
    <item:everycomp:q/minestuck/end_bookshelf> : 25,
    <item:everycomp:q/minestuck/end_chest> : 10,
    <item:everycomp:q/minestuck/end_hedge> : 1,
    <item:everycomp:q/minestuck/end_ladder> : 1,
    <item:everycomp:q/minestuck/end_trapped_chest> : 125,
    <item:everycomp:q/minestuck/frost_bookshelf> : 25,
    <item:everycomp:q/minestuck/frost_chest> : 10,
    <item:everycomp:q/minestuck/frost_hedge> : 1,
    <item:everycomp:q/minestuck/frost_ladder> : 1,
    <item:everycomp:q/minestuck/frost_trapped_chest> : 125,
    <item:everycomp:q/minestuck/glowing_bookshelf> : 25,
    <item:everycomp:q/minestuck/glowing_chest> : 10,
    <item:everycomp:q/minestuck/glowing_ladder> : 1,
    <item:everycomp:q/minestuck/glowing_trapped_chest> : 125,
    <item:everycomp:q/minestuck/heart_aspect_bookshelf> : 25,
    <item:everycomp:q/minestuck/heart_aspect_chest> : 10,
    <item:everycomp:q/minestuck/heart_aspect_hedge> : 1,
    <item:everycomp:q/minestuck/heart_aspect_ladder> : 1,
    <item:everycomp:q/minestuck/heart_aspect_trapped_chest> : 125,
    <item:everycomp:q/minestuck/hope_aspect_bookshelf> : 25,
    <item:everycomp:q/minestuck/hope_aspect_chest> : 10,
    <item:everycomp:q/minestuck/hope_aspect_hedge> : 1,
    <item:everycomp:q/minestuck/hope_aspect_ladder> : 1,
    <item:everycomp:q/minestuck/hope_aspect_trapped_chest> : 125,
    <item:everycomp:q/minestuck/life_aspect_bookshelf> : 25,
    <item:everycomp:q/minestuck/life_aspect_chest> : 10,
    <item:everycomp:q/minestuck/life_aspect_hedge> : 1,
    <item:everycomp:q/minestuck/life_aspect_ladder> : 1,
    <item:everycomp:q/minestuck/life_aspect_trapped_chest> : 125,
    <item:everycomp:q/minestuck/light_aspect_bookshelf> : 25,
    <item:everycomp:q/minestuck/light_aspect_chest> : 10,
    <item:everycomp:q/minestuck/light_aspect_hedge> : 1,
    <item:everycomp:q/minestuck/light_aspect_ladder> : 1,
    <item:everycomp:q/minestuck/light_aspect_trapped_chest> : 125,
    <item:everycomp:q/minestuck/mind_aspect_bookshelf> : 25,
    <item:everycomp:q/minestuck/mind_aspect_chest> : 10,
    <item:everycomp:q/minestuck/mind_aspect_hedge> : 1,
    <item:everycomp:q/minestuck/mind_aspect_ladder> : 1,
    <item:everycomp:q/minestuck/mind_aspect_trapped_chest> : 125,
    <item:everycomp:q/minestuck/rage_aspect_bookshelf> : 25,
    <item:everycomp:q/minestuck/rage_aspect_chest> : 10,
    <item:everycomp:q/minestuck/rage_aspect_hedge> : 1,
    <item:everycomp:q/minestuck/rage_aspect_ladder> : 1,
    <item:everycomp:q/minestuck/rage_aspect_trapped_chest> : 125,
    <item:everycomp:q/minestuck/rainbow_bookshelf> : 25,
    <item:everycomp:q/minestuck/rainbow_chest> : 10,
    <item:everycomp:q/minestuck/rainbow_hedge> : 1,
    <item:everycomp:q/minestuck/rainbow_ladder> : 1,
    <item:everycomp:q/minestuck/rainbow_trapped_chest> : 125,
    <item:everycomp:q/minestuck/space_aspect_bookshelf> : 25,
    <item:everycomp:q/minestuck/space_aspect_chest> : 10,
    <item:everycomp:q/minestuck/space_aspect_hedge> : 1,
    <item:everycomp:q/minestuck/space_aspect_ladder> : 1,
    <item:everycomp:q/minestuck/space_aspect_trapped_chest> : 125,
    <item:everycomp:q/minestuck/time_aspect_bookshelf> : 25,
    <item:everycomp:q/minestuck/time_aspect_chest> : 10,
    <item:everycomp:q/minestuck/time_aspect_hedge> : 1,
    <item:everycomp:q/minestuck/time_aspect_ladder> : 1,
    <item:everycomp:q/minestuck/time_aspect_trapped_chest> : 125,
    <item:everycomp:q/minestuck/vertical_blood_aspect_planks> : 1,
    <item:everycomp:q/minestuck/vertical_breath_aspect_planks> : 1,
    <item:everycomp:q/minestuck/vertical_dead_planks> : 1,
    <item:everycomp:q/minestuck/vertical_doom_aspect_planks> : 1,
    <item:everycomp:q/minestuck/vertical_end_planks> : 1,
    <item:everycomp:q/minestuck/vertical_frost_planks> : 1,
    <item:everycomp:q/minestuck/vertical_glowing_planks> : 1,
    <item:everycomp:q/minestuck/vertical_heart_aspect_planks> : 1,
    <item:everycomp:q/minestuck/vertical_hope_aspect_planks> : 1,
    <item:everycomp:q/minestuck/vertical_life_aspect_planks> : 1,
    <item:everycomp:q/minestuck/vertical_light_aspect_planks> : 1,
    <item:everycomp:q/minestuck/vertical_mind_aspect_planks> : 1,
    <item:everycomp:q/minestuck/vertical_rage_aspect_planks> : 1,
    <item:everycomp:q/minestuck/vertical_rainbow_planks> : 1,
    <item:everycomp:q/minestuck/vertical_space_aspect_planks> : 1,
    <item:everycomp:q/minestuck/vertical_time_aspect_planks> : 1,
    <item:everycomp:q/minestuck/vertical_void_aspect_planks> : 1,
    <item:everycomp:q/minestuck/void_aspect_bookshelf> : 25,
    <item:everycomp:q/minestuck/void_aspect_chest> : 10,
    <item:everycomp:q/minestuck/void_aspect_hedge> : 1,
    <item:everycomp:q/minestuck/void_aspect_ladder> : 1,
    <item:everycomp:q/minestuck/void_aspect_trapped_chest> : 125,
    <item:everycomp:q/the_vault/chromatic_bookshelf> : 25,
    <item:everycomp:q/the_vault/chromatic_chest> : 10,
    <item:everycomp:q/the_vault/chromatic_ladder> : 1,
    <item:everycomp:q/the_vault/chromatic_trapped_chest> : 125,
    <item:everycomp:q/the_vault/tenos_chest> : 10,
    <item:everycomp:q/the_vault/tenos_ladder> : 1,
    <item:everycomp:q/the_vault/tenos_trapped_chest> : 125,
    <item:everycomp:q/the_vault/velara_bookshelf> : 25,
    <item:everycomp:q/the_vault/velara_chest> : 10,
    <item:everycomp:q/the_vault/velara_hedge> : 1,
    <item:everycomp:q/the_vault/velara_ladder> : 1,
    <item:everycomp:q/the_vault/velara_trapped_chest> : 125,
    <item:everycomp:q/the_vault/vertical_chromatic_planks> : 1,
    <item:everycomp:q/the_vault/vertical_tenos_planks> : 1,
    <item:everycomp:q/the_vault/vertical_velara_planks> : 1,
    <item:everycomp:q/tropicraft/mahogany_bookshelf> : 25,
    <item:everycomp:q/tropicraft/mahogany_chest> : 10,
    <item:everycomp:q/tropicraft/mahogany_hedge> : 1,
    <item:everycomp:q/tropicraft/mahogany_ladder> : 1,
    <item:everycomp:q/tropicraft/mahogany_post> : 1,
    <item:everycomp:q/tropicraft/mahogany_trapped_chest> : 125,
    <item:everycomp:q/tropicraft/palm_bookshelf> : 25,
    <item:everycomp:q/tropicraft/palm_chest> : 10,
    <item:everycomp:q/tropicraft/palm_hedge> : 1,
    <item:everycomp:q/tropicraft/palm_ladder> : 1,
    <item:everycomp:q/tropicraft/palm_post> : 1,
    <item:everycomp:q/tropicraft/palm_trapped_chest> : 125,
    <item:everycomp:q/tropicraft/vertical_mahogany_planks> : 1,
    <item:everycomp:q/tropicraft/vertical_palm_planks> : 1,
    <item:everycomp:q/twigs/bamboo_bookshelf> : 25,
    <item:everycomp:q/twigs/bamboo_chest> : 10,
    <item:everycomp:q/twigs/bamboo_hedge> : 1,
    <item:everycomp:q/twigs/bamboo_ladder> : 1,
    <item:everycomp:q/twigs/bamboo_trapped_chest> : 125,
    <item:everycomp:q/twigs/vertical_bamboo_planks> : 1,
    <item:everycomp:tw/architects_palette/twisted_table> : 5,
    <item:everycomp:tw/botania/livingwood_table> : 5,
    <item:everycomp:tw/createdieselgenerators/chip_wood_table> : 5,
    <item:everycomp:tw/ecologics/azalea_table> : 5,
    <item:everycomp:tw/ecologics/coconut_table> : 5,
    <item:everycomp:tw/ecologics/flowering_azalea_table> : 5,
    <item:everycomp:tw/ecologics/walnut_table> : 5,
    <item:everycomp:tw/hexcasting/akashic_table> : 5,
    <item:everycomp:tw/integrateddynamics/menril_table> : 5,
    <item:everycomp:tw/luphieclutteredmod/luphie_flowering_pink_table> : 5,
    <item:everycomp:tw/luphieclutteredmod/luphie_flowering_purple_table> : 5,
    <item:everycomp:tw/luphieclutteredmod/luphie_flowering_yellow_table> : 5,
    <item:everycomp:tw/luphieclutteredmod/luphie_glow_table> : 5,
    <item:everycomp:tw/luphieclutteredmod/luphie_green_table> : 5,
    <item:everycomp:tw/luphieclutteredmod/luphie_pink_table> : 5,
    <item:everycomp:tw/luphieclutteredmod/luphie_purple_table> : 5,
    <item:everycomp:tw/luphieclutteredmod/luphie_yellow_table> : 5,
    <item:everycomp:tw/minestuck/blood_aspect_table> : 5,
    <item:everycomp:tw/minestuck/breath_aspect_table> : 5,
    <item:everycomp:tw/minestuck/dead_table> : 5,
    <item:everycomp:tw/minestuck/doom_aspect_table> : 5,
    <item:everycomp:tw/minestuck/end_table> : 5,
    <item:everycomp:tw/minestuck/frost_table> : 5,
    <item:everycomp:tw/minestuck/glowing_table> : 5,
    <item:everycomp:tw/minestuck/heart_aspect_table> : 5,
    <item:everycomp:tw/minestuck/hope_aspect_table> : 5,
    <item:everycomp:tw/minestuck/life_aspect_table> : 5,
    <item:everycomp:tw/minestuck/light_aspect_table> : 5,
    <item:everycomp:tw/minestuck/mind_aspect_table> : 5,
    <item:everycomp:tw/minestuck/rage_aspect_table> : 5,
    <item:everycomp:tw/minestuck/rainbow_table> : 5,
    <item:everycomp:tw/minestuck/space_aspect_table> : 5,
    <item:everycomp:tw/minestuck/time_aspect_table> : 5,
    <item:everycomp:tw/minestuck/void_aspect_table> : 5,
    <item:everycomp:tw/quark/azalea_table> : 5,
    <item:everycomp:tw/quark/blossom_table> : 5,
    <item:everycomp:tw/the_vault/chromatic_table> : 5,
    <item:everycomp:tw/the_vault/tenos_table> : 5,
    <item:everycomp:tw/the_vault/velara_table> : 5,
    <item:everycomp:tw/tropicraft/mahogany_table> : 5,
    <item:everycomp:tw/tropicraft/palm_table> : 5
};

// For each item in the map, check if we're in release mode. If we are, anything below 26 EMC/FMC becomes unburnable for EMC
for item, value in priceTable {
    if (ReleaseMode.releaseMode == true){
        if (value < 26 ) {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), 0);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        } else {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        }
        if (value > 999 && value < 10001) {
            <tag:items:tfb2:fop_miniscule>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Miniscule");
            });
        }
        if (value > 10000 && value < 25001) {
            <tag:items:tfb2:fop_small>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Small");
            });
        }
        if (value > 25000 && value < 75001) {
            <tag:items:tfb2:fop_medium>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Medium");
            });
        }
        if (value > 75000) {
            <tag:items:tfb2:fop_large>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Large");
            });
        }
    } else {
        CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
        <tag:items:projectextended:blacklist_condenser>.add(item);
        <tag:items:projectextended:blacklist_learning>.add(item);
    }
        if (value > 10000 && value < 25001) {
            <tag:items:tfb2:fop_small>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Small");
            });
        }
        if (value > 25000 && value < 75001) {
            <tag:items:tfb2:fop_medium>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Medium");
            });
        }
        if (value > 75000) {
            <tag:items:tfb2:fop_large>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Large");
            });
        }
}