import crafttweaker.api.tag.MCTag;
import crafttweaker.api.item.IItemStack;
import crafttweaker.api.ingredient.IIngredient;
import crafttweaker.api.item.tooltip.ITooltipFunction;
import stdlib.List;
import mods.projecte.CustomEMC;
import mods.projecte.NSSResolver;

// Item  to EMC/FMC value map.
val priceTable as int[IItemStack] = {
    <item:everycomp:db/the_vault/burnt_palisade> : 1,
    <item:everycomp:mcp/the_vault/burnt_planks_path> : 1,
    <item:everycomp:mcw/the_vault/burnt_shutter> : 1,
    <item:everycomp:mcl/the_vault/burnt_tiki_torch> : 1,
    <item:everycomp:cfm/the_vault/burnt_upgraded_fence> : 1,
    <item:everycomp:mcl/the_vault/chromatic_tiki_torch> : 1,
    <item:everycomp:mcl/the_vault/driftwood_tiki_torch> : 1,
    <item:everycomp:mcl/the_vault/soul_overgrown_wooden_tiki_torch> : 1,
    <item:everycomp:mcl/the_vault/soul_driftwood_tiki_torch> : 1,
    <item:everycomp:db/auxiliaryblocks/gloomy_beam> : 1,
    <item:everycomp:mcl/the_vault/soul_chromatic_tiki_torch> : 1,
    <item:everycomp:mcl/the_vault/soul_burnt_tiki_torch> : 1,
    <item:everycomp:cfm/buildscape/snowy_spruce_hedge> : 1,
    <item:everycomp:cfm/buildscape/snowy_oak_hedge> : 1,
    <item:everycomp:cfm/buildscape/snowy_mangrove_hedge> : 1,
    <item:everycomp:c/the_vault/burnt_window_pane> : 1,
    <item:everycomp:mcl/the_vault/soul_velara_tiki_torch> : 1,
    <item:everycomp:c/buildscape/mangrove_window_pane> : 1,
    <item:everycomp:mcl/the_vault/overgrown_wooden_tiki_torch> : 1,
    <item:everycomp:cfm/buildscape/snowy_acacia_hedge> : 1,
    <item:everycomp:cfm/buildscape/snowy_azalea_hedge> : 1,
    <item:everycomp:cfm/buildscape/snowy_birch_hedge> : 1,
    <item:everycomp:cfm/buildscape/snowy_dark_oak_hedge> : 1,
    <item:everycomp:cfm/buildscape/snowy_flowering_azalea_hedge> : 1,
    <item:everycomp:cfm/buildscape/snowy_hedge> : 1,
    <item:everycomp:cfm/buildscape/snowy_jungle_hedge> : 1,
    <item:everycomp:db/auxiliaryblocks/gloomy_palisade> : 1,
    <item:everycomp:mcp/auxiliaryblocks/gloomy_planks_path> : 1,
    <item:everycomp:q/auxiliaryblocks/gloomy_post> : 1,
    <item:everycomp:cfm/auxiliaryblocks/gloomy_upgraded_fence> : 1,
    <item:everycomp:cfm/buildscape/mangrove_hedge> : 1,
    <item:everycomp:db/buildscape/mangrove_palisade> : 1,
    <item:everycomp:mcp/buildscape/mangrove_planks_path> : 1,
    <item:everycomp:q/buildscape/mangrove_post> : 1,
    <item:everycomp:cfm/buildscape/mangrove_upgraded_fence> : 1,
    <item:everycomp:mcl/the_vault/wooden_tiki_torch> : 1,
    <item:everycomp:mcl/the_vault/soul_tenos_tiki_torch> : 1,
    <item:everycomp:mcl/the_vault/soul_wooden_tiki_torch> : 1,
    <item:everycomp:cfm/ecologics/stripped_azalea_mail_box> : 1,
    <item:everycomp:cfm/quark/stripped_azalea_mail_box> : 1,
    <item:everycomp:cfm/quark/stripped_blossom_mail_box> : 1,
    <item:everycomp:q/buildscape/stripped_mangrove_post> : 1,
    <item:everycomp:cfm/the_vault/stripped_wooden_mail_box> : 1,
    <item:everycomp:mcl/the_vault/velara_tiki_torch> : 1,
    <item:everycomp:mcl/the_vault/tenos_tiki_torch> : 1,
    <item:everycomp:cfm/the_vault/driftwood_mail_box> : 3450,
    <item:everycomp:q/buildscape/mangrove_trapped_chest> : 125,
    <item:everycomp:q/auxiliaryblocks/gloomy_trapped_chest> : 125,
    <item:everycomp:q/the_vault/burnt_trapped_chest> : 125,
    <item:everycomp:q/buildscape/mangrove_bookshelf> : 25,
    <item:everycomp:cfm/the_vault/stripped_overgrown_wooden_mail_box> : 75,
    <item:everycomp:cfm/the_vault/overgrown_wooden_mail_box> : 100,
    <item:everycomp:cfm/the_vault/burnt_kitchen_sink_dark> : 450,
    <item:everycomp:cfm/the_vault/burnt_kitchen_sink_light> : 450,
    <item:everycomp:cfm/the_vault/stripped_burnt_kitchen_sink_light> : 450,
    <item:everycomp:cfm/the_vault/stripped_burnt_kitchen_sink_dark> : 450,
    <item:everycomp:cfm/buildscape/stripped_mangrove_kitchen_sink_dark> : 450,
    <item:everycomp:cfm/buildscape/stripped_mangrove_kitchen_sink_light> : 450,
    <item:everycomp:cfm/buildscape/mangrove_kitchen_sink_light> : 450,
    <item:everycomp:fd/the_vault/burnt_cabinet> : 10,
    <item:everycomp:q/the_vault/burnt_chest> : 10,
    <item:everycomp:mcf/the_vault/burnt_highley_gate> : 10,
    <item:everycomp:cfm/the_vault/burnt_mail_box> : 10,
    <item:everycomp:q/auxiliaryblocks/gloomy_chest> : 10,
    <item:everycomp:mcf/auxiliaryblocks/gloomy_highley_gate> : 10,
    <item:everycomp:cfm/auxiliaryblocks/gloomy_mail_box> : 10,
    <item:everycomp:q/buildscape/mangrove_chest> : 10,
    <item:everycomp:cfm/the_vault/stripped_burnt_desk_cabinet> : 10,
    <item:everycomp:cfm/the_vault/stripped_burnt_crate> : 10,
    <item:everycomp:cfm/the_vault/stripped_burnt_cabinet> : 10,
    <item:everycomp:cfm/the_vault/stripped_burnt_bedside_cabinet> : 10,
    <item:everycomp:mcf/buildscape/mangrove_highley_gate> : 10,
    <item:everycomp:cfm/buildscape/mangrove_mail_box> : 10,
    <item:everycomp:mcfur/buildscape/stripped_mangrove_bookshelf> : 10,
    <item:everycomp:mcfur/buildscape/stripped_mangrove_cupboard_counter> : 10,
    <item:everycomp:mcfur/buildscape/stripped_mangrove_drawer> : 10,
    <item:everycomp:mcfur/buildscape/stripped_mangrove_drawer_counter> : 10,
    <item:everycomp:mcfur/buildscape/stripped_mangrove_large_drawer> : 10,
    <item:everycomp:mcfur/buildscape/stripped_mangrove_modern_wardrobe> : 10,
    <item:everycomp:mcfur/buildscape/stripped_mangrove_wardrobe> : 10,
    <item:everycomp:q/auxiliaryblocks/gloomy_bookshelf> : 25,
    <item:everycomp:q/the_vault/burnt_bookshelf> : 25,
    <item:everycomp:cfm/culturaldelights/avocado_hedge> : 1,
    <item:everycomp:mct/the_vault/burnt_barrel_trapdoor> : 1,
    <item:everycomp:ap/the_vault/burnt_boards> : 1,
    <item:everycomp:mcb/the_vault/burnt_log_bridge_middle> : 1,
    <item:everycomp:mcb/the_vault/burnt_bridge_pier> : 1,
    <item:everycomp:mcb/the_vault/burnt_log_bridge_stair> : 1,
    <item:everycomp:cfm/the_vault/burnt_kitchen_counter> : 1,
    <item:everycomp:q/the_vault/burnt_ladder> : 1,
    <item:everycomp:mcrf/auxiliaryblocks/gloomy_planks_steep_roof> : 1,
    <item:everycomp:mcrf/auxiliaryblocks/gloomy_planks_roof> : 1,
    <item:everycomp:mcrf/auxiliaryblocks/gloomy_planks_lower_roof> : 1,
    <item:everycomp:mcrf/auxiliaryblocks/gloomy_planks_attic_roof> : 1,
    <item:everycomp:mcw/auxiliaryblocks/gloomy_plank_parapet> : 1,
    <item:everycomp:mcw/auxiliaryblocks/gloomy_log_parapet> : 1,
    <item:everycomp:mcw/auxiliaryblocks/gloomy_louvered_shutter> : 1,
    <item:everycomp:q/auxiliaryblocks/gloomy_ladder> : 1,
    <item:everycomp:cfm/auxiliaryblocks/gloomy_kitchen_counter> : 1,
    <item:everycomp:mcrf/the_vault/burnt_planks_upper_steep_roof> : 1,
    <item:everycomp:mcb/the_vault/burnt_rail_bridge> : 1,
    <item:everycomp:ap/the_vault/burnt_railing> : 1,
    <item:everycomp:db/the_vault/burnt_seat> : 1,
    <item:everycomp:db/the_vault/burnt_support> : 1,
    <item:everycomp:mct/auxiliaryblocks/gloomy_barrel_trapdoor> : 1,
    <item:everycomp:mcb/auxiliaryblocks/gloomy_log_bridge_middle> : 1,
    <item:everycomp:mcb/auxiliaryblocks/gloomy_bridge_pier> : 1,
    <item:everycomp:mcb/auxiliaryblocks/gloomy_log_bridge_stair> : 1,
    <item:everycomp:mcrf/the_vault/burnt_planks_upper_lower_roof> : 1,
    <item:everycomp:mcrf/the_vault/burnt_planks_top_roof> : 1,
    <item:everycomp:mcrf/the_vault/burnt_planks_steep_roof> : 1,
    <item:everycomp:mcrf/the_vault/burnt_planks_roof> : 1,
    <item:everycomp:mcrf/the_vault/burnt_planks_lower_roof> : 1,
    <item:everycomp:mcrf/the_vault/burnt_planks_attic_roof> : 1,
    <item:everycomp:mcw/the_vault/burnt_plank_parapet> : 1,
    <item:everycomp:mcw/the_vault/burnt_log_parapet> : 1,
    <item:everycomp:mcw/the_vault/burnt_louvered_shutter> : 1,
    <item:everycomp:mcw/the_vault/burnt_blinds> : 2,
    <item:everycomp:mcd/the_vault/burnt_classic_door> : 2,
    <item:everycomp:mct/the_vault/burnt_classic_trapdoor> : 2,
    <item:everycomp:mcfur/the_vault/burnt_coffee_table> : 2,
    <item:everycomp:mcd/the_vault/burnt_cottage_door> : 2,
    <item:everycomp:mct/the_vault/burnt_cottage_trapdoor> : 2,
    <item:everycomp:mcfur/the_vault/burnt_counter> : 2,
    <item:everycomp:mcd/the_vault/burnt_four_panel_door> : 2,
    <item:everycomp:mcd/auxiliaryblocks/gloomy_mystic_door> : 2,
    <item:everycomp:mcf/auxiliaryblocks/gloomy_horse_fence> : 2,
    <item:everycomp:mct/auxiliaryblocks/gloomy_glass_trapdoor> : 2,
    <item:everycomp:mct/auxiliaryblocks/gloomy_four_panel_trapdoor> : 2,
    <item:everycomp:mcd/auxiliaryblocks/gloomy_four_panel_door> : 2,
    <item:everycomp:mct/auxiliaryblocks/gloomy_cottage_trapdoor> : 2,
    <item:everycomp:mcd/auxiliaryblocks/gloomy_cottage_door> : 2,
    <item:everycomp:mcfur/auxiliaryblocks/gloomy_coffee_table> : 2,
    <item:everycomp:mct/auxiliaryblocks/gloomy_classic_trapdoor> : 2,
    <item:everycomp:mcd/the_vault/burnt_tropical_door> : 2,
    <item:everycomp:mct/the_vault/burnt_tropical_trapdoor> : 2,
    <item:everycomp:mct/the_vault/burnt_blossom_trapdoor> : 2,
    <item:everycomp:mcd/auxiliaryblocks/gloomy_barn_door> : 2,
    <item:everycomp:mct/auxiliaryblocks/gloomy_barred_trapdoor> : 2,
    <item:everycomp:mcd/auxiliaryblocks/gloomy_beach_door> : 2,
    <item:everycomp:mct/auxiliaryblocks/gloomy_beach_trapdoor> : 2,
    <item:everycomp:mcw/auxiliaryblocks/gloomy_blinds> : 2,
    <item:everycomp:mcd/auxiliaryblocks/gloomy_classic_door> : 2,
    <item:everycomp:mcf/the_vault/burnt_stockade_fence> : 2,
    <item:everycomp:mcf/the_vault/burnt_picket_fence> : 2,
    <item:everycomp:mct/the_vault/burnt_paper_trapdoor> : 2,
    <item:everycomp:mcd/the_vault/burnt_nether_door> : 2,
    <item:everycomp:mct/the_vault/burnt_mystic_trapdoor> : 2,
    <item:everycomp:mcd/the_vault/burnt_mystic_door> : 2,
    <item:everycomp:mcf/the_vault/burnt_horse_fence> : 2,
    <item:everycomp:mct/the_vault/burnt_glass_trapdoor> : 2,
    <item:everycomp:mct/the_vault/burnt_four_panel_trapdoor> : 2,
    <item:everycomp:mct/auxiliaryblocks/gloomy_mystic_trapdoor> : 2,
    <item:everycomp:mcd/auxiliaryblocks/gloomy_nether_door> : 2,
    <item:everycomp:mct/auxiliaryblocks/gloomy_paper_trapdoor> : 2,
    <item:everycomp:mcf/auxiliaryblocks/gloomy_picket_fence> : 2,
    <item:everycomp:mcf/auxiliaryblocks/gloomy_stockade_fence> : 2,
    <item:everycomp:mcd/auxiliaryblocks/gloomy_tropical_door> : 2,
    <item:everycomp:mct/auxiliaryblocks/gloomy_tropical_trapdoor> : 2,
    <item:everycomp:cfm/the_vault/stripped_burnt_chair> : 2,
    <item:everycomp:cfm/auxiliaryblocks/gloomy_upgraded_gate> : 2,
    <item:everycomp:mct/buildscape/mangrove_blossom_trapdoor> : 2,
    <item:everycomp:cfm/buildscape/mangrove_upgraded_gate> : 2,
    <item:everycomp:mct/buildscape/mangrove_tropical_trapdoor> : 2,
    <item:everycomp:mcd/buildscape/mangrove_tropical_door> : 2,
    <item:everycomp:mcf/buildscape/mangrove_stockade_fence> : 2,
    <item:everycomp:mcf/buildscape/mangrove_picket_fence> : 2,
    <item:everycomp:mct/buildscape/mangrove_paper_trapdoor> : 2,
    <item:everycomp:mcd/buildscape/mangrove_nether_door> : 2,
    <item:everycomp:mcd/buildscape/mangrove_cottage_door> : 2,
    <item:everycomp:mct/buildscape/mangrove_cottage_trapdoor> : 2,
    <item:everycomp:mcfur/buildscape/mangrove_counter> : 2,
    <item:everycomp:mcd/buildscape/mangrove_four_panel_door> : 2,
    <item:everycomp:mct/buildscape/mangrove_four_panel_trapdoor> : 2,
    <item:everycomp:mct/buildscape/mangrove_glass_trapdoor> : 2,
    <item:everycomp:mcf/buildscape/mangrove_horse_fence> : 2,
    <item:everycomp:mcd/buildscape/mangrove_mystic_door> : 2,
    <item:everycomp:mct/buildscape/mangrove_mystic_trapdoor> : 2,
    <item:everycomp:mcfur/buildscape/mangrove_coffee_table> : 2,
    <item:everycomp:mct/buildscape/mangrove_classic_trapdoor> : 2,
    <item:everycomp:mcd/buildscape/mangrove_classic_door> : 2,
    <item:everycomp:mcw/buildscape/mangrove_blinds> : 2,
    <item:everycomp:mct/buildscape/mangrove_beach_trapdoor> : 2,
    <item:everycomp:mcd/buildscape/mangrove_beach_door> : 2,
    <item:everycomp:mct/buildscape/mangrove_barred_trapdoor> : 2,
    <item:everycomp:mcd/buildscape/mangrove_barn_door> : 2,
    <item:everycomp:mct/auxiliaryblocks/gloomy_blossom_trapdoor> : 2,
    <item:everycomp:mcfur/buildscape/stripped_mangrove_table> : 2,
    <item:everycomp:mcfur/buildscape/stripped_mangrove_stool_chair> : 2,
    <item:everycomp:mcfur/buildscape/stripped_mangrove_modern_desk> : 2,
    <item:everycomp:mcfur/the_vault/stripped_burnt_counter> : 2,
    <item:everycomp:mcfur/the_vault/stripped_burnt_coffee_table> : 2,
    <item:everycomp:mct/auxiliaryblocks/gloomy_ranch_trapdoor> : 5,
    <item:everycomp:mcfur/auxiliaryblocks/gloomy_end_table> : 5,
    <item:everycomp:mcfur/the_vault/stripped_burnt_end_table> : 5,
    <item:everycomp:cfm/buildscape/stripped_mangrove_desk_cabinet> : 5,
    <item:everycomp:mcfur/the_vault/burnt_chair> : 5,
    <item:everycomp:mcfur/the_vault/burnt_glass_table> : 5,
    <item:everycomp:mct/the_vault/burnt_bamboo_trapdoor> : 5,
    <item:everycomp:mcf/the_vault/burnt_pyramid_gate> : 5,
    <item:everycomp:tw/the_vault/burnt_table> : 5,
    <item:everycomp:mcfur/auxiliaryblocks/gloomy_glass_table> : 5,
    <item:everycomp:mct/auxiliaryblocks/gloomy_bamboo_trapdoor> : 5,
    <item:everycomp:mcf/auxiliaryblocks/gloomy_pyramid_gate> : 5,
    <item:everycomp:mcfur/the_vault/stripped_burnt_glass_table> : 5,
    <item:everycomp:cfm/the_vault/stripped_burnt_desk> : 5,
    <item:everycomp:mcfur/the_vault/stripped_burnt_chair> : 5,
    <item:everycomp:tw/buildscape/mangrove_table> : 5,
    <item:everycomp:mcf/buildscape/mangrove_pyramid_gate> : 5,
    <item:everycomp:mct/buildscape/mangrove_bamboo_trapdoor> : 5,
    <item:everycomp:mcfur/buildscape/mangrove_glass_table> : 5,
    <item:everycomp:mcfur/buildscape/mangrove_chair> : 5,
    <item:everycomp:tw/auxiliaryblocks/gloomy_table> : 5,
    <item:everycomp:cfm/ecologics/azalea_mail_box> : 5,
    <item:everycomp:cfm/quark/azalea_mail_box> : 5,
    <item:everycomp:cfm/quark/blossom_mail_box> : 5,
    <item:everycomp:mct/the_vault/burnt_barn_trapdoor> : 5,
    <item:everycomp:mcfur/the_vault/burnt_desk> : 5,
    <item:everycomp:cfm/the_vault/burnt_kitchen_drawer> : 5,
    <item:everycomp:mcfur/the_vault/burnt_modern_desk> : 5,
    <item:everycomp:mcfur/buildscape/stripped_mangrove_modern_chair> : 5,
    <item:everycomp:cfm/buildscape/stripped_mangrove_kitchen_drawer> : 5,
    <item:everycomp:mcfur/buildscape/stripped_mangrove_end_table> : 5,
    <item:everycomp:cfm/buildscape/stripped_mangrove_blinds> : 5,
    <item:everycomp:mcfur/the_vault/stripped_burnt_table> : 5,
    <item:everycomp:cfm/the_vault/stripped_burnt_park_bench> : 5,
    <item:everycomp:mcfur/the_vault/stripped_burnt_modern_desk> : 5,
    <item:everycomp:mcfur/the_vault/stripped_burnt_desk> : 5,
    <item:everycomp:mcfur/auxiliaryblocks/gloomy_table> : 5,
    <item:everycomp:mct/buildscape/mangrove_barn_trapdoor> : 5,
    <item:everycomp:mcfur/buildscape/mangrove_desk> : 5,
    <item:everycomp:cfm/buildscape/mangrove_kitchen_drawer> : 5,
    <item:everycomp:cfm/buildscape/mangrove_kitchen_sink_dark> : 5,
    <item:everycomp:mcfur/buildscape/mangrove_modern_desk> : 5,
    <item:everycomp:mcd/buildscape/mangrove_paper_door> : 5,
    <item:everycomp:mct/buildscape/mangrove_swamp_trapdoor> : 5,
    <item:everycomp:mcfur/buildscape/mangrove_table> : 5,
    <item:everycomp:mct/auxiliaryblocks/gloomy_swamp_trapdoor> : 5,
    <item:everycomp:mcd/auxiliaryblocks/gloomy_paper_door> : 5,
    <item:everycomp:mcfur/auxiliaryblocks/gloomy_modern_desk> : 5,
    <item:everycomp:cfm/auxiliaryblocks/gloomy_kitchen_drawer> : 5,
    <item:everycomp:mcfur/auxiliaryblocks/gloomy_desk> : 5,
    <item:everycomp:mct/auxiliaryblocks/gloomy_barn_trapdoor> : 5,
    <item:everycomp:mcfur/the_vault/burnt_table> : 5,
    <item:everycomp:mct/the_vault/burnt_swamp_trapdoor> : 5,
    <item:everycomp:mcd/the_vault/burnt_paper_door> : 5,
    <item:everycomp:mct/the_vault/burnt_bark_trapdoor> : 5,
    <item:everycomp:cfm/the_vault/burnt_bedside_cabinet> : 5,
    <item:everycomp:cfm/the_vault/burnt_cabinet> : 5,
    <item:everycomp:mcfur/the_vault/burnt_covered_desk> : 5,
    <item:everycomp:cfm/the_vault/burnt_desk> : 5,
    <item:everycomp:cfm/the_vault/burnt_desk_cabinet> : 5,
    <item:everycomp:mcfur/the_vault/burnt_modern_chair> : 5,
    <item:everycomp:mcfur/the_vault/burnt_stool_chair> : 5,
    <item:everycomp:mcfur/buildscape/stripped_mangrove_striped_chair> : 5,
    <item:everycomp:mcfur/buildscape/stripped_mangrove_glass_table> : 5,
    <item:everycomp:cfm/buildscape/stripped_mangrove_desk> : 5,
    <item:everycomp:mcfur/buildscape/stripped_mangrove_chair> : 5,
    <item:everycomp:cfm/buildscape/stripped_mangrove_cabinet> : 5,
    <item:everycomp:cfm/buildscape/mangrove_cabinet> : 5,
    <item:everycomp:mcfur/buildscape/mangrove_covered_desk> : 5,
    <item:everycomp:cfm/buildscape/mangrove_desk> : 5,
    <item:everycomp:cfm/buildscape/mangrove_desk_cabinet> : 5,
    <item:everycomp:mcfur/buildscape/mangrove_modern_chair> : 5,
    <item:everycomp:mcfur/buildscape/mangrove_stool_chair> : 5,
    <item:everycomp:mcfur/the_vault/stripped_burnt_covered_desk> : 5,
    <item:everycomp:mcfur/the_vault/stripped_burnt_modern_chair> : 5,
    <item:everycomp:mcfur/the_vault/stripped_burnt_stool_chair> : 5,
    <item:everycomp:cfm/buildscape/mangrove_bedside_cabinet> : 5,
    <item:everycomp:mct/buildscape/mangrove_bark_trapdoor> : 5,
    <item:everycomp:mcw/auxiliaryblocks/gloomy_shutter> : 5,
    <item:everycomp:cfm/auxiliaryblocks/gloomy_desk_cabinet> : 5,
    <item:everycomp:cfm/auxiliaryblocks/gloomy_desk> : 5,
    <item:everycomp:mcfur/auxiliaryblocks/gloomy_covered_desk> : 5,
    <item:everycomp:cfm/auxiliaryblocks/gloomy_cabinet> : 5,
    <item:everycomp:cfm/auxiliaryblocks/gloomy_bedside_cabinet> : 5,
    <item:everycomp:mct/auxiliaryblocks/gloomy_bark_trapdoor> : 5,
    <item:everycomp:cfm/the_vault/burnt_blinds> : 5,
    <item:everycomp:cfm/the_vault/burnt_crate> : 5,
    <item:everycomp:mcfur/the_vault/burnt_end_table> : 5,
    <item:everycomp:mct/the_vault/burnt_ranch_trapdoor> : 5,
    <item:everycomp:mcfur/the_vault/burnt_striped_chair> : 5,
    <item:everycomp:cfm/auxiliaryblocks/gloomy_blinds> : 5,
    <item:everycomp:cfm/auxiliaryblocks/gloomy_crate> : 5,
    <item:everycomp:cfm/the_vault/stripped_burnt_blinds> : 5,
    <item:everycomp:cfm/the_vault/stripped_burnt_kitchen_drawer> : 5,
    <item:everycomp:mcfur/the_vault/stripped_burnt_striped_chair> : 5,
    <item:everycomp:cfm/buildscape/stripped_mangrove_bedside_cabinet> : 5,
    <item:everycomp:cfm/buildscape/stripped_mangrove_crate> : 5,
    <item:everycomp:mcfur/buildscape/mangrove_striped_chair> : 5,
    <item:everycomp:mct/buildscape/mangrove_ranch_trapdoor> : 5,
    <item:everycomp:mcfur/buildscape/mangrove_end_table> : 5,
    <item:everycomp:cfm/buildscape/mangrove_crate> : 5,
    <item:everycomp:cfm/buildscape/mangrove_blinds> : 5,
    <item:everycomp:mcd/the_vault/burnt_stable_door> : 50,
    <item:everycomp:mcd/the_vault/burnt_stable_head_door> : 50,
    <item:everycomp:mcd/auxiliaryblocks/gloomy_stable_door> : 50,
    <item:everycomp:mcd/auxiliaryblocks/gloomy_stable_head_door> : 50,
    <item:everycomp:mcd/buildscape/mangrove_stable_door> : 50,
    <item:everycomp:mcd/buildscape/mangrove_stable_head_door> : 50,
    <item:everycomp:mcfur/the_vault/burnt_bookshelf> : 10,
    <item:everycomp:mcfur/the_vault/burnt_cupboard_counter> : 10,
    <item:everycomp:mcfur/the_vault/burnt_double_drawer> : 10,
    <item:everycomp:mcfur/the_vault/burnt_double_drawer_counter> : 10,
    <item:everycomp:mcfur/the_vault/burnt_double_wardrobe> : 10,
    <item:everycomp:mcfur/the_vault/burnt_drawer> : 10,
    <item:everycomp:mcfur/the_vault/burnt_drawer_counter> : 10,
    <item:everycomp:mcfur/the_vault/burnt_large_drawer> : 10,
    <item:everycomp:mcfur/the_vault/stripped_burnt_wardrobe> : 10,
    <item:everycomp:mcfur/the_vault/stripped_burnt_modern_wardrobe> : 10,
    <item:everycomp:cfm/the_vault/stripped_burnt_mail_box> : 10,
    <item:everycomp:mcfur/the_vault/stripped_burnt_large_drawer> : 10,
    <item:everycomp:mcfur/the_vault/stripped_burnt_drawer_counter> : 10,
    <item:everycomp:mcfur/the_vault/stripped_burnt_drawer> : 10,
    <item:everycomp:mcfur/the_vault/stripped_burnt_double_wardrobe> : 10,
    <item:everycomp:mcfur/the_vault/stripped_burnt_double_drawer_counter> : 10,
    <item:everycomp:mcfur/the_vault/stripped_burnt_double_drawer> : 10,
    <item:everycomp:mcfur/buildscape/mangrove_drawer> : 10,
    <item:everycomp:mcfur/buildscape/mangrove_drawer_counter> : 10,
    <item:everycomp:mcfur/buildscape/mangrove_large_drawer> : 10,
    <item:everycomp:mcfur/buildscape/mangrove_modern_wardrobe> : 10,
    <item:everycomp:mcfur/buildscape/mangrove_wardrobe> : 10,
    <item:everycomp:mcl/auxiliaryblocks/soul_gloomy_tiki_torch> : 10,
    <item:everycomp:mcl/buildscape/soul_mangrove_tiki_torch> : 10,
    <item:everycomp:mcfur/the_vault/stripped_burnt_bookshelf> : 10,
    <item:everycomp:mcfur/the_vault/stripped_burnt_cupboard_counter> : 10,
    <item:everycomp:mcfur/buildscape/mangrove_double_wardrobe> : 10,
    <item:everycomp:mcfur/buildscape/mangrove_double_drawer_counter> : 10,
    <item:everycomp:mcfur/buildscape/mangrove_double_drawer> : 10,
    <item:everycomp:mcfur/buildscape/mangrove_cupboard_counter> : 10,
    <item:everycomp:fd/buildscape/mangrove_cabinet> : 10,
    <item:everycomp:mcfur/buildscape/mangrove_bookshelf> : 10,
    <item:everycomp:fd/auxiliaryblocks/gloomy_cabinet> : 10,
    <item:everycomp:mcfur/the_vault/burnt_wardrobe> : 10,
    <item:everycomp:mcfur/the_vault/burnt_modern_wardrobe> : 10,
    <item:everycomp:cfm/buildscape/stripped_mangrove_mail_box> : 10,
    <item:everycomp:mcfur/buildscape/stripped_mangrove_lower_bookshelf_drawer> : 10,
    <item:everycomp:mcfur/buildscape/stripped_mangrove_double_wardrobe> : 10,
    <item:everycomp:mcfur/buildscape/stripped_mangrove_double_drawer_counter> : 10,
    <item:everycomp:mcfur/buildscape/stripped_mangrove_double_drawer> : 10,
    <item:everycomp:mcfur/buildscape/stripped_mangrove_bookshelf_drawer> : 10,
    <item:everycomp:mcfur/buildscape/stripped_mangrove_bookshelf_cupboard> : 10,
    <item:everycomp:mcrf/auxiliaryblocks/gloomy_planks_top_roof> : 1,
    <item:everycomp:mcrf/auxiliaryblocks/gloomy_planks_upper_lower_roof> : 1,
    <item:everycomp:mcrf/auxiliaryblocks/gloomy_planks_upper_steep_roof> : 1,
    <item:everycomp:mcb/auxiliaryblocks/gloomy_rail_bridge> : 1,
    <item:everycomp:db/auxiliaryblocks/gloomy_seat> : 1,
    <item:everycomp:db/auxiliaryblocks/gloomy_support> : 1,
    <item:everycomp:mct/buildscape/mangrove_barrel_trapdoor> : 1,
    <item:everycomp:db/buildscape/mangrove_beam> : 1,
    <item:everycomp:cfm/buildscape/stripped_mangrove_kitchen_counter> : 1,
    <item:everycomp:cfm/buildscape/stripped_mangrove_coffee_table> : 1,
    <item:everycomp:mcb/buildscape/mangrove_rope_bridge_stair> : 1,
    <item:everycomp:mcb/buildscape/rope_mangrove_bridge> : 1,
    <item:everycomp:mcb/auxiliaryblocks/gloomy_rope_bridge_stair> : 1,
    <item:everycomp:mcb/auxiliaryblocks/rope_gloomy_bridge> : 1,
    <item:everycomp:mcb/the_vault/burnt_rope_bridge_stair> : 1,
    <item:everycomp:mcb/the_vault/rope_burnt_bridge> : 1,
    <item:everycomp:db/buildscape/mangrove_support> : 1,
    <item:everycomp:mcrf/buildscape/mangrove_planks_attic_roof> : 1,
    <item:everycomp:mcrf/buildscape/mangrove_planks_lower_roof> : 1,
    <item:everycomp:mcrf/buildscape/mangrove_planks_roof> : 1,
    <item:everycomp:mcrf/buildscape/mangrove_planks_steep_roof> : 1,
    <item:everycomp:mcrf/buildscape/mangrove_planks_top_roof> : 1,
    <item:everycomp:mcrf/buildscape/mangrove_planks_upper_lower_roof> : 1,
    <item:everycomp:mcrf/buildscape/mangrove_planks_upper_steep_roof> : 1,
    <item:everycomp:mcb/buildscape/mangrove_rail_bridge> : 1,
    <item:everycomp:db/buildscape/mangrove_seat> : 1,
    <item:everycomp:mcw/buildscape/mangrove_plank_parapet> : 1,
    <item:everycomp:mcw/buildscape/mangrove_log_parapet> : 1,
    <item:everycomp:mcw/buildscape/mangrove_louvered_shutter> : 1,
    <item:everycomp:q/buildscape/mangrove_hedge> : 1,
    <item:everycomp:q/buildscape/mangrove_ladder> : 1,
    <item:everycomp:cfm/buildscape/mangrove_kitchen_counter> : 1,
    <item:everycomp:mcb/buildscape/mangrove_log_bridge_stair> : 1,
    <item:everycomp:mcb/buildscape/mangrove_bridge_pier> : 1,
    <item:everycomp:mcb/buildscape/mangrove_log_bridge_middle> : 1,
    <item:everycomp:cfm/buildscape/stripped_mangrove_table> : 1,
    <item:everycomp:q/the_vault/vertical_burnt_planks> : 1,
    <item:everycomp:q/auxiliaryblocks/vertical_gloomy_planks> : 1,
    <item:everycomp:q/buildscape/vertical_mangrove_planks> : 1,
    <item:everycomp:mcd/the_vault/driftwood_japanese2_door> : 100,
    <item:everycomp:cfm/the_vault/stripped_driftwood_mail_box> : 2600,
    <item:everycomp:cfm/auxiliaryblocks/gloomy_kitchen_sink_dark> : 450,
    <item:everycomp:cfm/auxiliaryblocks/gloomy_kitchen_sink_light> : 450,
    <item:everycomp:cfm/auxiliaryblocks/stripped_gloomy_kitchen_sink_dark> : 450,
    <item:everycomp:mcfur/the_vault/burnt_lower_triple_drawer> : 25,
    <item:everycomp:mcfur/the_vault/burnt_triple_drawer> : 25,
    <item:everycomp:mcf/the_vault/burnt_wired_fence> : 25,
    <item:everycomp:mcf/auxiliaryblocks/gloomy_wired_fence> : 25,
    <item:everycomp:mcfur/buildscape/mangrove_lower_triple_drawer> : 25,
    <item:everycomp:mcfur/buildscape/mangrove_triple_drawer> : 25,
    <item:everycomp:mcf/buildscape/mangrove_wired_fence> : 25,
    <item:everycomp:mcfur/the_vault/stripped_burnt_lower_triple_drawer> : 25,
    <item:everycomp:mcfur/the_vault/stripped_burnt_triple_drawer> : 25,
    <item:everycomp:mcfur/buildscape/stripped_mangrove_lower_triple_drawer> : 25,
    <item:everycomp:mcfur/buildscape/stripped_mangrove_triple_drawer> : 25,
    <item:everycomp:cfm/the_vault/wooden_mail_box> : 25,
    <item:everycomp:cfm/hexcasting/akashic_mail_box> : 10,
    <item:everycomp:cfm/minestuck/breath_aspect_mail_box> : 10,
    <item:everycomp:cfm/minestuck/blood_aspect_mail_box> : 10,
    <item:everycomp:cfm/twigs/bamboo_mail_box> : 10,
    <item:everycomp:cfm/createdieselgenerators/chip_wood_mail_box> : 10,
    <item:everycomp:cfm/the_vault/chromatic_mail_box> : 10,
    <item:everycomp:cfm/ecologics/coconut_mail_box> : 10,
    <item:everycomp:cfm/minestuck/dead_mail_box> : 10,
    <item:everycomp:mcfur/buildscape/mangrove_lower_bookshelf_drawer> : 10,
    <item:everycomp:mcfur/buildscape/mangrove_bookshelf_drawer> : 10,
    <item:everycomp:mcfur/buildscape/mangrove_bookshelf_cupboard> : 10,
    <item:everycomp:cfm/luphieclutteredmod/luphie_flowering_yellow_mail_box> : 10,
    <item:everycomp:cfm/luphieclutteredmod/luphie_glow_mail_box> : 10,
    <item:everycomp:cfm/minestuck/light_aspect_mail_box> : 10,
    <item:everycomp:cfm/botania/livingwood_mail_box> : 10,
    <item:everycomp:cfm/luphieclutteredmod/luphie_flowering_pink_mail_box> : 10,
    <item:everycomp:cfm/luphieclutteredmod/luphie_flowering_purple_mail_box> : 10,
    <item:everycomp:cfm/tropicraft/mahogany_mail_box> : 10,
    <item:everycomp:cfm/luphieclutteredmod/luphie_yellow_mail_box> : 10,
    <item:everycomp:cfm/luphieclutteredmod/luphie_purple_mail_box> : 10,
    <item:everycomp:cfm/luphieclutteredmod/luphie_pink_mail_box> : 10,
    <item:everycomp:cfm/luphieclutteredmod/luphie_green_mail_box> : 10,
    <item:everycomp:cfm/minestuck/life_aspect_mail_box> : 10,
    <item:everycomp:cfm/minestuck/hope_aspect_mail_box> : 10,
    <item:everycomp:cfm/minestuck/heart_aspect_mail_box> : 10,
    <item:everycomp:cfm/minestuck/glowing_mail_box> : 10,
    <item:everycomp:cfm/minestuck/frost_mail_box> : 10,
    <item:everycomp:cfm/ecologics/flowering_azalea_mail_box> : 10,
    <item:everycomp:cfm/minestuck/end_mail_box> : 10,
    <item:everycomp:cfm/botania/dreamwood_mail_box> : 10,
    <item:everycomp:cfm/minestuck/doom_aspect_mail_box> : 10,
    <item:everycomp:cfm/minestuck/mind_aspect_mail_box> : 10,
    <item:everycomp:cfm/integrateddynamics/menril_mail_box> : 10,
    <item:everycomp:cfm/tropicraft/palm_mail_box> : 10,
    <item:everycomp:cfm/minestuck/rage_aspect_mail_box> : 10,
    <item:everycomp:cfm/minestuck/rainbow_mail_box> : 10,
    <item:everycomp:cfm/minestuck/space_aspect_mail_box> : 10,
    <item:everycomp:cfm/twigs/stripped_bamboo_mail_box> : 10,
    <item:everycomp:mcfur/the_vault/stripped_burnt_bookshelf_cupboard> : 10,
    <item:everycomp:mcfur/the_vault/stripped_burnt_bookshelf_drawer> : 10,
    <item:everycomp:mcfur/the_vault/stripped_burnt_lower_bookshelf_drawer> : 10,
    <item:everycomp:cfm/the_vault/stripped_chromatic_mail_box> : 10,
    <item:everycomp:cfm/ecologics/stripped_coconut_mail_box> : 10,
    <item:everycomp:cfm/botania/stripped_dreamwood_mail_box> : 10,
    <item:everycomp:cfm/ecologics/stripped_flowering_azalea_mail_box> : 10,
    <item:everycomp:cfm/botania/stripped_livingwood_mail_box> : 10,
    <item:everycomp:cfm/luphieclutteredmod/stripped_luphie_flowering_purple_mail_box> : 10,
    <item:everycomp:cfm/luphieclutteredmod/stripped_luphie_glow_mail_box> : 10,
    <item:everycomp:cfm/luphieclutteredmod/stripped_luphie_green_mail_box> : 10,
    <item:everycomp:cfm/luphieclutteredmod/stripped_luphie_pink_mail_box> : 10,
    <item:everycomp:cfm/luphieclutteredmod/stripped_luphie_purple_mail_box> : 10,
    <item:everycomp:cfm/luphieclutteredmod/stripped_luphie_yellow_mail_box> : 10,
    <item:everycomp:cfm/the_vault/stripped_tenos_mail_box> : 10,
    <item:everycomp:cfm/architects_palette/stripped_twisted_mail_box> : 10,
    <item:everycomp:cfm/the_vault/stripped_velara_mail_box> : 10,
    <item:everycomp:cfm/ecologics/stripped_walnut_mail_box> : 10,
    <item:everycomp:cfm/the_vault/tenos_mail_box> : 10,
    <item:everycomp:cfm/minestuck/time_aspect_mail_box> : 10,
    <item:everycomp:cfm/architects_palette/twisted_mail_box> : 10,
    <item:everycomp:cfm/the_vault/velara_mail_box> : 10,
    <item:everycomp:cfm/minestuck/void_aspect_mail_box> : 10,
    <item:everycomp:cfm/ecologics/walnut_mail_box> : 10,
    <item:everycomp:mcfur/the_vault/burnt_bookshelf_cupboard> : 10,
    <item:everycomp:mcfur/the_vault/burnt_bookshelf_drawer> : 10,
    <item:everycomp:mcfur/the_vault/burnt_lower_bookshelf_drawer> : 10,
    <item:everycomp:mcfur/auxiliaryblocks/stripped_gloomy_modern_chair> : 5,
    <item:everycomp:mcd/the_vault/overgrown_wooden_japanese2_door> : 5,
    <item:everycomp:mcfur/auxiliaryblocks/gloomy_striped_chair> : 5,
    <item:everycomp:mcfur/auxiliaryblocks/gloomy_stool_chair> : 5,
    <item:everycomp:mcfur/auxiliaryblocks/gloomy_modern_chair> : 5,
    <item:everycomp:mcfur/auxiliaryblocks/gloomy_chair> : 5,
    <item:everycomp:mcw/the_vault/stripped_burnt_log_window> : 2,
    <item:everycomp:mcw/auxiliaryblocks/stripped_gloomy_log_window> : 2,
    <item:everycomp:mcd/quark/azalea_japanese2_door> : 2,
    <item:everycomp:mcw/buildscape/stripped_mangrove_log_window> : 2,
    <item:everycomp:mcd/hexcasting/akashic_japanese2_door> : 2,
    <item:everycomp:mcd/quark/blossom_japanese2_door> : 2,
    <item:everycomp:mcd/minestuck/breath_aspect_japanese2_door> : 2,
    <item:everycomp:mcrf/the_vault/burnt_attic_roof> : 2,
    <item:everycomp:mcd/the_vault/burnt_bark_glass_door> : 2,
    <item:everycomp:c/the_vault/burnt_window> : 2,
    <item:everycomp:mcd/the_vault/burnt_western_door> : 2,
    <item:everycomp:mcrf/the_vault/burnt_upper_steep_roof> : 2,
    <item:everycomp:mcrf/the_vault/burnt_upper_lower_roof> : 2,
    <item:everycomp:cfm/the_vault/burnt_upgraded_gate> : 2,
    <item:everycomp:mcrf/the_vault/burnt_top_roof> : 2,
    <item:everycomp:cfm/the_vault/burnt_table> : 2,
    <item:everycomp:mcrf/the_vault/burnt_steep_roof> : 2,
    <item:everycomp:mcrf/the_vault/burnt_lower_roof> : 2,
    <item:everycomp:mcd/the_vault/burnt_glass_door> : 2,
    <item:everycomp:mcd/the_vault/burnt_modern_door> : 2,
    <item:everycomp:mcd/the_vault/burnt_japanese2_door> : 2,
    <item:everycomp:mcw/the_vault/burnt_pane_window> : 2,
    <item:everycomp:cfm/the_vault/burnt_park_bench> : 2,
    <item:everycomp:mcw/the_vault/burnt_plank_four_window> : 2,
    <item:everycomp:mcw/the_vault/burnt_plank_pane_window> : 2,
    <item:everycomp:mcrf/the_vault/burnt_roof> : 2,
    <item:everycomp:mcd/the_vault/burnt_japanese_door> : 2,
    <item:everycomp:mcw/the_vault/burnt_four_window> : 2,
    <item:everycomp:cfm/the_vault/burnt_chair> : 2,
    <item:everycomp:cfm/the_vault/burnt_coffee_table> : 2,
    <item:everycomp:db/the_vault/burnt_beam> : 2,
    <item:everycomp:mct/the_vault/burnt_beach_trapdoor> : 2,
    <item:everycomp:mcd/the_vault/burnt_beach_door> : 2,
    <item:everycomp:mct/the_vault/burnt_barred_trapdoor> : 2,
    <item:everycomp:mcd/the_vault/burnt_barn_glass_door> : 2,
    <item:everycomp:mcd/the_vault/burnt_barn_door> : 2,
    <item:everycomp:mcd/createdieselgenerators/chip_wood_japanese2_door> : 2,
    <item:everycomp:mcd/the_vault/chromatic_japanese2_door> : 2,
    <item:everycomp:mcd/ecologics/coconut_japanese2_door> : 2,
    <item:everycomp:mcd/botania/dreamwood_japanese2_door> : 2,
    <item:everycomp:mcd/ecologics/flowering_azalea_japanese2_door> : 2,
    <item:everycomp:mcrf/auxiliaryblocks/gloomy_attic_roof> : 2,
    <item:everycomp:mcd/auxiliaryblocks/gloomy_bark_glass_door> : 2,
    <item:everycomp:mcd/auxiliaryblocks/gloomy_barn_glass_door> : 2,
    <item:everycomp:mcd/minestuck/glowing_japanese2_door> : 2,
    <item:everycomp:c/auxiliaryblocks/gloomy_window_pane> : 2,
    <item:everycomp:c/auxiliaryblocks/gloomy_window> : 2,
    <item:everycomp:mcd/auxiliaryblocks/gloomy_western_door> : 2,
    <item:everycomp:mcrf/auxiliaryblocks/gloomy_upper_steep_roof> : 2,
    <item:everycomp:mcrf/auxiliaryblocks/gloomy_upper_lower_roof> : 2,
    <item:everycomp:mcrf/auxiliaryblocks/gloomy_top_roof> : 2,
    <item:everycomp:mcl/auxiliaryblocks/gloomy_tiki_torch> : 2,
    <item:everycomp:mcrf/auxiliaryblocks/gloomy_roof> : 2,
    <item:everycomp:mcw/auxiliaryblocks/gloomy_plank_pane_window> : 2,
    <item:everycomp:mcd/auxiliaryblocks/gloomy_japanese_door> : 2,
    <item:everycomp:mcd/auxiliaryblocks/gloomy_japanese2_door> : 2,
    <item:everycomp:mcrf/auxiliaryblocks/gloomy_steep_roof> : 2,
    <item:everycomp:mcd/minestuck/dead_japanese2_door> : 2,
    <item:everycomp:mcd/minestuck/doom_aspect_japanese2_door> : 2,
    <item:everycomp:mcd/minestuck/end_japanese2_door> : 2,
    <item:everycomp:mcd/minestuck/frost_japanese2_door> : 2,
    <item:everycomp:cfm/auxiliaryblocks/gloomy_table> : 2,
    <item:everycomp:cfm/auxiliaryblocks/gloomy_chair> : 2,
    <item:everycomp:cfm/auxiliaryblocks/gloomy_coffee_table> : 2,
    <item:everycomp:mcw/auxiliaryblocks/gloomy_four_window> : 2,
    <item:everycomp:mcd/auxiliaryblocks/gloomy_glass_door> : 2,
    <item:everycomp:mcrf/auxiliaryblocks/gloomy_lower_roof> : 2,
    <item:everycomp:mcd/auxiliaryblocks/gloomy_modern_door> : 2,
    <item:everycomp:mcw/auxiliaryblocks/gloomy_pane_window> : 2,
    <item:everycomp:cfm/auxiliaryblocks/gloomy_park_bench> : 2,
    <item:everycomp:mcw/auxiliaryblocks/gloomy_plank_four_window> : 2,
    <item:everycomp:mcd/minestuck/heart_aspect_japanese2_door> : 2,
    <item:everycomp:mcd/minestuck/hope_aspect_japanese2_door> : 2,
    <item:everycomp:mcd/minestuck/life_aspect_japanese2_door> : 2,
    <item:everycomp:mcd/minestuck/light_aspect_japanese2_door> : 2,
    <item:everycomp:mcd/botania/livingwood_japanese2_door> : 2,
    <item:everycomp:mcd/luphieclutteredmod/luphie_flowering_pink_japanese2_door> : 2,
    <item:everycomp:mcd/luphieclutteredmod/luphie_flowering_purple_japanese2_door> : 2,
    <item:everycomp:mcd/luphieclutteredmod/luphie_flowering_yellow_japanese2_door> : 2,
    <item:everycomp:mcd/luphieclutteredmod/luphie_glow_japanese2_door> : 2,
    <item:everycomp:mcd/luphieclutteredmod/luphie_green_japanese2_door> : 2,
    <item:everycomp:mcd/luphieclutteredmod/luphie_pink_japanese2_door> : 2,
    <item:everycomp:mcd/luphieclutteredmod/luphie_purple_japanese2_door> : 2,
    <item:everycomp:mcd/luphieclutteredmod/luphie_yellow_japanese2_door> : 2,
    <item:everycomp:mcd/tropicraft/mahogany_japanese2_door> : 2,
    <item:everycomp:mcrf/buildscape/mangrove_attic_roof> : 2,
    <item:everycomp:mcd/buildscape/mangrove_bark_glass_door> : 2,
    <item:everycomp:mcd/buildscape/mangrove_barn_glass_door> : 2,
    <item:everycomp:cfm/buildscape/mangrove_chair> : 2,
    <item:everycomp:cfm/buildscape/mangrove_coffee_table> : 2,
    <item:everycomp:mcrf/buildscape/mangrove_lower_roof> : 2,
    <item:everycomp:mcd/buildscape/mangrove_modern_door> : 2,
    <item:everycomp:mcw/buildscape/mangrove_pane_window> : 2,
    <item:everycomp:cfm/buildscape/mangrove_park_bench> : 2,
    <item:everycomp:mcw/buildscape/mangrove_plank_four_window> : 2,
    <item:everycomp:mcw/buildscape/mangrove_four_window> : 2,
    <item:everycomp:mcd/buildscape/mangrove_glass_door> : 2,
    <item:everycomp:mcw/buildscape/mangrove_plank_pane_window> : 2,
    <item:everycomp:mcrf/buildscape/mangrove_roof> : 2,
    <item:everycomp:mcd/buildscape/mangrove_japanese_door> : 2,
    <item:everycomp:mcd/buildscape/mangrove_japanese2_door> : 2,
    <item:everycomp:mcw/buildscape/mangrove_shutter> : 2,
    <item:everycomp:mcrf/buildscape/mangrove_steep_roof> : 2,
    <item:everycomp:cfm/buildscape/mangrove_table> : 2,
    <item:everycomp:mcl/buildscape/mangrove_tiki_torch> : 2,
    <item:everycomp:mcrf/buildscape/mangrove_top_roof> : 2,
    <item:everycomp:mcrf/buildscape/mangrove_upper_lower_roof> : 2,
    <item:everycomp:mcrf/buildscape/mangrove_upper_steep_roof> : 2,
    <item:everycomp:mcd/buildscape/mangrove_western_door> : 2,
    <item:everycomp:c/buildscape/mangrove_window> : 2,
    <item:everycomp:mcd/integrateddynamics/menril_japanese2_door> : 2,
    <item:everycomp:mcd/minestuck/mind_aspect_japanese2_door> : 2,
    <item:everycomp:mcd/tropicraft/palm_japanese2_door> : 2,
    <item:everycomp:mcd/minestuck/rage_aspect_japanese2_door> : 2,
    <item:everycomp:mcfur/buildscape/stripped_mangrove_counter> : 2,
    <item:everycomp:mcfur/buildscape/stripped_mangrove_coffee_table> : 2,
    <item:everycomp:cfm/buildscape/stripped_mangrove_chair> : 2,
    <item:everycomp:mcw/auxiliaryblocks/stripped_gloomy_pane_window> : 2,
    <item:everycomp:mcw/auxiliaryblocks/stripped_gloomy_log_four_window> : 2,
    <item:everycomp:cfm/the_vault/stripped_burnt_table> : 2,
    <item:everycomp:mcw/the_vault/stripped_burnt_pane_window> : 2,
    <item:everycomp:cfm/the_vault/stripped_burnt_kitchen_counter> : 2,
    <item:everycomp:mcw/the_vault/stripped_burnt_log_four_window> : 2,
    <item:everycomp:mcw/buildscape/stripped_mangrove_log_window2> : 2,
    <item:everycomp:mcw/the_vault/burnt_plank_window> : 2,
    <item:everycomp:mcw/the_vault/burnt_window> : 2,
    <item:everycomp:mcw/auxiliaryblocks/gloomy_plank_window> : 2,
    <item:everycomp:mcw/auxiliaryblocks/gloomy_window> : 2,
    <item:everycomp:mcw/buildscape/mangrove_plank_window> : 2,
    <item:everycomp:mcw/buildscape/mangrove_window> : 2,
    <item:everycomp:mcd/minestuck/space_aspect_japanese2_door> : 2,
    <item:everycomp:cfm/the_vault/stripped_burnt_coffee_table> : 2,
    <item:everycomp:mcw/auxiliaryblocks/stripped_gloomy_log_window2> : 2,
    <item:everycomp:mcw/the_vault/stripped_burnt_log_window2> : 2,
    <item:everycomp:mcw/buildscape/mangrove_plank_window2> : 2,
    <item:everycomp:mcw/buildscape/mangrove_window2> : 2,
    <item:everycomp:mcw/auxiliaryblocks/gloomy_plank_window2> : 2,
    <item:everycomp:mcw/auxiliaryblocks/gloomy_window2> : 2,
    <item:everycomp:mcw/the_vault/burnt_plank_window2> : 2,
    <item:everycomp:mcw/the_vault/burnt_window2> : 2,
    <item:everycomp:mcd/minestuck/rainbow_japanese2_door> : 2,
    <item:everycomp:mcfur/buildscape/stripped_mangrove_covered_desk> : 2,
    <item:everycomp:mcfur/buildscape/stripped_mangrove_desk> : 2,
    <item:everycomp:mcw/buildscape/stripped_mangrove_log_four_window> : 2,
    <item:everycomp:mcw/buildscape/stripped_mangrove_pane_window> : 2,
    <item:everycomp:cfm/buildscape/stripped_mangrove_park_bench> : 2,
    <item:everycomp:mcd/the_vault/tenos_japanese2_door> : 2,
    <item:everycomp:mcd/minestuck/time_aspect_japanese2_door> : 2,
    <item:everycomp:mcd/architects_palette/twisted_japanese2_door> : 2,
    <item:everycomp:mcd/the_vault/velara_japanese2_door> : 2,
    <item:everycomp:mcd/minestuck/void_aspect_japanese2_door> : 2,
    <item:everycomp:mcd/ecologics/walnut_japanese2_door> : 2,
    <item:everycomp:mcd/the_vault/wooden_japanese2_door> : 2
};

// For each item in the map, check if we're in release mode. If we are, anything below 26 EMC/FMC becomes unburnable for EMC
for item, value in priceTable {
    if (ReleaseMode.releaseMode == true){
        if (value < 26 ) {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), 0);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        } else {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        }
        if (value > 999 && value < 10001) {
            <tag:items:tfb2:fop_miniscule>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Miniscule");
            });
        }
        if (value > 10000 && value < 25001) {
            <tag:items:tfb2:fop_small>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Small");
            });
        }
        if (value > 25000 && value < 75001) {
            <tag:items:tfb2:fop_medium>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Medium");
            });
        }
        if (value > 75000) {
            <tag:items:tfb2:fop_large>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Large");
            });
        }
    } else {
        CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
        <tag:items:projectextended:blacklist_condenser>.add(item);
        <tag:items:projectextended:blacklist_learning>.add(item);
    }
        if (value > 10000 && value < 25001) {
            <tag:items:tfb2:fop_small>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Small");
            });
        }
        if (value > 25000 && value < 75001) {
            <tag:items:tfb2:fop_medium>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Medium");
            });
        }
        if (value > 75000) {
            <tag:items:tfb2:fop_large>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Large");
            });
        }
}