import crafttweaker.api.tag.MCTag;
import crafttweaker.api.item.IItemStack;
import crafttweaker.api.ingredient.IIngredient;
import crafttweaker.api.item.tooltip.ITooltipFunction;
import stdlib.List;
import mods.projecte.CustomEMC;
import mods.projecte.NSSResolver;

// This variable controls whether we are in the pack dev mode or release mode. In Pack Dev mode, all EMC/FMC values are enabled to help calculate EMC/FMC for other mods.
var release_mode = false;

// Item  to EMC/FMC value map.
val priceTable as int[IItemStack] = {
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_glow_bookshelf_cupboard> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_glow_bookshelf_drawer> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_glow_chair> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_glow_coffee_table> : 5,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_glow_counter> : 1,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_glow_covered_desk> : 2,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_glow_cupboard_counter> : 2,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_glow_desk> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_glow_double_drawer> : 2,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_glow_double_drawer_counter> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_glow_double_wardrobe> : 25,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_glow_drawer> : 25,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_glow_drawer_counter> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_glow_end_table> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_glow_glass_table> : 5,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_glow_large_drawer> : 5,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_glow_lower_bookshelf_drawer> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_glow_lower_triple_drawer> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_glow_modern_chair> : 25,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_glow_modern_desk> : 5,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_glow_modern_wardrobe> : 2,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_glow_stool_chair> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_glow_striped_chair> : 2,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_glow_table> : 5,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_glow_triple_drawer> : 2,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_glow_wardrobe> : 25,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_green_bookshelf> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_green_bookshelf_cupboard> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_green_bookshelf_drawer> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_green_chair> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_green_coffee_table> : 5,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_green_counter> : 1,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_green_covered_desk> : 2,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_green_cupboard_counter> : 2,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_green_desk> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_green_double_drawer> : 2,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_green_double_drawer_counter> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_green_double_wardrobe> : 25,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_green_drawer> : 25,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_green_drawer_counter> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_green_end_table> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_green_glass_table> : 5,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_green_large_drawer> : 5,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_green_lower_bookshelf_drawer> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_green_lower_triple_drawer> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_green_modern_chair> : 25,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_green_modern_desk> : 5,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_green_modern_wardrobe> : 2,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_green_stool_chair> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_green_striped_chair> : 2,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_green_table> : 5,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_green_triple_drawer> : 2,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_green_wardrobe> : 25,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_pink_bookshelf> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_pink_bookshelf_cupboard> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_pink_bookshelf_drawer> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_pink_chair> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_pink_coffee_table> : 5,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_pink_counter> : 1,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_pink_covered_desk> : 2,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_pink_cupboard_counter> : 2,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_pink_desk> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_pink_double_drawer> : 2,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_pink_double_drawer_counter> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_pink_double_wardrobe> : 25,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_pink_drawer> : 25,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_pink_drawer_counter> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_pink_end_table> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_pink_glass_table> : 5,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_pink_large_drawer> : 5,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_pink_lower_bookshelf_drawer> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_pink_lower_triple_drawer> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_pink_modern_chair> : 25,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_pink_modern_desk> : 5,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_pink_modern_wardrobe> : 2,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_pink_stool_chair> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_pink_striped_chair> : 2,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_pink_table> : 5,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_pink_triple_drawer> : 2,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_pink_wardrobe> : 25,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_purple_bookshelf> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_purple_bookshelf_cupboard> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_purple_bookshelf_drawer> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_purple_chair> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_purple_coffee_table> : 5,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_purple_counter> : 1,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_purple_covered_desk> : 2,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_purple_cupboard_counter> : 2,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_purple_desk> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_purple_double_drawer> : 2,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_purple_double_drawer_counter> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_purple_double_wardrobe> : 25,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_purple_drawer> : 25,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_purple_drawer_counter> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_purple_end_table> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_purple_glass_table> : 5,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_purple_large_drawer> : 5,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_purple_lower_bookshelf_drawer> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_purple_lower_triple_drawer> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_purple_modern_chair> : 25,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_purple_modern_desk> : 5,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_purple_modern_wardrobe> : 2,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_purple_stool_chair> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_purple_striped_chair> : 2,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_purple_table> : 5,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_purple_triple_drawer> : 2,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_purple_wardrobe> : 25,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_yellow_bookshelf> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_yellow_bookshelf_cupboard> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_yellow_bookshelf_drawer> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_yellow_chair> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_yellow_coffee_table> : 5,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_yellow_counter> : 1,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_yellow_covered_desk> : 2,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_yellow_cupboard_counter> : 2,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_yellow_desk> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_yellow_double_drawer> : 2,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_yellow_double_drawer_counter> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_yellow_double_wardrobe> : 25,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_yellow_drawer> : 25,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_yellow_drawer_counter> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_yellow_end_table> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_yellow_glass_table> : 5,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_yellow_large_drawer> : 5,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_yellow_lower_bookshelf_drawer> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_yellow_lower_triple_drawer> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_yellow_modern_chair> : 25,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_yellow_modern_desk> : 5,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_yellow_modern_wardrobe> : 2,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_yellow_stool_chair> : 10,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_yellow_striped_chair> : 2,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_yellow_table> : 5,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_yellow_triple_drawer> : 2,
    <item:everycomp:mcfur/luphieclutteredmod/stripped_luphie_yellow_wardrobe> : 25,
    <item:everycomp:mcfur/minestuck/blood_aspect_chair> : 10,
    <item:everycomp:mcfur/minestuck/blood_aspect_coffee_table> : 10,
    <item:everycomp:mcfur/minestuck/blood_aspect_covered_desk> : 10,
    <item:everycomp:mcfur/minestuck/blood_aspect_desk> : 10,
    <item:everycomp:mcfur/minestuck/blood_aspect_end_table> : 5,
    <item:everycomp:mcfur/minestuck/blood_aspect_glass_table> : 1,
    <item:everycomp:mcfur/minestuck/blood_aspect_modern_chair> : 2,
    <item:everycomp:mcfur/minestuck/blood_aspect_modern_desk> : 2,
    <item:everycomp:mcfur/minestuck/blood_aspect_stool_chair> : 10,
    <item:everycomp:mcfur/minestuck/blood_aspect_striped_chair> : 2,
    <item:everycomp:mcfur/minestuck/blood_aspect_table> : 10,
    <item:everycomp:mcfur/minestuck/breath_aspect_chair> : 25,
    <item:everycomp:mcfur/minestuck/breath_aspect_coffee_table> : 25,
    <item:everycomp:mcfur/minestuck/breath_aspect_covered_desk> : 10,
    <item:everycomp:mcfur/minestuck/breath_aspect_desk> : 10,
    <item:everycomp:mcfur/minestuck/breath_aspect_end_table> : 5,
    <item:everycomp:mcfur/minestuck/breath_aspect_glass_table> : 5,
    <item:everycomp:mcfur/minestuck/breath_aspect_modern_chair> : 10,
    <item:everycomp:mcfur/minestuck/breath_aspect_modern_desk> : 10,
    <item:everycomp:mcfur/minestuck/breath_aspect_stool_chair> : 25,
    <item:everycomp:mcfur/minestuck/breath_aspect_striped_chair> : 5,
    <item:everycomp:mcfur/minestuck/breath_aspect_table> : 2,
    <item:everycomp:mcfur/minestuck/dead_chair> : 10,
    <item:everycomp:mcfur/minestuck/dead_coffee_table> : 2,
    <item:everycomp:mcfur/minestuck/dead_covered_desk> : 5,
    <item:everycomp:mcfur/minestuck/dead_desk> : 2,
    <item:everycomp:mcfur/minestuck/dead_end_table> : 25,
    <item:everycomp:mcfur/minestuck/dead_glass_table> : 10,
    <item:everycomp:mcfur/minestuck/dead_modern_chair> : 10,
    <item:everycomp:mcfur/minestuck/dead_modern_desk> : 10,
    <item:everycomp:mcfur/minestuck/dead_stool_chair> : 10,
    <item:everycomp:mcfur/minestuck/dead_striped_chair> : 5,
    <item:everycomp:mcfur/minestuck/dead_table> : 1,
    <item:everycomp:mcfur/minestuck/doom_aspect_chair> : 2,
    <item:everycomp:mcfur/minestuck/doom_aspect_coffee_table> : 2,
    <item:everycomp:mcfur/minestuck/doom_aspect_covered_desk> : 10,
    <item:everycomp:mcfur/minestuck/doom_aspect_desk> : 2,
    <item:everycomp:mcfur/minestuck/doom_aspect_end_table> : 10,
    <item:everycomp:mcfur/minestuck/doom_aspect_glass_table> : 25,
    <item:everycomp:mcfur/minestuck/doom_aspect_modern_chair> : 25,
    <item:everycomp:mcfur/minestuck/doom_aspect_modern_desk> : 10,
    <item:everycomp:mcfur/minestuck/doom_aspect_stool_chair> : 10,
    <item:everycomp:mcfur/minestuck/doom_aspect_striped_chair> : 5,
    <item:everycomp:mcfur/minestuck/doom_aspect_table> : 5,
    <item:everycomp:mcfur/minestuck/end_chair> : 10,
    <item:everycomp:mcfur/minestuck/end_coffee_table> : 10,
    <item:everycomp:mcfur/minestuck/end_covered_desk> : 25,
    <item:everycomp:mcfur/minestuck/end_desk> : 5,
    <item:everycomp:mcfur/minestuck/end_end_table> : 2,
    <item:everycomp:mcfur/minestuck/end_glass_table> : 10,
    <item:everycomp:mcfur/minestuck/end_modern_chair> : 2,
    <item:everycomp:mcfur/minestuck/end_modern_desk> : 5,
    <item:everycomp:mcfur/minestuck/end_stool_chair> : 2,
    <item:everycomp:mcfur/minestuck/end_striped_chair> : 25,
    <item:everycomp:mcfur/minestuck/end_table> : 10,
    <item:everycomp:mcfur/minestuck/frost_chair> : 10,
    <item:everycomp:mcfur/minestuck/frost_coffee_table> : 10,
    <item:everycomp:mcfur/minestuck/frost_covered_desk> : 10,
    <item:everycomp:mcfur/minestuck/frost_desk> : 5,
    <item:everycomp:mcfur/minestuck/frost_end_table> : 1,
    <item:everycomp:mcfur/minestuck/frost_glass_table> : 2,
    <item:everycomp:mcfur/minestuck/frost_modern_chair> : 2,
    <item:everycomp:mcfur/minestuck/frost_modern_desk> : 10,
    <item:everycomp:mcfur/minestuck/frost_stool_chair> : 2,
    <item:everycomp:mcfur/minestuck/frost_striped_chair> : 10,
    <item:everycomp:mcfur/minestuck/frost_table> : 25,
    <item:everycomp:mcfur/minestuck/glowing_chair> : 25,
    <item:everycomp:mcfur/minestuck/glowing_coffee_table> : 10,
    <item:everycomp:mcfur/minestuck/glowing_covered_desk> : 10,
    <item:everycomp:mcfur/minestuck/glowing_desk> : 5,
    <item:everycomp:mcfur/minestuck/glowing_end_table> : 5,
    <item:everycomp:mcfur/minestuck/glowing_glass_table> : 10,
    <item:everycomp:mcfur/minestuck/glowing_modern_chair> : 10,
    <item:everycomp:mcfur/minestuck/glowing_modern_desk> : 25,
    <item:everycomp:mcfur/minestuck/glowing_stool_chair> : 5,
    <item:everycomp:mcfur/minestuck/glowing_striped_chair> : 2,
    <item:everycomp:mcfur/minestuck/glowing_table> : 10,
    <item:everycomp:mcfur/minestuck/heart_aspect_chair> : 2,
    <item:everycomp:mcfur/minestuck/heart_aspect_coffee_table> : 5,
    <item:everycomp:mcfur/minestuck/heart_aspect_covered_desk> : 2,
    <item:everycomp:mcfur/minestuck/heart_aspect_desk> : 25,
    <item:everycomp:mcfur/minestuck/heart_aspect_end_table> : 10,
    <item:everycomp:mcfur/minestuck/heart_aspect_glass_table> : 10,
    <item:everycomp:mcfur/minestuck/heart_aspect_modern_chair> : 10,
    <item:everycomp:mcfur/minestuck/heart_aspect_modern_desk> : 10,
    <item:everycomp:mcfur/minestuck/heart_aspect_stool_chair> : 5,
    <item:everycomp:mcfur/minestuck/heart_aspect_striped_chair> : 1,
    <item:everycomp:mcfur/minestuck/heart_aspect_table> : 2,
    <item:everycomp:mcfur/minestuck/hope_aspect_chair> : 2,
    <item:everycomp:mcfur/minestuck/hope_aspect_coffee_table> : 10,
    <item:everycomp:mcfur/minestuck/hope_aspect_covered_desk> : 2,
    <item:everycomp:mcfur/minestuck/hope_aspect_desk> : 10,
    <item:everycomp:mcfur/minestuck/hope_aspect_end_table> : 25,
    <item:everycomp:mcfur/minestuck/hope_aspect_glass_table> : 25,
    <item:everycomp:mcfur/minestuck/hope_aspect_modern_chair> : 10,
    <item:everycomp:mcfur/minestuck/hope_aspect_modern_desk> : 10,
    <item:everycomp:mcfur/minestuck/hope_aspect_stool_chair> : 5,
    <item:everycomp:mcfur/minestuck/hope_aspect_striped_chair> : 5,
    <item:everycomp:mcfur/minestuck/hope_aspect_table> : 10,
    <item:everycomp:mcfur/minestuck/life_aspect_chair> : 10,
    <item:everycomp:mcfur/minestuck/life_aspect_coffee_table> : 25,
    <item:everycomp:mcfur/minestuck/life_aspect_covered_desk> : 5,
    <item:everycomp:mcfur/minestuck/life_aspect_desk> : 2,
    <item:everycomp:mcfur/minestuck/life_aspect_end_table> : 10,
    <item:everycomp:mcfur/minestuck/life_aspect_glass_table> : 2,
    <item:everycomp:mcfur/minestuck/life_aspect_modern_chair> : 5,
    <item:everycomp:mcfur/minestuck/life_aspect_modern_desk> : 2,
    <item:everycomp:mcfur/minestuck/life_aspect_stool_chair> : 25,
    <item:everycomp:mcfur/minestuck/life_aspect_striped_chair> : 10,
    <item:everycomp:mcfur/minestuck/life_aspect_table> : 10,
    <item:everycomp:mcfur/minestuck/light_aspect_chair> : 10,
    <item:everycomp:mcfur/minestuck/light_aspect_coffee_table> : 10,
    <item:everycomp:mcfur/minestuck/light_aspect_covered_desk> : 5,
    <item:everycomp:mcfur/minestuck/light_aspect_desk> : 1,
    <item:everycomp:mcfur/minestuck/light_aspect_end_table> : 2,
    <item:everycomp:mcfur/minestuck/light_aspect_glass_table> : 2,
    <item:everycomp:mcfur/minestuck/light_aspect_modern_chair> : 10,
    <item:everycomp:mcfur/minestuck/light_aspect_modern_desk> : 2,
    <item:everycomp:mcfur/minestuck/light_aspect_stool_chair> : 10,
    <item:everycomp:mcfur/minestuck/light_aspect_striped_chair> : 25,
    <item:everycomp:mcfur/minestuck/light_aspect_table> : 25,
    <item:everycomp:mcfur/minestuck/mind_aspect_chair> : 10,
    <item:everycomp:mcfur/minestuck/mind_aspect_coffee_table> : 10,
    <item:everycomp:mcfur/minestuck/mind_aspect_covered_desk> : 5,
    <item:everycomp:mcfur/minestuck/mind_aspect_desk> : 5,
    <item:everycomp:mcfur/minestuck/mind_aspect_end_table> : 10,
    <item:everycomp:mcfur/minestuck/mind_aspect_glass_table> : 10,
    <item:everycomp:mcfur/minestuck/mind_aspect_modern_chair> : 25,
    <item:everycomp:mcfur/minestuck/mind_aspect_modern_desk> : 5,
    <item:everycomp:mcfur/minestuck/mind_aspect_stool_chair> : 2,
    <item:everycomp:mcfur/minestuck/mind_aspect_striped_chair> : 10,
    <item:everycomp:mcfur/minestuck/mind_aspect_table> : 2,
    <item:everycomp:mcfur/minestuck/rage_aspect_chair> : 5,
    <item:everycomp:mcfur/minestuck/rage_aspect_coffee_table> : 2,
    <item:everycomp:mcfur/minestuck/rage_aspect_covered_desk> : 25,
    <item:everycomp:mcfur/minestuck/rage_aspect_desk> : 10,
    <item:everycomp:mcfur/minestuck/rage_aspect_end_table> : 10,
    <item:everycomp:mcfur/minestuck/rage_aspect_glass_table> : 10,
    <item:everycomp:mcfur/minestuck/rage_aspect_modern_chair> : 10,
    <item:everycomp:mcfur/minestuck/rage_aspect_modern_desk> : 5,
    <item:everycomp:mcfur/minestuck/rage_aspect_stool_chair> : 1,
    <item:everycomp:mcfur/minestuck/rage_aspect_striped_chair> : 2,
    <item:everycomp:mcfur/minestuck/rage_aspect_table> : 2,
    <item:everycomp:mcfur/minestuck/rainbow_chair> : 10,
    <item:everycomp:mcfur/minestuck/rainbow_coffee_table> : 2,
    <item:everycomp:mcfur/minestuck/rainbow_covered_desk> : 10,
    <item:everycomp:mcfur/minestuck/rainbow_desk> : 25,
    <item:everycomp:mcfur/minestuck/rainbow_end_table> : 25,
    <item:everycomp:mcfur/minestuck/rainbow_glass_table> : 10,
    <item:everycomp:mcfur/minestuck/rainbow_modern_chair> : 10,
    <item:everycomp:mcfur/minestuck/rainbow_modern_desk> : 5,
    <item:everycomp:mcfur/minestuck/rainbow_stool_chair> : 5,
    <item:everycomp:mcfur/minestuck/rainbow_striped_chair> : 10,
    <item:everycomp:mcfur/minestuck/rainbow_table> : 10,
    <item:everycomp:mcfur/minestuck/space_aspect_chair> : 25,
    <item:everycomp:mcfur/minestuck/space_aspect_coffee_table> : 5,
    <item:everycomp:mcfur/minestuck/space_aspect_covered_desk> : 2,
    <item:everycomp:mcfur/minestuck/space_aspect_desk> : 10,
    <item:everycomp:mcfur/minestuck/space_aspect_end_table> : 2,
    <item:everycomp:mcfur/minestuck/space_aspect_glass_table> : 5,
    <item:everycomp:mcfur/minestuck/space_aspect_modern_chair> : 2,
    <item:everycomp:mcfur/minestuck/space_aspect_modern_desk> : 25,
    <item:everycomp:mcfur/minestuck/space_aspect_stool_chair> : 10,
    <item:everycomp:mcfur/minestuck/space_aspect_striped_chair> : 10,
    <item:everycomp:mcfur/minestuck/space_aspect_table> : 10,
    <item:everycomp:mcfur/minestuck/stripped_blood_aspect_modern_chair> : 10,
    <item:everycomp:mcfur/minestuck/stripped_breath_aspect_modern_chair> : 5,
    <item:everycomp:mcfur/minestuck/stripped_dead_modern_chair> : 1,
    <item:everycomp:mcfur/minestuck/stripped_doom_aspect_modern_chair> : 2,
    <item:everycomp:mcfur/minestuck/stripped_end_modern_chair> : 2,
    <item:everycomp:mcfur/minestuck/stripped_frost_modern_chair> : 10,
    <item:everycomp:mcfur/minestuck/stripped_glowing_modern_chair> : 2,
    <item:everycomp:mcfur/minestuck/stripped_heart_aspect_modern_chair> : 10,
    <item:everycomp:mcfur/minestuck/stripped_hope_aspect_modern_chair> : 25,
    <item:everycomp:mcfur/minestuck/stripped_life_aspect_modern_chair> : 25,
    <item:everycomp:mcfur/minestuck/stripped_light_aspect_modern_chair> : 10,
    <item:everycomp:mcfur/minestuck/stripped_mind_aspect_modern_chair> : 10,
    <item:everycomp:mcfur/minestuck/stripped_rage_aspect_modern_chair> : 5,
    <item:everycomp:mcfur/minestuck/stripped_rainbow_modern_chair> : 5,
    <item:everycomp:mcfur/minestuck/stripped_space_aspect_modern_chair> : 10,
    <item:everycomp:mcfur/minestuck/stripped_time_aspect_modern_chair> : 10,
    <item:everycomp:mcfur/minestuck/stripped_void_aspect_modern_chair> : 25,
    <item:everycomp:mcfur/minestuck/time_aspect_chair> : 5,
    <item:everycomp:mcfur/minestuck/time_aspect_coffee_table> : 2,
    <item:everycomp:mcfur/minestuck/time_aspect_covered_desk> : 10,
    <item:everycomp:mcfur/minestuck/time_aspect_desk> : 2,
    <item:everycomp:mcfur/minestuck/time_aspect_end_table> : 5,
    <item:everycomp:mcfur/minestuck/time_aspect_glass_table> : 2,
    <item:everycomp:mcfur/minestuck/time_aspect_modern_chair> : 25,
    <item:everycomp:mcfur/minestuck/time_aspect_modern_desk> : 10,
    <item:everycomp:mcfur/minestuck/time_aspect_stool_chair> : 10,
    <item:everycomp:mcfur/minestuck/time_aspect_striped_chair> : 10,
    <item:everycomp:mcfur/minestuck/time_aspect_table> : 10,
    <item:everycomp:mcfur/minestuck/void_aspect_chair> : 5,
    <item:everycomp:mcfur/minestuck/void_aspect_coffee_table> : 1,
    <item:everycomp:mcfur/minestuck/void_aspect_covered_desk> : 2,
    <item:everycomp:mcfur/minestuck/void_aspect_desk> : 2,
    <item:everycomp:mcfur/minestuck/void_aspect_end_table> : 10,
    <item:everycomp:mcfur/minestuck/void_aspect_glass_table> : 2,
    <item:everycomp:mcfur/minestuck/void_aspect_modern_chair> : 10,
    <item:everycomp:mcfur/minestuck/void_aspect_modern_desk> : 25,
    <item:everycomp:mcfur/minestuck/void_aspect_stool_chair> : 25,
    <item:everycomp:mcfur/minestuck/void_aspect_striped_chair> : 10,
    <item:everycomp:mcfur/minestuck/void_aspect_table> : 10,
    <item:everycomp:mcfur/quark/azalea_bookshelf_cupboard> : 5,
    <item:everycomp:mcfur/quark/azalea_bookshelf_drawer> : 5,
    <item:everycomp:mcfur/quark/azalea_chair> : 10,
    <item:everycomp:mcfur/quark/azalea_coffee_table> : 10,
    <item:everycomp:mcfur/quark/azalea_counter> : 25,
    <item:everycomp:mcfur/quark/azalea_covered_desk> : 5,
    <item:everycomp:mcfur/quark/azalea_cupboard_counter> : 2,
    <item:everycomp:mcfur/quark/azalea_desk> : 10,
    <item:everycomp:mcfur/quark/azalea_double_drawer> : 2,
    <item:everycomp:mcfur/quark/azalea_double_drawer_counter> : 5,
    <item:everycomp:mcfur/quark/azalea_double_wardrobe> : 2,
    <item:everycomp:mcfur/quark/azalea_drawer> : 25,
    <item:everycomp:mcfur/quark/azalea_drawer_counter> : 10,
    <item:everycomp:mcfur/quark/azalea_end_table> : 10,
    <item:everycomp:mcfur/quark/azalea_glass_table> : 10,
    <item:everycomp:mcfur/quark/azalea_large_drawer> : 10,
    <item:everycomp:mcfur/quark/azalea_lower_bookshelf_drawer> : 5,
    <item:everycomp:mcfur/quark/azalea_lower_triple_drawer> : 1,
    <item:everycomp:mcfur/quark/azalea_modern_chair> : 2,
    <item:everycomp:mcfur/quark/azalea_modern_desk> : 2,
    <item:everycomp:mcfur/quark/azalea_modern_wardrobe> : 10,
    <item:everycomp:mcfur/quark/azalea_stool_chair> : 2,
    <item:everycomp:mcfur/quark/azalea_striped_chair> : 10,
    <item:everycomp:mcfur/quark/azalea_table> : 25,
    <item:everycomp:mcfur/quark/azalea_triple_drawer> : 25,
    <item:everycomp:mcfur/quark/azalea_wardrobe> : 10,
    <item:everycomp:mcfur/quark/blossom_bookshelf_cupboard> : 10,
    <item:everycomp:mcfur/quark/blossom_bookshelf_drawer> : 5,
    <item:everycomp:mcfur/quark/blossom_chair> : 5,
    <item:everycomp:mcfur/quark/blossom_coffee_table> : 10,
    <item:everycomp:mcfur/quark/blossom_counter> : 10,
    <item:everycomp:mcfur/quark/blossom_covered_desk> : 25,
    <item:everycomp:mcfur/quark/blossom_cupboard_counter> : 5,
    <item:everycomp:mcfur/quark/blossom_desk> : 2,
    <item:everycomp:mcfur/quark/blossom_double_drawer> : 10,
    <item:everycomp:mcfur/quark/blossom_double_drawer_counter> : 2,
    <item:everycomp:mcfur/quark/blossom_double_wardrobe> : 5,
    <item:everycomp:mcfur/quark/blossom_drawer> : 2,
    <item:everycomp:mcfur/quark/blossom_drawer_counter> : 25,
    <item:everycomp:mcfur/quark/blossom_end_table> : 10,
    <item:everycomp:mcfur/quark/blossom_glass_table> : 10,
    <item:everycomp:mcfur/quark/blossom_large_drawer> : 10,
    <item:everycomp:mcfur/quark/blossom_lower_bookshelf_drawer> : 10,
    <item:everycomp:mcfur/quark/blossom_lower_triple_drawer> : 5,
    <item:everycomp:mcfur/quark/blossom_modern_chair> : 1,
    <item:everycomp:mcfur/quark/blossom_modern_desk> : 2,
    <item:everycomp:mcfur/quark/blossom_modern_wardrobe> : 2,
    <item:everycomp:mcfur/quark/blossom_stool_chair> : 10,
    <item:everycomp:mcfur/quark/blossom_striped_chair> : 2,
    <item:everycomp:mcfur/quark/blossom_table> : 10,
    <item:everycomp:mcfur/quark/blossom_triple_drawer> : 25,
    <item:everycomp:mcfur/quark/blossom_wardrobe> : 25,
    <item:everycomp:mcfur/quark/stripped_azalea_bookshelf> : 10,
    <item:everycomp:mcfur/quark/stripped_azalea_bookshelf_cupboard> : 10,
    <item:everycomp:mcfur/quark/stripped_azalea_bookshelf_drawer> : 5,
    <item:everycomp:mcfur/quark/stripped_azalea_chair> : 5,
    <item:everycomp:mcfur/quark/stripped_azalea_coffee_table> : 10,
    <item:everycomp:mcfur/quark/stripped_azalea_counter> : 10,
    <item:everycomp:mcfur/quark/stripped_azalea_covered_desk> : 25,
    <item:everycomp:mcfur/quark/stripped_azalea_cupboard_counter> : 5,
    <item:everycomp:mcfur/quark/stripped_azalea_desk> : 2,
    <item:everycomp:mcfur/quark/stripped_azalea_double_drawer> : 10,
    <item:everycomp:mcfur/quark/stripped_azalea_double_drawer_counter> : 2,
    <item:everycomp:mcfur/quark/stripped_azalea_double_wardrobe> : 5,
    <item:everycomp:mcfur/quark/stripped_azalea_drawer> : 2,
    <item:everycomp:mcfur/quark/stripped_azalea_drawer_counter> : 25,
    <item:everycomp:mcfur/quark/stripped_azalea_end_table> : 10,
    <item:everycomp:mcfur/quark/stripped_azalea_glass_table> : 10,
    <item:everycomp:mcfur/quark/stripped_azalea_large_drawer> : 10,
    <item:everycomp:mcfur/quark/stripped_azalea_lower_bookshelf_drawer> : 10,
    <item:everycomp:mcfur/quark/stripped_azalea_lower_triple_drawer> : 5,
    <item:everycomp:mcfur/quark/stripped_azalea_modern_chair> : 1,
    <item:everycomp:mcfur/quark/stripped_azalea_modern_desk> : 2,
    <item:everycomp:mcfur/quark/stripped_azalea_modern_wardrobe> : 2,
    <item:everycomp:mcfur/quark/stripped_azalea_stool_chair> : 10,
    <item:everycomp:mcfur/quark/stripped_azalea_striped_chair> : 2,
    <item:everycomp:mcfur/quark/stripped_azalea_table> : 10,
    <item:everycomp:mcfur/quark/stripped_azalea_triple_drawer> : 25,
    <item:everycomp:mcfur/quark/stripped_azalea_wardrobe> : 25,
    <item:everycomp:mcfur/quark/stripped_blossom_bookshelf> : 10,
    <item:everycomp:mcfur/quark/stripped_blossom_bookshelf_cupboard> : 10,
    <item:everycomp:mcfur/quark/stripped_blossom_bookshelf_drawer> : 5,
    <item:everycomp:mcfur/quark/stripped_blossom_chair> : 5,
    <item:everycomp:mcfur/quark/stripped_blossom_coffee_table> : 10,
    <item:everycomp:mcfur/quark/stripped_blossom_counter> : 10,
    <item:everycomp:mcfur/quark/stripped_blossom_covered_desk> : 25,
    <item:everycomp:mcfur/quark/stripped_blossom_cupboard_counter> : 5,
    <item:everycomp:mcfur/quark/stripped_blossom_desk> : 2,
    <item:everycomp:mcfur/quark/stripped_blossom_double_drawer> : 10,
    <item:everycomp:mcfur/quark/stripped_blossom_double_drawer_counter> : 2,
    <item:everycomp:mcfur/quark/stripped_blossom_double_wardrobe> : 5,
    <item:everycomp:mcfur/quark/stripped_blossom_drawer> : 2,
    <item:everycomp:mcfur/quark/stripped_blossom_drawer_counter> : 25,
    <item:everycomp:mcfur/quark/stripped_blossom_end_table> : 10,
    <item:everycomp:mcfur/quark/stripped_blossom_glass_table> : 10,
    <item:everycomp:mcfur/quark/stripped_blossom_large_drawer> : 10,
    <item:everycomp:mcfur/quark/stripped_blossom_lower_bookshelf_drawer> : 10,
    <item:everycomp:mcfur/quark/stripped_blossom_lower_triple_drawer> : 5,
    <item:everycomp:mcfur/quark/stripped_blossom_modern_chair> : 1,
    <item:everycomp:mcfur/quark/stripped_blossom_modern_desk> : 2,
    <item:everycomp:mcfur/quark/stripped_blossom_modern_wardrobe> : 2,
    <item:everycomp:mcfur/quark/stripped_blossom_stool_chair> : 10,
    <item:everycomp:mcfur/quark/stripped_blossom_striped_chair> : 2,
    <item:everycomp:mcfur/quark/stripped_blossom_table> : 10,
    <item:everycomp:mcfur/quark/stripped_blossom_triple_drawer> : 25,
    <item:everycomp:mcfur/quark/stripped_blossom_wardrobe> : 25
};

// For each item in the map, check if we're in release mode. If we are, anything below 26 EMC/FMC becomes unburnable for EMC
for item, value in priceTable {
    if (release_mode == true){
        if (value < 26 ) {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), 0);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        } else {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        }
        if (value > 999 && value < 10001) {
            <tag:items:tfb2:fop_miniscule>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Miniscule");
            });
        }
        if (value > 10000 && value < 25001) {
            <tag:items:tfb2:fop_small>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Small");
            });
        }
        if (value > 25000 && value < 75001) {
            <tag:items:tfb2:fop_medium>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Medium");
            });
        }
        if (value > 75000) {
            <tag:items:tfb2:fop_large>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Large");
            });
        }
    } else {
        CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
        <tag:items:projectextended:blacklist_condenser>.add(item);
        <tag:items:projectextended:blacklist_learning>.add(item);
    }
        if (value > 10000 && value < 25001) {
            <tag:items:tfb2:fop_small>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Small");
            });
        }
        if (value > 25000 && value < 75001) {
            <tag:items:tfb2:fop_medium>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Medium");
            });
        }
        if (value > 75000) {
            <tag:items:tfb2:fop_large>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Large");
            });
        }
}