import crafttweaker.api.tag.MCTag;
import crafttweaker.api.item.IItemStack;
import crafttweaker.api.ingredient.IIngredient;
import crafttweaker.api.item.tooltip.ITooltipFunction;
import stdlib.List;
import mods.projecte.CustomEMC;
import mods.projecte.NSSResolver;

// Item  to EMC/FMC value map.
val priceTable as int[IItemStack] = {
    <item:everycomp:cfm/the_vault/chromatic_bedside_cabinet> : 5,
    <item:everycomp:cfm/the_vault/chromatic_blinds> : 5,
    <item:everycomp:cfm/the_vault/chromatic_cabinet> : 5,
    <item:everycomp:cfm/the_vault/chromatic_chair> : 1,
    <item:everycomp:cfm/the_vault/chromatic_coffee_table> : 1,
    <item:everycomp:cfm/the_vault/chromatic_crate> : 5,
    <item:everycomp:cfm/the_vault/chromatic_desk> : 2,
    <item:everycomp:cfm/the_vault/chromatic_desk_cabinet> :1,
    <item:everycomp:cfm/the_vault/chromatic_kitchen_counter> : 1,
    <item:everycomp:cfm/the_vault/chromatic_kitchen_drawer> : 2,
    <item:everycomp:cfm/the_vault/chromatic_park_bench> : 2,
    <item:everycomp:cfm/the_vault/chromatic_table> : 1,
    <item:everycomp:cfm/the_vault/chromatic_upgraded_fence> : 1,
    <item:everycomp:cfm/the_vault/chromatic_upgraded_gate> : 2,
    <item:everycomp:cfm/the_vault/stripped_chromatic_bedside_cabinet> : 5,
    <item:everycomp:cfm/the_vault/stripped_chromatic_blinds> : 5,
    <item:everycomp:cfm/the_vault/stripped_chromatic_cabinet> : 5,
    <item:everycomp:cfm/the_vault/stripped_chromatic_chair> : 1,
    <item:everycomp:cfm/the_vault/stripped_chromatic_coffee_table> : 1,
    <item:everycomp:cfm/the_vault/stripped_chromatic_crate> : 5,
    <item:everycomp:cfm/the_vault/stripped_chromatic_desk> : 2,
    <item:everycomp:cfm/the_vault/stripped_chromatic_desk_cabinet> :1,
    <item:everycomp:cfm/the_vault/stripped_chromatic_kitchen_counter> : 1,
    <item:everycomp:cfm/the_vault/stripped_chromatic_kitchen_drawer> : 2,
    <item:everycomp:cfm/the_vault/stripped_chromatic_park_bench> : 2,
    <item:everycomp:cfm/the_vault/stripped_chromatic_table> : 1,
    <item:everycomp:cfm/the_vault/stripped_tenos_bedside_cabinet> : 5,
    <item:everycomp:cfm/the_vault/stripped_tenos_blinds> : 5,
    <item:everycomp:cfm/the_vault/stripped_tenos_cabinet> : 5,
    <item:everycomp:cfm/the_vault/stripped_tenos_chair> : 1,
    <item:everycomp:cfm/the_vault/stripped_tenos_coffee_table> : 1,
    <item:everycomp:cfm/the_vault/stripped_tenos_crate> : 5,
    <item:everycomp:cfm/the_vault/stripped_tenos_desk> : 2,
    <item:everycomp:cfm/the_vault/stripped_tenos_desk_cabinet> :1,
    <item:everycomp:cfm/the_vault/stripped_tenos_kitchen_counter> : 1,
    <item:everycomp:cfm/the_vault/stripped_tenos_kitchen_drawer> : 2,
    <item:everycomp:cfm/the_vault/stripped_tenos_park_bench> : 2,
    <item:everycomp:cfm/the_vault/stripped_tenos_table> : 1,
    <item:everycomp:cfm/the_vault/stripped_velara_bedside_cabinet> : 5,
    <item:everycomp:cfm/the_vault/stripped_velara_blinds> : 5,
    <item:everycomp:cfm/the_vault/stripped_velara_cabinet> : 5,
    <item:everycomp:cfm/the_vault/stripped_velara_chair> : 1,
    <item:everycomp:cfm/the_vault/stripped_velara_coffee_table> : 1,
    <item:everycomp:cfm/the_vault/stripped_velara_crate> : 5,
    <item:everycomp:cfm/the_vault/stripped_velara_desk> : 2,
    <item:everycomp:cfm/the_vault/stripped_velara_desk_cabinet> :1,
    <item:everycomp:cfm/the_vault/stripped_velara_kitchen_counter> : 1,
    <item:everycomp:cfm/the_vault/stripped_velara_kitchen_drawer> : 2,
    <item:everycomp:cfm/the_vault/stripped_velara_park_bench> : 2,
    <item:everycomp:cfm/the_vault/stripped_velara_table> : 1,
    <item:everycomp:cfm/the_vault/tenos_bedside_cabinet> : 5,
    <item:everycomp:cfm/the_vault/tenos_blinds> : 5,
    <item:everycomp:cfm/the_vault/tenos_cabinet> : 5,
    <item:everycomp:cfm/the_vault/tenos_chair> : 1,
    <item:everycomp:cfm/the_vault/tenos_coffee_table> : 1,
    <item:everycomp:cfm/the_vault/tenos_crate> : 5,
    <item:everycomp:cfm/the_vault/tenos_desk> : 2,
    <item:everycomp:cfm/the_vault/tenos_desk_cabinet> :1,
    <item:everycomp:cfm/the_vault/tenos_kitchen_counter> : 1,
    <item:everycomp:cfm/the_vault/tenos_kitchen_drawer> : 2,
    <item:everycomp:cfm/the_vault/tenos_park_bench> : 2,
    <item:everycomp:cfm/the_vault/tenos_table> : 1,
    <item:everycomp:cfm/the_vault/tenos_upgraded_fence> : 1,
    <item:everycomp:cfm/the_vault/tenos_upgraded_gate> : 2,
    <item:everycomp:cfm/the_vault/velara_bedside_cabinet> : 5,
    <item:everycomp:cfm/the_vault/velara_blinds> : 5,
    <item:everycomp:cfm/the_vault/velara_cabinet> : 5,
    <item:everycomp:cfm/the_vault/velara_chair> : 1,
    <item:everycomp:cfm/the_vault/velara_coffee_table> : 1,
    <item:everycomp:cfm/the_vault/velara_crate> : 5,
    <item:everycomp:cfm/the_vault/velara_desk> : 2,
    <item:everycomp:cfm/the_vault/velara_desk_cabinet> :1,
    <item:everycomp:cfm/the_vault/velara_hedge> :1,
    <item:everycomp:cfm/the_vault/velara_kitchen_counter> : 1,
    <item:everycomp:cfm/the_vault/velara_kitchen_drawer> : 2,
    <item:everycomp:cfm/the_vault/velara_park_bench> : 2,
    <item:everycomp:cfm/the_vault/velara_table> : 1,
    <item:everycomp:cfm/the_vault/velara_upgraded_fence> : 1,
    <item:everycomp:cfm/the_vault/velara_upgraded_gate> : 2,
    <item:everycomp:cfm/tropicraft/black_mangrove_hedge> : 1,
    <item:everycomp:cfm/tropicraft/blue_flowering_hedge> : 1,
    <item:everycomp:cfm/tropicraft/fruit_hedge> : 1,
    <item:everycomp:cfm/tropicraft/grapefruit_hedge> : 1,
    <item:everycomp:cfm/tropicraft/kapok_hedge> : 1,
    <item:everycomp:cfm/tropicraft/lemon_hedge> : 1,
    <item:everycomp:cfm/tropicraft/lime_hedge> : 1,
    <item:everycomp:cfm/tropicraft/mahogany_bedside_cabinet> : 5,
    <item:everycomp:cfm/tropicraft/mahogany_blinds> : 5,
    <item:everycomp:cfm/tropicraft/mahogany_cabinet> : 5,
    <item:everycomp:cfm/tropicraft/mahogany_chair> : 1,
    <item:everycomp:cfm/tropicraft/mahogany_coffee_table> : 1,
    <item:everycomp:cfm/tropicraft/mahogany_crate> : 5,
    <item:everycomp:cfm/tropicraft/mahogany_desk> : 2,
    <item:everycomp:cfm/tropicraft/mahogany_desk_cabinet> :1,
    <item:everycomp:cfm/tropicraft/mahogany_hedge> :1,
    <item:everycomp:cfm/tropicraft/mahogany_kitchen_counter> : 1,
    <item:everycomp:cfm/tropicraft/mahogany_kitchen_drawer> : 2,
    <item:everycomp:cfm/tropicraft/mahogany_park_bench> : 2,
    <item:everycomp:cfm/tropicraft/mahogany_table> : 1,
    <item:everycomp:cfm/tropicraft/mahogany_upgraded_fence> : 1,
    <item:everycomp:cfm/tropicraft/mahogany_upgraded_gate> : 2,
    <item:everycomp:cfm/tropicraft/orange_hedge> : 1,
    <item:everycomp:cfm/tropicraft/palm_bedside_cabinet> : 5,
    <item:everycomp:cfm/tropicraft/palm_blinds> : 5,
    <item:everycomp:cfm/tropicraft/palm_cabinet> : 5,
    <item:everycomp:cfm/tropicraft/palm_chair> : 1,
    <item:everycomp:cfm/tropicraft/palm_coffee_table> : 1,
    <item:everycomp:cfm/tropicraft/palm_crate> : 5,
    <item:everycomp:cfm/tropicraft/palm_desk> : 2,
    <item:everycomp:cfm/tropicraft/palm_desk_cabinet> :1,
    <item:everycomp:cfm/tropicraft/palm_hedge> :1,
    <item:everycomp:cfm/tropicraft/palm_kitchen_counter> : 1,
    <item:everycomp:cfm/tropicraft/palm_kitchen_drawer> : 2,
    <item:everycomp:cfm/tropicraft/palm_park_bench> : 2,
    <item:everycomp:cfm/tropicraft/palm_table> : 1,
    <item:everycomp:cfm/tropicraft/palm_upgraded_fence> : 1,
    <item:everycomp:cfm/tropicraft/palm_upgraded_gate> : 2,
    <item:everycomp:cfm/tropicraft/papaya_hedge> : 1,
    <item:everycomp:cfm/tropicraft/purple_flowering_hedge> : 1,
    <item:everycomp:cfm/tropicraft/red_flowering_hedge> : 1,
    <item:everycomp:cfm/tropicraft/red_mangrove_hedge> : 1,
    <item:everycomp:cfm/tropicraft/tall_mangrove_hedge> : 1,
    <item:everycomp:cfm/tropicraft/tea_mangrove_hedge> : 1,
    <item:everycomp:cfm/tropicraft/white_flowering_hedge> : 1,
    <item:everycomp:cfm/tropicraft/yellow_flowering_hedge> : 1,
    <item:everycomp:cfm/twigs/bamboo_bedside_cabinet> : 5,
    <item:everycomp:cfm/twigs/bamboo_blinds> : 5,
    <item:everycomp:cfm/twigs/bamboo_cabinet> : 5,
    <item:everycomp:cfm/twigs/bamboo_chair> : 1,
    <item:everycomp:cfm/twigs/bamboo_coffee_table> : 1,
    <item:everycomp:cfm/twigs/bamboo_crate> : 5,
    <item:everycomp:cfm/twigs/bamboo_desk> : 2,
    <item:everycomp:cfm/twigs/bamboo_desk_cabinet> :1,
    <item:everycomp:cfm/twigs/bamboo_hedge> :1,
    <item:everycomp:cfm/twigs/bamboo_kitchen_counter> : 1,
    <item:everycomp:cfm/twigs/bamboo_kitchen_drawer> : 2,
    <item:everycomp:cfm/twigs/bamboo_park_bench> : 2,
    <item:everycomp:cfm/twigs/bamboo_table> : 1,
    <item:everycomp:cfm/twigs/bamboo_upgraded_fence> : 1,
    <item:everycomp:cfm/twigs/bamboo_upgraded_gate> : 2,
    <item:everycomp:cfm/twigs/stripped_bamboo_bedside_cabinet> : 5,
    <item:everycomp:cfm/twigs/stripped_bamboo_blinds> : 5,
    <item:everycomp:cfm/twigs/stripped_bamboo_cabinet> : 5,
    <item:everycomp:cfm/twigs/stripped_bamboo_chair> : 1,
    <item:everycomp:cfm/twigs/stripped_bamboo_coffee_table> : 1,
    <item:everycomp:cfm/twigs/stripped_bamboo_crate> : 5,
    <item:everycomp:cfm/twigs/stripped_bamboo_desk> : 2,
    <item:everycomp:cfm/twigs/stripped_bamboo_desk_cabinet> :1,
    <item:everycomp:cfm/twigs/stripped_bamboo_kitchen_counter> : 1,
    <item:everycomp:cfm/twigs/stripped_bamboo_kitchen_drawer> : 2,
    <item:everycomp:cfm/twigs/stripped_bamboo_park_bench> : 2,
    <item:everycomp:db/architects_palette/twisted_beam> : 1,
    <item:everycomp:db/architects_palette/twisted_palisade> : 1,
    <item:everycomp:db/architects_palette/twisted_seat> : 1,
    <item:everycomp:db/architects_palette/twisted_support> : 1,
    <item:everycomp:db/botania/dreamwood_beam> : 1,
    <item:everycomp:db/botania/dreamwood_palisade> : 1,
    <item:everycomp:db/botania/dreamwood_seat> : 1,
    <item:everycomp:db/botania/dreamwood_support> : 1,
    <item:everycomp:db/botania/livingwood_beam> : 1,
    <item:everycomp:db/botania/livingwood_palisade> : 1,
    <item:everycomp:db/botania/livingwood_seat> : 1,
    <item:everycomp:db/botania/livingwood_support> : 1,
    <item:everycomp:db/createdieselgenerators/chip_wood_palisade> : 1,
    <item:everycomp:db/createdieselgenerators/chip_wood_seat> : 1,
    <item:everycomp:db/createdieselgenerators/chip_wood_support> : 1,
    <item:everycomp:db/ecologics/azalea_beam> : 1,
    <item:everycomp:db/ecologics/azalea_palisade> : 1,
    <item:everycomp:db/ecologics/azalea_seat> : 1,
    <item:everycomp:db/ecologics/azalea_support> : 1,
    <item:everycomp:db/ecologics/coconut_beam> : 1,
    <item:everycomp:db/ecologics/coconut_palisade> : 1,
    <item:everycomp:db/ecologics/coconut_seat> : 1,
    <item:everycomp:db/ecologics/coconut_support> : 1,
    <item:everycomp:db/ecologics/flowering_azalea_beam> : 1,
    <item:everycomp:db/ecologics/flowering_azalea_palisade> : 1,
    <item:everycomp:db/ecologics/flowering_azalea_seat> : 1,
    <item:everycomp:db/ecologics/flowering_azalea_support> : 1,
    <item:everycomp:db/ecologics/walnut_beam> : 1,
    <item:everycomp:db/ecologics/walnut_palisade> : 1,
    <item:everycomp:db/ecologics/walnut_seat> : 1,
    <item:everycomp:db/ecologics/walnut_support> : 1,
    <item:everycomp:db/hexcasting/akashic_beam> : 1,
    <item:everycomp:db/hexcasting/akashic_palisade> : 1,
    <item:everycomp:db/hexcasting/akashic_seat> : 1,
    <item:everycomp:db/hexcasting/akashic_support> : 1,
    <item:everycomp:db/integrateddynamics/menril_beam> : 1,
    <item:everycomp:db/integrateddynamics/menril_palisade> : 1,
    <item:everycomp:db/integrateddynamics/menril_seat> : 1,
    <item:everycomp:db/integrateddynamics/menril_support> : 1,
    <item:everycomp:db/luphieclutteredmod/luphie_flowering_pink_beam> : 1,
    <item:everycomp:db/luphieclutteredmod/luphie_flowering_pink_palisade> : 1,
    <item:everycomp:db/luphieclutteredmod/luphie_flowering_pink_seat> : 1,
    <item:everycomp:db/luphieclutteredmod/luphie_flowering_pink_support> : 1,
    <item:everycomp:db/luphieclutteredmod/luphie_flowering_purple_beam> : 1,
    <item:everycomp:db/luphieclutteredmod/luphie_flowering_purple_palisade> : 1,
    <item:everycomp:db/luphieclutteredmod/luphie_flowering_purple_seat> : 1,
    <item:everycomp:db/luphieclutteredmod/luphie_flowering_purple_support> : 1,
    <item:everycomp:db/luphieclutteredmod/luphie_flowering_yellow_beam> : 1,
    <item:everycomp:db/luphieclutteredmod/luphie_flowering_yellow_palisade> : 1,
    <item:everycomp:db/luphieclutteredmod/luphie_flowering_yellow_seat> : 1,
    <item:everycomp:db/luphieclutteredmod/luphie_flowering_yellow_support> : 1,
    <item:everycomp:db/luphieclutteredmod/luphie_glow_beam> : 1,
    <item:everycomp:db/luphieclutteredmod/luphie_glow_palisade> : 1,
    <item:everycomp:db/luphieclutteredmod/luphie_glow_seat> : 1,
    <item:everycomp:db/luphieclutteredmod/luphie_glow_support> : 1,
    <item:everycomp:db/luphieclutteredmod/luphie_green_beam> : 1,
    <item:everycomp:db/luphieclutteredmod/luphie_green_palisade> : 1,
    <item:everycomp:db/luphieclutteredmod/luphie_green_seat> : 1,
    <item:everycomp:db/luphieclutteredmod/luphie_green_support> : 1,
    <item:everycomp:db/luphieclutteredmod/luphie_pink_beam> : 1,
    <item:everycomp:db/luphieclutteredmod/luphie_pink_palisade> : 1,
    <item:everycomp:db/luphieclutteredmod/luphie_pink_seat> : 1,
    <item:everycomp:db/luphieclutteredmod/luphie_pink_support> : 1,
    <item:everycomp:db/luphieclutteredmod/luphie_purple_beam> : 1,
    <item:everycomp:db/luphieclutteredmod/luphie_purple_palisade> : 1,
    <item:everycomp:db/luphieclutteredmod/luphie_purple_seat> : 1,
    <item:everycomp:db/luphieclutteredmod/luphie_purple_support> : 1,
    <item:everycomp:db/luphieclutteredmod/luphie_yellow_beam> : 1,
    <item:everycomp:db/luphieclutteredmod/luphie_yellow_palisade> : 1,
    <item:everycomp:db/luphieclutteredmod/luphie_yellow_seat> : 1,
    <item:everycomp:db/luphieclutteredmod/luphie_yellow_support> : 1,
    <item:everycomp:db/minestuck/blood_aspect_beam> : 1,
    <item:everycomp:db/minestuck/blood_aspect_palisade> : 1,
    <item:everycomp:db/minestuck/blood_aspect_seat> : 1,
    <item:everycomp:db/minestuck/blood_aspect_support> : 1,
    <item:everycomp:db/minestuck/breath_aspect_beam> : 1,
    <item:everycomp:db/minestuck/breath_aspect_palisade> : 1,
    <item:everycomp:db/minestuck/breath_aspect_seat> : 1,
    <item:everycomp:db/minestuck/breath_aspect_support> : 1,
    <item:everycomp:db/minestuck/dead_beam> : 1,
    <item:everycomp:db/minestuck/dead_palisade> : 1,
    <item:everycomp:db/minestuck/dead_seat> : 1,
    <item:everycomp:db/minestuck/dead_support> : 1,
    <item:everycomp:db/minestuck/doom_aspect_beam> : 1,
    <item:everycomp:db/minestuck/doom_aspect_palisade> : 1,
    <item:everycomp:db/minestuck/doom_aspect_seat> : 1,
    <item:everycomp:db/minestuck/doom_aspect_support> : 1,
    <item:everycomp:db/minestuck/end_beam> : 1,
    <item:everycomp:db/minestuck/end_palisade> : 1,
    <item:everycomp:db/minestuck/end_seat> : 1,
    <item:everycomp:db/minestuck/end_support> : 1,
    <item:everycomp:db/minestuck/frost_beam> : 1,
    <item:everycomp:db/minestuck/frost_palisade> : 1,
    <item:everycomp:db/minestuck/frost_seat> : 1,
    <item:everycomp:db/minestuck/frost_support> : 1,
    <item:everycomp:db/minestuck/glowing_beam> : 1,
    <item:everycomp:db/minestuck/glowing_palisade> : 1,
    <item:everycomp:db/minestuck/glowing_seat> : 1,
    <item:everycomp:db/minestuck/glowing_support> : 1,
    <item:everycomp:db/minestuck/heart_aspect_beam> : 1,
    <item:everycomp:db/minestuck/heart_aspect_palisade> : 1,
    <item:everycomp:db/minestuck/heart_aspect_seat> : 1,
    <item:everycomp:db/minestuck/heart_aspect_support> : 1,
    <item:everycomp:db/minestuck/hope_aspect_beam> : 1,
    <item:everycomp:db/minestuck/hope_aspect_palisade> : 1,
    <item:everycomp:db/minestuck/hope_aspect_seat> : 1,
    <item:everycomp:db/minestuck/hope_aspect_support> : 1,
    <item:everycomp:db/minestuck/life_aspect_beam> : 1,
    <item:everycomp:db/minestuck/life_aspect_palisade> : 1,
    <item:everycomp:db/minestuck/life_aspect_seat> : 1,
    <item:everycomp:db/minestuck/life_aspect_support> : 1,
    <item:everycomp:db/minestuck/light_aspect_beam> : 1,
    <item:everycomp:db/minestuck/light_aspect_palisade> : 1,
    <item:everycomp:db/minestuck/light_aspect_seat> : 1,
    <item:everycomp:db/minestuck/light_aspect_support> : 1,
    <item:everycomp:db/minestuck/mind_aspect_beam> : 1,
    <item:everycomp:db/minestuck/mind_aspect_palisade> : 1,
    <item:everycomp:db/minestuck/mind_aspect_seat> : 1,
    <item:everycomp:db/minestuck/mind_aspect_support> : 1,
    <item:everycomp:db/minestuck/rage_aspect_beam> : 1,
    <item:everycomp:db/minestuck/rage_aspect_palisade> : 1,
    <item:everycomp:db/minestuck/rage_aspect_seat> : 1,
    <item:everycomp:db/minestuck/rage_aspect_support> : 1,
    <item:everycomp:db/minestuck/rainbow_beam> : 1,
    <item:everycomp:db/minestuck/rainbow_palisade> : 1,
    <item:everycomp:db/minestuck/rainbow_seat> : 1,
    <item:everycomp:db/minestuck/rainbow_support> : 1,
    <item:everycomp:db/minestuck/space_aspect_beam> : 1,
    <item:everycomp:db/minestuck/space_aspect_palisade> : 1,
    <item:everycomp:db/minestuck/space_aspect_seat> : 1,
    <item:everycomp:db/minestuck/space_aspect_support> : 1,
    <item:everycomp:db/minestuck/time_aspect_beam> : 1,
    <item:everycomp:db/minestuck/time_aspect_palisade> : 1,
    <item:everycomp:db/minestuck/time_aspect_seat> : 1,
    <item:everycomp:db/minestuck/time_aspect_support> : 1,
    <item:everycomp:db/minestuck/void_aspect_beam> : 1,
    <item:everycomp:db/minestuck/void_aspect_palisade> : 1,
    <item:everycomp:db/minestuck/void_aspect_seat> : 1,
    <item:everycomp:db/minestuck/void_aspect_support> : 1,
    <item:everycomp:db/quark/azalea_beam> : 1,
    <item:everycomp:db/quark/azalea_palisade> : 1,
    <item:everycomp:db/quark/azalea_seat> : 1,
    <item:everycomp:db/quark/azalea_support> : 1,
    <item:everycomp:db/quark/blossom_beam> : 1,
    <item:everycomp:db/quark/blossom_palisade> : 1,
    <item:everycomp:db/quark/blossom_seat> : 1,
    <item:everycomp:db/quark/blossom_support> : 1,
    <item:everycomp:db/the_vault/chromatic_beam> : 1,
    <item:everycomp:db/the_vault/chromatic_palisade> : 1,
    <item:everycomp:db/the_vault/chromatic_seat> : 1,
    <item:everycomp:db/the_vault/chromatic_support> : 1,
    <item:everycomp:db/the_vault/tenos_beam> : 1,
    <item:everycomp:db/the_vault/tenos_palisade> : 1,
    <item:everycomp:db/the_vault/tenos_seat> : 1,
    <item:everycomp:db/the_vault/tenos_support> : 1,
    <item:everycomp:db/the_vault/velara_beam> : 1,
    <item:everycomp:db/the_vault/velara_palisade> : 1,
    <item:everycomp:db/the_vault/velara_seat> : 1,
    <item:everycomp:db/the_vault/velara_support> : 1,
    <item:everycomp:db/tropicraft/mahogany_beam> : 1,
    <item:everycomp:db/tropicraft/mahogany_palisade> : 1,
    <item:everycomp:db/tropicraft/mahogany_seat> : 1,
    <item:everycomp:db/tropicraft/mahogany_support> : 1,
    <item:everycomp:db/tropicraft/palm_beam> : 1,
    <item:everycomp:db/tropicraft/palm_palisade> : 1,
    <item:everycomp:db/tropicraft/palm_seat> : 1,
    <item:everycomp:db/tropicraft/palm_support> : 1,
    <item:everycomp:db/twigs/bamboo_beam> : 1,
    <item:everycomp:db/twigs/bamboo_palisade> : 1,
    <item:everycomp:db/twigs/bamboo_seat> : 1,
    <item:everycomp:db/twigs/bamboo_support> : 1,
    <item:everycomp:fd/architects_palette/twisted_cabinet> : 10,
    <item:everycomp:fd/botania/livingwood_cabinet> : 10,
    <item:everycomp:fd/createdieselgenerators/chip_wood_cabinet> : 1,
    <item:everycomp:fd/ecologics/azalea_cabinet> : 1,
    <item:everycomp:fd/ecologics/coconut_cabinet> : 1,
    <item:everycomp:fd/ecologics/flowering_azalea_cabinet> : 1,
    <item:everycomp:fd/ecologics/walnut_cabinet> : 1,
    <item:everycomp:fd/hexcasting/akashic_cabinet> : 1,
    <item:everycomp:fd/integrateddynamics/menril_cabinet> : 1,
    <item:everycomp:fd/luphieclutteredmod/luphie_flowering_pink_cabinet> : 1,
    <item:everycomp:fd/luphieclutteredmod/luphie_flowering_purple_cabinet> : 1,
    <item:everycomp:fd/luphieclutteredmod/luphie_flowering_yellow_cabinet> : 1,
    <item:everycomp:fd/luphieclutteredmod/luphie_glow_cabinet> : 1,
    <item:everycomp:fd/luphieclutteredmod/luphie_green_cabinet> : 1,
    <item:everycomp:fd/luphieclutteredmod/luphie_purple_cabinet> : 1,
    <item:everycomp:fd/minestuck/blood_aspect_cabinet> : 1,
    <item:everycomp:fd/minestuck/breath_aspect_cabinet> : 1,
    <item:everycomp:fd/minestuck/dead_cabinet> : 1,
    <item:everycomp:fd/minestuck/doom_aspect_cabinet> : 1,
    <item:everycomp:fd/minestuck/end_cabinet> : 1,
    <item:everycomp:fd/minestuck/frost_cabinet> : 1,
    <item:everycomp:fd/minestuck/glowing_cabinet> : 1,
    <item:everycomp:fd/minestuck/heart_aspect_cabinet> : 1,
    <item:everycomp:fd/minestuck/hope_aspect_cabinet> : 1,
    <item:everycomp:fd/minestuck/life_aspect_cabinet> : 1,
    <item:everycomp:fd/minestuck/light_aspect_cabinet> : 1,
    <item:everycomp:fd/minestuck/mind_aspect_cabinet> : 1,
    <item:everycomp:fd/minestuck/rage_aspect_cabinet> : 1,
    <item:everycomp:fd/minestuck/rainbow_cabinet> : 1,
    <item:everycomp:fd/minestuck/space_aspect_cabinet> : 1,
    <item:everycomp:fd/minestuck/time_aspect_cabinet> : 1,
    <item:everycomp:fd/minestuck/void_aspect_cabinet> : 1,
    <item:everycomp:fd/quark/azalea_cabinet> : 1,
    <item:everycomp:fd/quark/blossom_cabinet> : 1,
    <item:everycomp:fd/the_vault/chromatic_cabinet> : 1,
    <item:everycomp:fd/the_vault/tenos_cabinet> : 1,
    <item:everycomp:fd/the_vault/velara_cabinet> : 1,
    <item:everycomp:fd/tropicraft/mahogany_cabinet> : 1,
    <item:everycomp:fd/tropicraft/palm_cabinet> : 1,
    <item:everycomp:fd/twigs/bamboo_cabinet> : 1,
    <item:everycomp:mcb/architects_palette/rope_twisted_bridge> : 1,
    <item:everycomp:mcb/architects_palette/twisted_bridge_pier> : 1,
    <item:everycomp:mcb/architects_palette/twisted_log_bridge_middle> : 1,
    <item:everycomp:mcb/architects_palette/twisted_log_bridge_stair> : 1,
    <item:everycomp:mcb/architects_palette/twisted_rail_bridge> : 1,
    <item:everycomp:mcb/architects_palette/twisted_rope_bridge_stair> : 1,
    <item:everycomp:mcb/botania/livingwood_bridge_pier> : 1,
    <item:everycomp:mcb/botania/livingwood_log_bridge_middle> : 1,
    <item:everycomp:mcb/botania/livingwood_log_bridge_stair> : 1,
    <item:everycomp:mcb/botania/livingwood_rail_bridge> : 1,
    <item:everycomp:mcb/botania/livingwood_rope_bridge_stair> : 1,
    <item:everycomp:mcb/botania/rope_livingwood_bridge> : 1,
    <item:everycomp:mcb/createdieselgenerators/chip_wood_bridge_pier> : 1,
    <item:everycomp:mcb/createdieselgenerators/chip_wood_log_bridge_middle> : 1,
    <item:everycomp:mcb/createdieselgenerators/chip_wood_log_bridge_stair> : 1,
    <item:everycomp:mcb/createdieselgenerators/chip_wood_rail_bridge> : 1,
    <item:everycomp:mcb/createdieselgenerators/chip_wood_rope_bridge_stair> : 1,
    <item:everycomp:mcb/createdieselgenerators/rope_chip_wood_bridge> : 1,
    <item:everycomp:mcb/ecologics/azalea_bridge_pier> : 1,
    <item:everycomp:mcb/ecologics/azalea_log_bridge_middle> : 1,
    <item:everycomp:mcb/ecologics/azalea_log_bridge_stair> : 1,
    <item:everycomp:mcb/ecologics/azalea_rail_bridge> : 1,
    <item:everycomp:mcb/ecologics/azalea_rope_bridge_stair> : 1,
    <item:everycomp:mcb/ecologics/coconut_bridge_pier> : 1,
    <item:everycomp:mcb/ecologics/coconut_log_bridge_middle> : 1,
    <item:everycomp:mcb/ecologics/coconut_log_bridge_stair> : 1,
    <item:everycomp:mcb/ecologics/coconut_rail_bridge> : 1,
    <item:everycomp:mcb/ecologics/coconut_rope_bridge_stair> : 1,
    <item:everycomp:mcb/ecologics/flowering_azalea_bridge_pier> : 1,
    <item:everycomp:mcb/ecologics/flowering_azalea_log_bridge_middle> : 1,
    <item:everycomp:mcb/ecologics/flowering_azalea_log_bridge_stair> : 1,
    <item:everycomp:mcb/ecologics/flowering_azalea_rail_bridge> : 1,
    <item:everycomp:mcb/ecologics/flowering_azalea_rope_bridge_stair> : 1,
    <item:everycomp:mcb/ecologics/rope_azalea_bridge> : 1,
    <item:everycomp:mcb/ecologics/rope_coconut_bridge> : 1,
    <item:everycomp:mcb/ecologics/rope_flowering_azalea_bridge> : 1,
    <item:everycomp:mcb/ecologics/rope_walnut_bridge> : 1,
    <item:everycomp:mcb/ecologics/walnut_bridge_pier> : 1,
    <item:everycomp:mcb/ecologics/walnut_log_bridge_middle> : 1,
    <item:everycomp:mcb/ecologics/walnut_log_bridge_stair> : 1,
    <item:everycomp:mcb/ecologics/walnut_rail_bridge> : 1,
    <item:everycomp:mcb/ecologics/walnut_rope_bridge_stair> : 1,
    <item:everycomp:mcb/hexcasting/akashic_bridge_pier> : 1,
    <item:everycomp:mcb/hexcasting/akashic_log_bridge_middle> : 1,
    <item:everycomp:mcb/hexcasting/akashic_log_bridge_stair> : 1,
    <item:everycomp:mcb/hexcasting/akashic_rail_bridge> : 1,
    <item:everycomp:mcb/hexcasting/akashic_rope_bridge_stair> : 1,
    <item:everycomp:mcb/hexcasting/rope_akashic_bridge> : 1,
    <item:everycomp:mcb/integrateddynamics/menril_bridge_pier> : 1,
    <item:everycomp:mcb/integrateddynamics/menril_log_bridge_middle> : 1,
    <item:everycomp:mcb/integrateddynamics/menril_log_bridge_stair> : 1,
    <item:everycomp:mcb/integrateddynamics/menril_rail_bridge> : 1,
    <item:everycomp:mcb/integrateddynamics/menril_rope_bridge_stair> : 1,
    <item:everycomp:mcb/integrateddynamics/rope_menril_bridge> : 1,
    <item:everycomp:mcb/luphieclutteredmod/luphie_flowering_pink_bridge_pier> : 1,
    <item:everycomp:mcb/luphieclutteredmod/luphie_flowering_pink_log_bridge_middle> : 1,
    <item:everycomp:mcb/luphieclutteredmod/luphie_flowering_pink_log_bridge_stair> : 1,
    <item:everycomp:mcb/luphieclutteredmod/luphie_flowering_pink_rail_bridge> : 1,
    <item:everycomp:mcb/luphieclutteredmod/luphie_flowering_pink_rope_bridge_stair> : 1,
    <item:everycomp:mcb/luphieclutteredmod/luphie_flowering_purple_bridge_pier> : 1,
    <item:everycomp:mcb/luphieclutteredmod/luphie_flowering_purple_log_bridge_middle> : 1,
    <item:everycomp:mcb/luphieclutteredmod/luphie_flowering_purple_log_bridge_stair> : 1,
    <item:everycomp:mcb/luphieclutteredmod/luphie_flowering_purple_rail_bridge> : 1,
    <item:everycomp:mcb/luphieclutteredmod/luphie_flowering_purple_rope_bridge_stair> : 1,
    <item:everycomp:mcb/luphieclutteredmod/luphie_flowering_yellow_bridge_pier> : 1,
    <item:everycomp:mcb/luphieclutteredmod/luphie_flowering_yellow_log_bridge_middle> : 1,
    <item:everycomp:mcb/luphieclutteredmod/luphie_flowering_yellow_log_bridge_stair> : 1,
    <item:everycomp:mcb/luphieclutteredmod/luphie_flowering_yellow_rail_bridge> : 1,
    <item:everycomp:mcb/luphieclutteredmod/luphie_flowering_yellow_rope_bridge_stair> : 1,
    <item:everycomp:mcb/luphieclutteredmod/luphie_glow_bridge_pier> : 1,
    <item:everycomp:mcb/luphieclutteredmod/luphie_glow_log_bridge_middle> : 1,
    <item:everycomp:mcb/luphieclutteredmod/luphie_glow_log_bridge_stair> : 1,
    <item:everycomp:mcb/luphieclutteredmod/luphie_glow_rail_bridge> : 1,
    <item:everycomp:mcb/luphieclutteredmod/luphie_glow_rope_bridge_stair> : 1,
    <item:everycomp:mcb/luphieclutteredmod/luphie_green_bridge_pier> : 1,
    <item:everycomp:mcb/luphieclutteredmod/luphie_green_log_bridge_middle> : 1,
    <item:everycomp:mcb/luphieclutteredmod/luphie_green_log_bridge_stair> : 1,
    <item:everycomp:mcb/luphieclutteredmod/luphie_green_rail_bridge> : 1,
    <item:everycomp:mcb/luphieclutteredmod/luphie_green_rope_bridge_stair> : 1,
    <item:everycomp:mcb/luphieclutteredmod/luphie_pink_bridge_pier> : 1,
    <item:everycomp:mcb/luphieclutteredmod/luphie_pink_log_bridge_middle> : 1,
    <item:everycomp:mcb/luphieclutteredmod/luphie_pink_log_bridge_stair> : 1,
    <item:everycomp:mcb/luphieclutteredmod/luphie_pink_rail_bridge> : 1,
    <item:everycomp:mcb/luphieclutteredmod/luphie_pink_rope_bridge_stair> : 1,
    <item:everycomp:mcb/luphieclutteredmod/luphie_purple_bridge_pier> : 1,
    <item:everycomp:mcb/luphieclutteredmod/luphie_purple_log_bridge_middle> : 1,
    <item:everycomp:mcb/luphieclutteredmod/luphie_purple_log_bridge_stair> : 1,
    <item:everycomp:mcb/luphieclutteredmod/luphie_purple_rail_bridge> : 1,
    <item:everycomp:mcb/luphieclutteredmod/luphie_purple_rope_bridge_stair> : 1,
    <item:everycomp:mcb/luphieclutteredmod/luphie_yellow_bridge_pier> : 1,
    <item:everycomp:mcb/luphieclutteredmod/luphie_yellow_log_bridge_middle> : 1,
    <item:everycomp:mcb/luphieclutteredmod/luphie_yellow_log_bridge_stair> : 1,
    <item:everycomp:mcb/luphieclutteredmod/luphie_yellow_rail_bridge> : 1,
    <item:everycomp:mcb/luphieclutteredmod/luphie_yellow_rope_bridge_stair> : 1,
    <item:everycomp:mcb/luphieclutteredmod/rope_luphie_flowering_pink_bridge> : 1,
    <item:everycomp:mcb/luphieclutteredmod/rope_luphie_flowering_purple_bridge> : 1,
    <item:everycomp:mcb/luphieclutteredmod/rope_luphie_flowering_yellow_bridge> : 1,
    <item:everycomp:mcb/luphieclutteredmod/rope_luphie_glow_bridge> : 1,
    <item:everycomp:mcb/luphieclutteredmod/rope_luphie_green_bridge> : 1,
    <item:everycomp:mcb/luphieclutteredmod/rope_luphie_pink_bridge> : 1,
    <item:everycomp:mcb/luphieclutteredmod/rope_luphie_purple_bridge> : 1,
    <item:everycomp:mcb/luphieclutteredmod/rope_luphie_yellow_bridge> : 1,
    <item:everycomp:mcb/minestuck/blood_aspect_bridge_pier> : 1,
    <item:everycomp:mcb/minestuck/blood_aspect_log_bridge_middle> : 1,
    <item:everycomp:mcb/minestuck/blood_aspect_log_bridge_stair> : 1,
    <item:everycomp:mcb/minestuck/blood_aspect_rail_bridge> : 1,
    <item:everycomp:mcb/minestuck/blood_aspect_rope_bridge_stair> : 1,
    <item:everycomp:mcb/minestuck/breath_aspect_bridge_pier> : 1,
    <item:everycomp:mcb/minestuck/breath_aspect_log_bridge_middle> : 1,
    <item:everycomp:mcb/minestuck/breath_aspect_log_bridge_stair> : 1,
    <item:everycomp:mcb/minestuck/breath_aspect_rail_bridge> : 1,
    <item:everycomp:mcb/minestuck/breath_aspect_rope_bridge_stair> : 1,
    <item:everycomp:mcb/minestuck/dead_bridge_pier> : 1,
    <item:everycomp:mcb/minestuck/dead_log_bridge_middle> : 1,
    <item:everycomp:mcb/minestuck/dead_log_bridge_stair> : 1,
    <item:everycomp:mcb/minestuck/dead_rail_bridge> : 1,
    <item:everycomp:mcb/minestuck/dead_rope_bridge_stair> : 1,
    <item:everycomp:mcb/minestuck/doom_aspect_bridge_pier> : 1,
    <item:everycomp:mcb/minestuck/doom_aspect_log_bridge_middle> : 1,
    <item:everycomp:mcb/minestuck/doom_aspect_log_bridge_stair> : 1,
    <item:everycomp:mcb/minestuck/doom_aspect_rail_bridge> : 1,
    <item:everycomp:mcb/minestuck/doom_aspect_rope_bridge_stair> : 1,
    <item:everycomp:mcb/minestuck/end_bridge_pier> : 1,
    <item:everycomp:mcb/minestuck/end_log_bridge_middle> : 1,
    <item:everycomp:mcb/minestuck/end_log_bridge_stair> : 1,
    <item:everycomp:mcb/minestuck/end_rail_bridge> : 1,
    <item:everycomp:mcb/minestuck/end_rope_bridge_stair> : 1,
    <item:everycomp:mcb/minestuck/frost_bridge_pier> : 1,
    <item:everycomp:mcb/minestuck/frost_log_bridge_middle> : 1,
    <item:everycomp:mcb/minestuck/frost_log_bridge_stair> : 1,
    <item:everycomp:mcb/minestuck/frost_rail_bridge> : 1,
    <item:everycomp:mcb/minestuck/frost_rope_bridge_stair> : 1,
    <item:everycomp:mcb/minestuck/glowing_bridge_pier> : 1,
    <item:everycomp:mcb/minestuck/glowing_log_bridge_middle> : 1,
    <item:everycomp:mcb/minestuck/glowing_log_bridge_stair> : 1,
    <item:everycomp:mcb/minestuck/glowing_rail_bridge> : 1,
    <item:everycomp:mcb/minestuck/glowing_rope_bridge_stair> : 1,
    <item:everycomp:mcb/minestuck/heart_aspect_bridge_pier> : 1,
    <item:everycomp:mcb/minestuck/heart_aspect_log_bridge_middle> : 1,
    <item:everycomp:mcb/minestuck/heart_aspect_log_bridge_stair> : 1,
    <item:everycomp:mcb/minestuck/heart_aspect_rail_bridge> : 1,
    <item:everycomp:mcb/minestuck/heart_aspect_rope_bridge_stair> : 1,
    <item:everycomp:mcb/minestuck/hope_aspect_bridge_pier> : 1,
    <item:everycomp:mcb/minestuck/hope_aspect_log_bridge_middle> : 1,
    <item:everycomp:mcb/minestuck/hope_aspect_log_bridge_stair> : 1,
    <item:everycomp:mcb/minestuck/hope_aspect_rail_bridge> : 1,
    <item:everycomp:mcb/minestuck/hope_aspect_rope_bridge_stair> : 1,
    <item:everycomp:mcb/minestuck/life_aspect_bridge_pier> : 1,
    <item:everycomp:mcb/minestuck/life_aspect_log_bridge_middle> : 1,
    <item:everycomp:mcb/minestuck/life_aspect_log_bridge_stair> : 1,
    <item:everycomp:mcb/minestuck/life_aspect_rail_bridge> : 1,
    <item:everycomp:mcb/minestuck/life_aspect_rope_bridge_stair> : 1,
    <item:everycomp:mcb/minestuck/light_aspect_bridge_pier> : 1,
    <item:everycomp:mcb/minestuck/light_aspect_log_bridge_middle> : 1,
    <item:everycomp:mcb/minestuck/light_aspect_log_bridge_stair> : 1,
    <item:everycomp:mcb/minestuck/light_aspect_rail_bridge> : 1,
    <item:everycomp:mcb/minestuck/light_aspect_rope_bridge_stair> : 1,
    <item:everycomp:mcb/minestuck/mind_aspect_bridge_pier> : 1,
    <item:everycomp:mcb/minestuck/mind_aspect_log_bridge_middle> : 1,
    <item:everycomp:mcb/minestuck/mind_aspect_log_bridge_stair> : 1,
    <item:everycomp:mcb/minestuck/mind_aspect_rail_bridge> : 1,
    <item:everycomp:mcb/minestuck/mind_aspect_rope_bridge_stair> : 1,
    <item:everycomp:mcb/minestuck/rage_aspect_bridge_pier> : 1,
    <item:everycomp:mcb/minestuck/rage_aspect_log_bridge_middle> : 1,
    <item:everycomp:mcb/minestuck/rage_aspect_log_bridge_stair> : 1,
    <item:everycomp:mcb/minestuck/rage_aspect_rail_bridge> : 1,
    <item:everycomp:mcb/minestuck/rage_aspect_rope_bridge_stair> : 1,
    <item:everycomp:mcb/minestuck/rainbow_bridge_pier> : 1,
    <item:everycomp:mcb/minestuck/rainbow_log_bridge_middle> : 1,
    <item:everycomp:mcb/minestuck/rainbow_log_bridge_stair> : 1,
    <item:everycomp:mcb/minestuck/rainbow_rail_bridge> : 1,
    <item:everycomp:mcb/minestuck/rainbow_rope_bridge_stair> : 1,
    <item:everycomp:mcb/minestuck/rope_blood_aspect_bridge> : 1,
    <item:everycomp:mcb/minestuck/rope_breath_aspect_bridge> : 1,
    <item:everycomp:mcb/minestuck/rope_dead_bridge> : 1,
    <item:everycomp:mcb/minestuck/rope_doom_aspect_bridge> : 1,
    <item:everycomp:mcb/minestuck/rope_end_bridge> : 1,
    <item:everycomp:mcb/minestuck/rope_frost_bridge> : 1,
    <item:everycomp:mcb/minestuck/rope_glowing_bridge> : 1,
    <item:everycomp:mcb/minestuck/rope_heart_aspect_bridge> : 1,
    <item:everycomp:mcb/minestuck/rope_hope_aspect_bridge> : 1,
    <item:everycomp:mcb/minestuck/rope_life_aspect_bridge> : 1,
    <item:everycomp:mcb/minestuck/rope_light_aspect_bridge> : 1,
    <item:everycomp:mcb/minestuck/rope_mind_aspect_bridge> : 1,
    <item:everycomp:mcb/minestuck/rope_rage_aspect_bridge> : 1,
    <item:everycomp:mcb/minestuck/rope_rainbow_bridge> : 1,
    <item:everycomp:mcb/minestuck/rope_space_aspect_bridge> : 1,
    <item:everycomp:mcb/minestuck/rope_time_aspect_bridge> : 1,
    <item:everycomp:mcb/minestuck/rope_void_aspect_bridge> : 1,
    <item:everycomp:mcb/minestuck/space_aspect_bridge_pier> : 1,
    <item:everycomp:mcb/minestuck/space_aspect_log_bridge_middle> : 1,
    <item:everycomp:mcb/minestuck/space_aspect_log_bridge_stair> : 1,
    <item:everycomp:mcb/minestuck/space_aspect_rail_bridge> : 1,
    <item:everycomp:mcb/minestuck/space_aspect_rope_bridge_stair> : 1,
    <item:everycomp:mcb/minestuck/time_aspect_bridge_pier> : 1,
    <item:everycomp:mcb/minestuck/time_aspect_log_bridge_middle> : 1,
    <item:everycomp:mcb/minestuck/time_aspect_log_bridge_stair> : 1,
    <item:everycomp:mcb/minestuck/time_aspect_rail_bridge> : 1,
    <item:everycomp:mcb/minestuck/time_aspect_rope_bridge_stair> : 1,
    <item:everycomp:mcb/minestuck/void_aspect_bridge_pier> : 1,
    <item:everycomp:mcb/minestuck/void_aspect_log_bridge_middle> : 1,
    <item:everycomp:mcb/minestuck/void_aspect_log_bridge_stair> : 1,
    <item:everycomp:mcb/minestuck/void_aspect_rail_bridge> : 1,
    <item:everycomp:mcb/minestuck/void_aspect_rope_bridge_stair> : 1,
    <item:everycomp:mcb/quark/azalea_bridge_pier> : 1,
    <item:everycomp:mcb/quark/azalea_log_bridge_middle> : 1,
    <item:everycomp:mcb/quark/azalea_log_bridge_stair> : 1,
    <item:everycomp:mcb/quark/azalea_rail_bridge> : 1,
    <item:everycomp:mcb/quark/azalea_rope_bridge_stair> : 1,
    <item:everycomp:mcb/quark/blossom_bridge_pier> : 1,
    <item:everycomp:mcb/quark/blossom_log_bridge_middle> : 1,
    <item:everycomp:mcb/quark/blossom_log_bridge_stair> : 1,
    <item:everycomp:mcb/quark/blossom_rail_bridge> : 1,
    <item:everycomp:mcb/quark/blossom_rope_bridge_stair> : 1,
    <item:everycomp:mcb/quark/rope_azalea_bridge> : 1,
    <item:everycomp:mcb/quark/rope_blossom_bridge> : 1
};

// For each item in the map, check if we're in release mode. If we are, anything below 26 EMC/FMC becomes unburnable for EMC
for item, value in priceTable {
    if (ReleaseMode.releaseMode == true){
        if (value < 26 ) {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), 0);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        } else {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        }
        if (value > 999 && value < 10001) {
            <tag:items:tfb2:fop_miniscule>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Miniscule");
            });
        }
        if (value > 10000 && value < 25001) {
            <tag:items:tfb2:fop_small>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Small");
            });
        }
        if (value > 25000 && value < 75001) {
            <tag:items:tfb2:fop_medium>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Medium");
            });
        }
        if (value > 75000) {
            <tag:items:tfb2:fop_large>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Large");
            });
        }
    } else {
        CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
        <tag:items:projectextended:blacklist_condenser>.add(item);
        <tag:items:projectextended:blacklist_learning>.add(item);
    }
        if (value > 10000 && value < 25001) {
            <tag:items:tfb2:fop_small>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Small");
            });
        }
        if (value > 25000 && value < 75001) {
            <tag:items:tfb2:fop_medium>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Medium");
            });
        }
        if (value > 75000) {
            <tag:items:tfb2:fop_large>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Large");
            });
        }
}