import crafttweaker.api.tag.MCTag;
import crafttweaker.api.item.IItemStack;
import crafttweaker.api.ingredient.IIngredient;
import crafttweaker.api.item.tooltip.ITooltipFunction;
import stdlib.List;
import mods.projecte.CustomEMC;
import mods.projecte.NSSResolver;

// Item  to EMC/FMC value map.
val priceTable as int[IItemStack] = {
    <item:farmersdelight:netherite_knife> : 7850,
    <item:farmersdelight:crimson_cabinet> : 10,
    <item:farmersdelight:diamond_knife> : 1800,
    <item:farmersdelight:golden_knife> : 700,
    <item:farmersdelight:horse_feed> : 650,
    <item:farmersdelight:warped_cabinet> : 10,
    <item:farmersdelight:acacia_cabinet> : 10,
    <item:farmersdelight:apple_cider> : 10,
    <item:farmersdelight:apple_pie> : 50,
    <item:farmersdelight:apple_pie_slice> : 10,
    <item:farmersdelight:bacon> : 10,
    <item:farmersdelight:bacon_and_eggs> : 75,
    <item:farmersdelight:bacon_sandwich> : 25,
    <item:farmersdelight:baked_cod_stew> : 50,
    <item:farmersdelight:barbecue_stick> : 25,
    <item:farmersdelight:basket> : 25,
    <item:farmersdelight:beef_patty> : 10,
    <item:farmersdelight:beef_stew> : 25,
    <item:farmersdelight:beetroot_crate> : 50,
    <item:farmersdelight:birch_cabinet> : 10,
    <item:farmersdelight:black_canvas_sign> : 5,
    <item:farmersdelight:blue_canvas_sign> : 5,
    <item:farmersdelight:bone_broth> : 25,
    <item:farmersdelight:brown_canvas_sign> : 5,
    <item:farmersdelight:brown_mushroom_colony> : 5,
    <item:farmersdelight:cabbage> : 5,
    <item:farmersdelight:cabbage_crate> : 50,
    <item:farmersdelight:cabbage_leaf> : 2,
    <item:farmersdelight:cabbage_rolls> : 10,
    <item:farmersdelight:cabbage_seeds> : 5,
    <item:farmersdelight:cake_slice> : 5,
    <item:farmersdelight:canvas> : 5,
    <item:farmersdelight:canvas_rug> : 2,
    <item:farmersdelight:canvas_sign> : 5,
    <item:farmersdelight:carrot_crate> : 50,
    <item:farmersdelight:chicken_cuts> : 10,
    <item:farmersdelight:chicken_sandwich> : 25,
    <item:farmersdelight:chicken_soup> : 25,
    <item:farmersdelight:chocolate_pie> : 50,
    <item:farmersdelight:chocolate_pie_slice> : 10,
    <item:farmersdelight:cod_roll> : 10,
    <item:farmersdelight:cod_slice> : 10,
    <item:farmersdelight:cooked_bacon> : 10,
    <item:farmersdelight:cooked_chicken_cuts> : 10,
    <item:farmersdelight:cooked_cod_slice> : 10,
    <item:farmersdelight:cooked_mutton_chops> : 10,
    <item:farmersdelight:cooked_rice> : 5,
    <item:farmersdelight:cooked_salmon_slice> : 10,
    <item:farmersdelight:cooking_pot> : 850,
    <item:farmersdelight:cutting_board> : 5,
    <item:farmersdelight:cyan_canvas_sign> : 5,
    <item:farmersdelight:dark_oak_cabinet> : 10,
    <item:farmersdelight:dog_food> : 50,
    <item:farmersdelight:dumplings> : 10,
    <item:farmersdelight:egg_sandwich> : 50,
    <item:farmersdelight:fish_stew> : 25,
    <item:farmersdelight:flint_knife> : 5,
    <item:farmersdelight:fried_egg> : 25,
    <item:farmersdelight:fried_rice> : 50,
    <item:farmersdelight:fruit_salad> : 25,
    <item:farmersdelight:full_tatami_mat> : 2,
    <item:farmersdelight:glow_berry_custard> : 25,
    <item:farmersdelight:gray_canvas_sign> : 5,
    <item:farmersdelight:green_canvas_sign> : 5,
    <item:farmersdelight:grilled_salmon> : 25,
    <item:farmersdelight:half_tatami_mat> : 1,
    <item:farmersdelight:ham> : 25,
    <item:farmersdelight:hamburger> : 25,
    <item:farmersdelight:honey_cookie> : 5,
    <item:farmersdelight:honey_glazed_ham> : 25,
    <item:farmersdelight:honey_glazed_ham_block> : 100,
    <item:farmersdelight:hot_cocoa> : 10,
    <item:farmersdelight:iron_knife> : 225,
    <item:farmersdelight:jungle_cabinet> : 10,
    <item:farmersdelight:kelp_roll> : 25,
    <item:farmersdelight:kelp_roll_slice> : 10,
    <item:farmersdelight:light_blue_canvas_sign> : 5,
    <item:farmersdelight:light_gray_canvas_sign> : 5,
    <item:farmersdelight:lime_canvas_sign> : 5,
    <item:farmersdelight:magenta_canvas_sign> : 5,
    <item:farmersdelight:melon_juice> : 25,
    <item:farmersdelight:melon_popsicle> : 25,
    <item:farmersdelight:milk_bottle> : 1,
    <item:farmersdelight:minced_beef> : 10,
    <item:farmersdelight:mixed_salad> : 25,
    <item:farmersdelight:mushroom_rice> : 25,
    <item:farmersdelight:mutton_chops> : 10,
    <item:farmersdelight:mutton_wrap> : 25,
    <item:farmersdelight:nether_salad> : 10,
    <item:farmersdelight:noodle_soup> : 50,
    <item:farmersdelight:oak_cabinet> : 10,
    <item:farmersdelight:onion> : 5,
    <item:farmersdelight:onion_crate> : 50,
    <item:farmersdelight:orange_canvas_sign> : 5,
    <item:farmersdelight:organic_compost> : 25,
    <item:farmersdelight:pasta_with_meatballs> : 25,
    <item:farmersdelight:pasta_with_mutton_chop> : 25,
    <item:farmersdelight:pie_crust> : 10,
    <item:farmersdelight:pink_canvas_sign> : 5,
    <item:farmersdelight:potato_crate> : 50,
    <item:farmersdelight:pumpkin_slice> : 5,
    <item:farmersdelight:pumpkin_soup> : 25,
    <item:farmersdelight:purple_canvas_sign> : 5,
    <item:farmersdelight:ratatouille> : 25,
    <item:farmersdelight:raw_pasta> : 5,
    <item:farmersdelight:red_canvas_sign> : 5,
    <item:farmersdelight:red_mushroom_colony> : 5,
    <item:farmersdelight:rice> : 5,
    <item:farmersdelight:rice_bag> : 50,
    <item:farmersdelight:rice_bale> : 50,
    <item:farmersdelight:rice_roll_medley_block> : 75,
    <item:farmersdelight:rich_soil> : 25,
    <item:farmersdelight:roast_chicken> : 10,
    <item:farmersdelight:roast_chicken_block> : 75,
    <item:farmersdelight:roasted_mutton_chops> : 25,
    <item:farmersdelight:rope> : 1,
    <item:farmersdelight:rotten_tomato> : 5,
    <item:farmersdelight:safety_net> : 5,
    <item:farmersdelight:salmon_roll> : 10,
    <item:farmersdelight:salmon_slice> : 10,
    <item:farmersdelight:sandy_shrub> : 5,
    <item:farmersdelight:shepherds_pie> : 10,
    <item:farmersdelight:shepherds_pie_block> : 50,
    <item:farmersdelight:skillet> : 925,
    <item:farmersdelight:smoked_ham> : 25,
    <item:farmersdelight:spruce_cabinet> : 10,
    <item:farmersdelight:squid_ink_pasta> : 50,
    <item:farmersdelight:steak_and_potatoes> : 50,
    <item:farmersdelight:stove> : 875,
    <item:farmersdelight:straw> : 1,
    <item:farmersdelight:straw_bale> : 10,
    <item:farmersdelight:stuffed_potato> : 10,
    <item:farmersdelight:stuffed_pumpkin> : 5,
    <item:farmersdelight:stuffed_pumpkin_block> : 25,
    <item:farmersdelight:sweet_berry_cheesecake> : 50,
    <item:farmersdelight:sweet_berry_cheesecake_slice> : 10,
    <item:farmersdelight:sweet_berry_cookie> : 2,
    <item:farmersdelight:tatami> : 5,
    <item:farmersdelight:tomato> : 5,
    <item:farmersdelight:tomato_crate> : 50,
    <item:farmersdelight:tomato_sauce> : 10,
    <item:farmersdelight:tomato_seeds> : 5,
    <item:farmersdelight:tree_bark> : 1,
    <item:farmersdelight:vegetable_noodles> : 25,
    <item:farmersdelight:vegetable_soup> : 25,
    <item:farmersdelight:wheat_dough> : 5,
    <item:farmersdelight:white_canvas_sign> : 5,
    <item:farmersdelight:wild_beetroots> : 5,
    <item:farmersdelight:wild_cabbages> : 5,
    <item:farmersdelight:wild_carrots> : 5,
    <item:farmersdelight:wild_onions> : 5,
    <item:farmersdelight:wild_potatoes> : 5,
    <item:farmersdelight:wild_rice> : 5,
    <item:farmersdelight:wild_tomatoes> : 5,
    <item:farmersdelight:yellow_canvas_sign> : 5
};

// For each item in the map, check if we're in release mode. If we are, anything below 26 EMC/FMC becomes unburnable for EMC
for item, value in priceTable {
    if (ReleaseMode.releaseMode == true){
        if (value < 26 ) {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), 0);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        } else {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        }
    } else {
        CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
        <tag:items:projectextended:blacklist_condenser>.add(item);
        <tag:items:projectextended:blacklist_learning>.add(item);
    }
}