import crafttweaker.api.text.TextComponent;
import crafttweaker.api.tag.MCTag;
import crafttweaker.api.item.IItemStack;
import crafttweaker.api.ingredient.IIngredient;
import crafttweaker.api.item.tooltip.ITooltipFunction;
import stdlib.List;
import mods.projecte.CustomEMC;
import mods.projecte.NSSResolver;

// Item  to EMC/FMC value map.
val priceTable as int[IItemStack] = {
    <item:mcwfurnitures:acacia_bookshelf> : 10,
    <item:mcwfurnitures:acacia_bookshelf_cupboard> : 10,
    <item:mcwfurnitures:acacia_bookshelf_drawer> : 10,
    <item:mcwfurnitures:acacia_chair> : 5,
    <item:mcwfurnitures:acacia_coffee_table> : 2,
    <item:mcwfurnitures:acacia_counter> : 2,
    <item:mcwfurnitures:acacia_covered_desk> : 5,
    <item:mcwfurnitures:acacia_cupboard_counter> : 10,
    <item:mcwfurnitures:acacia_desk> : 5,
    <item:mcwfurnitures:acacia_double_drawer> : 10,
    <item:mcwfurnitures:acacia_double_drawer_counter> : 25,
    <item:mcwfurnitures:acacia_double_wardrobe> : 25,
    <item:mcwfurnitures:acacia_drawer> : 10,
    <item:mcwfurnitures:acacia_drawer_counter> : 10,
    <item:mcwfurnitures:acacia_end_table> : 5,
    <item:mcwfurnitures:acacia_glass_table> : 5,
    <item:mcwfurnitures:acacia_large_drawer> : 10,
    <item:mcwfurnitures:acacia_lower_bookshelf_drawer> : 10,
    <item:mcwfurnitures:acacia_lower_triple_drawer> : 25,
    <item:mcwfurnitures:acacia_modern_chair> : 5,
    <item:mcwfurnitures:acacia_modern_desk> : 5,
    <item:mcwfurnitures:acacia_modern_wardrobe> : 10,
    <item:mcwfurnitures:acacia_stool_chair> : 5,
    <item:mcwfurnitures:acacia_striped_chair> : 5,
    <item:mcwfurnitures:acacia_table> : 5,
    <item:mcwfurnitures:acacia_triple_drawer> : 25,
    <item:mcwfurnitures:acacia_wardrobe> : 10,
    <item:mcwfurnitures:birch_bookshelf> : 10,
    <item:mcwfurnitures:birch_bookshelf_cupboard> : 10,
    <item:mcwfurnitures:birch_bookshelf_drawer> : 10,
    <item:mcwfurnitures:birch_chair> : 5,
    <item:mcwfurnitures:birch_coffee_table> : 2,
    <item:mcwfurnitures:birch_counter> : 2,
    <item:mcwfurnitures:birch_covered_desk> : 5,
    <item:mcwfurnitures:birch_cupboard_counter> : 10,
    <item:mcwfurnitures:birch_desk> : 5,
    <item:mcwfurnitures:birch_double_drawer> : 10,
    <item:mcwfurnitures:birch_double_drawer_counter> : 25,
    <item:mcwfurnitures:birch_double_wardrobe> : 25,
    <item:mcwfurnitures:birch_drawer> : 10,
    <item:mcwfurnitures:birch_drawer_counter> : 10,
    <item:mcwfurnitures:birch_end_table> : 5,
    <item:mcwfurnitures:birch_glass_table> : 5,
    <item:mcwfurnitures:birch_large_drawer> : 10,
    <item:mcwfurnitures:birch_lower_bookshelf_drawer> : 10,
    <item:mcwfurnitures:birch_lower_triple_drawer> : 25,
    <item:mcwfurnitures:birch_modern_chair> : 5,
    <item:mcwfurnitures:birch_modern_desk> : 5,
    <item:mcwfurnitures:birch_modern_wardrobe> : 10,
    <item:mcwfurnitures:birch_stool_chair> : 5,
    <item:mcwfurnitures:birch_striped_chair> : 5,
    <item:mcwfurnitures:birch_table> : 5,
    <item:mcwfurnitures:birch_triple_drawer> : 25,
    <item:mcwfurnitures:birch_wardrobe> : 10,
    <item:mcwfurnitures:cabinet_door> : 25,
    <item:mcwfurnitures:cabinet_drawer> : 25,
    <item:mcwfurnitures:crimson_bookshelf> : 10,
    <item:mcwfurnitures:crimson_bookshelf_cupboard> : 10,
    <item:mcwfurnitures:crimson_bookshelf_drawer> : 10,
    <item:mcwfurnitures:crimson_chair> : 5,
    <item:mcwfurnitures:crimson_coffee_table> : 2,
    <item:mcwfurnitures:crimson_counter> : 2,
    <item:mcwfurnitures:crimson_covered_desk> : 5,
    <item:mcwfurnitures:crimson_cupboard_counter> : 10,
    <item:mcwfurnitures:crimson_desk> : 5,
    <item:mcwfurnitures:crimson_double_drawer> : 10,
    <item:mcwfurnitures:crimson_double_drawer_counter> : 25,
    <item:mcwfurnitures:crimson_double_wardrobe> : 25,
    <item:mcwfurnitures:crimson_drawer> : 10,
    <item:mcwfurnitures:crimson_drawer_counter> : 10,
    <item:mcwfurnitures:crimson_end_table> : 5,
    <item:mcwfurnitures:crimson_glass_table> : 5,
    <item:mcwfurnitures:crimson_large_drawer> : 10,
    <item:mcwfurnitures:crimson_lower_bookshelf_drawer> : 10,
    <item:mcwfurnitures:crimson_lower_triple_drawer> : 25,
    <item:mcwfurnitures:crimson_modern_chair> : 5,
    <item:mcwfurnitures:crimson_modern_desk> : 5,
    <item:mcwfurnitures:crimson_modern_wardrobe> : 10,
    <item:mcwfurnitures:crimson_stool_chair> : 5,
    <item:mcwfurnitures:crimson_striped_chair> : 5,
    <item:mcwfurnitures:crimson_table> : 5,
    <item:mcwfurnitures:crimson_triple_drawer> : 25,
    <item:mcwfurnitures:crimson_wardrobe> : 10,
    <item:mcwfurnitures:dark_oak_bookshelf> : 10,
    <item:mcwfurnitures:dark_oak_bookshelf_cupboard> : 10,
    <item:mcwfurnitures:dark_oak_bookshelf_drawer> : 10,
    <item:mcwfurnitures:dark_oak_chair> : 5,
    <item:mcwfurnitures:dark_oak_coffee_table> : 2,
    <item:mcwfurnitures:dark_oak_counter> : 2,
    <item:mcwfurnitures:dark_oak_covered_desk> : 5,
    <item:mcwfurnitures:dark_oak_cupboard_counter> : 10,
    <item:mcwfurnitures:dark_oak_desk> : 5,
    <item:mcwfurnitures:dark_oak_double_drawer> : 10,
    <item:mcwfurnitures:dark_oak_double_drawer_counter> : 25,
    <item:mcwfurnitures:dark_oak_double_wardrobe> : 25,
    <item:mcwfurnitures:dark_oak_drawer> : 10,
    <item:mcwfurnitures:dark_oak_drawer_counter> : 10,
    <item:mcwfurnitures:dark_oak_end_table> : 5,
    <item:mcwfurnitures:dark_oak_glass_table> : 5,
    <item:mcwfurnitures:dark_oak_large_drawer> : 10,
    <item:mcwfurnitures:dark_oak_lower_bookshelf_drawer> : 10,
    <item:mcwfurnitures:dark_oak_lower_triple_drawer> : 25,
    <item:mcwfurnitures:dark_oak_modern_chair> : 5,
    <item:mcwfurnitures:dark_oak_modern_desk> : 5,
    <item:mcwfurnitures:dark_oak_modern_wardrobe> : 10,
    <item:mcwfurnitures:dark_oak_stool_chair> : 5,
    <item:mcwfurnitures:dark_oak_striped_chair> : 5,
    <item:mcwfurnitures:dark_oak_table> : 5,
    <item:mcwfurnitures:dark_oak_triple_drawer> : 25,
    <item:mcwfurnitures:dark_oak_wardrobe> : 10,
    <item:mcwfurnitures:jungle_bookshelf> : 10,
    <item:mcwfurnitures:jungle_bookshelf_cupboard> : 10,
    <item:mcwfurnitures:jungle_bookshelf_drawer> : 10,
    <item:mcwfurnitures:jungle_chair> : 5,
    <item:mcwfurnitures:jungle_coffee_table> : 2,
    <item:mcwfurnitures:jungle_counter> : 2,
    <item:mcwfurnitures:jungle_covered_desk> : 5,
    <item:mcwfurnitures:jungle_cupboard_counter> : 10,
    <item:mcwfurnitures:jungle_desk> : 5,
    <item:mcwfurnitures:jungle_double_drawer> : 10,
    <item:mcwfurnitures:jungle_double_drawer_counter> : 25,
    <item:mcwfurnitures:jungle_double_wardrobe> : 25,
    <item:mcwfurnitures:jungle_drawer> : 10,
    <item:mcwfurnitures:jungle_drawer_counter> : 10,
    <item:mcwfurnitures:jungle_end_table> : 5,
    <item:mcwfurnitures:jungle_glass_table> : 5,
    <item:mcwfurnitures:jungle_large_drawer> : 10,
    <item:mcwfurnitures:jungle_lower_bookshelf_drawer> : 10,
    <item:mcwfurnitures:jungle_lower_triple_drawer> : 25,
    <item:mcwfurnitures:jungle_modern_chair> : 5,
    <item:mcwfurnitures:jungle_modern_desk> : 5,
    <item:mcwfurnitures:jungle_modern_wardrobe> : 10,
    <item:mcwfurnitures:jungle_stool_chair> : 5,
    <item:mcwfurnitures:jungle_striped_chair> : 5,
    <item:mcwfurnitures:jungle_table> : 5,
    <item:mcwfurnitures:jungle_triple_drawer> : 25,
    <item:mcwfurnitures:jungle_wardrobe> : 10,
    <item:mcwfurnitures:oak_bookshelf> : 10,
    <item:mcwfurnitures:oak_bookshelf_cupboard> : 10,
    <item:mcwfurnitures:oak_bookshelf_drawer> : 10,
    <item:mcwfurnitures:oak_chair> : 5,
    <item:mcwfurnitures:oak_coffee_table> : 2,
    <item:mcwfurnitures:oak_counter> : 2,
    <item:mcwfurnitures:oak_covered_desk> : 5,
    <item:mcwfurnitures:oak_cupboard_counter> : 10,
    <item:mcwfurnitures:oak_desk> : 5,
    <item:mcwfurnitures:oak_double_drawer> : 10,
    <item:mcwfurnitures:oak_double_drawer_counter> : 25,
    <item:mcwfurnitures:oak_double_wardrobe> : 25,
    <item:mcwfurnitures:oak_drawer> : 10,
    <item:mcwfurnitures:oak_drawer_counter> : 10,
    <item:mcwfurnitures:oak_end_table> : 5,
    <item:mcwfurnitures:oak_glass_table> : 5,
    <item:mcwfurnitures:oak_large_drawer> : 10,
    <item:mcwfurnitures:oak_lower_bookshelf_drawer> : 10,
    <item:mcwfurnitures:oak_lower_triple_drawer> : 25,
    <item:mcwfurnitures:oak_modern_chair> : 5,
    <item:mcwfurnitures:oak_modern_desk> : 5,
    <item:mcwfurnitures:oak_modern_wardrobe> : 10,
    <item:mcwfurnitures:oak_stool_chair> : 5,
    <item:mcwfurnitures:oak_striped_chair> : 5,
    <item:mcwfurnitures:oak_table> : 5,
    <item:mcwfurnitures:oak_triple_drawer> : 25,
    <item:mcwfurnitures:oak_wardrobe> : 10,
    <item:mcwfurnitures:spruce_bookshelf> : 10,
    <item:mcwfurnitures:spruce_bookshelf_cupboard> : 10,
    <item:mcwfurnitures:spruce_bookshelf_drawer> : 10,
    <item:mcwfurnitures:spruce_chair> : 5,
    <item:mcwfurnitures:spruce_coffee_table> : 2,
    <item:mcwfurnitures:spruce_counter> : 2,
    <item:mcwfurnitures:spruce_covered_desk> : 5,
    <item:mcwfurnitures:spruce_cupboard_counter> : 10,
    <item:mcwfurnitures:spruce_desk> : 5,
    <item:mcwfurnitures:spruce_double_drawer> : 10,
    <item:mcwfurnitures:spruce_double_drawer_counter> : 25,
    <item:mcwfurnitures:spruce_double_wardrobe> : 25,
    <item:mcwfurnitures:spruce_drawer> : 10,
    <item:mcwfurnitures:spruce_drawer_counter> : 10,
    <item:mcwfurnitures:spruce_end_table> : 5,
    <item:mcwfurnitures:spruce_glass_table> : 5,
    <item:mcwfurnitures:spruce_large_drawer> : 10,
    <item:mcwfurnitures:spruce_lower_bookshelf_drawer> : 10,
    <item:mcwfurnitures:spruce_lower_triple_drawer> : 25,
    <item:mcwfurnitures:spruce_modern_chair> : 5,
    <item:mcwfurnitures:spruce_modern_desk> : 5,
    <item:mcwfurnitures:spruce_modern_wardrobe> : 10,
    <item:mcwfurnitures:spruce_stool_chair> : 5,
    <item:mcwfurnitures:spruce_striped_chair> : 5,
    <item:mcwfurnitures:spruce_table> : 5,
    <item:mcwfurnitures:spruce_triple_drawer> : 25,
    <item:mcwfurnitures:spruce_wardrobe> : 10,
    <item:mcwfurnitures:stripped_acacia_bookshelf> : 10,
    <item:mcwfurnitures:stripped_acacia_bookshelf_cupboard> : 10,
    <item:mcwfurnitures:stripped_acacia_bookshelf_drawer> : 10,
    <item:mcwfurnitures:stripped_acacia_chair> : 5,
    <item:mcwfurnitures:stripped_acacia_coffee_table> : 2,
    <item:mcwfurnitures:stripped_acacia_counter> : 2,
    <item:mcwfurnitures:stripped_acacia_covered_desk> : 5,
    <item:mcwfurnitures:stripped_acacia_cupboard_counter> : 10,
    <item:mcwfurnitures:stripped_acacia_desk> : 5,
    <item:mcwfurnitures:stripped_acacia_double_drawer> : 10,
    <item:mcwfurnitures:stripped_acacia_double_drawer_counter> : 25,
    <item:mcwfurnitures:stripped_acacia_double_wardrobe> : 25,
    <item:mcwfurnitures:stripped_acacia_drawer> : 10,
    <item:mcwfurnitures:stripped_acacia_drawer_counter> : 10,
    <item:mcwfurnitures:stripped_acacia_end_table> : 5,
    <item:mcwfurnitures:stripped_acacia_glass_table> : 5,
    <item:mcwfurnitures:stripped_acacia_large_drawer> : 10,
    <item:mcwfurnitures:stripped_acacia_lower_bookshelf_drawer> : 10,
    <item:mcwfurnitures:stripped_acacia_lower_triple_drawer> : 25,
    <item:mcwfurnitures:stripped_acacia_modern_chair> : 5,
    <item:mcwfurnitures:stripped_acacia_modern_desk> : 5,
    <item:mcwfurnitures:stripped_acacia_modern_wardrobe> : 10,
    <item:mcwfurnitures:stripped_acacia_stool_chair> : 5,
    <item:mcwfurnitures:stripped_acacia_striped_chair> : 5,
    <item:mcwfurnitures:stripped_acacia_table> : 5,
    <item:mcwfurnitures:stripped_acacia_triple_drawer> : 25,
    <item:mcwfurnitures:stripped_acacia_wardrobe> : 10,
    <item:mcwfurnitures:stripped_birch_bookshelf> : 10,
    <item:mcwfurnitures:stripped_birch_bookshelf_cupboard> : 10,
    <item:mcwfurnitures:stripped_birch_bookshelf_drawer> : 10,
    <item:mcwfurnitures:stripped_birch_chair> : 5,
    <item:mcwfurnitures:stripped_birch_coffee_table> : 2,
    <item:mcwfurnitures:stripped_birch_counter> : 2,
    <item:mcwfurnitures:stripped_birch_covered_desk> : 5,
    <item:mcwfurnitures:stripped_birch_cupboard_counter> : 10,
    <item:mcwfurnitures:stripped_birch_desk> : 5,
    <item:mcwfurnitures:stripped_birch_double_drawer> : 10,
    <item:mcwfurnitures:stripped_birch_double_drawer_counter> : 25,
    <item:mcwfurnitures:stripped_birch_double_wardrobe> : 25,
    <item:mcwfurnitures:stripped_birch_drawer> : 10,
    <item:mcwfurnitures:stripped_birch_drawer_counter> : 10,
    <item:mcwfurnitures:stripped_birch_end_table> : 5,
    <item:mcwfurnitures:stripped_birch_glass_table> : 5,
    <item:mcwfurnitures:stripped_birch_large_drawer> : 10,
    <item:mcwfurnitures:stripped_birch_lower_bookshelf_drawer> : 10,
    <item:mcwfurnitures:stripped_birch_lower_triple_drawer> : 25,
    <item:mcwfurnitures:stripped_birch_modern_chair> : 5,
    <item:mcwfurnitures:stripped_birch_modern_desk> : 5,
    <item:mcwfurnitures:stripped_birch_modern_wardrobe> : 10,
    <item:mcwfurnitures:stripped_birch_stool_chair> : 5,
    <item:mcwfurnitures:stripped_birch_striped_chair> : 5,
    <item:mcwfurnitures:stripped_birch_table> : 5,
    <item:mcwfurnitures:stripped_birch_triple_drawer> : 25,
    <item:mcwfurnitures:stripped_birch_wardrobe> : 10,
    <item:mcwfurnitures:stripped_crimson_bookshelf> : 10,
    <item:mcwfurnitures:stripped_crimson_bookshelf_cupboard> : 10,
    <item:mcwfurnitures:stripped_crimson_bookshelf_drawer> : 10,
    <item:mcwfurnitures:stripped_crimson_chair> : 5,
    <item:mcwfurnitures:stripped_crimson_coffee_table> : 2,
    <item:mcwfurnitures:stripped_crimson_counter> : 2,
    <item:mcwfurnitures:stripped_crimson_covered_desk> : 5,
    <item:mcwfurnitures:stripped_crimson_cupboard_counter> : 10,
    <item:mcwfurnitures:stripped_crimson_desk> : 5,
    <item:mcwfurnitures:stripped_crimson_double_drawer> : 10,
    <item:mcwfurnitures:stripped_crimson_double_drawer_counter> : 25,
    <item:mcwfurnitures:stripped_crimson_double_wardrobe> : 25,
    <item:mcwfurnitures:stripped_crimson_drawer> : 10,
    <item:mcwfurnitures:stripped_crimson_drawer_counter> : 10,
    <item:mcwfurnitures:stripped_crimson_end_table> : 5,
    <item:mcwfurnitures:stripped_crimson_glass_table> : 5,
    <item:mcwfurnitures:stripped_crimson_large_drawer> : 10,
    <item:mcwfurnitures:stripped_crimson_lower_bookshelf_drawer> : 10,
    <item:mcwfurnitures:stripped_crimson_lower_triple_drawer> : 25,
    <item:mcwfurnitures:stripped_crimson_modern_chair> : 5,
    <item:mcwfurnitures:stripped_crimson_modern_desk> : 5,
    <item:mcwfurnitures:stripped_crimson_modern_wardrobe> : 10,
    <item:mcwfurnitures:stripped_crimson_stool_chair> : 5,
    <item:mcwfurnitures:stripped_crimson_striped_chair> : 5,
    <item:mcwfurnitures:stripped_crimson_table> : 5,
    <item:mcwfurnitures:stripped_crimson_triple_drawer> : 25,
    <item:mcwfurnitures:stripped_crimson_wardrobe> : 10,
    <item:mcwfurnitures:stripped_dark_oak_bookshelf> : 10,
    <item:mcwfurnitures:stripped_dark_oak_bookshelf_cupboard> : 10,
    <item:mcwfurnitures:stripped_dark_oak_bookshelf_drawer> : 10,
    <item:mcwfurnitures:stripped_dark_oak_chair> : 5,
    <item:mcwfurnitures:stripped_dark_oak_coffee_table> : 2,
    <item:mcwfurnitures:stripped_dark_oak_counter> : 2,
    <item:mcwfurnitures:stripped_dark_oak_covered_desk> : 5,
    <item:mcwfurnitures:stripped_dark_oak_cupboard_counter> : 10,
    <item:mcwfurnitures:stripped_dark_oak_desk> : 5,
    <item:mcwfurnitures:stripped_dark_oak_double_drawer> : 10,
    <item:mcwfurnitures:stripped_dark_oak_double_drawer_counter> : 25,
    <item:mcwfurnitures:stripped_dark_oak_double_wardrobe> : 25,
    <item:mcwfurnitures:stripped_dark_oak_drawer> : 10,
    <item:mcwfurnitures:stripped_dark_oak_drawer_counter> : 10,
    <item:mcwfurnitures:stripped_dark_oak_end_table> : 5,
    <item:mcwfurnitures:stripped_dark_oak_glass_table> : 5,
    <item:mcwfurnitures:stripped_dark_oak_large_drawer> : 10,
    <item:mcwfurnitures:stripped_dark_oak_lower_bookshelf_drawer> : 10,
    <item:mcwfurnitures:stripped_dark_oak_lower_triple_drawer> : 25,
    <item:mcwfurnitures:stripped_dark_oak_modern_chair> : 5,
    <item:mcwfurnitures:stripped_dark_oak_modern_desk> : 5,
    <item:mcwfurnitures:stripped_dark_oak_modern_wardrobe> : 10,
    <item:mcwfurnitures:stripped_dark_oak_stool_chair> : 5,
    <item:mcwfurnitures:stripped_dark_oak_striped_chair> : 5,
    <item:mcwfurnitures:stripped_dark_oak_table> : 5,
    <item:mcwfurnitures:stripped_dark_oak_triple_drawer> : 25,
    <item:mcwfurnitures:stripped_dark_oak_wardrobe> : 10,
    <item:mcwfurnitures:stripped_jungle_bookshelf> : 10,
    <item:mcwfurnitures:stripped_jungle_bookshelf_cupboard> : 10,
    <item:mcwfurnitures:stripped_jungle_bookshelf_drawer> : 10,
    <item:mcwfurnitures:stripped_jungle_chair> : 5,
    <item:mcwfurnitures:stripped_jungle_coffee_table> : 2,
    <item:mcwfurnitures:stripped_jungle_counter> : 2,
    <item:mcwfurnitures:stripped_jungle_covered_desk> : 5,
    <item:mcwfurnitures:stripped_jungle_cupboard_counter> : 10,
    <item:mcwfurnitures:stripped_jungle_desk> : 5,
    <item:mcwfurnitures:stripped_jungle_double_drawer> : 10,
    <item:mcwfurnitures:stripped_jungle_double_drawer_counter> : 25,
    <item:mcwfurnitures:stripped_jungle_double_wardrobe> : 25,
    <item:mcwfurnitures:stripped_jungle_drawer> : 10,
    <item:mcwfurnitures:stripped_jungle_drawer_counter> : 10,
    <item:mcwfurnitures:stripped_jungle_end_table> : 5,
    <item:mcwfurnitures:stripped_jungle_glass_table> : 5,
    <item:mcwfurnitures:stripped_jungle_large_drawer> : 10,
    <item:mcwfurnitures:stripped_jungle_lower_bookshelf_drawer> : 10,
    <item:mcwfurnitures:stripped_jungle_lower_triple_drawer> : 25,
    <item:mcwfurnitures:stripped_jungle_modern_chair> : 5,
    <item:mcwfurnitures:stripped_jungle_modern_desk> : 5,
    <item:mcwfurnitures:stripped_jungle_modern_wardrobe> : 10,
    <item:mcwfurnitures:stripped_jungle_stool_chair> : 5,
    <item:mcwfurnitures:stripped_jungle_striped_chair> : 5,
    <item:mcwfurnitures:stripped_jungle_table> : 5,
    <item:mcwfurnitures:stripped_jungle_triple_drawer> : 25,
    <item:mcwfurnitures:stripped_jungle_wardrobe> : 10,
    <item:mcwfurnitures:stripped_oak_bookshelf> : 10,
    <item:mcwfurnitures:stripped_oak_bookshelf_cupboard> : 10,
    <item:mcwfurnitures:stripped_oak_bookshelf_drawer> : 10,
    <item:mcwfurnitures:stripped_oak_chair> : 5,
    <item:mcwfurnitures:stripped_oak_coffee_table> : 2,
    <item:mcwfurnitures:stripped_oak_counter> : 2,
    <item:mcwfurnitures:stripped_oak_covered_desk> : 5,
    <item:mcwfurnitures:stripped_oak_cupboard_counter> : 10,
    <item:mcwfurnitures:stripped_oak_desk> : 5,
    <item:mcwfurnitures:stripped_oak_double_drawer> : 10,
    <item:mcwfurnitures:stripped_oak_double_drawer_counter> : 25,
    <item:mcwfurnitures:stripped_oak_double_wardrobe> : 25,
    <item:mcwfurnitures:stripped_oak_drawer> : 10,
    <item:mcwfurnitures:stripped_oak_drawer_counter> : 10,
    <item:mcwfurnitures:stripped_oak_end_table> : 5,
    <item:mcwfurnitures:stripped_oak_glass_table> : 5,
    <item:mcwfurnitures:stripped_oak_large_drawer> : 10,
    <item:mcwfurnitures:stripped_oak_lower_bookshelf_drawer> : 10,
    <item:mcwfurnitures:stripped_oak_lower_triple_drawer> : 25,
    <item:mcwfurnitures:stripped_oak_modern_chair> : 5,
    <item:mcwfurnitures:stripped_oak_modern_desk> : 5,
    <item:mcwfurnitures:stripped_oak_modern_wardrobe> : 10,
    <item:mcwfurnitures:stripped_oak_stool_chair> : 5,
    <item:mcwfurnitures:stripped_oak_striped_chair> : 5,
    <item:mcwfurnitures:stripped_oak_table> : 5,
    <item:mcwfurnitures:stripped_oak_triple_drawer> : 25,
    <item:mcwfurnitures:stripped_oak_wardrobe> : 10,
    <item:mcwfurnitures:stripped_spruce_bookshelf> : 10,
    <item:mcwfurnitures:stripped_spruce_bookshelf_cupboard> : 10,
    <item:mcwfurnitures:stripped_spruce_bookshelf_drawer> : 10,
    <item:mcwfurnitures:stripped_spruce_chair> : 5,
    <item:mcwfurnitures:stripped_spruce_coffee_table> : 2,
    <item:mcwfurnitures:stripped_spruce_counter> : 2,
    <item:mcwfurnitures:stripped_spruce_covered_desk> : 5,
    <item:mcwfurnitures:stripped_spruce_cupboard_counter> : 10,
    <item:mcwfurnitures:stripped_spruce_desk> : 5,
    <item:mcwfurnitures:stripped_spruce_double_drawer> : 10,
    <item:mcwfurnitures:stripped_spruce_double_drawer_counter> : 25,
    <item:mcwfurnitures:stripped_spruce_double_wardrobe> : 25,
    <item:mcwfurnitures:stripped_spruce_drawer> : 10,
    <item:mcwfurnitures:stripped_spruce_drawer_counter> : 10,
    <item:mcwfurnitures:stripped_spruce_end_table> : 5,
    <item:mcwfurnitures:stripped_spruce_glass_table> : 5,
    <item:mcwfurnitures:stripped_spruce_large_drawer> : 10,
    <item:mcwfurnitures:stripped_spruce_lower_bookshelf_drawer> : 10,
    <item:mcwfurnitures:stripped_spruce_lower_triple_drawer> : 25,
    <item:mcwfurnitures:stripped_spruce_modern_chair> : 5,
    <item:mcwfurnitures:stripped_spruce_modern_desk> : 5,
    <item:mcwfurnitures:stripped_spruce_modern_wardrobe> : 10,
    <item:mcwfurnitures:stripped_spruce_stool_chair> : 5,
    <item:mcwfurnitures:stripped_spruce_striped_chair> : 5,
    <item:mcwfurnitures:stripped_spruce_table> : 5,
    <item:mcwfurnitures:stripped_spruce_triple_drawer> : 25,
    <item:mcwfurnitures:stripped_spruce_wardrobe> : 10,
    <item:mcwfurnitures:stripped_warped_bookshelf> : 10,
    <item:mcwfurnitures:stripped_warped_bookshelf_cupboard> : 10,
    <item:mcwfurnitures:stripped_warped_bookshelf_drawer> : 10,
    <item:mcwfurnitures:stripped_warped_chair> : 5,
    <item:mcwfurnitures:stripped_warped_coffee_table> : 2,
    <item:mcwfurnitures:stripped_warped_counter> : 2,
    <item:mcwfurnitures:stripped_warped_covered_desk> : 5,
    <item:mcwfurnitures:stripped_warped_cupboard_counter> : 10,
    <item:mcwfurnitures:stripped_warped_desk> : 5,
    <item:mcwfurnitures:stripped_warped_double_drawer> : 10,
    <item:mcwfurnitures:stripped_warped_double_drawer_counter> : 25,
    <item:mcwfurnitures:stripped_warped_double_wardrobe> : 25,
    <item:mcwfurnitures:stripped_warped_drawer> : 10,
    <item:mcwfurnitures:stripped_warped_drawer_counter> : 10,
    <item:mcwfurnitures:stripped_warped_end_table> : 5,
    <item:mcwfurnitures:stripped_warped_glass_table> : 5,
    <item:mcwfurnitures:stripped_warped_large_drawer> : 10,
    <item:mcwfurnitures:stripped_warped_lower_bookshelf_drawer> : 10,
    <item:mcwfurnitures:stripped_warped_lower_triple_drawer> : 25,
    <item:mcwfurnitures:stripped_warped_modern_chair> : 5,
    <item:mcwfurnitures:stripped_warped_modern_desk> : 5,
    <item:mcwfurnitures:stripped_warped_modern_wardrobe> : 10,
    <item:mcwfurnitures:stripped_warped_stool_chair> : 5,
    <item:mcwfurnitures:stripped_warped_striped_chair> : 5,
    <item:mcwfurnitures:stripped_warped_table> : 5,
    <item:mcwfurnitures:stripped_warped_triple_drawer> : 25,
    <item:mcwfurnitures:stripped_warped_wardrobe> : 10,
    <item:mcwfurnitures:warped_bookshelf> : 10,
    <item:mcwfurnitures:warped_bookshelf_cupboard> : 10,
    <item:mcwfurnitures:warped_bookshelf_drawer> : 10,
    <item:mcwfurnitures:warped_chair> : 5,
    <item:mcwfurnitures:warped_coffee_table> : 2,
    <item:mcwfurnitures:warped_counter> : 2,
    <item:mcwfurnitures:warped_covered_desk> : 5,
    <item:mcwfurnitures:warped_cupboard_counter> : 10,
    <item:mcwfurnitures:warped_desk> : 5,
    <item:mcwfurnitures:warped_double_drawer> : 10,
    <item:mcwfurnitures:warped_double_drawer_counter> : 25,
    <item:mcwfurnitures:warped_double_wardrobe> : 25,
    <item:mcwfurnitures:warped_drawer> : 10,
    <item:mcwfurnitures:warped_drawer_counter> : 10,
    <item:mcwfurnitures:warped_end_table> : 5,
    <item:mcwfurnitures:warped_glass_table> : 5,
    <item:mcwfurnitures:warped_large_drawer> : 10,
    <item:mcwfurnitures:warped_lower_bookshelf_drawer> : 10,
    <item:mcwfurnitures:warped_lower_triple_drawer> : 25,
    <item:mcwfurnitures:warped_modern_chair> : 5,
    <item:mcwfurnitures:warped_modern_desk> : 5,
    <item:mcwfurnitures:warped_modern_wardrobe> : 10,
    <item:mcwfurnitures:warped_stool_chair> : 5,
    <item:mcwfurnitures:warped_striped_chair> : 5,
    <item:mcwfurnitures:warped_table> : 5,
    <item:mcwfurnitures:warped_triple_drawer> : 25,
    <item:mcwfurnitures:warped_wardrobe> : 10
};

// For each item in the map, check if we're in release mode. If we are, anything below 26 EMC/FMC becomes unburnable for EMC
for item, value in priceTable {
    if (ReleaseMode.releaseMode == true){
        if (value < 26 ) {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), 0);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        } else {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        }
        if (value > 999 && value < 10001) {
            <tag:items:tfb2:fop_miniscule>.add(item);
            item.addTooltip(new TextComponent("FOP Digitization Value: Miniscule").withStyle(style => style.withColor(<constant:minecraft:formatting:white>)));
        }
        if (value > 10000 && value < 25001) {
            <tag:items:tfb2:fop_small>.add(item);
            item.addTooltip(new TextComponent("FOP Digitization Value: Small").withStyle(style => style.withColor(<constant:minecraft:formatting:white>)));
        }
        if (value > 25000 && value < 75001) {
            <tag:items:tfb2:fop_medium>.add(item);
            item.addTooltip(new TextComponent("FOP Digitization Value: Medium").withStyle(style => style.withColor(<constant:minecraft:formatting:white>)));
        }
        if (value > 75000) {
            <tag:items:tfb2:fop_large>.add(item);
            item.addTooltip(new TextComponent("FOP Digitization Value: Large").withStyle(style => style.withColor(<constant:minecraft:formatting:white>)));
        }
    } else {
        CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
        <tag:items:projectextended:blacklist_condenser>.add(item);
        <tag:items:projectextended:blacklist_learning>.add(item);
        
        if (value > 10000 && value < 25001) {
            <tag:items:tfb2:fop_small>.add(item);
            item.addTooltip(new TextComponent("FOP Digitization Value: Small").withStyle(style => style.withColor(<constant:minecraft:formatting:white>)));
        }
        if (value > 25000 && value < 75001) {
            <tag:items:tfb2:fop_medium>.add(item);
            item.addTooltip(new TextComponent("FOP Digitization Value: Medium").withStyle(style => style.withColor(<constant:minecraft:formatting:white>)));
        }
        if (value > 75000) {
            <tag:items:tfb2:fop_large>.add(item);
            item.addTooltip(new TextComponent("FOP Digitization Value: Large").withStyle(style => style.withColor(<constant:minecraft:formatting:white>)));
        }
    }
}