import crafttweaker.api.text.TextComponent;
import crafttweaker.api.tag.MCTag;
import crafttweaker.api.item.IItemStack;
import crafttweaker.api.ingredient.IIngredient;
import crafttweaker.api.item.tooltip.ITooltipFunction;
import stdlib.List;
import mods.projecte.CustomEMC;
import mods.projecte.NSSResolver;

// Item  to EMC/FMC value map.
val priceTable as int[IItemStack] = {
    <item:mcwholidays:bat_awake> : 25,
    <item:mcwholidays:bat_doormat> : 5,
    <item:mcwholidays:bat_sleeping> : 25,
    <item:mcwholidays:bat_wall_deco_1> : 10,
    <item:mcwholidays:bat_wall_deco_2> : 10,
    <item:mcwholidays:bat_wall_deco_3> : 25,
    <item:mcwholidays:bell_wall_deco_1> : 5,
    <item:mcwholidays:bell_wall_deco_2> : 10,
    <item:mcwholidays:bell_wall_deco_3> : 25,
    <item:mcwholidays:bell_wall_deco_4> : 10,
    <item:mcwholidays:bells_wall_deco_1> : 5,
    <item:mcwholidays:bells_wall_deco_2> : 10,
    <item:mcwholidays:big_blue_present> : 10,
    <item:mcwholidays:big_cyan_present> : 10,
    <item:mcwholidays:big_dark_blue_present> : 10,
    <item:mcwholidays:big_green_present> : 10,
    <item:mcwholidays:big_magenta_present> : 10,
    <item:mcwholidays:big_purple_present> : 10,
    <item:mcwholidays:big_red_present> : 10,
    <item:mcwholidays:big_yellow_present> : 10,
    <item:mcwholidays:black_balloon> : 10,
    <item:mcwholidays:blue_candy_cane_block> : 25,
    <item:mcwholidays:blue_candy_cane_slab> : 10,
    <item:mcwholidays:blue_candy_cane_slim> : 10,
    <item:mcwholidays:blue_candy_cane_stairs> : 25,
    <item:mcwholidays:blue_cube_string_lights> : 5,
    <item:mcwholidays:blue_decorated_christmas_tree_base> : 10,
    <item:mcwholidays:blue_decorated_christmas_tree_bottom> : 10,
    <item:mcwholidays:blue_decorated_christmas_tree_middle> : 10,
    <item:mcwholidays:blue_decorated_christmas_tree_top> : 10,
    <item:mcwholidays:blue_garland_wall_deco_1> : 25,
    <item:mcwholidays:blue_garland_wall_deco_2> : 25,
    <item:mcwholidays:blue_ornament> : 2,
    <item:mcwholidays:blue_ornament_wall_deco_1> : 10,
    <item:mcwholidays:blue_ornament_wall_deco_2> : 10,
    <item:mcwholidays:blue_present> : 5,
    <item:mcwholidays:blue_stocking> : 5,
    <item:mcwholidays:blue_string_lights> : 10,
    <item:mcwholidays:blue_tiny_string_lights> : 2,
    <item:mcwholidays:bottom_garland_wall_deco_1> : 25,
    <item:mcwholidays:bottom_garland_wall_deco_2> : 25,
    <item:mcwholidays:brown_oak_leaves> : 1,
    <item:mcwholidays:brown_oak_leaves_carpet> : 1,
    <item:mcwholidays:brown_stocking> : 5,
    <item:mcwholidays:candy_cane> : 5,
    <item:mcwholidays:candy_cane_balloon> : 10,
    <item:mcwholidays:carved_evil_pumpkin> : 25,
    <item:mcwholidays:carved_friendly_pumpkin> : 25,
    <item:mcwholidays:carved_screaming_pumpkin> : 25,
    <item:mcwholidays:carved_shocked_pumpkin> : 25,
    <item:mcwholidays:carved_smile_pumpkin> : 25,
    <item:mcwholidays:cat_wall_deco_1> : 25,
    <item:mcwholidays:chaotic_cobweb> : 2,
    <item:mcwholidays:christmas_tree_base> : 5,
    <item:mcwholidays:christmas_tree_bottom> : 5,
    <item:mcwholidays:christmas_tree_middle> : 5,
    <item:mcwholidays:christmas_tree_top> : 5,
    <item:mcwholidays:colorful_cube_string_lights> : 5,
    <item:mcwholidays:colorful_decorated_christmas_tree_base> : 25,
    <item:mcwholidays:colorful_decorated_christmas_tree_bottom> : 25,
    <item:mcwholidays:colorful_decorated_christmas_tree_middle> : 25,
    <item:mcwholidays:colorful_decorated_christmas_tree_top> : 25,
    <item:mcwholidays:colorful_garland_wall_deco_1> : 25,
    <item:mcwholidays:colorful_garland_wall_deco_2> : 25,
    <item:mcwholidays:colorful_string_lights> : 10,
    <item:mcwholidays:colorful_tiny_string_lights> : 2,
    <item:mcwholidays:cornered_cobweb> : 2,
    <item:mcwholidays:couple_bells> : 5850,
    <item:mcwholidays:couple_blue_presents> : 10,
    <item:mcwholidays:couple_blue_stockings> : 10,
    <item:mcwholidays:couple_brown_stockings> : 10,
    <item:mcwholidays:couple_cyan_presents> : 10,
    <item:mcwholidays:couple_dark_blue_presents> : 10,
    <item:mcwholidays:couple_green_presents> : 10,
    <item:mcwholidays:couple_green_stockings> : 10,
    <item:mcwholidays:couple_magenta_presents> : 10,
    <item:mcwholidays:couple_purple_presents> : 10,
    <item:mcwholidays:couple_red_presents> : 10,
    <item:mcwholidays:couple_red_stockings> : 10,
    <item:mcwholidays:couple_white_stockings> : 10,
    <item:mcwholidays:couple_yellow_presents> : 10,
    <item:mcwholidays:cyan_ornament> : 2,
    <item:mcwholidays:cyan_present> : 5,
    <item:mcwholidays:dark_blue_present> : 5,
    <item:mcwholidays:fairy_garland_wall_deco> : 10,
    <item:mcwholidays:flat_dirt_gravestone> : 1,
    <item:mcwholidays:flat_gravestone> : 1,
    <item:mcwholidays:garland> : 1,
    <item:mcwholidays:garland_blue_lights> : 1,
    <item:mcwholidays:garland_colorful_lights> : 1,
    <item:mcwholidays:garland_green_lights> : 1,
    <item:mcwholidays:garland_orange_lights> : 1,
    <item:mcwholidays:garland_purple_lights> : 1,
    <item:mcwholidays:garland_red_lights> : 1,
    <item:mcwholidays:garland_wall_deco> : 10,
    <item:mcwholidays:garland_yellow_lights> : 1,
    <item:mcwholidays:ghost> : 25,
    <item:mcwholidays:ghost_balloon> : 10,
    <item:mcwholidays:ghost_doormat> : 5,
    <item:mcwholidays:ghost_wall_deco_1> : 5,
    <item:mcwholidays:ghost_wall_deco_2> : 5,
    <item:mcwholidays:golden_balloon> : 10,
    <item:mcwholidays:gravestone> : 1,
    <item:mcwholidays:gray_ornament> : 2,
    <item:mcwholidays:green_balloon> : 10,
    <item:mcwholidays:green_candy_cane_block> : 25,
    <item:mcwholidays:green_candy_cane_slab> : 10,
    <item:mcwholidays:green_candy_cane_slim> : 10,
    <item:mcwholidays:green_candy_cane_stairs> : 25,
    <item:mcwholidays:green_cube_string_lights> : 5,
    <item:mcwholidays:green_decorated_christmas_tree_base> : 10,
    <item:mcwholidays:green_decorated_christmas_tree_bottom> : 10,
    <item:mcwholidays:green_decorated_christmas_tree_middle> : 10,
    <item:mcwholidays:green_decorated_christmas_tree_top> : 10,
    <item:mcwholidays:green_garland_wall_deco_1> : 25,
    <item:mcwholidays:green_garland_wall_deco_2> : 25,
    <item:mcwholidays:green_ornament> : 2,
    <item:mcwholidays:green_ornament_wall_deco_1> : 10,
    <item:mcwholidays:green_ornament_wall_deco_2> : 10,
    <item:mcwholidays:green_present> : 5,
    <item:mcwholidays:green_stocking> : 5,
    <item:mcwholidays:green_string_lights> : 10,
    <item:mcwholidays:green_tiny_string_lights> : 2,
    <item:mcwholidays:ground_skeleton> : 175,
    <item:mcwholidays:half_cobweb> : 2,
    <item:mcwholidays:hanging_cobweb> : 2,
    <item:mcwholidays:happy_ghost> : 25,
    <item:mcwholidays:haunting_ghost> : 25,
    <item:mcwholidays:hay_wheelbarrow> : 50,
    <item:mcwholidays:horizontal_garland_wall_deco> : 10,
    <item:mcwholidays:icicle> : 1,
    <item:mcwholidays:icicle_big> : 1,
    <item:mcwholidays:icicle_sharp> : 1,
    <item:mcwholidays:icicle_straight> : 1,
    <item:mcwholidays:icicle_thick> : 1,
    <item:mcwholidays:large_pumpkin> : 25,
    <item:mcwholidays:laying_hay_bale> : 25,
    <item:mcwholidays:light_blue_ornament> : 2,
    <item:mcwholidays:lit_evil_pumpkin> : 25,
    <item:mcwholidays:lit_friendly_pumpkin> : 25,
    <item:mcwholidays:lit_screaming_pumpkin> : 25,
    <item:mcwholidays:lit_shocked_pumpkin> : 25,
    <item:mcwholidays:lit_smile_pumpkin> : 25,
    <item:mcwholidays:magenta_ornament> : 2,
    <item:mcwholidays:magenta_present> : 10,
    <item:mcwholidays:medium_pumpkin> : 10,
    <item:mcwholidays:mistletoe> : 5,
    <item:mcwholidays:mixed_oak_leaves> : 1,
    <item:mcwholidays:mixed_oak_leaves_carpet> : 1,
    <item:mcwholidays:orange_balloon> : 10,
    <item:mcwholidays:orange_cube_string_lights> : 5,
    <item:mcwholidays:orange_oak_leaves> : 1,
    <item:mcwholidays:orange_oak_leaves_carpet> : 1,
    <item:mcwholidays:orange_ornament> : 2,
    <item:mcwholidays:orange_string_lights> : 10,
    <item:mcwholidays:orange_tiny_string_lights> : 2,
    <item:mcwholidays:orn_blue_garland> : 1,
    <item:mcwholidays:orn_blue_wavy_garland> : 1,
    <item:mcwholidays:orn_golden_garland> : 1,
    <item:mcwholidays:orn_golden_wavy_garland> : 1,
    <item:mcwholidays:orn_red_garland> : 1,
    <item:mcwholidays:orn_red_wavy_garland> : 1,
    <item:mcwholidays:orn_silver_garland> : 1,
    <item:mcwholidays:orn_silver_wavy_garland> : 1,
    <item:mcwholidays:outlined_cobweb> : 2,
    <item:mcwholidays:pair_of_potions> : 10,
    <item:mcwholidays:pair_of_pumpkins> : 25,
    <item:mcwholidays:pile_of_birch_wood> : 2,
    <item:mcwholidays:pile_of_oak_wood> : 2,
    <item:mcwholidays:pile_of_spruce_wood> : 2,
    <item:mcwholidays:pine_bottom> : 1,
    <item:mcwholidays:pine_middle> : 1,
    <item:mcwholidays:pine_top> : 1,
    <item:mcwholidays:pink_ornament> : 2,
    <item:mcwholidays:present_doormat> : 5,
    <item:mcwholidays:present_wall_deco> : 10,
    <item:mcwholidays:pumpkin_balloon> : 10,
    <item:mcwholidays:pumpkin_doormat> : 5,
    <item:mcwholidays:pumpkin_wall_deco_1> : 25,
    <item:mcwholidays:pumpkin_wall_deco_2> : 25,
    <item:mcwholidays:pumpkin_wheelbarrow> : 25,
    <item:mcwholidays:purple_cube_string_lights> : 5,
    <item:mcwholidays:purple_decorated_christmas_tree_base> : 10,
    <item:mcwholidays:purple_decorated_christmas_tree_bottom> : 10,
    <item:mcwholidays:purple_decorated_christmas_tree_middle> : 10,
    <item:mcwholidays:purple_decorated_christmas_tree_top> : 10,
    <item:mcwholidays:purple_garland_wall_deco_1> : 25,
    <item:mcwholidays:purple_garland_wall_deco_2> : 25,
    <item:mcwholidays:purple_ornament> : 2,
    <item:mcwholidays:purple_ornament_wall_deco_1> : 10,
    <item:mcwholidays:purple_ornament_wall_deco_2> : 10,
    <item:mcwholidays:purple_present> : 5,
    <item:mcwholidays:purple_string_lights> : 10,
    <item:mcwholidays:purple_tiny_string_lights> : 2,
    <item:mcwholidays:pyramid_cobweb> : 2,
    <item:mcwholidays:red_balloon> : 10,
    <item:mcwholidays:red_candy_cane_block> : 25,
    <item:mcwholidays:red_candy_cane_slab> : 10,
    <item:mcwholidays:red_candy_cane_slim> : 10,
    <item:mcwholidays:red_candy_cane_stairs> : 25,
    <item:mcwholidays:red_cube_string_lights> : 5,
    <item:mcwholidays:red_decorated_christmas_tree_base> : 10,
    <item:mcwholidays:red_decorated_christmas_tree_bottom> : 10,
    <item:mcwholidays:red_decorated_christmas_tree_middle> : 10,
    <item:mcwholidays:red_decorated_christmas_tree_top> : 10,
    <item:mcwholidays:red_garland_wall_deco_1> : 25,
    <item:mcwholidays:red_garland_wall_deco_2> : 25,
    <item:mcwholidays:red_oak_leaves> : 1,
    <item:mcwholidays:red_oak_leaves_carpet> : 1,
    <item:mcwholidays:red_ornament> : 2,
    <item:mcwholidays:red_ornament_wall_deco_1> : 10,
    <item:mcwholidays:red_ornament_wall_deco_2> : 10,
    <item:mcwholidays:red_present> : 5,
    <item:mcwholidays:red_stocking> : 5,
    <item:mcwholidays:red_string_lights> : 10,
    <item:mcwholidays:red_tiny_string_lights> : 2,
    <item:mcwholidays:reindeer_doormat> : 5,
    <item:mcwholidays:santa_balloon> : 10,
    <item:mcwholidays:santa_hat_wall_deco> : 10,
    <item:mcwholidays:scarecrow> : 75,
    <item:mcwholidays:silver_ornament> : 2,
    <item:mcwholidays:single_bell> : 2925,
    <item:mcwholidays:single_potion> : 5,
    <item:mcwholidays:sitting_skeleton> : 200,
    <item:mcwholidays:skeleton_balloon> : 10,
    <item:mcwholidays:slanted_gravestone> : 1,
    <item:mcwholidays:small_gravestone> : 1,
    <item:mcwholidays:small_pumpkin> : 5,
    <item:mcwholidays:snow_covered_pine_bottom> : 1,
    <item:mcwholidays:snow_covered_pine_middle> : 1,
    <item:mcwholidays:snow_covered_pine_top> : 1,
    <item:mcwholidays:snowman> : 5,
    <item:mcwholidays:snowman_bottom> : 2,
    <item:mcwholidays:snowman_ear_muffs> : 10,
    <item:mcwholidays:snowman_grinch> : 10,
    <item:mcwholidays:snowman_with_pan> : 225,
    <item:mcwholidays:snowman_with_santa_hat> : 10,
    <item:mcwholidays:snowman_with_top_hat> : 10,
    <item:mcwholidays:snowman_with_ushanka> : 10,
    <item:mcwholidays:snowy_fern> : 5,
    <item:mcwholidays:snowy_grass> : 5,
    <item:mcwholidays:snowy_grass_block> : 5,
    <item:mcwholidays:snowy_oak_leaves> : 1,
    <item:mcwholidays:snowy_oak_leaves_carpet> : 1,
    <item:mcwholidays:snowy_pine_bottom> : 1,
    <item:mcwholidays:snowy_pine_middle> : 1,
    <item:mcwholidays:snowy_pine_top> : 1,
    <item:mcwholidays:snowy_spruce_leaves> : 1,
    <item:mcwholidays:snowy_spruce_leaves_carpet> : 1,
    <item:mcwholidays:snowy_tall_fern> : 5,
    <item:mcwholidays:snowy_tall_grass> : 5,
    <item:mcwholidays:sock_doormat> : 5,
    <item:mcwholidays:spider_balloon> : 10,
    <item:mcwholidays:spider_wall_deco_1> : 25,
    <item:mcwholidays:spider_wall_deco_2> : 25,
    <item:mcwholidays:spooky_cobweb> : 2,
    <item:mcwholidays:square_gravestone> : 1,
    <item:mcwholidays:standing_broomstick> : 5,
    <item:mcwholidays:standing_hay_bale> : 25,
    <item:mcwholidays:standing_rake> : 100,
    <item:mcwholidays:standing_shovel> : 250,
    <item:mcwholidays:star_wall_deco> : 25,
    <item:mcwholidays:stars_wall_deco> : 10,
    <item:mcwholidays:stocking_wall_deco_1> : 10,
    <item:mcwholidays:stocking_wall_deco_2> : 10,
    <item:mcwholidays:stone_cross> : 1,
    <item:mcwholidays:tall_gravestone> : 1,
    <item:mcwholidays:three_potions> : 25,
    <item:mcwholidays:three_pumpkins> : 25,
    <item:mcwholidays:tree_balloon> : 10,
    <item:mcwholidays:tree_doormat> : 5,
    <item:mcwholidays:triangle_cobweb> : 2,
    <item:mcwholidays:unmeltable_snow> : 1,
    <item:mcwholidays:vertical_garland_wall_deco> : 10,
    <item:mcwholidays:wavy_garland> : 1,
    <item:mcwholidays:wavy_garland_blue_lights> : 1,
    <item:mcwholidays:wavy_garland_colorful_lights> : 1,
    <item:mcwholidays:wavy_garland_green_lights> : 1,
    <item:mcwholidays:wavy_garland_orange_lights> : 1,
    <item:mcwholidays:wavy_garland_purple_lights> : 1,
    <item:mcwholidays:wavy_garland_red_lights> : 1,
    <item:mcwholidays:wavy_garland_yellow_lights> : 1,
    <item:mcwholidays:white_balloon> : 10,
    <item:mcwholidays:white_garland> : 1,
    <item:mcwholidays:white_garland_blue_lights> : 1,
    <item:mcwholidays:white_garland_colorful_lights> : 1,
    <item:mcwholidays:white_garland_green_lights> : 1,
    <item:mcwholidays:white_garland_orange_lights> : 1,
    <item:mcwholidays:white_garland_purple_lights> : 1,
    <item:mcwholidays:white_garland_red_lights> : 1,
    <item:mcwholidays:white_garland_yellow_lights> : 1,
    <item:mcwholidays:white_orn_blue_garland> : 1,
    <item:mcwholidays:white_orn_blue_wavy_garland> : 1,
    <item:mcwholidays:white_orn_golden_garland> : 1,
    <item:mcwholidays:white_orn_golden_wavy_garland> : 1,
    <item:mcwholidays:white_orn_red_garland> : 1,
    <item:mcwholidays:white_orn_red_wavy_garland> : 1,
    <item:mcwholidays:white_orn_silver_garland> : 1,
    <item:mcwholidays:white_orn_silver_wavy_garland> : 1,
    <item:mcwholidays:white_stocking> : 5,
    <item:mcwholidays:white_wavy_garland> : 1,
    <item:mcwholidays:white_wavy_garland_blue_lights> : 1,
    <item:mcwholidays:white_wavy_garland_colorful_lights> : 1,
    <item:mcwholidays:white_wavy_garland_green_lights> : 1,
    <item:mcwholidays:white_wavy_garland_orange_lights> : 1,
    <item:mcwholidays:white_wavy_garland_purple_lights> : 1,
    <item:mcwholidays:white_wavy_garland_red_lights> : 1,
    <item:mcwholidays:white_wavy_garland_yellow_lights> : 1,
    <item:mcwholidays:witch_cauldron> : 1775,
    <item:mcwholidays:witch_hat> : 100,
    <item:mcwholidays:witch_hat_wall_deco_1> : 10,
    <item:mcwholidays:witch_hat_wall_deco_2> : 10,
    <item:mcwholidays:wooden_cross> : 1,
    <item:mcwholidays:wooden_sled> : 5,
    <item:mcwholidays:wreath_wall_deco_1> : 25,
    <item:mcwholidays:wreath_wall_deco_2> : 25,
    <item:mcwholidays:yellow_candy_cane_block> : 25,
    <item:mcwholidays:yellow_candy_cane_slab> : 10,
    <item:mcwholidays:yellow_candy_cane_slim> : 10,
    <item:mcwholidays:yellow_candy_cane_stairs> : 25,
    <item:mcwholidays:yellow_cube_string_lights> : 5,
    <item:mcwholidays:yellow_decorated_christmas_tree_base> : 10,
    <item:mcwholidays:yellow_decorated_christmas_tree_bottom> : 10,
    <item:mcwholidays:yellow_decorated_christmas_tree_middle> : 10,
    <item:mcwholidays:yellow_decorated_christmas_tree_top> : 10,
    <item:mcwholidays:yellow_garland_wall_deco_1> : 25,
    <item:mcwholidays:yellow_garland_wall_deco_2> : 25,
    <item:mcwholidays:yellow_oak_leaves> : 1,
    <item:mcwholidays:yellow_oak_leaves_carpet> : 1,
    <item:mcwholidays:yellow_ornament> : 2,
    <item:mcwholidays:yellow_ornament_wall_deco_1> : 10,
    <item:mcwholidays:yellow_ornament_wall_deco_2> : 10,
    <item:mcwholidays:yellow_present> : 5,
    <item:mcwholidays:yellow_string_lights> : 10,
    <item:mcwholidays:yellow_tiny_string_lights> : 2
};

// For each item in the map, check if we're in release mode. If we are, anything below 26 EMC/FMC becomes unburnable for EMC
for item, value in priceTable {
    if (ReleaseMode.releaseMode == true){
        if (value < 26 ) {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), 0);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        } else {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        }
        if (value > 999 && value < 10001) {
            <tag:items:tfb2:fop_miniscule>.add(item);
            item.addTooltip(new TextComponent("FOP Digitization Value: Miniscule").withStyle(style => style.withColor(<constant:minecraft:formatting:white>)));
        }
        if (value > 10000 && value < 25001) {
            <tag:items:tfb2:fop_small>.add(item);
            item.addTooltip(new TextComponent("FOP Digitization Value: Small").withStyle(style => style.withColor(<constant:minecraft:formatting:white>)));
        }
        if (value > 25000 && value < 75001) {
            <tag:items:tfb2:fop_medium>.add(item);
            item.addTooltip(new TextComponent("FOP Digitization Value: Medium").withStyle(style => style.withColor(<constant:minecraft:formatting:white>)));
        }
        if (value > 75000) {
            <tag:items:tfb2:fop_large>.add(item);
            item.addTooltip(new TextComponent("FOP Digitization Value: Large").withStyle(style => style.withColor(<constant:minecraft:formatting:white>)));
        }
    } else {
        CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
        <tag:items:projectextended:blacklist_condenser>.add(item);
        <tag:items:projectextended:blacklist_learning>.add(item);
        
        if (value > 10000 && value < 25001) {
            <tag:items:tfb2:fop_small>.add(item);
            item.addTooltip(new TextComponent("FOP Digitization Value: Small").withStyle(style => style.withColor(<constant:minecraft:formatting:white>)));
        }
        if (value > 25000 && value < 75001) {
            <tag:items:tfb2:fop_medium>.add(item);
            item.addTooltip(new TextComponent("FOP Digitization Value: Medium").withStyle(style => style.withColor(<constant:minecraft:formatting:white>)));
        }
        if (value > 75000) {
            <tag:items:tfb2:fop_large>.add(item);
            item.addTooltip(new TextComponent("FOP Digitization Value: Large").withStyle(style => style.withColor(<constant:minecraft:formatting:white>)));
        }
    }
}