import crafttweaker.api.tag.MCTag;
import crafttweaker.api.item.IItemStack;
import crafttweaker.api.ingredient.IIngredient;
import crafttweaker.api.item.tooltip.ITooltipFunction;
import stdlib.List;
import mods.projecte.CustomEMC;
import mods.projecte.NSSResolver;

// This variable controls whether we are in the pack dev mode or release mode. In Pack Dev mode, all EMC/FMC values are enabled to help calculate EMC/FMC for other mods.
var release_mode = false;

// Item  to EMC/FMC value map.
val priceTable as int[IItemStack] = {
    <item:moa_decor_holidays:arana_en_telarana> : 250,
    <item:moa_decor_holidays:arana_en_telarana_2> : 250,
    <item:moa_decor_holidays:banderines_amarillo> : 250,
    <item:moa_decor_holidays:banderines_azul> : 250,
    <item:moa_decor_holidays:banderines_azul_claro> : 250,
    <item:moa_decor_holidays:banderines_blanco> : 250,
    <item:moa_decor_holidays:banderines_cafe> : 250,
    <item:moa_decor_holidays:banderines_cian> : 250,
    <item:moa_decor_holidays:banderines_gris> : 250,
    <item:moa_decor_holidays:banderines_gris_claro> : 250,
    <item:moa_decor_holidays:banderines_magenta> : 250,
    <item:moa_decor_holidays:banderines_morado> : 250,
    <item:moa_decor_holidays:banderines_naranja> : 250,
    <item:moa_decor_holidays:banderines_negro> : 250,
    <item:moa_decor_holidays:banderines_rojo> : 250,
    <item:moa_decor_holidays:banderines_rosa> : 250,
    <item:moa_decor_holidays:banderines_verde> : 250,
    <item:moa_decor_holidays:banderines_verde_lima> : 250,
    <item:moa_decor_holidays:base_pino_navideno> : 250,
    <item:moa_decor_holidays:bota_namarilla> : 250,
    <item:moa_decor_holidays:bota_nazul> : 250,
    <item:moa_decor_holidays:bota_nazulclara> : 250,
    <item:moa_decor_holidays:bota_ncafe> : 250,
    <item:moa_decor_holidays:bota_ncian> : 250,
    <item:moa_decor_holidays:bota_ngris> : 250,
    <item:moa_decor_holidays:bota_ngrisclara> : 250,
    <item:moa_decor_holidays:bota_nmagenta> : 250,
    <item:moa_decor_holidays:bota_nmorada> : 250,
    <item:moa_decor_holidays:bota_nnatanja> : 250,
    <item:moa_decor_holidays:bota_nnegra> : 250,
    <item:moa_decor_holidays:bota_nroja> : 250,
    <item:moa_decor_holidays:bota_nrosa> : 250,
    <item:moa_decor_holidays:bota_nverde> : 250,
    <item:moa_decor_holidays:bota_nverdelima> : 250,
    <item:moa_decor_holidays:bruja_escoba> : 250,
    <item:moa_decor_holidays:c_pblanco> : 250,
    <item:moa_decor_holidays:c_pcafe> : 250,
    <item:moa_decor_holidays:c_pdorado> : 250,
    <item:moa_decor_holidays:c_pnegro> : 250,
    <item:moa_decor_holidays:calabaza_creeper> : 250,
    <item:moa_decor_holidays:calabaza_creeper_l> : 250,
    <item:moa_decor_holidays:calabaza_creeper_nav_l> : 250,
    <item:moa_decor_holidays:calabaza_dulces> : 250,
    <item:moa_decor_holidays:calabaza_enderman> : 250,
    <item:moa_decor_holidays:calabaza_enderman_l> : 250,
    <item:moa_decor_holidays:calabaza_esqueleto> : 250,
    <item:moa_decor_holidays:calabaza_esqueleto_l> : 250,
    <item:moa_decor_holidays:calabaza_pillager> : 250,
    <item:moa_decor_holidays:calabaza_pillager_l> : 250,
    <item:moa_decor_holidays:calabaza_slime> : 250,
    <item:moa_decor_holidays:calabaza_slime_l> : 250,
    <item:moa_decor_holidays:calabaza_warden> : 250,
    <item:moa_decor_holidays:calabaza_warden_l> : 250,
    <item:moa_decor_holidays:calabaza_zombie> : 250,
    <item:moa_decor_holidays:calabaza_zomvie_l> : 250,
    <item:moa_decor_holidays:catrinacian> : 250,
    <item:moa_decor_holidays:catrinamorada> : 250,
    <item:moa_decor_holidays:catrinaroja> : 250,
    <item:moa_decor_holidays:clabaza_creeper_nav> : 250,
    <item:moa_decor_holidays:conejo_chocolate> : 250,
    <item:moa_decor_holidays:corona_navidena> : 250,
    <item:moa_decor_holidays:creeper_nieve> : 250,
    <item:moa_decor_holidays:duende_navidena> : 250,
    <item:moa_decor_holidays:duende_navideno> : 250,
    <item:moa_decor_holidays:esp_amarillo> : 250,
    <item:moa_decor_holidays:esp_azul> : 250,
    <item:moa_decor_holidays:esp_azulclaro> : 250,
    <item:moa_decor_holidays:esp_blanco> : 250,
    <item:moa_decor_holidays:esp_cafe> : 250,
    <item:moa_decor_holidays:esp_cian> : 250,
    <item:moa_decor_holidays:esp_gris> : 250,
    <item:moa_decor_holidays:esp_grisclaro> : 250,
    <item:moa_decor_holidays:esp_magenta> : 250,
    <item:moa_decor_holidays:esp_morado> : 250,
    <item:moa_decor_holidays:esp_naranja> : 250,
    <item:moa_decor_holidays:esp_negro> : 250,
    <item:moa_decor_holidays:esp_rojo> : 250,
    <item:moa_decor_holidays:esp_rosa> : 250,
    <item:moa_decor_holidays:esp_verde> : 250,
    <item:moa_decor_holidays:esp_verdelima> : 250,
    <item:moa_decor_holidays:esqueleto_enjaulado> : 250,
    <item:moa_decor_holidays:esqueletoacostado> : 250,
    <item:moa_decor_holidays:esqueletosentado> : 250,
    <item:moa_decor_holidays:estrella_navidena> : 250,
    <item:moa_decor_holidays:fantasma> : 250,
    <item:moa_decor_holidays:gema_festividades> : 250,
    <item:moa_decor_holidays:globos_amarillo> : 250,
    <item:moa_decor_holidays:globos_azul> : 250,
    <item:moa_decor_holidays:globos_azul_claro> : 250,
    <item:moa_decor_holidays:globos_blanco> : 250,
    <item:moa_decor_holidays:globos_cafe> : 250,
    <item:moa_decor_holidays:globos_cian> : 250,
    <item:moa_decor_holidays:globos_gris> : 250,
    <item:moa_decor_holidays:globos_gris_claro> : 250,
    <item:moa_decor_holidays:globos_magenta> : 250,
    <item:moa_decor_holidays:globos_morado> : 250,
    <item:moa_decor_holidays:globos_naranja> : 250,
    <item:moa_decor_holidays:globos_negro> : 250,
    <item:moa_decor_holidays:globos_rojo> : 250,
    <item:moa_decor_holidays:globos_rosa> : 250,
    <item:moa_decor_holidays:globos_verde> : 250,
    <item:moa_decor_holidays:globos_verde_lima> : 250,
    <item:moa_decor_holidays:jaula> : 250,
    <item:moa_decor_holidays:lapida> : 250,
    <item:moa_decor_holidays:lapida_cruz> : 250,
    <item:moa_decor_holidays:leprechaun> : 250,
    <item:moa_decor_holidays:leprechaunolladeoro> : 250,
    <item:moa_decor_holidays:mariachiguitarra> : 250,
    <item:moa_decor_holidays:mariachitrompeta> : 250,
    <item:moa_decor_holidays:mariachiviolin> : 250,
    <item:moa_decor_holidays:murcielagoabierto> : 250,
    <item:moa_decor_holidays:murcielagocerrado> : 250,
    <item:moa_decor_holidays:olladeoro> : 250,
    <item:moa_decor_holidays:p_galleta_jengibre> : 250,
    <item:moa_decor_holidays:p_galleta_jengibre_n> : 250,
    <item:moa_decor_holidays:p_oso_polar_n> : 250,
    <item:moa_decor_holidays:papelpicado_a> : 250,
    <item:moa_decor_holidays:papelpicado_cian> : 250,
    <item:moa_decor_holidays:papelpicado_lima> : 250,
    <item:moa_decor_holidays:papelpicado_morado> : 250,
    <item:moa_decor_holidays:papelpicado_rojo> : 250,
    <item:moa_decor_holidays:papelpicado_rosa> : 250,
    <item:moa_decor_holidays:pino_navideno> : 250,
    <item:moa_decor_holidays:pino_navideno_n> : 250,
    <item:moa_decor_holidays:regalo_amarillo> : 250,
    <item:moa_decor_holidays:regalo_azul> : 250,
    <item:moa_decor_holidays:regalo_azul_claro> : 250,
    <item:moa_decor_holidays:regalo_blanco> : 250,
    <item:moa_decor_holidays:regalo_cafe> : 250,
    <item:moa_decor_holidays:regalo_cian> : 250,
    <item:moa_decor_holidays:regalo_gris> : 250,
    <item:moa_decor_holidays:regalo_gris_claro> : 250,
    <item:moa_decor_holidays:regalo_magenta> : 250,
    <item:moa_decor_holidays:regalo_morado> : 250,
    <item:moa_decor_holidays:regalo_naranja> : 250,
    <item:moa_decor_holidays:regalo_negro> : 250,
    <item:moa_decor_holidays:regalo_rojo> : 250,
    <item:moa_decor_holidays:regalo_rosa> : 250,
    <item:moa_decor_holidays:regalo_verde> : 250,
    <item:moa_decor_holidays:regalo_verde_lima> : 250,
    <item:moa_decor_holidays:santa_claus> : 250,
    <item:moa_decor_holidays:trebol> : 250,
    <item:moa_decor_holidays:trebollargo> : 250,
    <item:moa_decor_holidays:trineo> : 250,
    <item:moa_decor_holidays:tumba> : 250,
    <item:moa_decor_holidays:tumbaabierta> : 250,
    <item:moa_decor_holidays:tumbaesqueleto> : 250,
    <item:moa_decor_holidays:tumbaesqueletosentado> : 250,
    <item:moa_decor_holidays:zombieacostado> : 250,
    <item:moa_decor_holidays:zombieenterrado> : 250,
    <item:moa_decor_holidays:zombiesaliendotierra> : 250
};

// For each item in the map, check if we're in release mode. If we are, anything below 26 EMC/FMC becomes unburnable for EMC
for item, value in priceTable {
    if (release_mode == true){
        if (value < 26 ) {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), 0);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        } else {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        }
    } else {
        CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
        <tag:items:projectextended:blacklist_condenser>.add(item);
        <tag:items:projectextended:blacklist_learning>.add(item);
    }
}