import crafttweaker.api.tag.MCTag;
import crafttweaker.api.item.IItemStack;
import crafttweaker.api.ingredient.IIngredient;
import crafttweaker.api.item.tooltip.ITooltipFunction;
import stdlib.List;
import mods.projecte.CustomEMC;
import mods.projecte.NSSResolver;

// This variable controls whether we are in the pack dev mode or release mode. In Pack Dev mode, all EMC/FMC values are enabled to help calculate EMC/FMC for other mods.
var release_mode = false;

// Item  to EMC/FMC value map.
val priceTable as int[IItemStack] = {
    <item:moa_decor_cookery:aabedul> : 250,
    <item:moa_decor_cookery:aabedulsc> : 250,
    <item:moa_decor_cookery:aabeto> : 250,
    <item:moa_decor_cookery:aabetosc> : 250,
    <item:moa_decor_cookery:aacacia> : 250,
    <item:moa_decor_cookery:aacaciasc> : 250,
    <item:moa_decor_cookery:acarmesi> : 250,
    <item:moa_decor_cookery:acarmesisc> : 250,
    <item:moa_decor_cookery:adistorsionado> : 250,
    <item:moa_decor_cookery:adistorsionadosc> : 250,
    <item:moa_decor_cookery:ajungla> : 250,
    <item:moa_decor_cookery:ajunglasc> : 250,
    <item:moa_decor_cookery:amangle> : 250,
    <item:moa_decor_cookery:amanglesc> : 250,
    <item:moa_decor_cookery:aroble> : 250,
    <item:moa_decor_cookery:arobleosc> : 250,
    <item:moa_decor_cookery:arobleoscsc> : 250,
    <item:moa_decor_cookery:aroblesc> : 250,
    <item:moa_decor_cookery:bandeja> : 250,
    <item:moa_decor_cookery:bandejadegalletas> : 250,
    <item:moa_decor_cookery:barrica> : 250,
    <item:moa_decor_cookery:barril> : 250,
    <item:moa_decor_cookery:barrilacostado> : 250,
    <item:moa_decor_cookery:barrilbetabel> : 250,
    <item:moa_decor_cookery:barrilcerrado> : 250,
    <item:moa_decor_cookery:barrilmanzana> : 250,
    <item:moa_decor_cookery:barrilmanzanadorada> : 250,
    <item:moa_decor_cookery:barrilpapa> : 250,
    <item:moa_decor_cookery:barrilzanahoria> : 250,
    <item:moa_decor_cookery:barrilzanahoriadorada> : 250,
    <item:moa_decor_cookery:betabel> : 250,
    <item:moa_decor_cookery:betabelcortado> : 250,
    <item:moa_decor_cookery:bolsadesemillas> : 250,
    <item:moa_decor_cookery:botelladeleche> : 250,
    <item:moa_decor_cookery:botelladetequila> : 250,
    <item:moa_decor_cookery:botelladevino> : 250,
    <item:moa_decor_cookery:c_abeto> : 250,
    <item:moa_decor_cookery:c_mangle> : 250,
    <item:moa_decor_cookery:c_roble> : 250,
    <item:moa_decor_cookery:cabedul> : 250,
    <item:moa_decor_cookery:cabedulsc> : 250,
    <item:moa_decor_cookery:cabetosc> : 250,
    <item:moa_decor_cookery:cacacia> : 250,
    <item:moa_decor_cookery:cacaciasc> : 250,
    <item:moa_decor_cookery:cafetera> : 250,
    <item:moa_decor_cookery:cajadepizza> : 250,
    <item:moa_decor_cookery:cajadepizzaabierta> : 250,
    <item:moa_decor_cookery:cajasdepizza> : 250,
    <item:moa_decor_cookery:calabaza> : 250,
    <item:moa_decor_cookery:ccarmesi> : 250,
    <item:moa_decor_cookery:ccarmesisc> : 250,
    <item:moa_decor_cookery:cdistorsionado> : 250,
    <item:moa_decor_cookery:cdistorsionadosc> : 250,
    <item:moa_decor_cookery:cestadepicnic> : 250,
    <item:moa_decor_cookery:cjungla> : 250,
    <item:moa_decor_cookery:cjunglasc> : 250,
    <item:moa_decor_cookery:cmanglesc> : 250,
    <item:moa_decor_cookery:copa> : 250,
    <item:moa_decor_cookery:copadevino> : 250,
    <item:moa_decor_cookery:crobleosc> : 250,
    <item:moa_decor_cookery:crobleoscuro_sc> : 250,
    <item:moa_decor_cookery:croblesc> : 250,
    <item:moa_decor_cookery:donas> : 250,
    <item:moa_decor_cookery:escurridordeplatos> : 250,
    <item:moa_decor_cookery:estufa> : 250,
    <item:moa_decor_cookery:estufaabierta> : 250,
    <item:moa_decor_cookery:estufapay> : 250,
    <item:moa_decor_cookery:fabedul> : 250,
    <item:moa_decor_cookery:fabedulsc> : 250,
    <item:moa_decor_cookery:fabeto> : 250,
    <item:moa_decor_cookery:fabetosc> : 250,
    <item:moa_decor_cookery:facacia> : 250,
    <item:moa_decor_cookery:facaciasc> : 250,
    <item:moa_decor_cookery:fcarmesi> : 250,
    <item:moa_decor_cookery:fcarmesisc> : 250,
    <item:moa_decor_cookery:fdistorsionado> : 250,
    <item:moa_decor_cookery:fdistorsionadosc> : 250,
    <item:moa_decor_cookery:fideos> : 250,
    <item:moa_decor_cookery:fjungla> : 250,
    <item:moa_decor_cookery:fjunglasc> : 250,
    <item:moa_decor_cookery:fmangle> : 250,
    <item:moa_decor_cookery:fmanglesc> : 250,
    <item:moa_decor_cookery:frasco> : 250,
    <item:moa_decor_cookery:frascoazucar> : 250,
    <item:moa_decor_cookery:frascocafe> : 250,
    <item:moa_decor_cookery:frascogalletas> : 250,
    <item:moa_decor_cookery:frascosemillas> : 250,
    <item:moa_decor_cookery:froble> : 250,
    <item:moa_decor_cookery:frobleosc> : 250,
    <item:moa_decor_cookery:frobleoscsc> : 250,
    <item:moa_decor_cookery:froblesc> : 250,
    <item:moa_decor_cookery:gemadecocina> : 250,
    <item:moa_decor_cookery:hamburguesa> : 250,
    <item:moa_decor_cookery:hongos> : 250,
    <item:moa_decor_cookery:hongoscortados> : 250,
    <item:moa_decor_cookery:hotdog> : 250,
    <item:moa_decor_cookery:ketchupymostaza> : 250,
    <item:moa_decor_cookery:langosta> : 250,
    <item:moa_decor_cookery:latadeatun> : 250,
    <item:moa_decor_cookery:latasdeatun> : 250,
    <item:moa_decor_cookery:licuadora> : 250,
    <item:moa_decor_cookery:litrodeleche> : 250,
    <item:moa_decor_cookery:manzana> : 250,
    <item:moa_decor_cookery:manzanacortada> : 250,
    <item:moa_decor_cookery:manzanadorada> : 250,
    <item:moa_decor_cookery:manzanadoradacortada> : 250,
    <item:moa_decor_cookery:mermelada> : 250,
    <item:moa_decor_cookery:microondas> : 250,
    <item:moa_decor_cookery:molcajete> : 250,
    <item:moa_decor_cookery:olla> : 250,
    <item:moa_decor_cookery:ollabetabel> : 250,
    <item:moa_decor_cookery:ollaconejo> : 250,
    <item:moa_decor_cookery:ollahongos> : 250,
    <item:moa_decor_cookery:pan> : 250,
    <item:moa_decor_cookery:pancortado> : 250,
    <item:moa_decor_cookery:pandemuerto> : 250,
    <item:moa_decor_cookery:papa> : 250,
    <item:moa_decor_cookery:pasteldechocolate> : 250,
    <item:moa_decor_cookery:pastelgrande> : 250,
    <item:moa_decor_cookery:pavo> : 250,
    <item:moa_decor_cookery:paydecalabaza> : 250,
    <item:moa_decor_cookery:paydemanzana> : 250,
    <item:moa_decor_cookery:pizza> : 250,
    <item:moa_decor_cookery:plato> : 250,
    <item:moa_decor_cookery:platos> : 250,
    <item:moa_decor_cookery:platosypinzas> : 250,
    <item:moa_decor_cookery:queso> : 250,
    <item:moa_decor_cookery:refrigerador> : 250,
    <item:moa_decor_cookery:rodilloymasa> : 250,
    <item:moa_decor_cookery:salypimienta> : 250,
    <item:moa_decor_cookery:sandia> : 250,
    <item:moa_decor_cookery:sandwich> : 250,
    <item:moa_decor_cookery:sarten> : 250,
    <item:moa_decor_cookery:sartenconhuevo> : 250,
    <item:moa_decor_cookery:sopabetabel> : 250,
    <item:moa_decor_cookery:sopaconejo> : 250,
    <item:moa_decor_cookery:sopahongos> : 250,
    <item:moa_decor_cookery:soportedelantal> : 250,
    <item:moa_decor_cookery:soporteinstrumentos> : 250,
    <item:moa_decor_cookery:soportetazas> : 250,
    <item:moa_decor_cookery:sushi> : 250,
    <item:moa_decor_cookery:tabladecortar> : 250,
    <item:moa_decor_cookery:tacos> : 250,
    <item:moa_decor_cookery:tarro> : 250,
    <item:moa_decor_cookery:tarrodecerveza> : 250,
    <item:moa_decor_cookery:taza> : 250,
    <item:moa_decor_cookery:tazadecafe> : 250,
    <item:moa_decor_cookery:tazon> : 250,
    <item:moa_decor_cookery:tazonazucar> : 250,
    <item:moa_decor_cookery:tetera> : 250,
    <item:moa_decor_cookery:tostador> : 250,
    <item:moa_decor_cookery:waffles> : 250,
    <item:moa_decor_cookery:zanahoria> : 250,
    <item:moa_decor_cookery:zanahoriacortada> : 250,
    <item:moa_decor_cookery:zanahoriadorada> : 250,
    <item:moa_decor_cookery:zanahoriadoradacortada> : 250
};

// For each item in the map, check if we're in release mode. If we are, anything below 26 EMC/FMC becomes unburnable for EMC
for item, value in priceTable {
    if (release_mode == true){
        if (value < 26 ) {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), 0);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        } else {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        }
    } else {
        CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
        <tag:items:projectextended:blacklist_condenser>.add(item);
        <tag:items:projectextended:blacklist_learning>.add(item);
    }
}