import crafttweaker.api.text.TextComponent;
import crafttweaker.api.tag.MCTag;
import crafttweaker.api.item.IItemStack;
import crafttweaker.api.ingredient.IIngredient;
import crafttweaker.api.item.tooltip.ITooltipFunction;
import stdlib.List;
import mods.projecte.CustomEMC;
import mods.projecte.NSSResolver;

// Item  to EMC/FMC value map.
val priceTable as int[IItemStack] = {
    <item:moa_decor_toys:abeja> : 250,
    <item:moa_decor_toys:ajoloteazul> : 250,
    <item:moa_decor_toys:ajolotecafe> : 250,
    <item:moa_decor_toys:ajolotecian> : 250,
    <item:moa_decor_toys:ajolotedorado> : 250,
    <item:moa_decor_toys:ajoloterosa> : 250,
    <item:moa_decor_toys:aldeano> : 250,
    <item:moa_decor_toys:aldeanodesierto> : 250,
    <item:moa_decor_toys:aldeanoinvierno> : 250,
    <item:moa_decor_toys:aldeanojungla> : 250,
    <item:moa_decor_toys:aldeanopantano> : 250,
    <item:moa_decor_toys:aldeanosabana> : 250,
    <item:moa_decor_toys:aldeanotaiga> : 250,
    <item:moa_decor_toys:aleanozombie> : 250,
    <item:moa_decor_toys:alex> : 250,
    <item:moa_decor_toys:allay> : 250,
    <item:moa_decor_toys:arana> : 250,
    <item:moa_decor_toys:aranadelascuevas> : 250,
    <item:moa_decor_toys:aranayesqueleto> : 250,
    <item:moa_decor_toys:blaze> : 250,
    <item:moa_decor_toys:bruja> : 250,
    <item:moa_decor_toys:burro> : 250,
    <item:moa_decor_toys:caballoblanco> : 250,
    <item:moa_decor_toys:caballoblanco_h> : 250,
    <item:moa_decor_toys:caballocafe> : 250,
    <item:moa_decor_toys:caballocafe_c> : 250,
    <item:moa_decor_toys:caballocafe_h> : 250,
    <item:moa_decor_toys:caballocafe_m> : 250,
    <item:moa_decor_toys:caballocafe_r> : 250,
    <item:moa_decor_toys:caballocafeosc> : 250,
    <item:moa_decor_toys:caballocafeosc_c> : 250,
    <item:moa_decor_toys:caballocafeosc_h> : 250,
    <item:moa_decor_toys:caballocafeosc_m_1> : 250,
    <item:moa_decor_toys:caballocafeosc_r> : 250,
    <item:moa_decor_toys:caballocastano> : 250,
    <item:moa_decor_toys:caballocastano_c> : 250,
    <item:moa_decor_toys:caballocastano_h> : 250,
    <item:moa_decor_toys:caballocastano_m> : 250,
    <item:moa_decor_toys:caballocastano_r> : 250,
    <item:moa_decor_toys:caballocrema> : 250,
    <item:moa_decor_toys:caballocrema_c> : 250,
    <item:moa_decor_toys:caballocrema_h> : 250,
    <item:moa_decor_toys:caballocrema_m> : 250,
    <item:moa_decor_toys:caballocrema_r> : 250,
    <item:moa_decor_toys:caballoesqueleto> : 250,
    <item:moa_decor_toys:caballoesqueletoyesqueleto> : 250,
    <item:moa_decor_toys:caballogris> : 250,
    <item:moa_decor_toys:caballogris_c> : 250,
    <item:moa_decor_toys:caballogris_h> : 250,
    <item:moa_decor_toys:caballogris_m> : 250,
    <item:moa_decor_toys:caballogris_r> : 250,
    <item:moa_decor_toys:caballonegro> : 250,
    <item:moa_decor_toys:caballonegro_c> : 250,
    <item:moa_decor_toys:caballonegro_h> : 250,
    <item:moa_decor_toys:caballonegro_m> : 250,
    <item:moa_decor_toys:caballonegro_r> : 250,
    <item:moa_decor_toys:cabra> : 250,
    <item:moa_decor_toys:calamar> : 250,
    <item:moa_decor_toys:calamarbrillante> : 250,
    <item:moa_decor_toys:camello> : 250,
    <item:moa_decor_toys:cerdo> : 250,
    <item:moa_decor_toys:champivaca> : 250,
    <item:moa_decor_toys:conejoblanco> : 250,
    <item:moa_decor_toys:conejoblancoynegro> : 250,
    <item:moa_decor_toys:conejocafe> : 250,
    <item:moa_decor_toys:conejocastano> : 250,
    <item:moa_decor_toys:conejodorado> : 250,
    <item:moa_decor_toys:conejonegro> : 250,
    <item:moa_decor_toys:creeper> : 250,
    <item:moa_decor_toys:cubodemagma> : 250,
    <item:moa_decor_toys:delfin> : 250,
    <item:moa_decor_toys:devastador> : 250,
    <item:moa_decor_toys:devastadorysaqueador> : 250,
    <item:moa_decor_toys:dragondelender> : 250,
    <item:moa_decor_toys:enderman> : 250,
    <item:moa_decor_toys:endermite> : 250,
    <item:moa_decor_toys:esqueleto> : 250,
    <item:moa_decor_toys:esqueletoglacial> : 250,
    <item:moa_decor_toys:esqueletowither> : 250,
    <item:moa_decor_toys:fantasma> : 250,
    <item:moa_decor_toys:gallina> : 250,
    <item:moa_decor_toys:gallinayahogado> : 250,
    <item:moa_decor_toys:gallinayjinetealdeanozombie> : 250,
    <item:moa_decor_toys:gallinaypiglinzombie> : 250,
    <item:moa_decor_toys:gallinayzombie> : 250,
    <item:moa_decor_toys:gallinayzombiemomificado> : 250,
    <item:moa_decor_toys:gatoatigrado> : 250,
    <item:moa_decor_toys:gatoblanco> : 250,
    <item:moa_decor_toys:gatobritanico> : 250,
    <item:moa_decor_toys:gatocalico> : 250,
    <item:moa_decor_toys:gatojellie> : 250,
    <item:moa_decor_toys:gatonegro> : 250,
    <item:moa_decor_toys:gatopersa> : 250,
    <item:moa_decor_toys:gatoragdoll> : 250,
    <item:moa_decor_toys:gatosiames> : 250,
    <item:moa_decor_toys:gatotabby> : 250,
    <item:moa_decor_toys:gatotuxedo> : 250,
    <item:moa_decor_toys:gemadejuguetes> : 250,
    <item:moa_decor_toys:ghast> : 250,
    <item:moa_decor_toys:golemdehierro> : 250,
    <item:moa_decor_toys:golemdenieve> : 250,
    <item:moa_decor_toys:guardian> : 250,
    <item:moa_decor_toys:guardiananciano> : 250,
    <item:moa_decor_toys:hoglin> : 250,
    <item:moa_decor_toys:invocador> : 250,
    <item:moa_decor_toys:lavagante> : 250,
    <item:moa_decor_toys:lavaganteypiglinzombie> : 250,
    <item:moa_decor_toys:lepisma> : 250,
    <item:moa_decor_toys:llamablanca> : 250,
    <item:moa_decor_toys:llamacafe> : 250,
    <item:moa_decor_toys:llamacrema> : 250,
    <item:moa_decor_toys:llamagris> : 250,
    <item:moa_decor_toys:lobo> : 250,
    <item:moa_decor_toys:loroazul> : 250,
    <item:moa_decor_toys:lorocian> : 250,
    <item:moa_decor_toys:lorogris> : 250,
    <item:moa_decor_toys:lororojo> : 250,
    <item:moa_decor_toys:loroverde> : 250,
    <item:moa_decor_toys:mula> : 250,
    <item:moa_decor_toys:murcielago> : 250,
    <item:moa_decor_toys:ocelote> : 250,
    <item:moa_decor_toys:osopolar> : 250,
    <item:moa_decor_toys:ovejaamarilla> : 250,
    <item:moa_decor_toys:ovejaazul> : 250,
    <item:moa_decor_toys:ovejaazulclara> : 250,
    <item:moa_decor_toys:ovejablanca> : 250,
    <item:moa_decor_toys:ovejacafe> : 250,
    <item:moa_decor_toys:ovejacian> : 250,
    <item:moa_decor_toys:ovejagris> : 250,
    <item:moa_decor_toys:ovejagrisclara> : 250,
    <item:moa_decor_toys:ovejamagenta> : 250,
    <item:moa_decor_toys:ovejamorada> : 250,
    <item:moa_decor_toys:ovejanaranja> : 250,
    <item:moa_decor_toys:ovejanegra> : 250,
    <item:moa_decor_toys:ovejaroja> : 250,
    <item:moa_decor_toys:ovejarosa> : 250,
    <item:moa_decor_toys:ovejaverde> : 250,
    <item:moa_decor_toys:ovejaverdelima> : 250,
    <item:moa_decor_toys:panda> : 250,
    <item:moa_decor_toys:piglin> : 250,
    <item:moa_decor_toys:piglinbruto> : 250,
    <item:moa_decor_toys:piglinzombie> : 250,
    <item:moa_decor_toys:ranacalida> : 250,
    <item:moa_decor_toys:ranahelada> : 250,
    <item:moa_decor_toys:ranatemplada> : 250,
    <item:moa_decor_toys:saqueador> : 250,
    <item:moa_decor_toys:shulker> : 250,
    <item:moa_decor_toys:slime> : 250,
    <item:moa_decor_toys:sniffer> : 250,
    <item:moa_decor_toys:steve> : 250,
    <item:moa_decor_toys:tortugamarina> : 250,
    <item:moa_decor_toys:vaca> : 250,
    <item:moa_decor_toys:vendedorambulante> : 250,
    <item:moa_decor_toys:vex> : 250,
    <item:moa_decor_toys:vindicador> : 250,
    <item:moa_decor_toys:warden> : 250,
    <item:moa_decor_toys:wither> : 250,
    <item:moa_decor_toys:zoglin> : 250,
    <item:moa_decor_toys:zombie> : 250,
    <item:moa_decor_toys:zombieahogado> : 250,
    <item:moa_decor_toys:zombiemomificado> : 250,
    <item:moa_decor_toys:zorro> : 250,
    <item:moa_decor_toys:zorroblanco> : 250
};

// For each item in the map, check if we're in release mode. If we are, anything below 26 EMC/FMC becomes unburnable for EMC
for item, value in priceTable {
    if (ReleaseMode.releaseMode == true){
        if (value < 26 ) {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), 0);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        } else {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
            item.addTooltip(new TextComponent("Lost Deco").withStyle(style => style.withColor(<constant:minecraft:formatting:gold>)));
            item.addTooltip(new TextComponent("Only Found in the Liminal Mall").withStyle(style => style.withColor(<constant:minecraft:formatting:gold>)));
        }
    } else {
        CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
        <tag:items:projectextended:blacklist_condenser>.add(item);
        <tag:items:projectextended:blacklist_learning>.add(item);
            item.addTooltip(new TextComponent("Lost Deco").withStyle(style => style.withColor(<constant:minecraft:formatting:gold>)));
            item.addTooltip(new TextComponent("Only Found in the Liminal Mall").withStyle(style => style.withColor(<constant:minecraft:formatting:gold>)));
    }
}