import crafttweaker.api.tag.MCTag;
import crafttweaker.api.item.IItemStack;
import crafttweaker.api.ingredient.IIngredient;
import crafttweaker.api.item.tooltip.ITooltipFunction;
import stdlib.List;
import mods.projecte.CustomEMC;
import mods.projecte.NSSResolver;

// This variable controls whether we are in the pack dev mode or release mode. In Pack Dev mode, all EMC/FMC values are enabled to help calculate EMC/FMC for other mods.
var release_mode = false;

// Item  to EMC/FMC value map.
val priceTable as int[IItemStack] = {
    <item:moa_decor_art:acuarelas> : 250,
    <item:moa_decor_art:aerosolamarillo> : 250,
    <item:moa_decor_art:aerosolazul> : 250,
    <item:moa_decor_art:aerosolazulclaro> : 250,
    <item:moa_decor_art:aerosolblanco> : 250,
    <item:moa_decor_art:aerosolcafe> : 250,
    <item:moa_decor_art:aerosolcian> : 250,
    <item:moa_decor_art:aerosolgris> : 250,
    <item:moa_decor_art:aerosolgrisclaro> : 250,
    <item:moa_decor_art:aerosolmagenta> : 250,
    <item:moa_decor_art:aerosolmorado> : 250,
    <item:moa_decor_art:aerosolnaranja> : 250,
    <item:moa_decor_art:aerosolnegro> : 250,
    <item:moa_decor_art:aerosolrojo> : 250,
    <item:moa_decor_art:aerosolrosa> : 250,
    <item:moa_decor_art:aerosolverde> : 250,
    <item:moa_decor_art:aerosolverdelima> : 250,
    <item:moa_decor_art:amplificador> : 250,
    <item:moa_decor_art:arpa> : 250,
    <item:moa_decor_art:banyo> : 250,
    <item:moa_decor_art:bateriaamarilla> : 250,
    <item:moa_decor_art:bateriaazul> : 250,
    <item:moa_decor_art:bateriaazulclara> : 250,
    <item:moa_decor_art:bateriablanca> : 250,
    <item:moa_decor_art:bateriacafe> : 250,
    <item:moa_decor_art:bateriacian> : 250,
    <item:moa_decor_art:bateriagris> : 250,
    <item:moa_decor_art:bateriagrisclaro> : 250,
    <item:moa_decor_art:bateriamagenta> : 250,
    <item:moa_decor_art:bateriamorada> : 250,
    <item:moa_decor_art:baterianaranja> : 250,
    <item:moa_decor_art:baterianegra> : 250,
    <item:moa_decor_art:bateriaroja> : 250,
    <item:moa_decor_art:bateriarosa> : 250,
    <item:moa_decor_art:bateriaverde> : 250,
    <item:moa_decor_art:bateriaverdelima> : 250,
    <item:moa_decor_art:caballete> : 250,
    <item:moa_decor_art:caballeteconlamonalisa> : 250,
    <item:moa_decor_art:caballeteelgrito> : 250,
    <item:moa_decor_art:caballetegoticoestadounidense> : 250,
    <item:moa_decor_art:caballetelajovendelaperla> : 250,
    <item:moa_decor_art:caballetelanocheestrellada> : 250,
    <item:moa_decor_art:caballetelienzo> : 250,
    <item:moa_decor_art:caballeteserenatamexicana> : 250,
    <item:moa_decor_art:camaradecine> : 250,
    <item:moa_decor_art:claqueta> : 250,
    <item:moa_decor_art:esculturabuda> : 250,
    <item:moa_decor_art:esculturachacmool> : 250,
    <item:moa_decor_art:esculturadragonchino> : 250,
    <item:moa_decor_art:esculturaeldavid> : 250,
    <item:moa_decor_art:esculturaeldiscobolo> : 250,
    <item:moa_decor_art:esculturaelpensador> : 250,
    <item:moa_decor_art:esculturajesuscrucificado> : 250,
    <item:moa_decor_art:esculturalavictoriodesamotracia> : 250,
    <item:moa_decor_art:esculturamujerconjarra> : 250,
    <item:moa_decor_art:esculturavenusdemilo> : 250,
    <item:moa_decor_art:fonografo> : 250,
    <item:moa_decor_art:gafas_3d> : 250,
    <item:moa_decor_art:gemadearte> : 250,
    <item:moa_decor_art:guitarra> : 250,
    <item:moa_decor_art:guitarraelectricaamarilla> : 250,
    <item:moa_decor_art:guitarraelectricaazul> : 250,
    <item:moa_decor_art:guitarraelectricaazulclara> : 250,
    <item:moa_decor_art:guitarraelectricablanca> : 250,
    <item:moa_decor_art:guitarraelectricacafe> : 250,
    <item:moa_decor_art:guitarraelectricacian> : 250,
    <item:moa_decor_art:guitarraelectricagris> : 250,
    <item:moa_decor_art:guitarraelectricagrisclara> : 250,
    <item:moa_decor_art:guitarraelectricamagenta> : 250,
    <item:moa_decor_art:guitarraelectricamorada> : 250,
    <item:moa_decor_art:guitarraelectricanaranja> : 250,
    <item:moa_decor_art:guitarraelectricanegra> : 250,
    <item:moa_decor_art:guitarraelectricaroja> : 250,
    <item:moa_decor_art:guitarraelectricarosa> : 250,
    <item:moa_decor_art:guitarraelectricaverde> : 250,
    <item:moa_decor_art:guitarraelectricaverdelima> : 250,
    <item:moa_decor_art:hiloamarillo> : 250,
    <item:moa_decor_art:hiloazul> : 250,
    <item:moa_decor_art:hiloazulclaro> : 250,
    <item:moa_decor_art:hiloblanco> : 250,
    <item:moa_decor_art:hilocafe> : 250,
    <item:moa_decor_art:hilocian> : 250,
    <item:moa_decor_art:hilogris> : 250,
    <item:moa_decor_art:hilogrisclaro> : 250,
    <item:moa_decor_art:hilomagenta> : 250,
    <item:moa_decor_art:hilomorado> : 250,
    <item:moa_decor_art:hilonaranja> : 250,
    <item:moa_decor_art:hilonegro> : 250,
    <item:moa_decor_art:hilorojo> : 250,
    <item:moa_decor_art:hilorosa> : 250,
    <item:moa_decor_art:hiloverde> : 250,
    <item:moa_decor_art:hiloverdelima> : 250,
    <item:moa_decor_art:lienzo> : 250,
    <item:moa_decor_art:maniqui> : 250,
    <item:moa_decor_art:maquinadecoser> : 250,
    <item:moa_decor_art:maquinadediscos> : 250,
    <item:moa_decor_art:martilloycincel> : 250,
    <item:moa_decor_art:mezcladordj> : 250,
    <item:moa_decor_art:microfono> : 250,
    <item:moa_decor_art:microfonoenpedestal> : 250,
    <item:moa_decor_art:paletadepintura> : 250,
    <item:moa_decor_art:pelgrito> : 250,
    <item:moa_decor_art:pgoticoestadounidense> : 250,
    <item:moa_decor_art:pianodecola> : 250,
    <item:moa_decor_art:pincelesenagua> : 250,
    <item:moa_decor_art:pinturaamarilla> : 250,
    <item:moa_decor_art:pinturaazul> : 250,
    <item:moa_decor_art:pinturaazulclara> : 250,
    <item:moa_decor_art:pinturablanca> : 250,
    <item:moa_decor_art:pinturacafe> : 250,
    <item:moa_decor_art:pinturacian> : 250,
    <item:moa_decor_art:pinturagris> : 250,
    <item:moa_decor_art:pinturagrisclara> : 250,
    <item:moa_decor_art:pinturamagenta> : 250,
    <item:moa_decor_art:pinturamorada> : 250,
    <item:moa_decor_art:pinturanaranja> : 250,
    <item:moa_decor_art:pinturanegra> : 250,
    <item:moa_decor_art:pinturaroja> : 250,
    <item:moa_decor_art:pinturarosa> : 250,
    <item:moa_decor_art:pinturaverde> : 250,
    <item:moa_decor_art:pinturaverdelima> : 250,
    <item:moa_decor_art:plajovendelaperla> : 250,
    <item:moa_decor_art:plamonalisa> : 250,
    <item:moa_decor_art:planocheestrellada> : 250,
    <item:moa_decor_art:premiogrammy> : 250,
    <item:moa_decor_art:premiooscar> : 250,
    <item:moa_decor_art:pserenatamexicana> : 250,
    <item:moa_decor_art:reflector> : 250,
    <item:moa_decor_art:rollodepelicula> : 250,
    <item:moa_decor_art:rollosdepelicula> : 250,
    <item:moa_decor_art:silladedirector> : 250,
    <item:moa_decor_art:tamboramarillo> : 250,
    <item:moa_decor_art:tamborazul> : 250,
    <item:moa_decor_art:tamborazulclaro> : 250,
    <item:moa_decor_art:tamborblanco> : 250,
    <item:moa_decor_art:tamborcafe> : 250,
    <item:moa_decor_art:tamborcian> : 250,
    <item:moa_decor_art:tamborgris> : 250,
    <item:moa_decor_art:tamborgrisclaro> : 250,
    <item:moa_decor_art:tambormagenta> : 250,
    <item:moa_decor_art:tambormorado> : 250,
    <item:moa_decor_art:tambornaranja> : 250,
    <item:moa_decor_art:tambornegro> : 250,
    <item:moa_decor_art:tamborrojo> : 250,
    <item:moa_decor_art:tamborrosa> : 250,
    <item:moa_decor_art:tamborverde> : 250,
    <item:moa_decor_art:tamborverdelima> : 250,
    <item:moa_decor_art:tecladomusical> : 250,
    <item:moa_decor_art:tijeras> : 250,
    <item:moa_decor_art:tocadiscos> : 250,
    <item:moa_decor_art:violin> : 250
};

// For each item in the map, check if we're in release mode. If we are, anything below 26 EMC/FMC becomes unburnable for EMC
for item, value in priceTable {
    if (release_mode == true){
        if (value < 26 ) {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), 0);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        } else {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        }
    } else {
        CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
        <tag:items:projectextended:blacklist_condenser>.add(item);
        <tag:items:projectextended:blacklist_learning>.add(item);
    }
}