import crafttweaker.api.tag.MCTag;
import crafttweaker.api.item.IItemStack;
import crafttweaker.api.ingredient.IIngredient;
import crafttweaker.api.item.tooltip.ITooltipFunction;
import stdlib.List;
import mods.projecte.CustomEMC;
import mods.projecte.NSSResolver;

// This variable controls whether we are in the pack dev mode or release mode. In Pack Dev mode, all EMC/FMC values are enabled to help calculate EMC/FMC for other mods.
var release_mode = false;

// Item  to EMC/FMC value map.
val priceTable as int[IItemStack] = {
    <item:moa_decor_science:barrilinflamable> : 250,
    <item:moa_decor_science:barrilinflamablederramado> : 250,
    <item:moa_decor_science:barriltoxico> : 250,
    <item:moa_decor_science:barriltoxicoderramado> : 250,
    <item:moa_decor_science:bascula> : 250,
    <item:moa_decor_science:biombomamarillo> : 250,
    <item:moa_decor_science:biombomazul> : 250,
    <item:moa_decor_science:biombomazulclaro> : 250,
    <item:moa_decor_science:biombomblanco> : 250,
    <item:moa_decor_science:biombomcafe> : 250,
    <item:moa_decor_science:biombomcian> : 250,
    <item:moa_decor_science:biombomgris> : 250,
    <item:moa_decor_science:biombomgrisclaro> : 250,
    <item:moa_decor_science:biombommagenta> : 250,
    <item:moa_decor_science:biombommorado> : 250,
    <item:moa_decor_science:biombomnaranja> : 250,
    <item:moa_decor_science:biombomnegro> : 250,
    <item:moa_decor_science:biombomrojo> : 250,
    <item:moa_decor_science:biombomrosa> : 250,
    <item:moa_decor_science:biombomverde> : 250,
    <item:moa_decor_science:biombomverdelima> : 250,
    <item:moa_decor_science:botiquindepared> : 250,
    <item:moa_decor_science:brujula> : 250,
    <item:moa_decor_science:calculadora> : 250,
    <item:moa_decor_science:camahamarilla> : 250,
    <item:moa_decor_science:camahazul> : 250,
    <item:moa_decor_science:camahazulclara> : 250,
    <item:moa_decor_science:camahblanca> : 250,
    <item:moa_decor_science:camahcafe> : 250,
    <item:moa_decor_science:camahcian> : 250,
    <item:moa_decor_science:camahgris> : 250,
    <item:moa_decor_science:camahgrisclara> : 250,
    <item:moa_decor_science:camahmagenta> : 250,
    <item:moa_decor_science:camahmorada> : 250,
    <item:moa_decor_science:camahnaranja> : 250,
    <item:moa_decor_science:camahnegra> : 250,
    <item:moa_decor_science:camahroja> : 250,
    <item:moa_decor_science:camahrosa> : 250,
    <item:moa_decor_science:camahverde> : 250,
    <item:moa_decor_science:camahverdelima> : 250,
    <item:moa_decor_science:documento> : 250,
    <item:moa_decor_science:documentos> : 250,
    <item:moa_decor_science:frascodepildoras> : 250,
    <item:moa_decor_science:frascodepildorasabierto> : 250,
    <item:moa_decor_science:gemadeciencia> : 250,
    <item:moa_decor_science:globoterraqueo> : 250,
    <item:moa_decor_science:jeringa> : 250,
    <item:moa_decor_science:jeringaamarilla> : 250,
    <item:moa_decor_science:jeringaazul> : 250,
    <item:moa_decor_science:jeringaazulclara> : 250,
    <item:moa_decor_science:jeringablanca> : 250,
    <item:moa_decor_science:jeringacafe> : 250,
    <item:moa_decor_science:jeringacian> : 250,
    <item:moa_decor_science:jeringagris> : 250,
    <item:moa_decor_science:jeringagrisclara> : 250,
    <item:moa_decor_science:jeringamagenta> : 250,
    <item:moa_decor_science:jeringamorada> : 250,
    <item:moa_decor_science:jeringanaranja> : 250,
    <item:moa_decor_science:jeringanegra> : 250,
    <item:moa_decor_science:jeringaroja> : 250,
    <item:moa_decor_science:jeringarosa> : 250,
    <item:moa_decor_science:jeringaverde> : 250,
    <item:moa_decor_science:jeringaverdelima> : 250,
    <item:moa_decor_science:lectordesignosvitales> : 250,
    <item:moa_decor_science:libro> : 250,
    <item:moa_decor_science:libroabierto> : 250,
    <item:moa_decor_science:libros> : 250,
    <item:moa_decor_science:librosapilados> : 250,
    <item:moa_decor_science:libroytintero> : 250,
    <item:moa_decor_science:lupa> : 250,
    <item:moa_decor_science:mapadeltesoro> : 250,
    <item:moa_decor_science:matrazb> : 250,
    <item:moa_decor_science:matrazbamarillo> : 250,
    <item:moa_decor_science:matrazbazul> : 250,
    <item:moa_decor_science:matrazbazulclaro> : 250,
    <item:moa_decor_science:matrazbblanco> : 250,
    <item:moa_decor_science:matrazbcafe> : 250,
    <item:moa_decor_science:matrazbcian> : 250,
    <item:moa_decor_science:matrazbgris> : 250,
    <item:moa_decor_science:matrazbgrisclaro> : 250,
    <item:moa_decor_science:matrazbmagenta> : 250,
    <item:moa_decor_science:matrazbmorado> : 250,
    <item:moa_decor_science:matrazbnaranja> : 250,
    <item:moa_decor_science:matrazbnegro> : 250,
    <item:moa_decor_science:matrazbrojo> : 250,
    <item:moa_decor_science:matrazbrosa> : 250,
    <item:moa_decor_science:matrazbverde> : 250,
    <item:moa_decor_science:matrazbverdelima> : 250,
    <item:moa_decor_science:microscopio> : 250,
    <item:moa_decor_science:pergamino> : 250,
    <item:moa_decor_science:pergaminoenrollado> : 250,
    <item:moa_decor_science:pergaminos> : 250,
    <item:moa_decor_science:pizarra> : 250,
    <item:moa_decor_science:pizarraabecedario> : 250,
    <item:moa_decor_science:pizarraadn> : 250,
    <item:moa_decor_science:pizarramatematicas> : 250,
    <item:moa_decor_science:pizarravolumenes> : 250,
    <item:moa_decor_science:portapapeles> : 250,
    <item:moa_decor_science:sueroamarillo> : 250,
    <item:moa_decor_science:sueroazul> : 250,
    <item:moa_decor_science:sueroazulclaro> : 250,
    <item:moa_decor_science:sueroblanco> : 250,
    <item:moa_decor_science:suerocafe> : 250,
    <item:moa_decor_science:suerocian> : 250,
    <item:moa_decor_science:suerogris> : 250,
    <item:moa_decor_science:suerogrisclaro> : 250,
    <item:moa_decor_science:sueromagenta> : 250,
    <item:moa_decor_science:sueromorado> : 250,
    <item:moa_decor_science:sueronaranja> : 250,
    <item:moa_decor_science:sueronegro> : 250,
    <item:moa_decor_science:suerorojo> : 250,
    <item:moa_decor_science:suerorosa> : 250,
    <item:moa_decor_science:sueroverde> : 250,
    <item:moa_decor_science:sueroverdelima> : 250,
    <item:moa_decor_science:telescopio> : 250,
    <item:moa_decor_science:tintero> : 250,
    <item:moa_decor_science:tuboensayo> : 250,
    <item:moa_decor_science:tuboensayoamarillo> : 250,
    <item:moa_decor_science:tuboensayoazul> : 250,
    <item:moa_decor_science:tuboensayoazulclaro> : 250,
    <item:moa_decor_science:tuboensayoblanco> : 250,
    <item:moa_decor_science:tuboensayocafe> : 250,
    <item:moa_decor_science:tuboensayocian> : 250,
    <item:moa_decor_science:tuboensayogris> : 250,
    <item:moa_decor_science:tuboensayogrisclaro> : 250,
    <item:moa_decor_science:tuboensayomagenta> : 250,
    <item:moa_decor_science:tuboensayomorado> : 250,
    <item:moa_decor_science:tuboensayonaranja> : 250,
    <item:moa_decor_science:tuboensayonegro> : 250,
    <item:moa_decor_science:tuboensayorojo> : 250,
    <item:moa_decor_science:tuboensayorosa> : 250,
    <item:moa_decor_science:tuboensayoverde> : 250,
    <item:moa_decor_science:tuboensayoverdelima> : 250,
    <item:moa_decor_science:tubosensayo> : 250,
    <item:moa_decor_science:tubosensayoamarillo> : 250,
    <item:moa_decor_science:tubosensayoazul> : 250,
    <item:moa_decor_science:tubosensayoazulclaro> : 250,
    <item:moa_decor_science:tubosensayoblanco> : 250,
    <item:moa_decor_science:tubosensayocafe> : 250,
    <item:moa_decor_science:tubosensayocian> : 250,
    <item:moa_decor_science:tubosensayogris> : 250,
    <item:moa_decor_science:tubosensayogrisclaro> : 250,
    <item:moa_decor_science:tubosensayomagenta> : 250,
    <item:moa_decor_science:tubosensayomorado> : 250,
    <item:moa_decor_science:tubosensayonaranja> : 250,
    <item:moa_decor_science:tubosensayonegro> : 250,
    <item:moa_decor_science:tubosensayorojo> : 250,
    <item:moa_decor_science:tubosensayorosa> : 250,
    <item:moa_decor_science:tubosensayoverde> : 250,
    <item:moa_decor_science:tubosensayoverdelima> : 250,
    <item:moa_decor_science:veneno> : 250
};

// For each item in the map, check if we're in release mode. If we are, anything below 26 EMC/FMC becomes unburnable for EMC
for item, value in priceTable {
    if (release_mode == true){
        if (value < 26 ) {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), 0);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        } else {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        }
    } else {
        CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
        <tag:items:projectextended:blacklist_condenser>.add(item);
        <tag:items:projectextended:blacklist_learning>.add(item);
    }
}