import crafttweaker.api.text.TextComponent;
import crafttweaker.api.tag.MCTag;
import crafttweaker.api.item.IItemStack;
import crafttweaker.api.ingredient.IIngredient;
import crafttweaker.api.item.tooltip.ITooltipFunction;
import stdlib.List;
import mods.projecte.CustomEMC;
import mods.projecte.NSSResolver;

// Item  to EMC/FMC value map.
val priceTable as int[IItemStack] = {
    <item:moa_decor_bath:babedul> : 250,
    <item:moa_decor_bath:babedulsc> : 250,
    <item:moa_decor_bath:babeto> : 250,
    <item:moa_decor_bath:babetosc> : 250,
    <item:moa_decor_bath:bacacia> : 250,
    <item:moa_decor_bath:bacaciasc> : 250,
    <item:moa_decor_bath:banera> : 250,
    <item:moa_decor_bath:barradebanohorizontal> : 250,
    <item:moa_decor_bath:barradebanovertical> : 250,
    <item:moa_decor_bath:bataamarilla> : 250,
    <item:moa_decor_bath:bataazul> : 250,
    <item:moa_decor_bath:bataazulclara> : 250,
    <item:moa_decor_bath:batablanca> : 250,
    <item:moa_decor_bath:batacafe> : 250,
    <item:moa_decor_bath:batacian> : 250,
    <item:moa_decor_bath:batagris> : 250,
    <item:moa_decor_bath:batagrisclara> : 250,
    <item:moa_decor_bath:batamagenta> : 250,
    <item:moa_decor_bath:batamorada> : 250,
    <item:moa_decor_bath:batanaranja> : 250,
    <item:moa_decor_bath:batanegra> : 250,
    <item:moa_decor_bath:bataroja> : 250,
    <item:moa_decor_bath:batarosa> : 250,
    <item:moa_decor_bath:bataverde> : 250,
    <item:moa_decor_bath:bataverdelima> : 250,
    <item:moa_decor_bath:bcarmesi> : 250,
    <item:moa_decor_bath:bcarmesisc> : 250,
    <item:moa_decor_bath:bdistorsionado> : 250,
    <item:moa_decor_bath:bdistorsionadosc> : 250,
    <item:moa_decor_bath:bjungla> : 250,
    <item:moa_decor_bath:bjunglasc> : 250,
    <item:moa_decor_bath:bmanglar> : 250,
    <item:moa_decor_bath:bmanglarsc> : 250,
    <item:moa_decor_bath:broble> : 250,
    <item:moa_decor_bath:brobleosc> : 250,
    <item:moa_decor_bath:brobleoscsc> : 250,
    <item:moa_decor_bath:broblesc> : 250,
    <item:moa_decor_bath:c_tamarillas> : 250,
    <item:moa_decor_bath:c_tazules> : 250,
    <item:moa_decor_bath:c_tazulesclaras> : 250,
    <item:moa_decor_bath:c_tblancas> : 250,
    <item:moa_decor_bath:c_tcafes> : 250,
    <item:moa_decor_bath:c_tcian> : 250,
    <item:moa_decor_bath:c_tgrises> : 250,
    <item:moa_decor_bath:c_tgrisesclaras> : 250,
    <item:moa_decor_bath:c_tmagentas> : 250,
    <item:moa_decor_bath:c_tmoradas> : 250,
    <item:moa_decor_bath:c_tnaranjas> : 250,
    <item:moa_decor_bath:c_tnegras> : 250,
    <item:moa_decor_bath:c_trojas> : 250,
    <item:moa_decor_bath:c_trosas> : 250,
    <item:moa_decor_bath:c_tverdes> : 250,
    <item:moa_decor_bath:c_tverdeslima> : 250,
    <item:moa_decor_bath:cubetadeagua> : 250,
    <item:moa_decor_bath:destapador> : 250,
    <item:moa_decor_bath:esco> : 250,
    <item:moa_decor_bath:esp_b> : 250,
    <item:moa_decor_bath:esp_bcent> : 250,
    <item:moa_decor_bath:esp_bder> : 250,
    <item:moa_decor_bath:esp_bizq> : 250,
    <item:moa_decor_bath:esp_c> : 250,
    <item:moa_decor_bath:esp_ccent> : 250,
    <item:moa_decor_bath:esp_cder> : 250,
    <item:moa_decor_bath:esp_cizq> : 250,
    <item:moa_decor_bath:esp_d> : 250,
    <item:moa_decor_bath:esp_dcent> : 250,
    <item:moa_decor_bath:esp_dder> : 250,
    <item:moa_decor_bath:esp_dizq> : 250,
    <item:moa_decor_bath:esp_n> : 250,
    <item:moa_decor_bath:esp_ncent> : 250,
    <item:moa_decor_bath:esp_nder> : 250,
    <item:moa_decor_bath:esp_nizq> : 250,
    <item:moa_decor_bath:esponjadebano> : 250,
    <item:moa_decor_bath:gemadbano> : 250,
    <item:moa_decor_bath:inodoro> : 250,
    <item:moa_decor_bath:jabon> : 250,
    <item:moa_decor_bath:jabonera> : 250,
    <item:moa_decor_bath:jaboneradepared> : 250,
    <item:moa_decor_bath:l_bdiscapacitados> : 250,
    <item:moa_decor_bath:l_bhombres> : 250,
    <item:moa_decor_bath:l_bmujeres> : 250,
    <item:moa_decor_bath:labedul> : 250,
    <item:moa_decor_bath:labedulsc> : 250,
    <item:moa_decor_bath:labeto> : 250,
    <item:moa_decor_bath:labetosc> : 250,
    <item:moa_decor_bath:lacacia> : 250,
    <item:moa_decor_bath:lacaciasc> : 250,
    <item:moa_decor_bath:lavabo> : 250,
    <item:moa_decor_bath:lavaboconpedestal> : 250,
    <item:moa_decor_bath:lavadora> : 250,
    <item:moa_decor_bath:lavadoraabierta> : 250,
    <item:moa_decor_bath:lb_bdiscapacitados> : 250,
    <item:moa_decor_bath:lb_bhombres> : 250,
    <item:moa_decor_bath:lb_bmujeres> : 250,
    <item:moa_decor_bath:lcarmesi> : 250,
    <item:moa_decor_bath:lcarmesisc> : 250,
    <item:moa_decor_bath:ldistorsionado> : 250,
    <item:moa_decor_bath:ldistorsionadosc> : 250,
    <item:moa_decor_bath:letreropisomojado> : 250,
    <item:moa_decor_bath:ljungla> : 250,
    <item:moa_decor_bath:ljunglasc> : 250,
    <item:moa_decor_bath:llavesdebanera> : 250,
    <item:moa_decor_bath:llavesderegadera> : 250,
    <item:moa_decor_bath:lmangle> : 250,
    <item:moa_decor_bath:lmanglesc> : 250,
    <item:moa_decor_bath:lroble> : 250,
    <item:moa_decor_bath:lrobleosc> : 250,
    <item:moa_decor_bath:lrobleoscsc> : 250,
    <item:moa_decor_bath:lroblesc> : 250,
    <item:moa_decor_bath:mingitorio> : 250,
    <item:moa_decor_bath:papelhigienico> : 250,
    <item:moa_decor_bath:planch> : 250,
    <item:moa_decor_bath:portapapelhigienico> : 250,
    <item:moa_decor_bath:regadera> : 250,
    <item:moa_decor_bath:rollospapelhigienico> : 250,
    <item:moa_decor_bath:secadormanos> : 250,
    <item:moa_decor_bath:soporteparajabon> : 250,
    <item:moa_decor_bath:tabladeplanchar> : 250,
    <item:moa_decor_bath:tendederoconropafemenina> : 250,
    <item:moa_decor_bath:tendederoconropamasculina> : 250,
    <item:moa_decor_bath:tendederoconsabanas> : 250,
    <item:moa_decor_bath:toallaamarillacolg> : 250,
    <item:moa_decor_bath:toallaazulcolg> : 250,
    <item:moa_decor_bath:toallablancacolg> : 250,
    <item:moa_decor_bath:toallacafecolg> : 250,
    <item:moa_decor_bath:toallaciancolg> : 250,
    <item:moa_decor_bath:toallagrisclaracolg> : 250,
    <item:moa_decor_bath:toallagriscolg> : 250,
    <item:moa_decor_bath:toallamagentacolg> : 250,
    <item:moa_decor_bath:toallamoradacolg> : 250,
    <item:moa_decor_bath:toallanaranjacolg> : 250,
    <item:moa_decor_bath:toallanegracolg> : 250,
    <item:moa_decor_bath:toallarojacolg> : 250,
    <item:moa_decor_bath:toallarosacolg> : 250,
    <item:moa_decor_bath:toallasamarillas> : 250,
    <item:moa_decor_bath:toallasazules> : 250,
    <item:moa_decor_bath:toallasblancas> : 250,
    <item:moa_decor_bath:toallascafes> : 250,
    <item:moa_decor_bath:toallascian> : 250,
    <item:moa_decor_bath:toallasgrises> : 250,
    <item:moa_decor_bath:toallasgrisesclaras> : 250,
    <item:moa_decor_bath:toallasmagentas> : 250,
    <item:moa_decor_bath:toallasmoradas> : 250,
    <item:moa_decor_bath:toallasnaranjas> : 250,
    <item:moa_decor_bath:toallasnegras> : 250,
    <item:moa_decor_bath:toallasrojas> : 250,
    <item:moa_decor_bath:toallasrosas> : 250,
    <item:moa_decor_bath:toallasverdes> : 250,
    <item:moa_decor_bath:toallasverdeslima> : 250,
    <item:moa_decor_bath:toallaszulesclaras> : 250,
    <item:moa_decor_bath:toallaverdecolg> : 250,
    <item:moa_decor_bath:toallaverdelimacolg> : 250,
    <item:moa_decor_bath:toallazulclaracolg> : 250,
    <item:moa_decor_bath:trap> : 250,
    <item:moa_decor_bath:vasocepillosdedientes> : 250
};

// For each item in the map, check if we're in release mode. If we are, anything below 26 EMC/FMC becomes unburnable for EMC
for item, value in priceTable {
    if (ReleaseMode.releaseMode == true){
        if (value < 26 ) {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), 0);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        } else {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
            item.addTooltip(new TextComponent("Lost Deco").withStyle(style => style.withColor(<constant:minecraft:formatting:gold>)));
            item.addTooltip(new TextComponent("Only Found in the Liminal Mall").withStyle(style => style.withColor(<constant:minecraft:formatting:gold>)));
        }
    } else {
        CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
        <tag:items:projectextended:blacklist_condenser>.add(item);
        <tag:items:projectextended:blacklist_learning>.add(item);
            item.addTooltip(new TextComponent("Lost Deco").withStyle(style => style.withColor(<constant:minecraft:formatting:gold>)));
            item.addTooltip(new TextComponent("Only Found in the Liminal Mall").withStyle(style => style.withColor(<constant:minecraft:formatting:gold>)));
    }
}