import crafttweaker.api.tag.MCTag;
import crafttweaker.api.item.IItemStack;
import crafttweaker.api.ingredient.IIngredient;
import crafttweaker.api.item.tooltip.ITooltipFunction;
import stdlib.List;
import mods.projecte.CustomEMC;
import mods.projecte.NSSResolver;

// This variable controls whether we are in the pack dev mode or release mode. In Pack Dev mode, all EMC/FMC values are enabled to help calculate EMC/FMC for other mods.
var release_mode = false;

// Item  to EMC/FMC value map.
val priceTable as int[IItemStack] = {
    <item:moremekanismprocessing:aluminum_ingot> : 175,
    <item:moremekanismprocessing:aluminum_nugget> : 25,
    <item:moremekanismprocessing:bismuth_ingot> : 275,
    <item:moremekanismprocessing:bismuth_nugget> : 25,
    <item:moremekanismprocessing:calorite_ingot> : 150,
    <item:moremekanismprocessing:calorite_nugget> : 25,
    <item:moremekanismprocessing:clump_aluminum> : 175,
    <item:moremekanismprocessing:clump_bismuth> : 275,
    <item:moremekanismprocessing:clump_bort> : 250,
    <item:moremekanismprocessing:clump_calorite> : 150,
    <item:moremekanismprocessing:clump_cinnabar> : 1500,
    <item:moremekanismprocessing:clump_desh> : 725,
    <item:moremekanismprocessing:clump_dilithium> : 175,
    <item:moremekanismprocessing:clump_draconium> : 1750,
    <item:moremekanismprocessing:clump_green_sapphire> : 400,
    <item:moremekanismprocessing:clump_iridium> : 1125,
    <item:moremekanismprocessing:clump_nickel> : 350,
    <item:moremekanismprocessing:clump_ostrum> : 300,
    <item:moremekanismprocessing:clump_platinum> : 675,
    <item:moremekanismprocessing:clump_silver> : 350,
    <item:moremekanismprocessing:clump_sulfur> : 100,
    <item:moremekanismprocessing:clump_titanium> : 500,
    <item:moremekanismprocessing:clump_tungsten> : 675,
    <item:moremekanismprocessing:crystal_aluminum> : 175,
    <item:moremekanismprocessing:crystal_bismuth> : 275,
    <item:moremekanismprocessing:crystal_bort> : 250,
    <item:moremekanismprocessing:crystal_calorite> : 150,
    <item:moremekanismprocessing:crystal_cinnabar> : 1500,
    <item:moremekanismprocessing:crystal_desh> : 725,
    <item:moremekanismprocessing:crystal_dilithium> : 175,
    <item:moremekanismprocessing:crystal_draconium> : 1750,
    <item:moremekanismprocessing:crystal_green_sapphire> : 400,
    <item:moremekanismprocessing:crystal_iridium> : 1125,
    <item:moremekanismprocessing:crystal_nickel> : 350,
    <item:moremekanismprocessing:crystal_ostrum> : 300,
    <item:moremekanismprocessing:crystal_platinum> : 675,
    <item:moremekanismprocessing:crystal_silver> : 350,
    <item:moremekanismprocessing:crystal_sulfur> : 100,
    <item:moremekanismprocessing:crystal_titanium> : 500,
    <item:moremekanismprocessing:crystal_tungsten> : 675,
    <item:moremekanismprocessing:desh_ingot> : 725,
    <item:moremekanismprocessing:desh_nugget> : 75,
    <item:moremekanismprocessing:dirty_dust_aluminum> : 175,
    <item:moremekanismprocessing:dirty_dust_bismuth> : 275,
    <item:moremekanismprocessing:dirty_dust_bort> : 250,
    <item:moremekanismprocessing:dirty_dust_calorite> : 150,
    <item:moremekanismprocessing:dirty_dust_cinnabar> : 1500,
    <item:moremekanismprocessing:dirty_dust_desh> : 725,
    <item:moremekanismprocessing:dirty_dust_dilithium> : 175,
    <item:moremekanismprocessing:dirty_dust_draconium> : 1750,
    <item:moremekanismprocessing:dirty_dust_green_sapphire> : 400,
    <item:moremekanismprocessing:dirty_dust_iridium> : 1125,
    <item:moremekanismprocessing:dirty_dust_nickel> : 350,
    <item:moremekanismprocessing:dirty_dust_ostrum> : 300,
    <item:moremekanismprocessing:dirty_dust_platinum> : 675,
    <item:moremekanismprocessing:dirty_dust_silver> : 350,
    <item:moremekanismprocessing:dirty_dust_sulfur> : 100,
    <item:moremekanismprocessing:dirty_dust_titanium> : 500,
    <item:moremekanismprocessing:dirty_dust_tungsten> : 675,
    <item:moremekanismprocessing:draconium_ingot> : 1750,
    <item:moremekanismprocessing:draconium_nugget> : 200,
    <item:moremekanismprocessing:dust_aluminum> : 175,
    <item:moremekanismprocessing:dust_bismuth> : 275,
    <item:moremekanismprocessing:dust_bort> : 250,
    <item:moremekanismprocessing:dust_calorite> : 150,
    <item:moremekanismprocessing:dust_cinnabar> : 1500,
    <item:moremekanismprocessing:dust_desh> : 725,
    <item:moremekanismprocessing:dust_dilithium> : 175,
    <item:moremekanismprocessing:dust_draconium> : 1750,
    <item:moremekanismprocessing:dust_green_sapphire> : 400,
    <item:moremekanismprocessing:dust_iridium> : 1125,
    <item:moremekanismprocessing:dust_nickel> : 350,
    <item:moremekanismprocessing:dust_ostrum> : 300,
    <item:moremekanismprocessing:dust_platinum> : 675,
    <item:moremekanismprocessing:dust_silver> : 350,
    <item:moremekanismprocessing:dust_titanium> : 500,
    <item:moremekanismprocessing:dust_tungsten> : 675,
    <item:moremekanismprocessing:gem_bort> : 250,
    <item:moremekanismprocessing:gem_cinnabar> : 1500,
    <item:moremekanismprocessing:gem_dilithium> : 175,
    <item:moremekanismprocessing:gem_green_sapphire> : 400,
    <item:moremekanismprocessing:iridium_ingot> : 1125,
    <item:moremekanismprocessing:iridium_nugget> : 125,
    <item:moremekanismprocessing:nickel_ingot> : 350,
    <item:moremekanismprocessing:nickel_nugget> : 50,
    <item:moremekanismprocessing:ostrum_ingot> : 300,
    <item:moremekanismprocessing:ostrum_nugget> : 25,
    <item:moremekanismprocessing:platinum_ingot> : 675,
    <item:moremekanismprocessing:platinum_nugget> : 75,
    <item:moremekanismprocessing:shard_aluminum> : 175,
    <item:moremekanismprocessing:shard_bismuth> : 275,
    <item:moremekanismprocessing:shard_bort> : 250,
    <item:moremekanismprocessing:shard_calorite> : 150,
    <item:moremekanismprocessing:shard_cinnabar> : 1500,
    <item:moremekanismprocessing:shard_desh> : 725,
    <item:moremekanismprocessing:shard_dilithium> : 175,
    <item:moremekanismprocessing:shard_draconium> : 1750,
    <item:moremekanismprocessing:shard_green_sapphire> : 400,
    <item:moremekanismprocessing:shard_iridium> : 1125,
    <item:moremekanismprocessing:shard_nickel> : 350,
    <item:moremekanismprocessing:shard_ostrum> : 300,
    <item:moremekanismprocessing:shard_platinum> : 675,
    <item:moremekanismprocessing:shard_silver> : 350,
    <item:moremekanismprocessing:shard_sulfur> : 100,
    <item:moremekanismprocessing:shard_titanium> : 500,
    <item:moremekanismprocessing:shard_tungsten> : 675,
    <item:moremekanismprocessing:silver_ingot> : 350,
    <item:moremekanismprocessing:silver_nugget> : 50,
    <item:moremekanismprocessing:titanium_ingot> : 500,
    <item:moremekanismprocessing:titanium_nugget> : 50,
    <item:moremekanismprocessing:tungsten_ingot> : 675,
    <item:moremekanismprocessing:tungsten_nugget> : 75,
    <item:moremekanismprocessing:azure_silver_ingot> : 50,
    <item:moremekanismprocessing:azure_silver_nugget> : 5,
    <item:moremekanismprocessing:clump_amethyst> : 25,
    <item:moremekanismprocessing:clump_apatite> : 25,
    <item:moremekanismprocessing:clump_azure_silver> : 50,
    <item:moremekanismprocessing:clump_cobalt> : 25,
    <item:moremekanismprocessing:clump_crimson_iron> : 250,
    <item:moremekanismprocessing:clump_lithium> : 10,
    <item:moremekanismprocessing:clump_niter> : 325,
    <item:moremekanismprocessing:clump_peridot> : 100,
    <item:moremekanismprocessing:clump_ruby> : 100,
    <item:moremekanismprocessing:clump_sapphire> : 100,
    <item:moremekanismprocessing:clump_zinc> : 125,
    <item:moremekanismprocessing:cobalt_ingot> : 25,
    <item:moremekanismprocessing:cobalt_nugget> : 2,
    <item:moremekanismprocessing:crimson_iron_ingot> : 250,
    <item:moremekanismprocessing:crimson_iron_nugget> : 25,
    <item:moremekanismprocessing:crystal_amethyst> : 25,
    <item:moremekanismprocessing:crystal_apatite> : 25,
    <item:moremekanismprocessing:crystal_azure_silver> : 50,
    <item:moremekanismprocessing:crystal_cobalt> : 25,
    <item:moremekanismprocessing:crystal_crimson_iron> : 250,
    <item:moremekanismprocessing:crystal_lithium> : 10,
    <item:moremekanismprocessing:crystal_niter> : 325,
    <item:moremekanismprocessing:crystal_peridot> : 100,
    <item:moremekanismprocessing:crystal_ruby> : 100,
    <item:moremekanismprocessing:crystal_sapphire> : 100,
    <item:moremekanismprocessing:crystal_zinc> : 125,
    <item:moremekanismprocessing:dirty_dust_amethyst> : 25,
    <item:moremekanismprocessing:dirty_dust_apatite> : 25,
    <item:moremekanismprocessing:dirty_dust_azure_silver> : 50,
    <item:moremekanismprocessing:dirty_dust_cobalt> : 25,
    <item:moremekanismprocessing:dirty_dust_crimson_iron> : 250,
    <item:moremekanismprocessing:dirty_dust_lithium> : 10,
    <item:moremekanismprocessing:dirty_dust_niter> : 325,
    <item:moremekanismprocessing:dirty_dust_peridot> : 100,
    <item:moremekanismprocessing:dirty_dust_ruby> : 100,
    <item:moremekanismprocessing:dirty_dust_sapphire> : 100,
    <item:moremekanismprocessing:dirty_dust_zinc> : 125,
    <item:moremekanismprocessing:dust_amethyst> : 25,
    <item:moremekanismprocessing:dust_apatite> : 25,
    <item:moremekanismprocessing:dust_azure_silver> : 50,
    <item:moremekanismprocessing:dust_cobalt> : 25,
    <item:moremekanismprocessing:dust_crimson_iron> : 250,
    <item:moremekanismprocessing:dust_lithium> : 10,
    <item:moremekanismprocessing:dust_niter> : 325,
    <item:moremekanismprocessing:dust_peridot> : 100,
    <item:moremekanismprocessing:dust_ruby> : 100,
    <item:moremekanismprocessing:dust_sapphire> : 100,
    <item:moremekanismprocessing:dust_zinc> : 125,
    <item:moremekanismprocessing:gem_apatite> : 25,
    <item:moremekanismprocessing:gem_niter> : 325,
    <item:moremekanismprocessing:gem_peridot> : 100,
    <item:moremekanismprocessing:gem_ruby> : 100,
    <item:moremekanismprocessing:gem_sapphire> : 100,
    <item:moremekanismprocessing:lithium_ingot> : 10,
    <item:moremekanismprocessing:lithium_nugget> : 1,
    <item:moremekanismprocessing:shard_amethyst> : 25,
    <item:moremekanismprocessing:shard_apatite> : 25,
    <item:moremekanismprocessing:shard_azure_silver> : 50,
    <item:moremekanismprocessing:shard_cobalt> : 25,
    <item:moremekanismprocessing:shard_crimson_iron> : 250,
    <item:moremekanismprocessing:shard_lithium> : 10,
    <item:moremekanismprocessing:shard_niter> : 325,
    <item:moremekanismprocessing:shard_peridot> : 100,
    <item:moremekanismprocessing:shard_ruby> : 100,
    <item:moremekanismprocessing:shard_sapphire> : 100,
    <item:moremekanismprocessing:shard_zinc> : 125,
    <item:moremekanismprocessing:zinc_ingot> : 125,
    <item:moremekanismprocessing:zinc_nugget> : 10
};

// For each item in the map, check if we're in release mode. If we are, anything below 26 EMC/FMC becomes unburnable for EMC
for item, value in priceTable {
    if (release_mode == true){
        if (value < 26 ) {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), 0);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        } else {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        }
    } else {
        CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
        <tag:items:projectextended:blacklist_condenser>.add(item);
        <tag:items:projectextended:blacklist_learning>.add(item);
    }
}