import crafttweaker.api.tag.MCTag;
import crafttweaker.api.item.IItemStack;
import crafttweaker.api.ingredient.IIngredient;
import crafttweaker.api.item.tooltip.ITooltipFunction;
import stdlib.List;
import mods.projecte.CustomEMC;
import mods.projecte.NSSResolver;

// Item  to EMC/FMC value map.
val priceTable as int[IItemStack] = {
    <item:mysticalagriculture:absorption_i_augment> : 0,
    <item:mysticalagriculture:absorption_ii_augment> : 0,
    <item:mysticalagriculture:absorption_iii_augment> : 0,
    <item:mysticalagriculture:absorption_iv_augment> : 0,
    <item:mysticalagriculture:absorption_v_augment> : 0,
    <item:mysticalagriculture:air_agglomeratio> : 0,
    <item:mysticalagriculture:air_essence> : 0,
    <item:mysticalagriculture:air_seeds> : 0,
    <item:mysticalagriculture:aluminum_essence> : 0,
    <item:mysticalagriculture:aluminum_seeds> : 0,
    <item:mysticalagriculture:amethyst_bronze_essence> : 0,
    <item:mysticalagriculture:amethyst_bronze_seeds> : 0,
    <item:mysticalagriculture:amethyst_essence> : 0,
    <item:mysticalagriculture:amethyst_seeds> : 0,
    <item:mysticalagriculture:apatite_essence> : 0,
    <item:mysticalagriculture:apatite_seeds> : 0,
    <item:mysticalagriculture:aquamarine_essence> : 0,
    <item:mysticalagriculture:aquamarine_seeds> : 0,
    <item:mysticalagriculture:attack_aoe_i_augment> : 0,
    <item:mysticalagriculture:attack_aoe_ii_augment> : 0,
    <item:mysticalagriculture:attack_aoe_iii_augment> : 0,
    <item:mysticalagriculture:awakened_draconium_essence> : 0,
    <item:mysticalagriculture:awakened_draconium_seeds> : 0,
    <item:mysticalagriculture:basalt_essence> : 0,
    <item:mysticalagriculture:basalt_seeds> : 0,
    <item:mysticalagriculture:basalz_essence> : 0,
    <item:mysticalagriculture:basalz_seeds> : 0,
    <item:mysticalagriculture:basic_reprocessor> : 0,
    <item:mysticalagriculture:blank_record> : 0,
    <item:mysticalagriculture:blank_skull> : 0,
    <item:mysticalagriculture:blaze_essence> : 0,
    <item:mysticalagriculture:blaze_seeds> : 0,
    <item:mysticalagriculture:blazing_crystal_essence> : 0,
    <item:mysticalagriculture:blazing_crystal_seeds> : 0,
    <item:mysticalagriculture:blitz_essence> : 0,
    <item:mysticalagriculture:blitz_seeds> : 0,
    <item:mysticalagriculture:blizz_essence> : 0,
    <item:mysticalagriculture:blizz_seeds> : 0,
    <item:mysticalagriculture:brass_essence> : 0,
    <item:mysticalagriculture:brass_seeds> : 0,
    <item:mysticalagriculture:bronze_essence> : 0,
    <item:mysticalagriculture:bronze_seeds> : 0,
    <item:mysticalagriculture:certus_quartz_essence> : 0,
    <item:mysticalagriculture:certus_quartz_seeds> : 0,
    <item:mysticalagriculture:chicken_essence> : 0,
    <item:mysticalagriculture:chicken_seeds> : 0,
    <item:mysticalagriculture:chromatic_iron_essence> : 0,
    <item:mysticalagriculture:chromatic_iron_seeds> : 0,
    <item:mysticalagriculture:chrome_essence> : 0,
    <item:mysticalagriculture:chrome_seeds> : 0,
    <item:mysticalagriculture:coal_essence> : 0,
    <item:mysticalagriculture:coal_seeds> : 0,
    <item:mysticalagriculture:cobalt_essence> : 0,
    <item:mysticalagriculture:cobalt_seeds> : 0,
    <item:mysticalagriculture:compressed_iron_essence> : 0,
    <item:mysticalagriculture:compressed_iron_seeds> : 0,
    <item:mysticalagriculture:constantan_essence> : 0,
    <item:mysticalagriculture:constantan_seeds> : 0,
    <item:mysticalagriculture:copper_essence> : 0,
    <item:mysticalagriculture:copper_seeds> : 0,
    <item:mysticalagriculture:coral_agglomeratio> : 0,
    <item:mysticalagriculture:coral_essence> : 0,
    <item:mysticalagriculture:coral_seeds> : 0,
    <item:mysticalagriculture:cow_essence> : 0,
    <item:mysticalagriculture:cow_seeds> : 0,
    <item:mysticalagriculture:creative_soulium_dagger> : 0,
    <item:mysticalagriculture:creeper_essence> : 0,
    <item:mysticalagriculture:creeper_seeds> : 0,
    <item:mysticalagriculture:cyanite_essence> : 0,
    <item:mysticalagriculture:cyanite_seeds> : 0,
    <item:mysticalagriculture:deepslate_essence> : 0,
    <item:mysticalagriculture:deepslate_inferium_ore> : 0,
    <item:mysticalagriculture:deepslate_prosperity_ore> : 0,
    <item:mysticalagriculture:deepslate_seeds> : 0,
    <item:mysticalagriculture:diamond_essence> : 0,
    <item:mysticalagriculture:diamond_seeds> : 0,
    <item:mysticalagriculture:dirt_essence> : 0,
    <item:mysticalagriculture:dirt_seeds> : 0,
    <item:mysticalagriculture:draconium_essence> : 0,
    <item:mysticalagriculture:draconium_seeds> : 0,
    <item:mysticalagriculture:dragon_egg_essence> : 0,
    <item:mysticalagriculture:dragon_egg_seeds> : 0,
    <item:mysticalagriculture:dye_agglomeratio> : 0,
    <item:mysticalagriculture:dye_essence> : 0,
    <item:mysticalagriculture:dye_seeds> : 0,
    <item:mysticalagriculture:earth_agglomeratio> : 0,
    <item:mysticalagriculture:earth_essence> : 0,
    <item:mysticalagriculture:earth_seeds> : 0,
    <item:mysticalagriculture:electrum_essence> : 0,
    <item:mysticalagriculture:electrum_seeds> : 0,
    <item:mysticalagriculture:elementium_essence> : 0,
    <item:mysticalagriculture:elementium_seeds> : 0,
    <item:mysticalagriculture:emerald_essence> : 0,
    <item:mysticalagriculture:emerald_seeds> : 0,
    <item:mysticalagriculture:end_agglomeratio> : 0,
    <item:mysticalagriculture:end_essence> : 0,
    <item:mysticalagriculture:end_seeds> : 0,
    <item:mysticalagriculture:enderium_essence> : 0,
    <item:mysticalagriculture:enderium_seeds> : 0,
    <item:mysticalagriculture:enderman_essence> : 0,
    <item:mysticalagriculture:enderman_seeds> : 0,
    <item:mysticalagriculture:energized_steel_essence> : 0,
    <item:mysticalagriculture:energized_steel_seeds> : 0,
    <item:mysticalagriculture:experience_capsule> : 0,
    <item:mysticalagriculture:experience_droplet> : 0,
    <item:mysticalagriculture:experience_essence> : 0,
    <item:mysticalagriculture:experience_seeds> : 0,
    <item:mysticalagriculture:fertilized_essence> : 0,
    <item:mysticalagriculture:fiery_ingot_essence> : 0,
    <item:mysticalagriculture:fiery_ingot_seeds> : 0,
    <item:mysticalagriculture:fire_agglomeratio> : 0,
    <item:mysticalagriculture:fire_essence> : 0,
    <item:mysticalagriculture:fire_resistance_augment> : 0,
    <item:mysticalagriculture:fire_seeds> : 0,
    <item:mysticalagriculture:fish_essence> : 0,
    <item:mysticalagriculture:fish_seeds> : 0,
    <item:mysticalagriculture:flight_augment> : 0,
    <item:mysticalagriculture:fluix_essence> : 0,
    <item:mysticalagriculture:fluix_seeds> : 0,
    <item:mysticalagriculture:fluorite_essence> : 0,
    <item:mysticalagriculture:fluorite_seeds> : 0,
    <item:mysticalagriculture:gaia_spirit_essence> : 0,
    <item:mysticalagriculture:gaia_spirit_seeds> : 0,
    <item:mysticalagriculture:ghast_essence> : 0,
    <item:mysticalagriculture:ghast_seeds> : 0,
    <item:mysticalagriculture:glowstone_essence> : 0,
    <item:mysticalagriculture:glowstone_seeds> : 0,
    <item:mysticalagriculture:gold_essence> : 0,
    <item:mysticalagriculture:gold_seeds> : 0,
    <item:mysticalagriculture:graphite_essence> : 0,
    <item:mysticalagriculture:graphite_seeds> : 0,
    <item:mysticalagriculture:health_boost_i_augment> : 0,
    <item:mysticalagriculture:health_boost_ii_augment> : 0,
    <item:mysticalagriculture:health_boost_iii_augment> : 0,
    <item:mysticalagriculture:health_boost_iv_augment> : 0,
    <item:mysticalagriculture:health_boost_v_augment> : 0,
    <item:mysticalagriculture:hepatizon_essence> : 0,
    <item:mysticalagriculture:hepatizon_seeds> : 0,
    <item:mysticalagriculture:honey_agglomeratio> : 0,
    <item:mysticalagriculture:honey_essence> : 0,
    <item:mysticalagriculture:honey_seeds> : 0,
    <item:mysticalagriculture:hop_graphite_essence> : 0,
    <item:mysticalagriculture:hop_graphite_seeds> : 0,
    <item:mysticalagriculture:hostile_soulium_dagger> : 0,
    <item:mysticalagriculture:ice_essence> : 0,
    <item:mysticalagriculture:ice_seeds> : 0,
    <item:mysticalagriculture:imperium_axe> : 0,
    <item:mysticalagriculture:imperium_block> : 0,
    <item:mysticalagriculture:imperium_boots> : 0,
    <item:mysticalagriculture:imperium_bow> : 0,
    <item:mysticalagriculture:imperium_chestplate> : 0,
    <item:mysticalagriculture:imperium_crossbow> : 0,
    <item:mysticalagriculture:imperium_essence> : 0,
    <item:mysticalagriculture:imperium_farmland> : 0,
    <item:mysticalagriculture:imperium_furnace> : 0,
    <item:mysticalagriculture:imperium_gemstone> : 0,
    <item:mysticalagriculture:imperium_gemstone_block> : 0,
    <item:mysticalagriculture:imperium_growth_accelerator> : 0,
    <item:mysticalagriculture:imperium_helmet> : 0,
    <item:mysticalagriculture:imperium_hoe> : 0,
    <item:mysticalagriculture:imperium_ingot> : 0,
    <item:mysticalagriculture:imperium_ingot_block> : 0,
    <item:mysticalagriculture:imperium_leggings> : 0,
    <item:mysticalagriculture:imperium_nugget> : 0,
    <item:mysticalagriculture:imperium_pickaxe> : 0,
    <item:mysticalagriculture:imperium_reprocessor> : 0,
    <item:mysticalagriculture:imperium_shovel> : 0,
    <item:mysticalagriculture:imperium_staff> : 0,
    <item:mysticalagriculture:imperium_sword> : 0,
    <item:mysticalagriculture:imperium_watering_can> : 0,
    <item:mysticalagriculture:inferium_axe> : 0,
    <item:mysticalagriculture:inferium_block> : 0,
    <item:mysticalagriculture:inferium_boots> : 0,
    <item:mysticalagriculture:inferium_bow> : 0,
    <item:mysticalagriculture:inferium_chestplate> : 0,
    <item:mysticalagriculture:inferium_crossbow> : 0,
    <item:mysticalagriculture:inferium_essence> : 0,
    <item:mysticalagriculture:inferium_farmland> : 0,
    <item:mysticalagriculture:inferium_furnace> : 0,
    <item:mysticalagriculture:inferium_gemstone> : 0,
    <item:mysticalagriculture:inferium_gemstone_block> : 0,
    <item:mysticalagriculture:inferium_growth_accelerator> : 0,
    <item:mysticalagriculture:inferium_helmet> : 0,
    <item:mysticalagriculture:inferium_hoe> : 0,
    <item:mysticalagriculture:inferium_ingot> : 0,
    <item:mysticalagriculture:inferium_ingot_block> : 0,
    <item:mysticalagriculture:inferium_leggings> : 0,
    <item:mysticalagriculture:inferium_nugget> : 0,
    <item:mysticalagriculture:inferium_ore> : 0,
    <item:mysticalagriculture:inferium_pickaxe> : 0,
    <item:mysticalagriculture:inferium_reprocessor> : 0,
    <item:mysticalagriculture:inferium_seeds> : 0,
    <item:mysticalagriculture:inferium_shovel> : 0,
    <item:mysticalagriculture:inferium_staff> : 0,
    <item:mysticalagriculture:inferium_sword> : 0,
    <item:mysticalagriculture:inferium_watering_can> : 0,
    <item:mysticalagriculture:infusion_altar> : 0,
    <item:mysticalagriculture:infusion_crystal> : 0,
    <item:mysticalagriculture:infusion_pedestal> : 0,
    <item:mysticalagriculture:invar_essence> : 0,
    <item:mysticalagriculture:invar_seeds> : 0,
    <item:mysticalagriculture:iridium_essence> : 0,
    <item:mysticalagriculture:iridium_seeds> : 0,
    <item:mysticalagriculture:iron_essence> : 0,
    <item:mysticalagriculture:iron_seeds> : 0,
    <item:mysticalagriculture:ironwood_essence> : 0,
    <item:mysticalagriculture:ironwood_seeds> : 0,
    <item:mysticalagriculture:jump_boost_i_augment> : 0,
    <item:mysticalagriculture:jump_boost_ii_augment> : 0,
    <item:mysticalagriculture:jump_boost_iii_augment> : 0,
    <item:mysticalagriculture:knightmetal_essence> : 0,
    <item:mysticalagriculture:knightmetal_seeds> : 0,
    <item:mysticalagriculture:lapis_lazuli_essence> : 0,
    <item:mysticalagriculture:lapis_lazuli_seeds> : 0,
    <item:mysticalagriculture:lead_essence> : 0,
    <item:mysticalagriculture:lead_seeds> : 0,
    <item:mysticalagriculture:limestone_essence> : 0,
    <item:mysticalagriculture:limestone_seeds> : 0,
    <item:mysticalagriculture:lumium_essence> : 0,
    <item:mysticalagriculture:lumium_seeds> : 0,
    <item:mysticalagriculture:machine_frame> : 0,
    <item:mysticalagriculture:manasteel_essence> : 0,
    <item:mysticalagriculture:manasteel_seeds> : 0,
    <item:mysticalagriculture:manyullyn_essence> : 0,
    <item:mysticalagriculture:manyullyn_seeds> : 0,
    <item:mysticalagriculture:marble_essence> : 0,
    <item:mysticalagriculture:marble_seeds> : 0,
    <item:mysticalagriculture:master_infusion_crystal> : 0,
    <item:mysticalagriculture:menril_essence> : 0,
    <item:mysticalagriculture:menril_seeds> : 0,
    <item:mysticalagriculture:mining_aoe_i_augment> : 0,
    <item:mysticalagriculture:mining_aoe_ii_augment> : 0,
    <item:mysticalagriculture:mining_aoe_iii_augment> : 0,
    <item:mysticalagriculture:mining_aoe_iv_augment> : 0,
    <item:mysticalagriculture:mining_fatigue_resistance_augment> : 0,
    <item:mysticalagriculture:mithril_essence> : 0,
    <item:mysticalagriculture:mithril_seeds> : 0,
    <item:mysticalagriculture:mystical_fertilizer> : 0,
    <item:mysticalagriculture:mystical_flower_agglomeratio> : 0,
    <item:mysticalagriculture:mystical_flower_essence> : 0,
    <item:mysticalagriculture:mystical_flower_seeds> : 0,
    <item:mysticalagriculture:nature_agglomeratio> : 0,
    <item:mysticalagriculture:nature_essence> : 0,
    <item:mysticalagriculture:nature_seeds> : 0,
    <item:mysticalagriculture:nether_agglomeratio> : 0,
    <item:mysticalagriculture:nether_essence> : 0,
    <item:mysticalagriculture:nether_quartz_essence> : 0,
    <item:mysticalagriculture:nether_quartz_seeds> : 0,
    <item:mysticalagriculture:nether_seeds> : 0,
    <item:mysticalagriculture:nether_star_essence> : 0,
    <item:mysticalagriculture:nether_star_seeds> : 0,
    <item:mysticalagriculture:netherite_essence> : 0,
    <item:mysticalagriculture:netherite_seeds> : 0,
    <item:mysticalagriculture:neutronium_essence> : 0,
    <item:mysticalagriculture:neutronium_seeds> : 0,
    <item:mysticalagriculture:nickel_essence> : 0,
    <item:mysticalagriculture:nickel_seeds> : 0,
    <item:mysticalagriculture:night_vision_augment> : 0,
    <item:mysticalagriculture:niotic_crystal_essence> : 0,
    <item:mysticalagriculture:niotic_crystal_seeds> : 0,
    <item:mysticalagriculture:nitro_crystal_essence> : 0,
    <item:mysticalagriculture:nitro_crystal_seeds> : 0,
    <item:mysticalagriculture:no_fall_damage_augment> : 0,
    <item:mysticalagriculture:obsidian_essence> : 0,
    <item:mysticalagriculture:obsidian_seeds> : 0,
    <item:mysticalagriculture:osmium_essence> : 0,
    <item:mysticalagriculture:osmium_seeds> : 0,
    <item:mysticalagriculture:passive_soulium_dagger> : 0,
    <item:mysticalagriculture:pathing_aoe_i_augment> : 0,
    <item:mysticalagriculture:pathing_aoe_ii_augment> : 0,
    <item:mysticalagriculture:pathing_aoe_iii_augment> : 0,
    <item:mysticalagriculture:pathing_aoe_iv_augment> : 0,
    <item:mysticalagriculture:pig_essence> : 0,
    <item:mysticalagriculture:pig_iron_essence> : 0,
    <item:mysticalagriculture:pig_iron_seeds> : 0,
    <item:mysticalagriculture:pig_seeds> : 0,
    <item:mysticalagriculture:platinum_essence> : 0,
    <item:mysticalagriculture:platinum_seeds> : 0,
    <item:mysticalagriculture:poison_resistance_augment> : 0,
    <item:mysticalagriculture:prismarine_agglomeratio> : 0,
    <item:mysticalagriculture:prismarine_essence> : 0,
    <item:mysticalagriculture:prismarine_seeds> : 0,
    <item:mysticalagriculture:prosperity_block> : 0,
    <item:mysticalagriculture:prosperity_gemstone> : 0,
    <item:mysticalagriculture:prosperity_gemstone_block> : 0,
    <item:mysticalagriculture:prosperity_ingot> : 0,
    <item:mysticalagriculture:prosperity_ingot_block> : 0,
    <item:mysticalagriculture:prosperity_nugget> : 0,
    <item:mysticalagriculture:prosperity_ore> : 0,
    <item:mysticalagriculture:prosperity_seed_base> : 0,
    <item:mysticalagriculture:prosperity_shard> : 0,
    <item:mysticalagriculture:prudentium_axe> : 0,
    <item:mysticalagriculture:prudentium_block> : 0,
    <item:mysticalagriculture:prudentium_boots> : 0,
    <item:mysticalagriculture:prudentium_bow> : 0,
    <item:mysticalagriculture:prudentium_chestplate> : 0,
    <item:mysticalagriculture:prudentium_crossbow> : 0,
    <item:mysticalagriculture:prudentium_essence> : 0,
    <item:mysticalagriculture:prudentium_farmland> : 0,
    <item:mysticalagriculture:prudentium_furnace> : 0,
    <item:mysticalagriculture:prudentium_gemstone> : 0,
    <item:mysticalagriculture:prudentium_gemstone_block> : 0,
    <item:mysticalagriculture:prudentium_growth_accelerator> : 0,
    <item:mysticalagriculture:prudentium_helmet> : 0,
    <item:mysticalagriculture:prudentium_hoe> : 0,
    <item:mysticalagriculture:prudentium_ingot> : 0,
    <item:mysticalagriculture:prudentium_ingot_block> : 0,
    <item:mysticalagriculture:prudentium_leggings> : 0,
    <item:mysticalagriculture:prudentium_nugget> : 0,
    <item:mysticalagriculture:prudentium_pickaxe> : 0,
    <item:mysticalagriculture:prudentium_reprocessor> : 0,
    <item:mysticalagriculture:prudentium_shovel> : 0,
    <item:mysticalagriculture:prudentium_staff> : 0,
    <item:mysticalagriculture:prudentium_sword> : 0,
    <item:mysticalagriculture:prudentium_watering_can> : 0,
    <item:mysticalagriculture:quartz_enriched_iron_essence> : 0,
    <item:mysticalagriculture:quartz_enriched_iron_seeds> : 0,
    <item:mysticalagriculture:queens_slime_essence> : 0,
    <item:mysticalagriculture:queens_slime_seeds> : 0,
    <item:mysticalagriculture:rabbit_essence> : 0,
    <item:mysticalagriculture:rabbit_seeds> : 0,
    <item:mysticalagriculture:redstone_essence> : 0,
    <item:mysticalagriculture:redstone_seeds> : 0,
    <item:mysticalagriculture:refined_glowstone_essence> : 0,
    <item:mysticalagriculture:refined_glowstone_seeds> : 0,
    <item:mysticalagriculture:refined_obsidian_essence> : 0,
    <item:mysticalagriculture:refined_obsidian_seeds> : 0,
    <item:mysticalagriculture:rock_crystal_essence> : 0,
    <item:mysticalagriculture:rock_crystal_seeds> : 0,
    <item:mysticalagriculture:rose_gold_essence> : 0,
    <item:mysticalagriculture:rose_gold_seeds> : 0,
    <item:mysticalagriculture:rubber_essence> : 0,
    <item:mysticalagriculture:rubber_seeds> : 0,
    <item:mysticalagriculture:ruby_essence> : 0,
    <item:mysticalagriculture:ruby_seeds> : 0,
    <item:mysticalagriculture:saltpeter_essence> : 0,
    <item:mysticalagriculture:saltpeter_seeds> : 0,
    <item:mysticalagriculture:sapphire_essence> : 0,
    <item:mysticalagriculture:sapphire_seeds> : 0,
    <item:mysticalagriculture:sheep_essence> : 0,
    <item:mysticalagriculture:sheep_seeds> : 0,
    <item:mysticalagriculture:signalum_essence> : 0,
    <item:mysticalagriculture:signalum_seeds> : 0,
    <item:mysticalagriculture:silicon_essence> : 0,
    <item:mysticalagriculture:silicon_seeds> : 0,
    <item:mysticalagriculture:silver_essence> : 0,
    <item:mysticalagriculture:silver_seeds> : 0,
    <item:mysticalagriculture:skeleton_essence> : 0,
    <item:mysticalagriculture:skeleton_seeds> : 0,
    <item:mysticalagriculture:sky_stone_essence> : 0,
    <item:mysticalagriculture:sky_stone_seeds> : 0,
    <item:mysticalagriculture:slime_essence> : 0,
    <item:mysticalagriculture:slime_seeds> : 0,
    <item:mysticalagriculture:slimesteel_essence> : 0,
    <item:mysticalagriculture:slimesteel_seeds> : 0,
    <item:mysticalagriculture:soul_dust> : 0,
    <item:mysticalagriculture:soul_extractor> : 0,
    <item:mysticalagriculture:soul_glass> : 0,
    <item:mysticalagriculture:soul_jar> : 0,
    <item:mysticalagriculture:soulium_block> : 0,
    <item:mysticalagriculture:soulium_dagger> : 0,
    <item:mysticalagriculture:soulium_dust> : 0,
    <item:mysticalagriculture:soulium_gemstone> : 0,
    <item:mysticalagriculture:soulium_gemstone_block> : 0,
    <item:mysticalagriculture:soulium_ingot> : 0,
    <item:mysticalagriculture:soulium_ingot_block> : 0,
    <item:mysticalagriculture:soulium_nugget> : 0,
    <item:mysticalagriculture:soulium_ore> : 0,
    <item:mysticalagriculture:soulium_seed_base> : 0,
    <item:mysticalagriculture:soulstone> : 0,
    <item:mysticalagriculture:soulstone_bricks> : 0,
    <item:mysticalagriculture:soulstone_bricks_slab> : 0,
    <item:mysticalagriculture:soulstone_bricks_stairs> : 0,
    <item:mysticalagriculture:soulstone_bricks_wall> : 0,
    <item:mysticalagriculture:soulstone_chiseled_bricks> : 0,
    <item:mysticalagriculture:soulstone_cobble> : 0,
    <item:mysticalagriculture:soulstone_cobble_slab> : 0,
    <item:mysticalagriculture:soulstone_cobble_stairs> : 0,
    <item:mysticalagriculture:soulstone_cobble_wall> : 0,
    <item:mysticalagriculture:soulstone_cracked_bricks> : 0,
    <item:mysticalagriculture:soulstone_slab> : 0,
    <item:mysticalagriculture:soulstone_smooth> : 0,
    <item:mysticalagriculture:soulstone_smooth_slab> : 0,
    <item:mysticalagriculture:soulstone_stairs> : 0,
    <item:mysticalagriculture:speed_i_augment> : 0,
    <item:mysticalagriculture:speed_ii_augment> : 0,
    <item:mysticalagriculture:speed_iii_augment> : 0,
    <item:mysticalagriculture:spider_essence> : 0,
    <item:mysticalagriculture:spider_seeds> : 0,
    <item:mysticalagriculture:spirited_crystal_essence> : 0,
    <item:mysticalagriculture:spirited_crystal_seeds> : 0,
    <item:mysticalagriculture:squid_essence> : 0,
    <item:mysticalagriculture:squid_seeds> : 0,
    <item:mysticalagriculture:starmetal_essence> : 0,
    <item:mysticalagriculture:starmetal_seeds> : 0,
    <item:mysticalagriculture:steel_essence> : 0,
    <item:mysticalagriculture:steel_seeds> : 0,
    <item:mysticalagriculture:steeleaf_essence> : 0,
    <item:mysticalagriculture:steeleaf_seeds> : 0,
    <item:mysticalagriculture:step_assist_augment> : 0,
    <item:mysticalagriculture:stone_essence> : 0,
    <item:mysticalagriculture:stone_seeds> : 0,
    <item:mysticalagriculture:strength_i_augment> : 0,
    <item:mysticalagriculture:strength_ii_augment> : 0,
    <item:mysticalagriculture:strength_iii_augment> : 0,
    <item:mysticalagriculture:sulfur_essence> : 0,
    <item:mysticalagriculture:sulfur_seeds> : 0,
    <item:mysticalagriculture:supremium_axe> : 0,
    <item:mysticalagriculture:supremium_block> : 0,
    <item:mysticalagriculture:supremium_boots> : 0,
    <item:mysticalagriculture:supremium_bow> : 0,
    <item:mysticalagriculture:supremium_chestplate> : 0,
    <item:mysticalagriculture:supremium_crossbow> : 0,
    <item:mysticalagriculture:supremium_essence> : 0,
    <item:mysticalagriculture:supremium_farmland> : 0,
    <item:mysticalagriculture:supremium_furnace> : 0,
    <item:mysticalagriculture:supremium_gemstone> : 0,
    <item:mysticalagriculture:supremium_gemstone_block> : 0,
    <item:mysticalagriculture:supremium_growth_accelerator> : 0,
    <item:mysticalagriculture:supremium_helmet> : 0,
    <item:mysticalagriculture:supremium_hoe> : 0,
    <item:mysticalagriculture:supremium_ingot> : 0,
    <item:mysticalagriculture:supremium_ingot_block> : 0,
    <item:mysticalagriculture:supremium_leggings> : 0,
    <item:mysticalagriculture:supremium_nugget> : 0,
    <item:mysticalagriculture:supremium_pickaxe> : 0,
    <item:mysticalagriculture:supremium_reprocessor> : 0,
    <item:mysticalagriculture:supremium_shovel> : 0,
    <item:mysticalagriculture:supremium_staff> : 0,
    <item:mysticalagriculture:supremium_sword> : 0,
    <item:mysticalagriculture:supremium_watering_can> : 0,
    <item:mysticalagriculture:terrasteel_essence> : 0,
    <item:mysticalagriculture:terrasteel_seeds> : 0,
    <item:mysticalagriculture:tertium_axe> : 0,
    <item:mysticalagriculture:tertium_block> : 0,
    <item:mysticalagriculture:tertium_boots> : 0,
    <item:mysticalagriculture:tertium_bow> : 0,
    <item:mysticalagriculture:tertium_chestplate> : 0,
    <item:mysticalagriculture:tertium_crossbow> : 0,
    <item:mysticalagriculture:tertium_essence> : 0,
    <item:mysticalagriculture:tertium_farmland> : 0,
    <item:mysticalagriculture:tertium_furnace> : 0,
    <item:mysticalagriculture:tertium_gemstone> : 0,
    <item:mysticalagriculture:tertium_gemstone_block> : 0,
    <item:mysticalagriculture:tertium_growth_accelerator> : 0,
    <item:mysticalagriculture:tertium_helmet> : 0,
    <item:mysticalagriculture:tertium_hoe> : 0,
    <item:mysticalagriculture:tertium_ingot> : 0,
    <item:mysticalagriculture:tertium_ingot_block> : 0,
    <item:mysticalagriculture:tertium_leggings> : 0,
    <item:mysticalagriculture:tertium_nugget> : 0,
    <item:mysticalagriculture:tertium_pickaxe> : 0,
    <item:mysticalagriculture:tertium_reprocessor> : 0,
    <item:mysticalagriculture:tertium_shovel> : 0,
    <item:mysticalagriculture:tertium_staff> : 0,
    <item:mysticalagriculture:tertium_sword> : 0,
    <item:mysticalagriculture:tertium_watering_can> : 0,
    <item:mysticalagriculture:tilling_aoe_i_augment> : 0,
    <item:mysticalagriculture:tilling_aoe_ii_augment> : 0,
    <item:mysticalagriculture:tilling_aoe_iii_augment> : 0,
    <item:mysticalagriculture:tilling_aoe_iv_augment> : 0,
    <item:mysticalagriculture:tin_essence> : 0,
    <item:mysticalagriculture:tin_seeds> : 0,
    <item:mysticalagriculture:tinkering_table> : 0,
    <item:mysticalagriculture:tinkers_bronze_essence> : 0,
    <item:mysticalagriculture:tinkers_bronze_seeds> : 0,
    <item:mysticalagriculture:titanium_essence> : 0,
    <item:mysticalagriculture:titanium_seeds> : 0,
    <item:mysticalagriculture:tungsten_essence> : 0,
    <item:mysticalagriculture:tungsten_seeds> : 0,
    <item:mysticalagriculture:turtle_essence> : 0,
    <item:mysticalagriculture:turtle_seeds> : 0,
    <item:mysticalagriculture:unattuned_augment> : 0,
    <item:mysticalagriculture:uraninite_essence> : 0,
    <item:mysticalagriculture:uraninite_seeds> : 0,
    <item:mysticalagriculture:uranium_essence> : 0,
    <item:mysticalagriculture:uranium_seeds> : 0,
    <item:mysticalagriculture:water_agglomeratio> : 0,
    <item:mysticalagriculture:water_breathing_augment> : 0,
    <item:mysticalagriculture:water_essence> : 0,
    <item:mysticalagriculture:water_seeds> : 0,
    <item:mysticalagriculture:watering_can> : 0,
    <item:mysticalagriculture:wither_resistance_augment> : 0,
    <item:mysticalagriculture:wither_skeleton_essence> : 0,
    <item:mysticalagriculture:wither_skeleton_seeds> : 0,
    <item:mysticalagriculture:witherproof_block> : 0,
    <item:mysticalagriculture:witherproof_bricks> : 0,
    <item:mysticalagriculture:witherproof_glass> : 0,
    <item:mysticalagriculture:wood_essence> : 0,
    <item:mysticalagriculture:wood_seeds> : 0,
    <item:mysticalagriculture:yellorium_essence> : 0,
    <item:mysticalagriculture:yellorium_seeds> : 0,
    <item:mysticalagriculture:zinc_essence> : 0,
    <item:mysticalagriculture:zinc_seeds> : 0,
    <item:mysticalagriculture:zombie_essence> : 0,
    <item:mysticalagriculture:zombie_seeds> : 0
};

// For each item in the map, check if we're in release mode. If we are, anything below 26 EMC/FMC becomes unburnable for EMC
for item, value in priceTable {
    if (ReleaseMode.releaseMode == true){
        if (value < 26 ) {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), 0);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        } else {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        }
        if (value > 999 && value < 10001) {
            <tag:items:tfb2:fop_miniscule>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Miniscule");
            });
        }
        if (value > 10000 && value < 25001) {
            <tag:items:tfb2:fop_small>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Small");
            });
        }
        if (value > 25000 && value < 75001) {
            <tag:items:tfb2:fop_medium>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Medium");
            });
        }
        if (value > 75000) {
            <tag:items:tfb2:fop_large>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Large");
            });
        }
    } else {
        CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
        <tag:items:projectextended:blacklist_condenser>.add(item);
        <tag:items:projectextended:blacklist_learning>.add(item);
    }
        if (value > 10000 && value < 25001) {
            <tag:items:tfb2:fop_small>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Small");
            });
        }
        if (value > 25000 && value < 75001) {
            <tag:items:tfb2:fop_medium>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Medium");
            });
        }
        if (value > 75000) {
            <tag:items:tfb2:fop_large>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Large");
            });
        }
}