import crafttweaker.api.tag.MCTag;
import crafttweaker.api.item.IItemStack;
import crafttweaker.api.ingredient.IIngredient;
import crafttweaker.api.item.tooltip.ITooltipFunction;
import stdlib.List;
import mods.projecte.CustomEMC;
import mods.projecte.NSSResolver;

// This variable controls whether we are in the pack dev mode or release mode. In Pack Dev mode, all EMC/FMC values are enabled to help calculate EMC/FMC for other mods.
var release_mode = false;

// Item  to EMC/FMC value map.
val priceTable as int[IItemStack] = {
    <item:rechiseledcreate:crimson_window_bars> : 1,
    <item:rechiseledcreate:crimson_window_bars_connecting> : 1,
    <item:rechiseledcreate:crimson_window_covered> : 1,
    <item:rechiseledcreate:crimson_window_covered_connecting> : 1,
    <item:rechiseledcreate:crimson_window_large> : 1,
    <item:rechiseledcreate:crimson_window_large_connecting> : 1,
    <item:rechiseledcreate:crimson_window_panes> : 1,
    <item:rechiseledcreate:crimson_window_panes_connecting> : 1,
    <item:rechiseledcreate:crimson_window_slim> : 1,
    <item:rechiseledcreate:crimson_window_slim_connecting> : 1,
    <item:rechiseledcreate:crimson_window_swirling> : 1,
    <item:rechiseledcreate:crimson_window_swirling_connecting> : 1,
    <item:rechiseledcreate:crimson_window_tiles> : 1,
    <item:rechiseledcreate:crimson_window_tiles_connecting> : 1,
    <item:rechiseledcreate:rose_quartz_bricks> : 75,
    <item:rechiseledcreate:rose_quartz_bricks_connecting> : 75,
    <item:rechiseledcreate:rose_quartz_chiseled> : 75,
    <item:rechiseledcreate:rose_quartz_chiseled_connecting> : 75,
    <item:rechiseledcreate:rose_quartz_crushed> : 75,
    <item:rechiseledcreate:rose_quartz_crushed_connecting> : 75,
    <item:rechiseledcreate:rose_quartz_polished_block> : 75,
    <item:rechiseledcreate:rose_quartz_polished_block_connecting> : 75,
    <item:rechiseledcreate:rose_quartz_squares> : 75,
    <item:rechiseledcreate:rose_quartz_squares_connecting> : 75,
    <item:rechiseledcreate:rose_quartz_tiles_connecting> : 75,
    <item:rechiseledcreate:warped_window_bars> : 1,
    <item:rechiseledcreate:warped_window_bars_connecting> : 1,
    <item:rechiseledcreate:warped_window_covered> : 1,
    <item:rechiseledcreate:warped_window_covered_connecting> : 1,
    <item:rechiseledcreate:warped_window_diagonal> : 1,
    <item:rechiseledcreate:warped_window_diagonal_connecting> : 1,
    <item:rechiseledcreate:warped_window_large> : 1,
    <item:rechiseledcreate:warped_window_large_connecting> : 1,
    <item:rechiseledcreate:warped_window_panes> : 1,
    <item:rechiseledcreate:warped_window_panes_connecting> : 1,
    <item:rechiseledcreate:warped_window_slim> : 1,
    <item:rechiseledcreate:warped_window_slim_connecting> : 1,
    <item:rechiseledcreate:warped_window_tiles> : 1,
    <item:rechiseledcreate:warped_window_tiles_connecting> : 1,
    <item:rechiseledcreate:acacia_window_covered> : 1,
    <item:rechiseledcreate:acacia_window_covered_connecting> : 1,
    <item:rechiseledcreate:acacia_window_diagonal> : 1,
    <item:rechiseledcreate:acacia_window_diagonal_connecting> : 1,
    <item:rechiseledcreate:acacia_window_large> : 1,
    <item:rechiseledcreate:acacia_window_large_connecting> : 1,
    <item:rechiseledcreate:acacia_window_panes> : 1,
    <item:rechiseledcreate:acacia_window_panes_connecting> : 1,
    <item:rechiseledcreate:acacia_window_slim> : 1,
    <item:rechiseledcreate:acacia_window_slim_connecting> : 1,
    <item:rechiseledcreate:acacia_window_swirling> : 1,
    <item:rechiseledcreate:acacia_window_swirling_connecting> : 1,
    <item:rechiseledcreate:acacia_window_tiles> : 1,
    <item:rechiseledcreate:acacia_window_tiles_connecting> : 1,
    <item:rechiseledcreate:andesite_cut_polished_connecting> : 1,
    <item:rechiseledcreate:andesite_cut_small_brick_connecting> : 1,
    <item:rechiseledcreate:asurine_cut_polished_connecting> : 5,
    <item:rechiseledcreate:asurine_cut_small_brick_connecting> : 5,
    <item:rechiseledcreate:birch_window_bars> : 1,
    <item:rechiseledcreate:birch_window_bars_connecting> : 1,
    <item:rechiseledcreate:birch_window_diagonal> : 1,
    <item:rechiseledcreate:birch_window_diagonal_connecting> : 1,
    <item:rechiseledcreate:birch_window_large> : 1,
    <item:rechiseledcreate:birch_window_large_connecting> : 1,
    <item:rechiseledcreate:birch_window_panes> : 1,
    <item:rechiseledcreate:birch_window_panes_connecting> : 1,
    <item:rechiseledcreate:birch_window_slim> : 1,
    <item:rechiseledcreate:birch_window_slim_connecting> : 1,
    <item:rechiseledcreate:birch_window_swirling> : 1,
    <item:rechiseledcreate:birch_window_swirling_connecting> : 1,
    <item:rechiseledcreate:birch_window_tiles> : 1,
    <item:rechiseledcreate:birch_window_tiles_connecting> : 1,
    <item:rechiseledcreate:calcite_cut_polished_connecting> : 1,
    <item:rechiseledcreate:calcite_cut_small_brick_connecting> : 1,
    <item:rechiseledcreate:crimsite_cut_polished_connecting> : 10,
    <item:rechiseledcreate:crimsite_cut_small_brick_connecting> : 10,
    <item:rechiseledcreate:dark_oak_window_bars> : 1,
    <item:rechiseledcreate:dark_oak_window_bars_connecting> : 1,
    <item:rechiseledcreate:dark_oak_window_covered> : 1,
    <item:rechiseledcreate:dark_oak_window_covered_connecting> : 1,
    <item:rechiseledcreate:dark_oak_window_diagonal> : 1,
    <item:rechiseledcreate:dark_oak_window_diagonal_connecting> : 1,
    <item:rechiseledcreate:dark_oak_window_panes> : 1,
    <item:rechiseledcreate:dark_oak_window_panes_connecting> : 1,
    <item:rechiseledcreate:dark_oak_window_slim> : 1,
    <item:rechiseledcreate:dark_oak_window_slim_connecting> : 1,
    <item:rechiseledcreate:dark_oak_window_swirling> : 1,
    <item:rechiseledcreate:dark_oak_window_swirling_connecting> : 1,
    <item:rechiseledcreate:dark_oak_window_tiles> : 1,
    <item:rechiseledcreate:dark_oak_window_tiles_connecting> : 1,
    <item:rechiseledcreate:deepslate_cut_polished_connecting> : 1,
    <item:rechiseledcreate:deepslate_cut_small_brick_connecting> : 1,
    <item:rechiseledcreate:diorite_cut_polished_connecting> : 1,
    <item:rechiseledcreate:diorite_cut_small_brick_connecting> : 1,
    <item:rechiseledcreate:dripstone_cut_polished_connecting> : 10,
    <item:rechiseledcreate:dripstone_cut_small_brick_connecting> : 10,
    <item:rechiseledcreate:granite_cut_polished_connecting> : 1,
    <item:rechiseledcreate:granite_cut_small_brick_connecting> : 1,
    <item:rechiseledcreate:jungle_window_bars> : 1,
    <item:rechiseledcreate:jungle_window_bars_connecting> : 1,
    <item:rechiseledcreate:jungle_window_covered> : 1,
    <item:rechiseledcreate:jungle_window_covered_connecting> : 1,
    <item:rechiseledcreate:jungle_window_diagonal> : 1,
    <item:rechiseledcreate:jungle_window_diagonal_connecting> : 1,
    <item:rechiseledcreate:jungle_window_large> : 1,
    <item:rechiseledcreate:jungle_window_large_connecting> : 1,
    <item:rechiseledcreate:jungle_window_panes> : 1,
    <item:rechiseledcreate:jungle_window_panes_connecting> : 1,
    <item:rechiseledcreate:jungle_window_swirling> : 1,
    <item:rechiseledcreate:jungle_window_swirling_connecting> : 1,
    <item:rechiseledcreate:jungle_window_tiles> : 1,
    <item:rechiseledcreate:jungle_window_tiles_connecting> : 1,
    <item:rechiseledcreate:limestone_cut_polished_connecting> : 1,
    <item:rechiseledcreate:limestone_cut_small_brick_connecting> : 1,
    <item:rechiseledcreate:mechanical_chisel> : 650,
    <item:rechiseledcreate:oak_window_bars> : 1,
    <item:rechiseledcreate:oak_window_bars_connecting> : 1,
    <item:rechiseledcreate:oak_window_covered> : 1,
    <item:rechiseledcreate:oak_window_covered_connecting> : 1,
    <item:rechiseledcreate:oak_window_diagonal> : 1,
    <item:rechiseledcreate:oak_window_diagonal_connecting> : 1,
    <item:rechiseledcreate:oak_window_large> : 1,
    <item:rechiseledcreate:oak_window_large_connecting> : 1,
    <item:rechiseledcreate:oak_window_slim> : 1,
    <item:rechiseledcreate:oak_window_slim_connecting> : 1,
    <item:rechiseledcreate:oak_window_swirling> : 1,
    <item:rechiseledcreate:oak_window_swirling_connecting> : 1,
    <item:rechiseledcreate:oak_window_tiles> : 1,
    <item:rechiseledcreate:oak_window_tiles_connecting> : 1,
    <item:rechiseledcreate:ochrum_cut_polished_connecting> : 50,
    <item:rechiseledcreate:ochrum_cut_small_brick_connecting> : 50,
    <item:rechiseledcreate:scorchia_cut_polished_connecting> : 25,
    <item:rechiseledcreate:scorchia_cut_small_brick_connecting> : 25,
    <item:rechiseledcreate:scoria_cut_polished_connecting> : 25,
    <item:rechiseledcreate:scoria_cut_small_brick_connecting> : 25,
    <item:rechiseledcreate:spruce_window_bars> : 1,
    <item:rechiseledcreate:spruce_window_bars_connecting> : 1,
    <item:rechiseledcreate:spruce_window_covered> : 1,
    <item:rechiseledcreate:spruce_window_covered_connecting> : 1,
    <item:rechiseledcreate:spruce_window_diagonal> : 1,
    <item:rechiseledcreate:spruce_window_diagonal_connecting> : 1,
    <item:rechiseledcreate:spruce_window_large> : 1,
    <item:rechiseledcreate:spruce_window_large_connecting> : 1,
    <item:rechiseledcreate:spruce_window_panes> : 1,
    <item:rechiseledcreate:spruce_window_panes_connecting> : 1,
    <item:rechiseledcreate:spruce_window_slim> : 1,
    <item:rechiseledcreate:spruce_window_slim_connecting> : 1,
    <item:rechiseledcreate:spruce_window_swirling> : 1,
    <item:rechiseledcreate:spruce_window_swirling_connecting> : 1,
    <item:rechiseledcreate:spruce_window_tiles> : 1,
    <item:rechiseledcreate:spruce_window_tiles_connecting> : 1,
    <item:rechiseledcreate:tuff_cut_polished_connecting> : 1,
    <item:rechiseledcreate:tuff_cut_small_brick_connecting> : 1,
    <item:rechiseledcreate:veridium_cut_polished_connecting> : 5,
    <item:rechiseledcreate:veridium_cut_small_brick_connecting> : 5
};

// For each item in the map, check if we're in release mode. If we are, anything below 26 EMC/FMC becomes unburnable for EMC
for item, value in priceTable {
    if (release_mode == true){
        if (value < 26 ) {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), 0);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        } else {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        }
    } else {
        CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
        <tag:items:projectextended:blacklist_condenser>.add(item);
        <tag:items:projectextended:blacklist_learning>.add(item);
    }
}