import crafttweaker.api.tag.MCTag;
import crafttweaker.api.item.IItemStack;
import crafttweaker.api.ingredient.IIngredient;
import crafttweaker.api.item.tooltip.ITooltipFunction;
import stdlib.List;
import mods.projecte.CustomEMC;
import mods.projecte.NSSResolver;

// Item  to EMC/FMC value map.
val priceTable as int[IItemStack] = {
    <item:silence_s_defense_tower:hellraiser_level_4_p> : 319825,
    <item:silence_s_defense_tower:magic_shield_3> : 334400,
    <item:silence_s_defense_tower:tyrant_cannon_level2_p> : 309350,
    <item:silence_s_defense_tower:amethyst_cannon_p> : 203750,
    <item:silence_s_defense_tower:dry_ice_4> : 221850,
    <item:silence_s_defense_tower:magic_shield_2> : 206325,
    <item:silence_s_defense_tower:particle_barrier_2> : 201400,
    <item:silence_s_defense_tower:arcane_missiles_2> : 119225,
    <item:silence_s_defense_tower:battery_2> : 156925,
    <item:silence_s_defense_tower:black_hole_generator_p> : 99175,
    <item:silence_s_defense_tower:cruel_soul_3> : 94200,
    <item:silence_s_defense_tower:dry_ice_3> : 107200,
    <item:silence_s_defense_tower:energy_shield> : 131775,
    <item:silence_s_defense_tower:firework_launcher_p> : 138750,
    <item:silence_s_defense_tower:hell_core_4> : 179650,
    <item:silence_s_defense_tower:hellraiser_level_3_p> : 112900,
    <item:silence_s_defense_tower:nano_armor> : 133450,
    <item:silence_s_defense_tower:netherite_armor_1> : 99550,
    <item:silence_s_defense_tower:particle_barrier_1> : 129225,
    <item:silence_s_defense_tower:pulse> : 99550,
    <item:silence_s_defense_tower:shield_generator_2> : 106125,
    <item:silence_s_defense_tower:sticky_bomb_battery_p> : 140875,
    <item:silence_s_defense_tower:wither_armor_2> : 160475,
    <item:silence_s_defense_tower:acid_core_3> : 29925,
    <item:silence_s_defense_tower:acid_eater_level2_p> : 38825,
    <item:silence_s_defense_tower:acid_eater_level3_p> : 96275,
    <item:silence_s_defense_tower:amethyst_armor_2> : 83625,
    <item:silence_s_defense_tower:arcane_missiles_1> : 29450,
    <item:silence_s_defense_tower:arrogance> : 93100,
    <item:silence_s_defense_tower:ball_lightning_2> : 30050,
    <item:silence_s_defense_tower:ball_lightning_gennerator_p> : 86450,
    <item:silence_s_defense_tower:battery_1> : 96425,
    <item:silence_s_defense_tower:blood_magic_2> : 95325,
    <item:silence_s_defense_tower:bloodthirsty_soul_3> : 40175,
    <item:silence_s_defense_tower:bronze_armor_4> : 81275,
    <item:silence_s_defense_tower:cruel_soul> : 46300,
    <item:silence_s_defense_tower:cruel_soul_2> : 70250,
    <item:silence_s_defense_tower:diamond_armor_2> : 77700,
    <item:silence_s_defense_tower:driving_core_4> : 80625,
    <item:silence_s_defense_tower:electric_arc> : 55775,
    <item:silence_s_defense_tower:electromagnetic_gun_p> : 86200,
    <item:silence_s_defense_tower:electromagnetic_railgun_p> : 88425,
    <item:silence_s_defense_tower:emergency_maintenance_2> : 70150,
    <item:silence_s_defense_tower:enmity_3> : 52600,
    <item:silence_s_defense_tower:flesh_armor_1> : 20650,
    <item:silence_s_defense_tower:flesh_armor_2> : 93525,
    <item:silence_s_defense_tower:fracture_2> : 35800,
    <item:silence_s_defense_tower:fracture_3> : 52600,
    <item:silence_s_defense_tower:frightened_soul> : 45925,
    <item:silence_s_defense_tower:heavy_armor> : 85900,
    <item:silence_s_defense_tower:heavy_crossbow_p> : 68825,
    <item:silence_s_defense_tower:hell_core_3> : 90450,
    <item:silence_s_defense_tower:impatient_soul_2> : 24900,
    <item:silence_s_defense_tower:iron_armor_4> : 83675,
    <item:silence_s_defense_tower:large_fireworks_2> : 27150,
    <item:silence_s_defense_tower:leakage> : 86100,
    <item:silence_s_defense_tower:magic_shield> : 76700,
    <item:silence_s_defense_tower:overclock> : 51250,
    <item:silence_s_defense_tower:overload_2> : 23050,
    <item:silence_s_defense_tower:pactof_blood> : 54400,
    <item:silence_s_defense_tower:plague_silverfish_1> : 49375,
    <item:silence_s_defense_tower:precision_components_2> : 25875,
    <item:silence_s_defense_tower:reinforcement_materials_2> : 24000,
    <item:silence_s_defense_tower:shield_generator_1> : 58125,
    <item:silence_s_defense_tower:tactical_chip_2> : 54150,
    <item:silence_s_defense_tower:tesla_electric_tower> : 57625,
    <item:silence_s_defense_tower:thorn_armor_2> : 77775,
    <item:silence_s_defense_tower:type_a_robot_barracks_p> : 94850,
    <item:silence_s_defense_tower:type_c_robot_barracks_p> : 43975,
    <item:silence_s_defense_tower:type_s_robot_barracks_p> : 96025,
    <item:silence_s_defense_tower:tyrant_cannon_level1_p> : 99400,
    <item:silence_s_defense_tower:weeping_soul> : 54400,
    <item:silence_s_defense_tower:welding_torch_2> : 24650,
    <item:silence_s_defense_tower:wither_armor_1> : 73200,
    <item:silence_s_defense_tower:acid_core_1> : 3900,
    <item:silence_s_defense_tower:acid_core_2> : 8325,
    <item:silence_s_defense_tower:acid_eater_level1_p> : 6475,
    <item:silence_s_defense_tower:advanced_part> : 900,
    <item:silence_s_defense_tower:aluminum_part> : 900,
    <item:silence_s_defense_tower:amethyst_armor> : 5475,
    <item:silence_s_defense_tower:arrow_turret_leavl1_p> : 1925,
    <item:silence_s_defense_tower:arrow_turret_leavl2_p> : 6300,
    <item:silence_s_defense_tower:ball_lightning_1> : 11150,
    <item:silence_s_defense_tower:blood_arrow_1> : 14175,
    <item:silence_s_defense_tower:blood_arrow_2> : 17775,
    <item:silence_s_defense_tower:blood_magic_1> : 8925,
    <item:silence_s_defense_tower:bloodthirsty_soul> : 10750,
    <item:silence_s_defense_tower:bloodthirsty_soul_2> : 16250,
    <item:silence_s_defense_tower:bouncy_ball> : 1375,
    <item:silence_s_defense_tower:brand_new> : 21100,
    <item:silence_s_defense_tower:bronze_armor_1> : 1350,
    <item:silence_s_defense_tower:bronze_armor_2> : 5250,
    <item:silence_s_defense_tower:bronze_armor_3> : 9025,
    <item:silence_s_defense_tower:bursts_1> : 3425,
    <item:silence_s_defense_tower:candy_turret_base> : 9800,
    <item:silence_s_defense_tower:cannon_level1_p> : 2075,
    <item:silence_s_defense_tower:cannon_level2_p> : 6450,
    <item:silence_s_defense_tower:counter_2> : 10550,
    <item:silence_s_defense_tower:dart_launcher_level1_p> : 1925,
    <item:silence_s_defense_tower:dart_launcher_level2_p> : 6300,
    <item:silence_s_defense_tower:diamond_armor_1> : 4475,
    <item:silence_s_defense_tower:driving_core_2> : 3200,
    <item:silence_s_defense_tower:driving_core_3> : 7250,
    <item:silence_s_defense_tower:dry_ice_1> : 6425,
    <item:silence_s_defense_tower:dry_ice_2> : 11150,
    <item:silence_s_defense_tower:electric_field_diffusion> : 1700,
    <item:silence_s_defense_tower:emergency_maintenance_1> : 13200,
    <item:silence_s_defense_tower:enmity_2> : 1500,
    <item:silence_s_defense_tower:fracture> : 3900,
    <item:silence_s_defense_tower:fury_chip_1> : 12075,
    <item:silence_s_defense_tower:fury_chip_2> : 18975,
    <item:silence_s_defense_tower:giant_dart_launcher_p> : 12800,
    <item:silence_s_defense_tower:hell_core_1> : 3900,
    <item:silence_s_defense_tower:hell_core_2> : 9425,
    <item:silence_s_defense_tower:hellraiser_level_1_p> : 4725,
    <item:silence_s_defense_tower:hellraiser_level_2_p> : 17225,
    <item:silence_s_defense_tower:ice_cannon_p> : 6450,
    <item:silence_s_defense_tower:impatient_soul> : 7200,
    <item:silence_s_defense_tower:iron_armor_1> : 2100,
    <item:silence_s_defense_tower:iron_armor_2> : 6750,
    <item:silence_s_defense_tower:iron_armor_3> : 10975,
    <item:silence_s_defense_tower:large_container> : 18900,
    <item:silence_s_defense_tower:large_fireworks> : 9100,
    <item:silence_s_defense_tower:living_lightning> : 7750,
    <item:silence_s_defense_tower:maintenance_station0> : 4650,
    <item:silence_s_defense_tower:miniature_electromagnetic_gun_p> : 10300,
    <item:silence_s_defense_tower:molotov_cocktail_2> : 2400,
    <item:silence_s_defense_tower:molotov_cocktail_3> : 21450,
    <item:silence_s_defense_tower:multishot_1> : 8350,
    <item:silence_s_defense_tower:nether_wart_sauce> : 1750,
    <item:silence_s_defense_tower:overload_1> : 7600,
    <item:silence_s_defense_tower:power_chip_1> : 900,
    <item:silence_s_defense_tower:power_chip_2> : 19950,
    <item:silence_s_defense_tower:precision_components_1> : 5175,
    <item:silence_s_defense_tower:quick_loading_1> : 900,
    <item:silence_s_defense_tower:quick_loading_2> : 17700,
    <item:silence_s_defense_tower:reinforcement_materials_1> : 1175,
    <item:silence_s_defense_tower:rubber_band> : 1300,
    <item:silence_s_defense_tower:sentry_gun_p> : 11650,
    <item:silence_s_defense_tower:soul> : 6300,
    <item:silence_s_defense_tower:soul_container> : 6300,
    <item:silence_s_defense_tower:strafing_1> : 3425,
    <item:silence_s_defense_tower:strong_acidity_1> : 3200,
    <item:silence_s_defense_tower:strong_acidity_2> : 10000,
    <item:silence_s_defense_tower:tactical_chip_1> : 5100,
    <item:silence_s_defense_tower:thorn_armor> : 5075,
    <item:silence_s_defense_tower:welding_torch> : 6450,
    <item:silence_s_defense_tower:chip> : 200,
    <item:silence_s_defense_tower:driving_core_1> : 1150,
    <item:silence_s_defense_tower:enmity> : 450,
    <item:silence_s_defense_tower:explosives> : 700,
    <item:silence_s_defense_tower:glass_jar> : 1,
    <item:silence_s_defense_tower:hammer> : 100,
    <item:silence_s_defense_tower:handing_glove> : 400,
    <item:silence_s_defense_tower:molotov_cocktail> : 700,
    <item:silence_s_defense_tower:resource_box_1> : 300,
    <item:silence_s_defense_tower:technology_damage> : 100,
    <item:silence_s_defense_tower:technology_damage_2> : 25,
    <item:silence_s_defense_tower:technology_heal> : 100,
    <item:silence_s_defense_tower:technology_heal_2> : 25,
    <item:silence_s_defense_tower:technology_health> : 100,
    <item:silence_s_defense_tower:technology_health_2> : 25,
    <item:silence_s_defense_tower:technology_speed> : 100,
    <item:silence_s_defense_tower:technology_speed_2> : 25,
    <item:silence_s_defense_tower:tesla_electric_tower_base> : 5
};

// For each item in the map, check if we're in release mode. If we are, anything below 26 EMC/FMC becomes unburnable for EMC
for item, value in priceTable {
    if (ReleaseMode.releaseMode == true){
        if (value < 26 ) {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), 0);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        } else {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        }
    } else {
        CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
        <tag:items:projectextended:blacklist_condenser>.add(item);
        <tag:items:projectextended:blacklist_learning>.add(item);
    }
}