import crafttweaker.api.tag.MCTag;
import crafttweaker.api.item.IItemStack;
import crafttweaker.api.ingredient.IIngredient;
import crafttweaker.api.item.tooltip.ITooltipFunction;
import stdlib.List;
import mods.projecte.CustomEMC;
import mods.projecte.NSSResolver;

// This variable controls whether we are in the pack dev mode or release mode. In Pack Dev mode, all EMC/FMC values are enabled to help calculate EMC/FMC for other mods.
var release_mode = false;

// Item  to EMC/FMC value map.
val priceTable as int[IItemStack] = {
    <item:tanukidecor:alarm_clock> : 225,
    <item:tanukidecor:anniversary_clock> : 225,
    <item:tanukidecor:antique_bed> : 225,
    <item:tanukidecor:antique_bookcase> : 225,
    <item:tanukidecor:antique_bureau> : 225,
    <item:tanukidecor:antique_cabinet> : 225,
    <item:tanukidecor:antique_chair> : 225,
    <item:tanukidecor:antique_clock> : 225,
    <item:tanukidecor:antique_desk> : 225,
    <item:tanukidecor:antique_mirror> : 225,
    <item:tanukidecor:antique_phone> : 225,
    <item:tanukidecor:antique_radio> : 225,
    <item:tanukidecor:antique_small_table> : 225,
    <item:tanukidecor:antique_small_table_with_doily> : 225,
    <item:tanukidecor:antique_sofa> : 225,
    <item:tanukidecor:antique_table> : 225,
    <item:tanukidecor:antique_wall_oil_lamp> : 225,
    <item:tanukidecor:antique_wall_shelf> : 225,
    <item:tanukidecor:antique_wardrobe> : 225,
    <item:tanukidecor:banjo_clock> : 225,
    <item:tanukidecor:birdcage> : 225,
    <item:tanukidecor:blue_bed> : 225,
    <item:tanukidecor:blue_bench> : 225,
    <item:tanukidecor:blue_bookshelf> : 225,
    <item:tanukidecor:blue_bureau> : 225,
    <item:tanukidecor:blue_cabinet> : 225,
    <item:tanukidecor:blue_chair> : 225,
    <item:tanukidecor:blue_clock> : 225,
    <item:tanukidecor:blue_dresser> : 225,
    <item:tanukidecor:blue_lamp> : 225,
    <item:tanukidecor:blue_rocket_lamp> : 225,
    <item:tanukidecor:blue_science_pod> : 225,
    <item:tanukidecor:blue_stall_tarp> : 225,
    <item:tanukidecor:blue_table> : 225,
    <item:tanukidecor:blue_wall_tarp> : 225,
    <item:tanukidecor:blue_wardrobe> : 225,
    <item:tanukidecor:brown_mushroom_bed> : 225,
    <item:tanukidecor:brown_mushroom_lamp> : 225,
    <item:tanukidecor:brown_mushroom_log_stool> : 225,
    <item:tanukidecor:brown_mushroom_stool> : 225,
    <item:tanukidecor:brown_mushroom_table> : 225,
    <item:tanukidecor:cabana_armchair> : 225,
    <item:tanukidecor:cabana_bed> : 225,
    <item:tanukidecor:cabana_bookcase> : 225,
    <item:tanukidecor:cabana_chair> : 225,
    <item:tanukidecor:cabana_dresser> : 225,
    <item:tanukidecor:cabana_lamp> : 225,
    <item:tanukidecor:cabana_screen> : 225,
    <item:tanukidecor:cabana_table> : 225,
    <item:tanukidecor:cabana_vanity> : 225,
    <item:tanukidecor:cabana_wardrobe> : 225,
    <item:tanukidecor:carriage_clock> : 225,
    <item:tanukidecor:cash_register> : 225,
    <item:tanukidecor:classic_vase> : 225,
    <item:tanukidecor:crystal_clock> : 225,
    <item:tanukidecor:cuckoo_clock> : 225,
    <item:tanukidecor:dessert_case> : 225,
    <item:tanukidecor:developer_mini_figure> : 225,
    <item:tanukidecor:display_case> : 225,
    <item:tanukidecor:display_watch> : 225,
    <item:tanukidecor:diy_workbench> : 450,
    <item:tanukidecor:egyptian_bed> : 225,
    <item:tanukidecor:egyptian_chair> : 225,
    <item:tanukidecor:egyptian_crest> : 225,
    <item:tanukidecor:egyptian_lamp> : 225,
    <item:tanukidecor:egyptian_table> : 225,
    <item:tanukidecor:elegant_birdcage> : 225,
    <item:tanukidecor:emblem_clock> : 225,
    <item:tanukidecor:fancy_vase> : 225,
    <item:tanukidecor:firewood> : 225,
    <item:tanukidecor:foliot_clock> : 225,
    <item:tanukidecor:gingerbread_clock> : 225,
    <item:tanukidecor:globe> : 225,
    <item:tanukidecor:glowing_moss_jar> : 225,
    <item:tanukidecor:gorgeous_bed> : 225,
    <item:tanukidecor:gorgeous_chest> : 225,
    <item:tanukidecor:gorgeous_clock> : 225,
    <item:tanukidecor:gorgeous_closet> : 225,
    <item:tanukidecor:gorgeous_counter> : 225,
    <item:tanukidecor:gorgeous_desk> : 225,
    <item:tanukidecor:gorgeous_lamp> : 225,
    <item:tanukidecor:gorgeous_mini_drawer> : 225,
    <item:tanukidecor:gorgeous_seat> : 225,
    <item:tanukidecor:gorgeous_sofa> : 225,
    <item:tanukidecor:gorgeous_stool> : 225,
    <item:tanukidecor:gorgeous_table> : 225,
    <item:tanukidecor:grandfather_clock> : 225,
    <item:tanukidecor:green_bed> : 225,
    <item:tanukidecor:green_bench> : 225,
    <item:tanukidecor:green_chair> : 225,
    <item:tanukidecor:green_clock> : 225,
    <item:tanukidecor:green_counter> : 225,
    <item:tanukidecor:green_desk> : 225,
    <item:tanukidecor:green_dresser> : 225,
    <item:tanukidecor:green_lamp> : 225,
    <item:tanukidecor:green_mini_drawer> : 225,
    <item:tanukidecor:green_pantry> : 225,
    <item:tanukidecor:green_rocket_lamp> : 225,
    <item:tanukidecor:green_science_pod> : 225,
    <item:tanukidecor:green_stall_tarp> : 225,
    <item:tanukidecor:green_table> : 225,
    <item:tanukidecor:green_wall_tarp> : 225,
    <item:tanukidecor:green_wardrobe> : 225,
    <item:tanukidecor:gumball_machine> : 225,
    <item:tanukidecor:handcart> : 225,
    <item:tanukidecor:holiday_tree> : 225,
    <item:tanukidecor:hourglass> : 225,
    <item:tanukidecor:lantern_clock> : 225,
    <item:tanukidecor:large_clock_tower_dial> : 225,
    <item:tanukidecor:large_fancy_vase> : 225,
    <item:tanukidecor:large_fireplace> : 225,
    <item:tanukidecor:large_striped_vase> : 225,
    <item:tanukidecor:library_clock> : 225,
    <item:tanukidecor:log_bench> : 225,
    <item:tanukidecor:log_stool> : 225,
    <item:tanukidecor:long_display_case> : 225,
    <item:tanukidecor:mantle_clock> : 225,
    <item:tanukidecor:mayoral_mini_figure> : 225,
    <item:tanukidecor:metronome> : 225,
    <item:tanukidecor:minimalist_bed> : 225,
    <item:tanukidecor:minimalist_chair> : 225,
    <item:tanukidecor:minimalist_clock> : 225,
    <item:tanukidecor:minimalist_couch> : 225,
    <item:tanukidecor:minimalist_dresser> : 225,
    <item:tanukidecor:minimalist_lamp> : 225,
    <item:tanukidecor:minimalist_mirror> : 225,
    <item:tanukidecor:minimalist_small_table> : 225,
    <item:tanukidecor:minimalist_stool> : 225,
    <item:tanukidecor:minimalist_table> : 225,
    <item:tanukidecor:minimalist_wardrobe> : 225,
    <item:tanukidecor:narrow_blue_streamer> : 225,
    <item:tanukidecor:narrow_green_streamer> : 225,
    <item:tanukidecor:narrow_red_streamer> : 225,
    <item:tanukidecor:narrow_string_lights> : 225,
    <item:tanukidecor:narrow_yellow_streamer> : 225,
    <item:tanukidecor:neon_club_sign> : 225,
    <item:tanukidecor:neon_diamond_sign> : 225,
    <item:tanukidecor:neon_heart_sign> : 225,
    <item:tanukidecor:neon_spade_sign> : 225,
    <item:tanukidecor:newtons_cradle> : 225,
    <item:tanukidecor:orange_science_pod> : 225,
    <item:tanukidecor:owl_clock> : 225,
    <item:tanukidecor:phonograph> : 225,
    <item:tanukidecor:piano> : 225,
    <item:tanukidecor:pink_rocket_lamp> : 225,
    <item:tanukidecor:plasma_ball> : 225,
    <item:tanukidecor:purple_rocket_lamp> : 225,
    <item:tanukidecor:recognizable_clock> : 225,
    <item:tanukidecor:red_clock> : 225,
    <item:tanukidecor:red_mushroom_bed> : 225,
    <item:tanukidecor:red_mushroom_lamp> : 225,
    <item:tanukidecor:red_mushroom_log_stool> : 225,
    <item:tanukidecor:red_mushroom_stool> : 225,
    <item:tanukidecor:red_mushroom_table> : 225,
    <item:tanukidecor:red_rocket_lamp> : 225,
    <item:tanukidecor:red_science_pod> : 225,
    <item:tanukidecor:red_stall_tarp> : 225,
    <item:tanukidecor:red_wall_tarp> : 225,
    <item:tanukidecor:reed_clock> : 225,
    <item:tanukidecor:regal_armoire> : 225,
    <item:tanukidecor:regal_bed> : 225,
    <item:tanukidecor:regal_bookshelf> : 225,
    <item:tanukidecor:regal_chair> : 225,
    <item:tanukidecor:regal_clock> : 225,
    <item:tanukidecor:regal_dresser> : 225,
    <item:tanukidecor:regal_lamp> : 225,
    <item:tanukidecor:regal_small_table> : 225,
    <item:tanukidecor:regal_sofa> : 225,
    <item:tanukidecor:regal_table> : 225,
    <item:tanukidecor:regal_vanity> : 225,
    <item:tanukidecor:regal_wall_lamp> : 225,
    <item:tanukidecor:rococo_clock> : 225,
    <item:tanukidecor:rough_log_bench> : 225,
    <item:tanukidecor:ship_in_a_bottle> : 225,
    <item:tanukidecor:slate_clock> : 225,
    <item:tanukidecor:slot_machine> : 225,
    <item:tanukidecor:small_clock_tower_dial> : 225,
    <item:tanukidecor:small_fancy_vase> : 225,
    <item:tanukidecor:small_fireplace> : 225,
    <item:tanukidecor:small_striped_vase> : 225,
    <item:tanukidecor:snowglobe> : 225,
    <item:tanukidecor:station_clock> : 225,
    <item:tanukidecor:sweets_bed> : 225,
    <item:tanukidecor:sweets_bookcase> : 225,
    <item:tanukidecor:sweets_chair> : 225,
    <item:tanukidecor:sweets_closet> : 225,
    <item:tanukidecor:sweets_dresser> : 225,
    <item:tanukidecor:sweets_mini_lamp> : 225,
    <item:tanukidecor:sweets_mini_table> : 225,
    <item:tanukidecor:sweets_sofa> : 225,
    <item:tanukidecor:sweets_table> : 225,
    <item:tanukidecor:sweets_wall_lamp> : 225,
    <item:tanukidecor:train_set> : 225,
    <item:tanukidecor:turquoise_rocket_lamp> : 225,
    <item:tanukidecor:wide_blue_streamer> : 225,
    <item:tanukidecor:wide_green_streamer> : 225,
    <item:tanukidecor:wide_red_streamer> : 225,
    <item:tanukidecor:wide_string_lights> : 225,
    <item:tanukidecor:wide_yellow_streamer> : 225,
    <item:tanukidecor:wooden_block_bed> : 225,
    <item:tanukidecor:wooden_block_bench> : 225,
    <item:tanukidecor:wooden_block_bookshelf> : 225,
    <item:tanukidecor:wooden_block_chair> : 225,
    <item:tanukidecor:wooden_block_clock> : 225,
    <item:tanukidecor:wooden_block_drawers> : 225,
    <item:tanukidecor:wooden_block_stool> : 225,
    <item:tanukidecor:wooden_block_table> : 225,
    <item:tanukidecor:wooden_block_toys> : 225,
    <item:tanukidecor:yellow_rocket_lamp> : 225,
    <item:tanukidecor:yellow_stall_tarp> : 225,
    <item:tanukidecor:yellow_wall_tarp> : 225
};

// For each item in the map, check if we're in release mode. If we are, anything below 26 EMC/FMC becomes unburnable for EMC
for item, value in priceTable {
    if (release_mode == true){
        if (value < 26 ) {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), 0);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        } else {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        }
    } else {
        CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
        <tag:items:projectextended:blacklist_condenser>.add(item);
        <tag:items:projectextended:blacklist_learning>.add(item);
    }
}