import crafttweaker.api.tag.MCTag;
import crafttweaker.api.item.IItemStack;
import crafttweaker.api.ingredient.IIngredient;
import crafttweaker.api.item.tooltip.ITooltipFunction;
import stdlib.List;
import mods.projecte.CustomEMC;
import mods.projecte.NSSResolver;

// This variable controls whether we are in the pack dev mode or release mode. In Pack Dev mode, all EMC/FMC values are enabled to help calculate EMC/FMC for other mods.
var release_mode = false;

// Item  to EMC/FMC value map.
val priceTable as int[IItemStack] = {
    <item:the_vault:god_token> : 5500,
    <item:the_vault:augment> : 4000,
    <item:the_vault:angel_block> : 148200,
    <item:the_vault:burger_chili> : 750,
    <item:the_vault:waning_focus> : 6500,
    <item:the_vault:waxing_focus> : 6500,
    <item:the_vault:cheese_burger_feast> : 1775,
    <item:the_vault:crystal_seal_herald> : 0,
    <item:the_vault:crystal_seal_raid_infinite> : 0,
    <item:the_vault:echoing_ingot> : 260550,
    <item:the_vault:etching> : 49000,
    <item:the_vault:infused_eternal_soul> : 147000,
    <item:the_vault:map> : 2000,
    <item:the_vault:mystic_pear> : 100000,
    <item:the_vault:neuralizer> : 900400,
    <item:the_vault:orb_frame> : 410500,
    <item:the_vault:salty_deluxe_cheese_burger> : 1275,
    <item:the_vault:vault_iridium> : 590500,
    <item:the_vault:adaptive_focus> : 8750,
    <item:the_vault:altar_chest> : 4650,
    <item:the_vault:altar_chest_scroll> : 2000,
    <item:the_vault:ancient_copper_conduit_block> : 600,
    <item:the_vault:artifact_fragment> : 6300,
    <item:the_vault:artifact_projector_block> : 10625,
    <item:the_vault:ascension_forge> : 69125,
    <item:the_vault:bitter_lemon> : 50000,
    <item:the_vault:black_chromatic_steel_block> : 41050,
    <item:the_vault:blank_key> : 43600,
    <item:the_vault:burger_pickles> : 450,
    <item:the_vault:burger_sauce> : 500,
    <item:the_vault:capstone_peaceful> : 5750,
    <item:the_vault:capstone_treasure_hunter> : 10400,
    <item:the_vault:card_essence_extractor> : 6300,
    <item:the_vault:crispy_deluxe_cheese_burger> : 825,
    <item:the_vault:cryonic_focus> : 8750,
    <item:the_vault:crystal_seal_architect> : 10825,
    <item:the_vault:crystal_seal_cake> : 20000,
    <item:the_vault:crystal_seal_prophet> : 9850,
    <item:the_vault:echo_pog> : 100000,
    <item:the_vault:ember> : 0,
    <item:the_vault:empowered_chaotic_focus> : 8750,
    <item:the_vault:enigma_chest> : 4575,
    <item:the_vault:enigma_chest_scroll> : 2000,
    <item:the_vault:extraordinary_echo_gem> : 112000,
    <item:the_vault:hardened_wutodic_mass> : 75975,
    <item:the_vault:key_ashium> : 54000,
    <item:the_vault:key_bomignite> : 54000,
    <item:the_vault:key_gorginite> : 54000,
    <item:the_vault:key_iskallium> : 54000,
    <item:the_vault:key_mould> : 37600,
    <item:the_vault:key_petzanite> : 54000,
    <item:the_vault:key_piece> : 750,
    <item:the_vault:key_puffium> : 54000,
    <item:the_vault:key_sparkletine> : 54000,
    <item:the_vault:key_tubium> : 54000,
    <item:the_vault:key_upaline> : 54000,
    <item:the_vault:key_xenium> : 54000,
    <item:the_vault:large_charm> : 6300,
    <item:the_vault:majestic_charm> : 12600,
    <item:the_vault:mango> : 75000,
    <item:the_vault:old_notes> : 5000,
    <item:the_vault:omega_pog> : 93600,
    <item:the_vault:phoenix_dust> : 525,
    <item:the_vault:pyretic_focus> : 8750,
    <item:the_vault:resilient_focus> : 8000,
    <item:the_vault:small_charm> : 3150,
    <item:the_vault:sour_orange> : 50000,
    <item:the_vault:spicy_hearty_burger> : 2525,
    <item:the_vault:sublime_vault_elixir> : 38250,
    <item:the_vault:sublime_vault_substance> : 60425,
    <item:the_vault:sublime_vault_vision> : 66450,
    <item:the_vault:treasure_chest> : 9550,
    <item:the_vault:treasure_chest_scroll> : 7000,
    <item:the_vault:unidentified_artifact> : 25000,
    <item:the_vault:unidentified_treasure_key> : 52725,
    <item:the_vault:vault_artifact> : 6300,
    <item:the_vault:vault_catalyst_chaos> : 20000,
    <item:the_vault:vault_harvester> : 120475,
    <item:the_vault:vault_palladium> : 65600,
    <item:the_vault:vorpal_focus> : 8500,
    <item:the_vault:alchemy_table> : 5650,
    <item:the_vault:antique_collector_book> : 7025,
    <item:the_vault:black_chromatic_steel_ingot> : 4550,
    <item:the_vault:black_chromatic_steel_nugget> : 500,
    <item:the_vault:block_gem_echo> : 56000,
    <item:the_vault:burger_cheese> : 125,
    <item:the_vault:burger_lettuce> : 350,
    <item:the_vault:burger_tomato> : 250,
    <item:the_vault:capstone_dungeon_hunter> : 8250,
    <item:the_vault:capstone_pylon_hunter> : 5750,
    <item:the_vault:capstone_vendoor_hunter> : 10200,
    <item:the_vault:catalyst_infusion_table> : 10525,
    <item:the_vault:chaotic_focus> : 5500,
    <item:the_vault:chunk_ashium> : 93600,
    <item:the_vault:chunk_bomignite> : 93600,
    <item:the_vault:chunk_gorginite> : 93600,
    <item:the_vault:chunk_iskallium> : 93600,
    <item:the_vault:chunk_petzanite> : 93600,
    <item:the_vault:chunk_sparkletine> : 93600,
    <item:the_vault:chunk_tubium> : 93600,
    <item:the_vault:chunk_upaline> : 93600,
    <item:the_vault:chunk_xenium> : 93600,
    <item:the_vault:cluster_ashium> : 10400,
    <item:the_vault:cluster_bomignite> : 10400,
    <item:the_vault:cluster_gorginite> : 10400,
    <item:the_vault:cluster_iskallium> : 10400,
    <item:the_vault:cluster_netherite> : 20650,
    <item:the_vault:cluster_petzanite> : 10400,
    <item:the_vault:cluster_sparkletine> : 10400,
    <item:the_vault:cluster_tubium> : 10400,
    <item:the_vault:cluster_upaline> : 10400,
    <item:the_vault:cluster_xenium> : 10400,
    <item:the_vault:crystal_seal_empty> : 3875,
    <item:the_vault:crystal_seal_executioner> : 9250,
    <item:the_vault:crystal_seal_hunter> : 11650,
    <item:the_vault:crystal_seal_sage> : 9850,
    <item:the_vault:crystal_seal_scout> : 12000,
    <item:the_vault:crystal_seal_trial_chamber> : 100,
    <item:the_vault:crystal_workbench> : 7675,
    <item:the_vault:deluxe_cheese_burger> : 475,
    <item:the_vault:double_cheese_burger> : 300,
    <item:the_vault:dreamstone> : 2250,
    <item:the_vault:extraordinary_black_opal> : 9600,
    <item:the_vault:extraordinary_painite> : 7200,
    <item:the_vault:extraordinary_wutodie> : 5750,
    <item:the_vault:eye_of_avarice> : 3025,
    <item:the_vault:fools_gold> : 5000,
    <item:the_vault:fundamental_focus> : 8000,
    <item:the_vault:gem_pog> : 9000,
    <item:the_vault:gilded_barrel> : 2450,
    <item:the_vault:golden_tooth> : 1000,
    <item:the_vault:grand_charm> : 5000,
    <item:the_vault:grapes> : 10000,
    <item:the_vault:idona_brick> : 475,
    <item:the_vault:idona_brick_chiseled> : 475,
    <item:the_vault:idona_dark_smooth_brick> : 475,
    <item:the_vault:idona_gem_block> : 475,
    <item:the_vault:idona_light_smooth_brick> : 475,
    <item:the_vault:inscription> : 1000,
    <item:the_vault:inscription_piece> : 150,
    <item:the_vault:inscription_table> : 11725,
    <item:the_vault:knowledge_star> : 55800,
    <item:the_vault:knowledge_star_core> : 1800,
    <item:the_vault:knowledge_star_shard> : 7650,
    <item:the_vault:loot_sack> : 2000,
    <item:the_vault:lost_bounty> : 5000,
    <item:the_vault:mod_box> : 725,
    <item:the_vault:modifier_scroll> : 5000,
    <item:the_vault:mystical_powder> : 6700,
    <item:the_vault:opportunistic_focus> : 8000,
    <item:the_vault:ore_echo> : 14000,
    <item:the_vault:ornate_bricks_netherite> : 800,
    <item:the_vault:packed_vault_meat_block> : 10125,
    <item:the_vault:perfect_alexandrite> : 700,
    <item:the_vault:perfect_benitoite> : 200,
    <item:the_vault:perfect_black_opal> : 2400,
    <item:the_vault:perfect_echo_gem> : 28000,
    <item:the_vault:perfect_larimar> : 75,
    <item:the_vault:perfect_painite> : 1800,
    <item:the_vault:perfect_wutodie> : 1450,
    <item:the_vault:phoenix_feather> : 4675,
    <item:the_vault:plunderer_pearl> : 9400,
    <item:the_vault:plushie> : 2000,
    <item:the_vault:repair_core> : 23950,
    <item:the_vault:skill_altar> : 15450,
    <item:the_vault:spirit_extractor> : 11575,
    <item:the_vault:star_fruit> : 15000,
    <item:the_vault:temporal_shard> : 5000,
    <item:the_vault:trinket> : 2000,
    <item:the_vault:trinket_forge> : 6075,
    <item:the_vault:trinket_scrap> : 2000,
    <item:the_vault:unique_crate> : 9575,
    <item:the_vault:unique_crate_scroll> : 7000,
    <item:the_vault:vault_alloy> : 5550,
    <item:the_vault:vault_anvil> : 25525,
    <item:the_vault:vault_artisan_station> : 14275,
    <item:the_vault:vault_catalyst> : 5850,
    <item:the_vault:vault_catalyst_fragment> : 650,
    <item:the_vault:vault_compass> : 17800,
    <item:the_vault:vault_diamond_block> : 1125,
    <item:the_vault:vault_diffuser> : 5675,
    <item:the_vault:vault_god_charm> : 6300,
    <item:the_vault:vault_gold> : 800,
    <item:the_vault:vault_ingot> : 14450,
    <item:the_vault:vault_platinum> : 7300,
    <item:the_vault:void_liquid_bucket> : 925,
    <item:the_vault:void_stone> : 19300,
    <item:the_vault:wutodic_mass> : 8450,
    <item:the_vault:amplifying_focus> : 675,
    <item:the_vault:ancient_copper_block> : 25,
    <item:the_vault:ancient_copper_block_exposed> : 25,
    <item:the_vault:ancient_copper_block_oxidized> : 25,
    <item:the_vault:ancient_copper_block_pillar> : 25,
    <item:the_vault:ancient_copper_block_pillar_exposed> : 25,
    <item:the_vault:ancient_copper_block_pillar_oxidized> : 25,
    <item:the_vault:ancient_copper_block_pillar_weathered> : 25,
    <item:the_vault:ancient_copper_block_weathered> : 25,
    <item:the_vault:ancient_copper_bricks> : 25,
    <item:the_vault:ancient_copper_bricks_exposed> : 25,
    <item:the_vault:ancient_copper_bricks_oxidized> : 25,
    <item:the_vault:ancient_copper_bricks_weathered> : 25,
    <item:the_vault:ancient_copper_button> : 25,
    <item:the_vault:ancient_copper_button_exposed> : 25,
    <item:the_vault:ancient_copper_button_oxidized> : 25,
    <item:the_vault:ancient_copper_button_weathered> : 25,
    <item:the_vault:ancient_copper_ingot> : 2,
    <item:the_vault:ancient_copper_small_bricks> : 25,
    <item:the_vault:ancient_copper_small_bricks_exposed> : 25,
    <item:the_vault:ancient_copper_small_bricks_oxidized> : 25,
    <item:the_vault:ancient_copper_small_bricks_weathered> : 25,
    <item:the_vault:ancient_copper_trapdoor> : 10,
    <item:the_vault:ancient_copper_trapdoor_exposed> : 10,
    <item:the_vault:ancient_copper_trapdoor_oxidized> : 10,
    <item:the_vault:ancient_copper_trapdoor_weathered> : 10,
    <item:the_vault:animal_jar> : 1,
    <item:the_vault:animal_pen> : 1,
    <item:the_vault:animatrix_block> : 368,
    <item:the_vault:axe> : 2000,
    <item:the_vault:banished_soul> : 875,
    <item:the_vault:battlestaff> : 2000,
    <item:the_vault:black_market> : 1525,
    <item:the_vault:block_gem_alexandrite> : 1440,
    <item:the_vault:block_gem_ashium> : 8000,
    <item:the_vault:block_gem_benitoite> : 400,
    <item:the_vault:block_gem_black_opal> : 4800,
    <item:the_vault:block_gem_bomignite> : 8000,
    <item:the_vault:block_gem_gorginite> : 8000,
    <item:the_vault:block_gem_iskallium> : 8000,
    <item:the_vault:block_gem_larimar> : 150,
    <item:the_vault:block_gem_painite> : 3600,
    <item:the_vault:block_gem_petzanite> : 8000,
    <item:the_vault:block_gem_sparkletine> : 8000,
    <item:the_vault:block_gem_tubium> : 8000,
    <item:the_vault:block_gem_upaline> : 8000,
    <item:the_vault:block_gem_wutodie> : 2875,
    <item:the_vault:block_gem_xenium> : 8000,
    <item:the_vault:blue_puzzle_concrete> : 250,
    <item:the_vault:boots> : 2000,
    <item:the_vault:bounty_block> : 1975,
    <item:the_vault:bounty_pearl> : 100,
    <item:the_vault:bumbo_polished_vault_stone> : 1,
    <item:the_vault:burger_bun> : 75,
    <item:the_vault:burger_patty> : 25,
    <item:the_vault:carbon> : 50,
    <item:the_vault:carbon_nugget> : 5,
    <item:the_vault:cheese_burger> : 250,
    <item:the_vault:chestplate> : 2000,
    <item:the_vault:chiseled_vault_stone> : 1,
    <item:the_vault:chromatic_iron_block> : 400,
    <item:the_vault:chromatic_iron_clump> : 10,
    <item:the_vault:chromatic_iron_crystal> : 10,
    <item:the_vault:chromatic_iron_dirty_dust> : 10,
    <item:the_vault:chromatic_iron_dust> : 10,
    <item:the_vault:chromatic_iron_ingot> : 50,
    <item:the_vault:chromatic_iron_nugget> : 5,
    <item:the_vault:chromatic_iron_ore> : 100,
    <item:the_vault:chromatic_iron_shard> : 10,
    <item:the_vault:chromatic_log> : 2,
    <item:the_vault:chromatic_planks> : 1,
    <item:the_vault:chromatic_slab> : 1,
    <item:the_vault:chromatic_stairs> : 1,
    <item:the_vault:chromatic_steel_block> : 2425,
    <item:the_vault:chromatic_steel_ingot> : 275,
    <item:the_vault:chromatic_steel_nugget> : 25,
    <item:the_vault:compressed_soot_block> : 25,
    <item:the_vault:cooked_vault_steak> : 500,
    <item:the_vault:crystal_budding> : 3500,
    <item:the_vault:debagnetizer> : 1725,
    <item:the_vault:dehammerizer> : 1350,
    <item:the_vault:demagnetizer> : 1475,
    <item:the_vault:diamond_nugget> : 200,
    <item:the_vault:driftwood> : 75,
    <item:the_vault:driftwood_log> : 1275,
    <item:the_vault:driftwood_planks> : 325,
    <item:the_vault:driftwood_slab> : 150,
    <item:the_vault:driftwood_stairs> : 475,
    <item:the_vault:eternal_soul> : 3000,
    <item:the_vault:extraordinary_alexandrite> : 2875,
    <item:the_vault:extraordinary_benitoite> : 800,
    <item:the_vault:extraordinary_larimar> : 325,
    <item:the_vault:flesh_chest> : 2750,
    <item:the_vault:flesh_chest_scroll> : 200,
    <item:the_vault:focus> : 2000,
    <item:the_vault:gem_alexandrite> : 175,
    <item:the_vault:gem_ashium> : 1000,
    <item:the_vault:gem_benitoite> : 50,
    <item:the_vault:gem_black_opal> : 600,
    <item:the_vault:gem_bomignite> : 1000,
    <item:the_vault:gem_echo> : 7000,
    <item:the_vault:gem_gorginite> : 1000,
    <item:the_vault:gem_iskallium> : 1000,
    <item:the_vault:gem_larimar> : 25,
    <item:the_vault:gem_painite> : 450,
    <item:the_vault:gem_petzanite> : 1000,
    <item:the_vault:gem_puffium> : 1000,
    <item:the_vault:gem_sparkletine> : 1000,
    <item:the_vault:gem_tubium> : 1000,
    <item:the_vault:gem_upaline> : 1000,
    <item:the_vault:gem_wutodie> : 350,
    <item:the_vault:gem_xenium> : 1000,
    <item:the_vault:gemstone> : 1600,
    <item:the_vault:gilded_block> : 10,
    <item:the_vault:gilded_block_bumbo> : 10,
    <item:the_vault:gilded_block_chiseled> : 10,
    <item:the_vault:gilded_block_pillar> : 10,
    <item:the_vault:gilded_bricks> : 10,
    <item:the_vault:gilded_bricks_cracked> : 10,
    <item:the_vault:gilded_bricks_cracked_dull> : 10,
    <item:the_vault:gilded_bricks_dull> : 10,
    <item:the_vault:gilded_candelabra> : 10,
    <item:the_vault:gilded_chest> : 2750,
    <item:the_vault:gilded_chest_scroll> : 200,
    <item:the_vault:gilded_cobble> : 10,
    <item:the_vault:gilded_ingot> : 2,
    <item:the_vault:gilded_sconce> : 2,
    <item:the_vault:green_puzzle_concrete> : 2000,
    <item:the_vault:hardened_chest> : 2675,
    <item:the_vault:hardened_chest_scroll> : 100,
    <item:the_vault:helmet> : 2000,
    <item:the_vault:identification_stand> : 6075,
    <item:the_vault:identification_tome> : 5550,
    <item:the_vault:infinite_water_bucket> : 9750,
    <item:the_vault:jewel_crafting_table> : 1500,
    <item:the_vault:jewel_pouch> : 1000,
    <item:the_vault:knowledge_star_essence> : 750,
    <item:the_vault:leggings> : 2000,
    <item:the_vault:living_barrel> : 2450,
    <item:the_vault:living_chest> : 2750,
    <item:the_vault:living_chest_scroll> : 200,
    <item:the_vault:living_rock> : 10,
    <item:the_vault:living_rock_block_cobble> : 10,
    <item:the_vault:living_rock_block_polished> : 10,
    <item:the_vault:living_rock_block_stacked> : 10,
    <item:the_vault:living_rock_bricks> : 10,
    <item:the_vault:living_rock_planter> : 75,
    <item:the_vault:magic_silk> : 150,
    <item:the_vault:magic_silk_block> : 1400,
    <item:the_vault:magnet> : 2000,
    <item:the_vault:modifier_workbench> : 19300,
    <item:the_vault:mossy_bone> : 2,
    <item:the_vault:mossy_bone_block> : 10,
    <item:the_vault:mossy_living_rock_block_cobble> : 10,
    <item:the_vault:mossy_living_rock_block_polished> : 10,
    <item:the_vault:mossy_living_rock_block_stacked> : 10,
    <item:the_vault:mossy_living_rock_bricks> : 10,
    <item:the_vault:mystery_box> : 2550,
    <item:the_vault:mystery_egg> : 1500,
    <item:the_vault:mystery_hostile_egg> : 5500,
    <item:the_vault:nullifying_focus> : 2025,
    <item:the_vault:ore_alexandrite> : 350,
    <item:the_vault:ore_ashium> : 2000,
    <item:the_vault:ore_benitoite> : 100,
    <item:the_vault:ore_black_opal> : 1200,
    <item:the_vault:ore_bomignite> : 2000,
    <item:the_vault:ore_gorginite> : 2000,
    <item:the_vault:ore_iskallium> : 2000,
    <item:the_vault:ore_larimar> : 50,
    <item:the_vault:ore_painite> : 900,
    <item:the_vault:ore_petzanite> : 2000,
    <item:the_vault:ore_sparkletine> : 2000,
    <item:the_vault:ore_tubium> : 2000,
    <item:the_vault:ore_upaline> : 2000,
    <item:the_vault:ore_wutodie> : 700,
    <item:the_vault:ore_xenium> : 2000,
    <item:the_vault:ornate_barrel> : 2450,
    <item:the_vault:ornate_block> : 10,
    <item:the_vault:ornate_block_chiseled> : 10,
    <item:the_vault:ornate_block_pillar> : 10,
    <item:the_vault:ornate_block_tiled> : 10,
    <item:the_vault:ornate_block_velvet> : 10,
    <item:the_vault:ornate_block_velvet_chiseled> : 10,
    <item:the_vault:ornate_block_velvet_pillar> : 10,
    <item:the_vault:ornate_bricks> : 10,
    <item:the_vault:ornate_bricks_chipped> : 10,
    <item:the_vault:ornate_bricks_cracked> : 10,
    <item:the_vault:ornate_bricks_rusty> : 10,
    <item:the_vault:ornate_bricks_velvet> : 10,
    <item:the_vault:ornate_chain> : 10,
    <item:the_vault:ornate_chain_rusty> : 10,
    <item:the_vault:ornate_chest> : 2750,
    <item:the_vault:ornate_chest_scroll> : 200,
    <item:the_vault:ornate_ingot> : 2,
    <item:the_vault:overgrown_wooden_chunk> : 2,
    <item:the_vault:overgrown_wooden_log> : 50,
    <item:the_vault:overgrown_wooden_planks> : 10,
    <item:the_vault:overgrown_wooden_slab> : 5,
    <item:the_vault:overgrown_wooden_stairs> : 5,
    <item:the_vault:pink_puzzle_concrete> : 1000,
    <item:the_vault:plain_burger> : 125,
    <item:the_vault:polished_vault_stone> : 1,
    <item:the_vault:polished_vault_stone_slab> : 1,
    <item:the_vault:polished_vault_stone_stairs> : 1,
    <item:the_vault:rang> : 2000,
    <item:the_vault:raw_chromatic_iron> : 50,
    <item:the_vault:raw_chromatic_iron_block> : 400,
    <item:the_vault:raw_vault_steak> : 500,
    <item:the_vault:red_vault_essence> : 8800,
    <item:the_vault:rotten_meat> : 2,
    <item:the_vault:rotten_meat_block> : 10,
    <item:the_vault:sandy_block> : 10,
    <item:the_vault:sandy_block_bumbo> : 10,
    <item:the_vault:sandy_block_chiseled> : 10,
    <item:the_vault:sandy_block_polished> : 10,
    <item:the_vault:sandy_bricks> : 10,
    <item:the_vault:sandy_bricks_cracked> : 10,
    <item:the_vault:sandy_rocks> : 10,
    <item:the_vault:sandy_small_bricks> : 10,
    <item:the_vault:sandy_small_bricks_cracked> : 10,
    <item:the_vault:shard_pouch> : 225,
    <item:the_vault:shield> : 2000,
    <item:the_vault:silver_scrap> : 25,
    <item:the_vault:soot> : 1,
    <item:the_vault:stripped_chromatic_log> : 1,
    <item:the_vault:stripped_driftwood_log> : 1275,
    <item:the_vault:stripped_overgrown_wooden_log> : 50,
    <item:the_vault:stripped_wooden_log> : 10,
    <item:the_vault:sugar_plum_fairy_flower> : 1,
    <item:the_vault:sweet_kiwi> : 1000,
    <item:the_vault:sword> : 2000,
    <item:the_vault:tenos_bookshelf> : 25,
    <item:the_vault:tenos_bookshelf_empty> : 25,
    <item:the_vault:tenos_brick> : 425,
    <item:the_vault:tenos_brick_chiseled> : 425,
    <item:the_vault:tenos_dark_smooth_brick> : 425,
    <item:the_vault:tenos_gem_block> : 425,
    <item:the_vault:tenos_light_smooth_brick> : 425,
    <item:the_vault:tenos_log> : 2,
    <item:the_vault:tenos_planks> : 1,
    <item:the_vault:tenos_stripped_log> : 2,
    <item:the_vault:tenos_vertical_planks> : 1,
    <item:the_vault:tool_station> : 450,
    <item:the_vault:topaz_block> : 10,
    <item:the_vault:topaz_shard> : 2,
    <item:the_vault:transmog_table> : 5575,
    <item:the_vault:trident> : 2000,
    <item:the_vault:unique_codex> : 5350,
    <item:the_vault:vault_altar> : 1950,
    <item:the_vault:vault_apple> : 14025,
    <item:the_vault:vault_ash> : 1,
    <item:the_vault:vault_bars> : 1,
    <item:the_vault:vault_bronze> : 10,
    <item:the_vault:vault_cobblestone> : 1,
    <item:the_vault:vault_diamond> : 125,
    <item:the_vault:vault_dust> : 200,
    <item:the_vault:vault_enchanter> : 6425,
    <item:the_vault:vault_essence> : 875,
    <item:the_vault:vault_forge> : 10300,
    <item:the_vault:vault_jewel_application_station> : 10500,
    <item:the_vault:vault_meat> : 125,
    <item:the_vault:vault_meat_block> : 1125,
    <item:the_vault:vault_moss> : 2,
    <item:the_vault:vault_nugget> : 1600,
    <item:the_vault:vault_plating> : 50,
    <item:the_vault:vault_recycler> : 7500,
    <item:the_vault:vault_rock> : 1,
    <item:the_vault:vault_scrap> : 400,
    <item:the_vault:vault_silver> : 100,
    <item:the_vault:vault_stone> : 1,
    <item:the_vault:vault_stone_brick_slab> : 1,
    <item:the_vault:vault_stone_brick_stairs> : 1,
    <item:the_vault:vault_stone_bricks> : 1,
    <item:the_vault:vault_stone_bricks_cracked> : 1,
    <item:the_vault:vault_stone_pillar> : 1,
    <item:the_vault:vault_stone_slab> : 1,
    <item:the_vault:vault_stone_stairs> : 1,
    <item:the_vault:vault_sweets> : 2,
    <item:the_vault:vault_sweets_block> : 10,
    <item:the_vault:vaulterite_ingot> : 2500,
    <item:the_vault:velara_brick> : 425,
    <item:the_vault:velara_brick_chiseled> : 425,
    <item:the_vault:velara_dark_smooth_brick> : 425,
    <item:the_vault:velara_gem_block> : 425,
    <item:the_vault:velara_leaves> : 50,
    <item:the_vault:velara_light_smooth_brick> : 425,
    <item:the_vault:velara_log> : 25,
    <item:the_vault:velara_mossy_block> : 425,
    <item:the_vault:velara_mossy_blooming_log> : 25,
    <item:the_vault:velara_mossy_log> : 50,
    <item:the_vault:velara_planks> : 5,
    <item:the_vault:velara_planks_slab> : 2,
    <item:the_vault:velara_planks_stairs> : 2,
    <item:the_vault:velara_stripped_log> : 25,
    <item:the_vault:velara_vertical_planks> : 2,
    <item:the_vault:velara_vine> : 50,
    <item:the_vault:velvet> : 2,
    <item:the_vault:velvet_bed> : 50,
    <item:the_vault:velvet_block> : 10,
    <item:the_vault:velvet_block_chiseled> : 10,
    <item:the_vault:velvet_block_strips> : 10,
    <item:the_vault:velvet_carpet> : 5,
    <item:the_vault:wand> : 2000,
    <item:the_vault:wardens_pearl> : 1800,
    <item:the_vault:wardrobe> : 2000,
    <item:the_vault:wendarr_brick> : 425,
    <item:the_vault:wendarr_brick_chiseled> : 425,
    <item:the_vault:wendarr_dark_smooth_brick> : 425,
    <item:the_vault:wendarr_gem_block> : 425,
    <item:the_vault:wendarr_jewel_block> : 425,
    <item:the_vault:wendarr_jewel_glass> : 2,
    <item:the_vault:wendarr_jewel_glass_pane> : 1,
    <item:the_vault:wendarr_light_smooth_brick> : 425,
    <item:the_vault:wild_focus> : 225,
    <item:the_vault:wooden_barrel> : 2450,
    <item:the_vault:wooden_chest> : 2750,
    <item:the_vault:wooden_chest_scroll> : 200,
    <item:the_vault:wooden_chunk> : 1,
    <item:the_vault:wooden_log> : 10,
    <item:the_vault:wooden_planks> : 2,
    <item:the_vault:wooden_slab> : 1,
    <item:the_vault:wooden_stairs> : 1,
    <item:the_vault:wutodic_silver_ingot> : 1675,
    <item:the_vault:wutodic_silver_nugget> : 200,
    <item:the_vault:yellow_puzzle_concrete> : 500,
    <item:the_vault:scavenger_benitoite_gemstone> : 100,
    <item:the_vault:scavenger_blue_bangle> : 100,
    <item:the_vault:scavenger_blue_scroll> : 100,
    <item:the_vault:scavenger_broken_pottery> : 100,
    <item:the_vault:scavenger_cracked_pearl> : 100,
    <item:the_vault:scavenger_cracked_script> : 100,
    <item:the_vault:scavenger_creeper_eye> : 100,
    <item:the_vault:scavenger_creeper_foot> : 100,
    <item:the_vault:scavenger_creeper_fuse> : 100,
    <item:the_vault:scavenger_creeper_soul_charm> : 100,
    <item:the_vault:scavenger_creeper_tnt> : 100,
    <item:the_vault:scavenger_creeper_vial> : 100,
    <item:the_vault:scavenger_drowned_barnacle> : 100,
    <item:the_vault:scavenger_drowned_eye> : 100,
    <item:the_vault:scavenger_drowned_hide> : 100,
    <item:the_vault:scavenger_drowned_soul_charm> : 100,
    <item:the_vault:scavenger_drowned_vial> : 100,
    <item:the_vault:scavenger_earrings> : 100,
    <item:the_vault:scavenger_echoing_gemstone> : 100,
    <item:the_vault:scavenger_empty_jar> : 100,
    <item:the_vault:scavenger_ender_artifact> : 100,
    <item:the_vault:scavenger_ender_crystal> : 100,
    <item:the_vault:scavenger_ender_heart> : 100,
    <item:the_vault:scavenger_enderman_eye> : 100,
    <item:the_vault:scavenger_goblet> : 100,
    <item:the_vault:scavenger_green_bangle> : 100,
    <item:the_vault:scavenger_mob_black> : 100,
    <item:the_vault:scavenger_mob_green> : 100,
    <item:the_vault:scavenger_mob_purple> : 100,
    <item:the_vault:scavenger_old_book> : 100,
    <item:the_vault:scavenger_pink_bangle> : 100,
    <item:the_vault:scavenger_pogging_gemstone> : 100,
    <item:the_vault:scavenger_pottery_shard> : 100,
    <item:the_vault:scavenger_poultice_jar> : 100,
    <item:the_vault:scavenger_preserves_jar> : 100,
    <item:the_vault:scavenger_red_scroll> : 100,
    <item:the_vault:scavenger_ripped_page> : 100,
    <item:the_vault:scavenger_sack> : 100,
    <item:the_vault:scavenger_saddle_bag> : 100,
    <item:the_vault:scavenger_skeleton_bone_shard> : 100,
    <item:the_vault:scavenger_skeleton_milky_eye> : 100,
    <item:the_vault:scavenger_skeleton_milky_vial> : 100,
    <item:the_vault:scavenger_skeleton_ribcage> : 100,
    <item:the_vault:scavenger_skeleton_skull> : 100,
    <item:the_vault:scavenger_skeleton_soul_charm> : 100,
    <item:the_vault:scavenger_skeleton_wishbone> : 100,
    <item:the_vault:scavenger_spice_jar> : 100,
    <item:the_vault:scavenger_spider_cursed_charm> : 100,
    <item:the_vault:scavenger_spider_fangs> : 100,
    <item:the_vault:scavenger_spider_leg> : 100,
    <item:the_vault:scavenger_spider_soul_charm> : 100,
    <item:the_vault:scavenger_spider_vial> : 100,
    <item:the_vault:scavenger_spider_webbing_spool> : 100,
    <item:the_vault:scavenger_wizard_wand> : 100,
    <item:the_vault:scavenger_wutodic_gemstone> : 100,
    <item:the_vault:scavenger_zombie_arm> : 100,
    <item:the_vault:scavenger_zombie_blood_vial> : 100,
    <item:the_vault:scavenger_zombie_brain> : 100,
    <item:the_vault:scavenger_zombie_ear> : 100,
    <item:the_vault:scavenger_zombie_eye> : 100,
    <item:the_vault:scavenger_zombie_hide> : 100,
    <item:the_vault:scavenger_zombie_nose> : 100,
    <item:the_vault:vault_catalyst_infused> : 6000
};

// For each item in the map, check if we're in release mode. If we are, anything below 26 EMC/FMC becomes unburnable for EMC
for item, value in priceTable {
    if (release_mode == true){
        if (value < 26 ) {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), 0);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        } else {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        }
        if (value > 999 && value < 10001) {
            <tag:items:tfb2:fop_miniscule>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Miniscule");
            });
        }
        if (value > 10000 && value < 25001) {
            <tag:items:tfb2:fop_small>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Small");
            });
        }
        if (value > 25000 && value < 75001) {
            <tag:items:tfb2:fop_medium>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Medium");
            });
        }
        if (value > 75000) {
            <tag:items:tfb2:fop_large>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Large");
            });
        }
    } else {
        CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
        <tag:items:projectextended:blacklist_condenser>.add(item);
        <tag:items:projectextended:blacklist_learning>.add(item);
    }
        if (value > 10000 && value < 25001) {
            <tag:items:tfb2:fop_small>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Small");
            });
        }
        if (value > 25000 && value < 75001) {
            <tag:items:tfb2:fop_medium>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Medium");
            });
        }
        if (value > 75000) {
            <tag:items:tfb2:fop_large>.add(item);
            item.modifyTooltip((stack, tooltip, flag) => {
                tooltip.insert(2, "FOP Digitization Value: Large");
            });
        }
}