import crafttweaker.api.tag.MCTag;
import crafttweaker.api.item.IItemStack;
import crafttweaker.api.ingredient.IIngredient;
import crafttweaker.api.item.tooltip.ITooltipFunction;
import stdlib.List;
import mods.projecte.CustomEMC;
import mods.projecte.NSSResolver;

// Item  to EMC/FMC value map.
val priceTable as int[IItemStack] = {
    <item:twigs:bloodstone> : 150,
    <item:twigs:bloodstone_slab> : 75,
    <item:twigs:bloodstone_stairs> : 150,
    <item:twigs:bloodstone_vertical_slab> : 75,
    <item:twigs:bloodstone_wall> : 150,
    <item:twigs:chiseled_polished_amethyst> : 100,
    <item:twigs:cracked_polished_amethyst_bricks> : 900,
    <item:twigs:cracked_polished_bloodstone_bricks> : 150,
    <item:twigs:cracked_polished_rhyolite_bricks> : 125,
    <item:twigs:cracked_polished_schist_bricks> : 125,
    <item:twigs:crimson_shroomlamp> : 25,
    <item:twigs:polished_amethyst> : 100,
    <item:twigs:polished_amethyst_brick_slab> : 50,
    <item:twigs:polished_amethyst_brick_stairs> : 100,
    <item:twigs:polished_amethyst_brick_vertical_slab> : 50,
    <item:twigs:polished_amethyst_brick_wall> : 100,
    <item:twigs:polished_amethyst_bricks> : 100,
    <item:twigs:polished_amethyst_slab> : 50,
    <item:twigs:polished_amethyst_stairs> : 100,
    <item:twigs:polished_amethyst_vertical_slab> : 50,
    <item:twigs:polished_bloodstone> : 150,
    <item:twigs:polished_bloodstone_brick_slab> : 75,
    <item:twigs:polished_bloodstone_brick_stairs> : 150,
    <item:twigs:polished_bloodstone_brick_vertical_slab> : 75,
    <item:twigs:polished_bloodstone_brick_wall> : 150,
    <item:twigs:polished_bloodstone_bricks> : 150,
    <item:twigs:polished_bloodstone_slab> : 75,
    <item:twigs:polished_bloodstone_stairs> : 150,
    <item:twigs:polished_bloodstone_vertical_slab> : 75,
    <item:twigs:polished_rhyolite> : 125,
    <item:twigs:polished_rhyolite_brick_slab> : 50,
    <item:twigs:polished_rhyolite_brick_stairs> : 125,
    <item:twigs:polished_rhyolite_brick_vertical_slab> : 50,
    <item:twigs:polished_rhyolite_brick_wall> : 125,
    <item:twigs:polished_rhyolite_bricks> : 125,
    <item:twigs:polished_rhyolite_slab> : 50,
    <item:twigs:polished_rhyolite_stairs> : 125,
    <item:twigs:polished_rhyolite_vertical_slab> : 50,
    <item:twigs:polished_schist> : 125,
    <item:twigs:polished_schist_brick_slab> : 50,
    <item:twigs:polished_schist_brick_stairs> : 125,
    <item:twigs:polished_schist_brick_vertical_slab> : 50,
    <item:twigs:polished_schist_brick_wall> : 125,
    <item:twigs:polished_schist_bricks> : 125,
    <item:twigs:polished_schist_slab> : 50,
    <item:twigs:polished_schist_stairs> : 125,
    <item:twigs:polished_schist_vertical_slab> : 50,
    <item:twigs:rhyolite> : 125,
    <item:twigs:rhyolite_slab> : 50,
    <item:twigs:rhyolite_stairs> : 125,
    <item:twigs:rhyolite_vertical_slab> : 50,
    <item:twigs:rhyolite_wall> : 125,
    <item:twigs:schist> : 125,
    <item:twigs:schist_slab> : 50,
    <item:twigs:schist_stairs> : 125,
    <item:twigs:schist_vertical_slab> : 50,
    <item:twigs:schist_wall> : 125,
    <item:twigs:soul_lamp> : 775,
    <item:twigs:twisting_polished_blackstone_brick_slab> : 2,
    <item:twigs:twisting_polished_blackstone_brick_stairs> : 5,
    <item:twigs:twisting_polished_blackstone_brick_vertical_slab> : 2,
    <item:twigs:twisting_polished_blackstone_brick_wall> : 5,
    <item:twigs:twisting_polished_blackstone_bricks> : 5,
    <item:twigs:warped_shroomlamp> : 25,
    <item:twigs:weeping_polished_blackstone_brick_slab> : 2,
    <item:twigs:weeping_polished_blackstone_brick_stairs> : 5,
    <item:twigs:weeping_polished_blackstone_brick_vertical_slab> : 2,
    <item:twigs:weeping_polished_blackstone_brick_wall> : 5,
    <item:twigs:weeping_polished_blackstone_bricks> : 5,
    <item:twigs:acacia_table> : 5,
    <item:twigs:allium_paper_lantern> : 10,
    <item:twigs:azalea_flowers> : 5,
    <item:twigs:bamboo_leaves> : 5,
    <item:twigs:bamboo_thatch> : 10,
    <item:twigs:bamboo_thatch_slab> : 5,
    <item:twigs:bamboo_thatch_stairs> : 10,
    <item:twigs:bamboo_thatch_vertical_slab> : 5,
    <item:twigs:birch_table> : 5,
    <item:twigs:blue_orchid_paper_lantern> : 5,
    <item:twigs:bundled_bamboo> : 10,
    <item:twigs:calcite_slab> : 1,
    <item:twigs:calcite_stairs> : 1,
    <item:twigs:calcite_vertical_slab> : 1,
    <item:twigs:calcite_wall> : 1,
    <item:twigs:chiseled_bricks> : 10,
    <item:twigs:cobblestone_brick_slab> : 1,
    <item:twigs:cobblestone_brick_stairs> : 1,
    <item:twigs:cobblestone_brick_vertical_slab> : 1,
    <item:twigs:cobblestone_brick_wall> : 1,
    <item:twigs:cobblestone_bricks> : 1,
    <item:twigs:copper_pillar> : 900,
    <item:twigs:cracked_bricks> : 10,
    <item:twigs:cracked_cobblestone_bricks> : 1,
    <item:twigs:cracked_polished_calcite_bricks> : 1,
    <item:twigs:cracked_polished_tuff_bricks> : 1,
    <item:twigs:crimson_roots_paper_lantern> : 5,
    <item:twigs:crimson_table> : 5,
    <item:twigs:dandelion_paper_lantern> : 5,
    <item:twigs:dark_oak_table> : 5,
    <item:twigs:exposed_copper_pillar> : 900,
    <item:twigs:jungle_table> : 5,
    <item:twigs:lamp> : 775,
    <item:twigs:mossy_brick_slab> : 10,
    <item:twigs:mossy_brick_stairs> : 25,
    <item:twigs:mossy_brick_vertical_slab> : 10,
    <item:twigs:mossy_brick_wall> : 25,
    <item:twigs:mossy_bricks> : 25,
    <item:twigs:mossy_cobblestone_brick_slab> : 1,
    <item:twigs:mossy_cobblestone_brick_stairs> : 2,
    <item:twigs:mossy_cobblestone_brick_vertical_slab> : 1,
    <item:twigs:mossy_cobblestone_brick_wall> : 2,
    <item:twigs:mossy_cobblestone_bricks> : 2,
    <item:twigs:oak_table> : 5,
    <item:twigs:oxidized_copper_pillar> : 900,
    <item:twigs:paper_lantern> : 5,
    <item:twigs:pebble> : 1,
    <item:twigs:polished_basalt_bricks> : 1,
    <item:twigs:polished_calcite> : 1,
    <item:twigs:polished_calcite_brick_slab> : 1,
    <item:twigs:polished_calcite_brick_stairs> : 1,
    <item:twigs:polished_calcite_brick_vertical_slab> : 1,
    <item:twigs:polished_calcite_brick_wall> : 1,
    <item:twigs:polished_calcite_bricks> : 1,
    <item:twigs:polished_calcite_slab> : 1,
    <item:twigs:polished_calcite_stairs> : 1,
    <item:twigs:polished_calcite_vertical_slab> : 1,
    <item:twigs:polished_tuff> : 1,
    <item:twigs:polished_tuff_brick_slab> : 1,
    <item:twigs:polished_tuff_brick_stairs> : 1,
    <item:twigs:polished_tuff_brick_vertical_slab> : 1,
    <item:twigs:polished_tuff_brick_wall> : 1,
    <item:twigs:polished_tuff_bricks> : 1,
    <item:twigs:polished_tuff_slab> : 1,
    <item:twigs:polished_tuff_stairs> : 1,
    <item:twigs:polished_tuff_vertical_slab> : 1,
    <item:twigs:rocky_dirt> : 2,
    <item:twigs:smooth_basalt_brick_slab> : 1,
    <item:twigs:smooth_basalt_brick_stairs> : 1,
    <item:twigs:smooth_basalt_brick_vertical_slab> : 1,
    <item:twigs:smooth_basalt_brick_wall> : 1,
    <item:twigs:smooth_basalt_bricks> : 1,
    <item:twigs:spruce_table> : 5,
    <item:twigs:stripped_bamboo> : 5,
    <item:twigs:stripped_bamboo_boat> : 250,
    <item:twigs:stripped_bamboo_button> : 50,
    <item:twigs:stripped_bamboo_door> : 100,
    <item:twigs:stripped_bamboo_fence> : 50,
    <item:twigs:stripped_bamboo_fence_gate> : 100,
    <item:twigs:stripped_bamboo_mat> : 5,
    <item:twigs:stripped_bamboo_planks> : 50,
    <item:twigs:stripped_bamboo_planks_vertical_slab> : 25,
    <item:twigs:stripped_bamboo_pressure_plate> : 100,
    <item:twigs:stripped_bamboo_slab> : 25,
    <item:twigs:stripped_bamboo_stairs> : 50,
    <item:twigs:stripped_bamboo_table> : 300,
    <item:twigs:stripped_bamboo_trapdoor> : 125,
    <item:twigs:stripped_bundled_bamboo> : 10,
    <item:twigs:tuff_slab> : 1,
    <item:twigs:tuff_stairs> : 1,
    <item:twigs:tuff_vertical_slab> : 1,
    <item:twigs:tuff_wall> : 1,
    <item:twigs:twig> : 1,
    <item:twigs:warped_table> : 5,
    <item:twigs:waxed_copper_pillar> : 900,
    <item:twigs:waxed_exposed_copper_pillar> : 900,
    <item:twigs:waxed_oxidized_copper_pillar> : 900,
    <item:twigs:waxed_weathered_copper_pillar> : 900,
    <item:twigs:weathered_copper_pillar> : 900
};

// For each item in the map, check if we're in release mode. If we are, anything below 26 EMC/FMC becomes unburnable for EMC
for item, value in priceTable {
    if (ReleaseMode.releaseMode == true){
        if (value < 26 ) {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), 0);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        } else {
            CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
            <tag:items:projectextended:blacklist_condenser>.add(item);
            <tag:items:projectextended:blacklist_learning>.add(item);
        }
    } else {
        CustomEMC.setEMCValue(NSSResolver.fromItem(item), value);
        <tag:items:projectextended:blacklist_condenser>.add(item);
        <tag:items:projectextended:blacklist_learning>.add(item);
    }
}